### ISSUE TITLE
Corrections to User Manual

### ISSUE THREAD

**Issue by dhevang** [AIDASoft/DD4hep#1003]
I'm not sure if this is the right place for this but here goes.
DD4hep is being used for EIC detector development and there are many new users trying to learn the software at the moment.  
The current User Manual has quite some mistakes/typos from what I can see.  I (and others) can post what I find here as "issues" if that's appropriate.
For instance on page 50, there is repeated reference to multipoles or moments as "momentum".  The 2nd equation of the block of 4 long ones seems to have a mistake: should be "C_n" instead of "S_n".  Then in the code box on page 51, they write "coeffizient" instead of coefficient.

**Comment by andresailer** [comment]
@dhevang I think I fixed the issues you mentioned in #1005

**Comment by dhevang** [comment]
Thanks.  For other little typos I find in the future, I'll edit the files myself and issue a PR.
By the way, how often do you update the officially available DD4hep manual from this repo?  https://dd4hep.web.cern.ch/dd4hep/page/users-manual/
It would be good if this one stays up to date.

**Comment by andresailer** [comment]
In principle there is a CI job that updates the manuals whenever there is a change in the master branch. It was broken these last few weeks though. Hopefully the manuals will soon say today's date again.

**Comment by andresailer** [comment]
Now the manual is up-to-date on the website.

**Comment by dhevang** [comment]
Thanks.  I just issued a PR, which makes that multipole formula more readable.

**Comment by andresailer** [comment]
Thanks! I will close this issue then.
