### ISSUE TITLE
ParticleGun: Isotropic distribution along different axis

### ISSUE THREAD

**Issue by michael-pitt** [AIDASoft/DD4hep#1007]
Can G4Particle gun generate particles using isotropic distribution along a different axis?

Currently, in [Geant4ParticleGun.cpp](https://github.com/AIDASoft/DD4hep/blob/master/DDG4/src/Geant4ParticleGun.cpp), particle direction is set according to the nominal (x,y,z) coordinates. Is there a way to generate isotropic distribution along a different axis?

For example, if I could run the following script to generate particles with Theta in (0.,0.1) along (x0,y0,z0):
```
from DDSim.DD4hepSimulation import DD4hepSimulation
SIM = DD4hepSimulation()
SIM.enableGun = True
SIM.gun.direction = (x0, y0, z0)
SIM.gun.thetaMax = 0.0
SIM.gun.thetaMin = 0.1
```
Thanks,
Michael

**Comment by andresailer** [comment]
Hi @michael-pitt 

Just in case: if you want to get a distribution along a beam-line with a crossing angle, you can use the Lorentz Boost configuration:
https://github.com/AIDASoft/DD4hep/blob/d12273f22b9088da05882f09aba905896b4fec87/DDG4/python/DDSim/DD4hepSimulation.py#L166-L168
This is a boost along the X coordinate

In general, I hope one is able to achieve this with the Geant4 General Particle source
https://geant4-userdoc.web.cern.ch/UsersGuides/ForApplicationDeveloper/html/GettingStarted/generalParticleSource.html

Create a macro file with the gps commands, and run

`ddsim --enableG4GPS --runType run --macroFile mygps.mac ...`

Cheers,
Andre

**Comment by michael-pitt** [comment]
Hi @andresailer 

Thanks. Indeed, I was interested in a distribution along a beamline with a crossing angle of 25mrad. Your proposed solution works for me:
```
from DDSim.DD4hepSimulation import DD4hepSimulation
from g4units import mrad
SIM = DD4hepSimulation()
SIM.enableGun = True
SIM.gun.thetaMax = 0.0
SIM.gun.thetaMin = 0.1

## Lorentz boost for the crossing angle (a boost along the X coordinate)
SIM.crossingAngleBoost = -25.0*mrad
```

**Comment by andresailer** [comment]
Great!
To be more precise, the angle is the half crossing angle between two beams, so the angle with respect to the Z-axis.
