### ISSUE TITLE
help understanding channel encoding

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#1009]
Hi,
I am trying to make the channel encoding more sensible for my application.  I am using the NoSegmentation segmentation. In my xml file that defines the segmentation, I want to remove the "barreL" descriptor, since this is a test beam module, not a collider detector.  But when I try to do this, I  am getting the error from this code: https://github.com/AIDASoft/DD4hep/blob/136b80877667f3f33be3f4a1afc45a22f3cfd976/DDCore/src/IDDescriptor.cpp#L97
and it complains that there is no barrel field.

It looks to me like the encoder and its fields is associated with the segmentation through the constructor  https://github.com/AIDASoft/DD4hep/blob/136b80877667f3f33be3f4a1afc45a22f3cfd976/DDCore/include/DDSegmentation/Segmentation.h#L139

but I don't know where/how it gets what it uses there?  I have tried greping "barrel" in DDCore but cannot find anything that it might be using?

In my geometry file, I have a line
   sens.setType("calorimeter")
Is that what is doing that?  
If so, what are the valid types that can be set?
also, if this is the cause, can you point me to the lines of code that associate it with a BitField that contains "barrel"?

**Comment by saraheno** [comment]
let me work on this one more day and see if I can figure it out.  There must be some code somewhere doing something like    pv.addPhysVolID("barrel",0); even though I cannot seem to find this code, right?  It is a command like this followed by something like sdet.add(sd); that will cause this error code if I don't have "barrel" in the xml line like <id>system:3,barrel:1,side:1,slice:2,layer:2,ieta:9,iphi:9,eta:-8,phi:9</id>?  I swear I commented out all the lines like addPhysVolID that contain barrel, but there must be one somewhere?

**Comment by saraheno** [comment]
okay, I'm sorry.  I do need your help.  The warning from IDDescriptor is coming from Geant4Exec:: initialize, in the line runManager.Initialize.  But this seems to be calling a GEANT4 routine, not a dd4hep routine?  I attach the spew
[haha.txt](https://github.com/AIDASoft/DD4hep/files/9962855/haha.txt)

**Comment by saraheno** [comment]
I guess my question is this: when you defined a readout in the xml, using a segmentation type like "NoSegmentation", are you forced in the <id> descriptor to have a field "barrel" and "side"?  if so, where is the code that forces this?

**Comment by andresailer** [comment]
Can I see the code and XML you are running somewhere?

**Comment by andresailer** [comment]
Somewhere in your LD_LIBRARY_PATH you have a library and a components file from an older version of your developments, and this library is used instead of your new developments

```$ cat libDDDualCrystal.components
v2::libDDDualCrystal.so:DD4hep_DRCrystal
v2::libDDDualCrystal.so:DRCrystal
v2::libDDDualCrystal.so:DualCrystalCalorimeterSDAction
```
Luckily I was following your developments along and I ran into the same issue as you observe...

When I changed the couts from DRCrystal_geo nothing changed in the ddsim running, which is the usual thing of changing a file that is not actually being used in the end.. Cleaning the install directory and installing again solved the problem.

**Comment by saraheno** [comment]
I have deleted the "build" directory and rebuilt and had the same problem.  Is the "install"directory not a subdirectory of the build directory?

**Comment by saraheno** [comment]
my cmake command does not specific the install directory

cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=ON -DBUILD_TESTING=ON -DROOT_DIR=$ROOTSYS -D CMAKE_BUILD_TYPE=Release -DDD4HEP_BUILD_EXAMPLES=ON ..

What is the default one?

(for that code snippet you suggest, I put that in a .sh file? or how to I run it?)

**Comment by andresailer** [comment]
The default is `/usr/lib` ? If you do `make install` it should print the same location then.

Yes, they are shell commands, you can just copy them to the shell, or into a script file.

**Comment by andresailer** [comment]
`/usr/local` (https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html)

**Comment by saraheno** [comment]
Thank you.  It is working now.

**Comment by andresailer** [comment]
Great!
