### ISSUE TITLE
Problems for example "OpticalSurfaces" for version 01-22 and 01-23

### ISSUE THREAD

**Issue by haliupmo** [AIDASoft/DD4hep#1015]
!!!IMPORTANT!!!: To facilitate faster and easier response to your issue please provide in addition to the description of the issue also the following information

 - OS version: ubuntu 22.04
 - Compiler version: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
 - Package version: 01-22  and 01-23
 - Reproduced by: Geant4.10.7-patch4/ROOT 6.26.06,
 - Input: offical opticalSurfaces examples
 - Output: full build and run log output 
[新建文本文档 (2).txt](https://github.com/AIDASoft/DD4hep/files/10001598/2.txt)

 -  Goal:I want to run this example, it works with version 01-21 and -1-20-02,but not with 01-22 and 01-23

**Comment by andresailer** [comment]
Hi @haliupmo 

Is this the only example that doesn't work?

How are you running the example?

Did you build all packages (ROOT, Geant4, DD4hep) in a consistent way, e.g., C++ standard, same python version?

**Comment by haliupmo** [comment]
> Hi @haliupmo
> 
> Is this the only example that doesn't work?
> 
> How are you running the example?
> 
> Did you build all packages (ROOT, Geant4, DD4hep) in a consistent way, e.g., C++ standard, same python version?

Dear andresailer,
Thank you for your fast responses.I have built the packages all with C++17 standard, and python 3.10, and the example OpticalTracker can run properly,see 
[opticaltracker.log](https://github.com/AIDASoft/DD4hep/files/10002411/opticaltracker.log)

. As far as I have tried, opticalSurfaces is the only one that can not run properly. When I look into the log files, there appears something of "the double free()" etc... ,did it mean it free something twice which led to memory leaking?I have tried to compare the source codes of version 01-20 and 01-23, but you see it is not easy for me to figure out what happened...
I also would like to attach the log file of opticalsurface run with version 01-21,which is quite good.
[opticalsurfaces_v01-21_good.log](https://github.com/AIDASoft/DD4hep/files/10002456/opticalsurfaces_v01-21_good.log)
you may also interested in the log file during build...
[cmake version 3.22.1_build.txt](https://github.com/AIDASoft/DD4hep/files/10002499/cmake.version.3.22.1_build.txt)

**Comment by andresailer** [comment]
Hi @haliupmo 

You are just running `python path/to/OpNovice.py`, right?
I think I am reproducing the issue now.

Let's see if I can find the problematic change.

**Comment by andresailer** [comment]
Can you try out #1016 ?

**Comment by haliupmo** [comment]
Great job！It works as it should be!
