### ISSUE TITLE
Calorimeter Energy Deposition with Multiple Readout Segmentations

### ISSUE THREAD

**Issue by demisra** [AIDASoft/DD4hep#1020]
I'm trying to obtain the total energy deposited in each layer of a segmented calorimeter with multiple segmentations in the readout. Specifically, in the EIC EPIC environment (https://github.com/eic/epic) with the following geometry: 

https://github.com/eic/epic/blob/main/compact/far_forward/ZDC.xml
https://github.com/eic/epic/blob/main/compact/far_forward/ZDC_WSi.xml

there are 23 layers, of which layers 1, 12, and 23 are "pixel" layers with transverse segmentation of 3mm^2. The remaining layers are "pad" layers, with segmentation of 1cm^2. The two layer types are otherwise effectively identical. I'm running ddsim using the following steering file: 

```
from DDSim.DD4hepSimulation import DD4hepSimulation
from g4units import mm, cm, GeV, MeV, degree, radian
SIM = DD4hepSimulation()

energy = "50*GeV"
particle = "neutron"
count = "10e3"
format = "edm4hep"

ionCrossingAngle = -0.025 * radian
ZDC_z_pos = 3560 * cm
ZDC_x_pos = ionCrossingAngle * ZDC_z_pos
ZDC_y_pos = 0 * cm

SIM.gun.position = (ZDC_x_pos, ZDC_y_pos, ZDC_z_pos)
SIM.gun.thetaMin = ionCrossingAngle
SIM.gun.thetaMax = ionCrossingAngle
SIM.gun.phiMin = -90*degree
SIM.gun.phiMax = -90*degree
SIM.gun.distribution = "uniform"
SIM.gun.momentumMin = eval(energy)
SIM.gun.momentumMax = eval(energy)
SIM.gun.particle = particle
SIM.gun.multiplicity = 1

SIM.outputFile = f"zdc_{particle}_{energy.replace('*','')}_{count}.{format}.root"
```

I noticed that when plotting the sum of hit energy for each layer vs. layerID, the pixel layers pick up much more energy than expected. For reference, I modified the readout to use uniform segmentation in both layer types, causing this discrepancy to disappear. Note that the finer segmentation also results in uniformly greater energy deposition in most layers. Modifying the segmentation of the pixel layers further shows that the degree to which the energy deposited in these layers differs from the pad layers is correlated with the segmentation, with pixel layers with 1mm segmentation picking up more energy than those with 3mm. 

This plot is the mean energy deposition for several segmentation configurations from a sample of 1000 neutrons at 50GeV.
<img width="303" alt="seg_1mm" src="https://user-images.githubusercontent.com/115676845/202284217-532c21f1-a41e-40bb-9374-11004ee0cfff.PNG">

This also seems like it could probably be replicated outside of the EPIC environment but I'm not sure how I would go about doing that myself. The above a relatively simple case -- single particles in a segmented calorimeter with two different readout segmentations. Is this a DD4hep problem with the use of multiple segmentations in a single geometry file or something else? I'm working on creating a minimal example which can be run separate from the EIC container.

@wdconinc

**Comment by demisra** [comment]
I've tried to create a standalone geometry configuration which reproduces this result, but getting MultiSegmentation to function correctly outside of the EIC container is quite challenging. When attempting to replicate, the following error is returned by ddsim:

```
ERROR: MultiSegmentation: Invalid sub-segmentation identifier!
Position: Pre (                       (4.72287084139247667736e+02,-2.94995585786709124676e+00,1.75265957691934818286e+03)) Post (                       (4.72282999736711758487e+02,-2.93482350873438679884e+00,1.75269164890685806313e+03))
```

**Comment by MarkusFrankATcernch** [comment]
This sounds quite bizarre:

- Geant4 does not know about segmentations: it only delivers energy deposits at a given position (better betwwen the step's start and end point). 
- The cell id only enters the game in the calorimeter sensitive detector where multiple such deposits are combined to a hit.
- This means something must go wrong in this recombination to calorimeter hits if a multi-segmentation is in place. Difficult to debug without a standalone example, but I think this is the only place where things can go wrong. This means in 
`CellID MultiSegmentation::cellID(...)` things must go bad provided the local position of the deposit is correct.
- The local position is the middle of the pre- and post-step point: can this cause such a bias where the "small" cells suck in part of the shared deposited energy from the larger cells?

**Comment by andresailer** [comment]
I copied your src file (the right one?) and xmls and made a standalone version of the ZDC_WSi 
https://github.com/andresailer/ZDC

Had to add some constants.

Simulated with
`ddsim --compactFile ZDC.xml -G -N 200 --gun.energy "10*GeV" --gun.particle neutron --part.userParticleHandler='' -O out_neutron.root`

At least in these plots I don't see anything really wrong.
I just plot total energy deposit vs. Z position of the hits (I use the root output form dd4hep, _not_ edm4hep)

Simulated muons and pretty much get what I expect from the silicon thickness, right?

![zdc_muon](https://user-images.githubusercontent.com/2115797/202716592-b84b464d-1344-4d54-a139-a168ff95c1f6.png)

Simulated 10 GeV Neutrons, can't really tell that anything goes wrong.

![zdc_neutron](https://user-images.githubusercontent.com/2115797/202715477-f8132f94-8182-481e-8399-ef546b68ba9c.png)

If you could complete the standalone version, or do the same plot you have done before to see if things are wrong?

**Comment by demisra** [comment]
Thanks for putting this together. I compiled the standalone version you provided and made a couple of tweaks to simplify:

```
<lccdd>

  <info name="ZDC"
        title="EPIC ZDC"
        author="Sailer"
        status="development"
        version="alpha">
  </info>

  <comment>Far Forward Hadron Detectors</comment>

  <define>
    <comment>
      -------------------------------------------
      Zero Degree Calorimeter General Parameters
      -------------------------------------------
    </comment>
    <constant name="ZDC_z_pos"         value="35.600 * m"/> 
    <constant name="ZDC_x_pos"         value="0.0 * cm"/>
    <constant name="ZDC_y_pos"         value="0.0 * cm"/>
    <constant name="ZDC_rotateX_angle" value="0.0 * rad"/>
    <constant name="ZDC_rotateY_angle" value="0.0 * rad"/>
    <constant name="ZDC_rotateZ_angle" value="0.0 * rad"/>
    <constant name="ZDC_width"         value="60.0 * cm"/>
    <constant name="ZDC_length"        value="200.0 * cm"/>
    <constant name="world_x"         value="10*m"/>
    <constant name="world_y"         value="10*m"/>
    <constant name="world_z"         value="50*m"/>
    <constant name="ZDC_WSi_ID"  value="13" />
    <comment>
      -------------------------------
      Zero Degree Calorimeter - ECAL
      -------------------------------
    </comment>

    <constant name="ZDC_WSi_z_pos"               value="ZDC_z_pos"/>
    <constant name="ZDC_WSi_x_pos"               value="ZDC_x_pos"/>
    <constant name="ZDC_WSi_y_pos"               value="ZDC_y_pos"/>
    <constant name="ZDC_WSi_rotateX_angle"       value="ZDC_rotateX_angle"/>
    <constant name="ZDC_WSi_rotateY_angle"       value="ZDC_rotateY_angle"/>
    <constant name="ZDC_WSi_rotateZ_angle"       value="ZDC_rotateZ_angle"/>
    <constant name="ZDC_WSi_nblocks"             value="2"/>
    <constant name="ZDC_WSi_pad_nlayers_per_block"         value="10"/>

    <constant name="ZDC_pad_thickness"           value="320.0 * um"/>
    <constant name="ZDC_pixel_thickness"         value="300.0 * um"/>
    <constant name="ZDC_glue_thickness"          value="0.11 * mm"/>
    <constant name="ZDC_PCB_thickness"           value="1.6 * mm"/>
    <constant name="ZDC_Si_Air_thickness"        value="5. *mm"/>
    <constant name="ZDC_Tungsten_thickness"      value="3.5 *mm"/>
    <constant name="ZDC_Lead_thickness"          value="3. *cm"/>
    <constant name="ZDC_Sci_thickness"           value="2.* mm"/>

  </define>


  <includes>
    <gdmlFile ref="${DD4hepINSTALL}/DDDetectors/compact/elements.xml"/>
    <gdmlFile ref="materials.xml"/>
  </includes>

  <include ref="ZDC_WSi.xml"/>

</lccdd>
```

With the standalone version of the geometry, I performed the same analysis (taking the mean of the *sum* of energy deposits in each layer) with `ddsim --compactFile ZDC.xml -G -N 1000 --gun.energy "10*GeV" --gun.particle neutron --part.userParticleHandler='' -O out_neutron.edm4hep.root`, and the issue persists: 

<img width="306" alt="standalone_edep" src="https://user-images.githubusercontent.com/115676845/202792373-e41b4cb9-4e5f-4780-9ccc-2d0c7abbcb6b.PNG">

Comparing to the analogous plot of mean energy depositions:

<img width="406" alt="standalone_edep_edm" src="https://user-images.githubusercontent.com/115676845/202792279-0d0058e4-cf40-4cbe-9be1-25c350e001e2.PNG">

this isn't apparent from the mean energy deposition alone. I also ran a sample of 5000 neutrons at 50GeV, since this issue seems to become more pronounced at higher energies:

<img width="295" alt="standalone_50" src="https://user-images.githubusercontent.com/115676845/202796110-89ed3928-2bfc-49b0-999d-8303df891af3.PNG">

**Comment by andresailer** [comment]
Can you share the script to make that mean sum of energies?
And push your changes as well?

**Comment by demisra** [comment]
> Can you share the script to make that mean sum of energies? And push your changes as well?

I forked the repo since I don't have write access -- my changes are here:
https://github.com/demisra/ZDC

and the Python code: 

```
import os
import uproot as ur
import numpy as np
import pandas as pd

paths = []

for (path, dirnames, filenames) in os.walk('$DATA_PATH/'):
    paths.extend(os.path.join(path, name) for name in filenames)

samples = {}

for path in paths:
    with ur.open(path) as file:
       tree = file["events"]
       samples[os.path.basename(f'{path}')] = tree.arrays()

#Get layerID from cellID
def bitExtract(n, k, p):  
    return (((1 << k) - 1)  &  (n >> (p-1)))

#Get sum of energy depositions in each layer
def layer_edep(data, branch, count):
    edep = pd.DataFrame()

    for i in range(count):
        index = str(i)
        energies = np.array(data[f"{branch}.energy"][i])
        cellID = np.array(data[f"{branch}.cellID"][i])
        layerID = sorted(bitExtract(cellID, 6, 9))
        df = pd.DataFrame({f'{index}': energies, 'layerID': layerID})
        layers = df.groupby("layerID").sum()

        if len(layers) != 0:
            edep = pd.concat([edep,layers], axis=1).replace(np.NaN,0)
            
    return edep

layer_edep(samples['out_neutron_2.edm4hep.root'],"ZDC_WSi_Hits",5000).mean(axis=1).plot()
```

**Comment by demisra** [comment]
> > Can you share the script to make that mean sum of energies? And push your changes as well?
> 
> My changes are here: https://github.com/demisra/ZDC
> 
> and the Python code:
> 
> ```
> import os
> import uproot as ur
> import numpy as np
> import pandas as pd
> 
> paths = []
> 
> for (path, dirnames, filenames) in os.walk('$DATA_PATH/'):
>     paths.extend(os.path.join(path, name) for name in filenames)
> 
> samples = {}
> 
> for path in paths:
>     with ur.open(path) as file:
>        tree = file["events"]
>        samples[os.path.basename(f'{path}')] = tree.arrays()
> 
> #Get layerID from cellID
> def bitExtract(n, k, p):  
>     return (((1 << k) - 1)  &  (n >> (p-1)))
> 
> #Get sum of energy depositions in each layer
> def layer_edep(data, branch, count):
>     edep = pd.DataFrame()
> 
>     for i in range(count):
>         index = str(i)
>         energies = np.array(data[f"{branch}.energy"][i])
>         cellID = np.array(data[f"{branch}.cellID"][i])
>         layerID = sorted(bitExtract(cellID, 6, 9))
>         df = pd.DataFrame({f'{index}': energies, 'layerID': layerID})
>         layers = df.groupby("layerID").sum()
> 
>         if len(layers) != 0:
>             edep = pd.concat([edep,layers], axis=1).replace(np.NaN,0)
>             
>     return edep
> 
> layer_edep(samples['out_neutron.edm4hep.root'],"ZDC_WSi_Hits",5000).mean(axis=1).plot()
> ```

Just caught a bug in the python code here -- sorting the layerIDs decouples the layerIDs from their corresponding energies. However, when fixed, the discrepancy persists (but in the _opposite direction_). Still seems that something is going wrong, though perhaps not double counting of same sort as previously assumed.
[wsiedep_layers.pdf](https://github.com/AIDASoft/DD4hep/files/10233055/wsiedep_layers.pdf)

**Comment by andresailer** [comment]
But those dips in the energy deposits correspond to the thinner silicon layers: pad vs. pixel thickness
https://github.com/andresailer/ZDC/blob/82adb9fb35eb202eb835e9df59d7e500c0e3fa95/compact/ZDC.xml#L45-L46

So I don't think there is anything wrong.

What happens if they have the same thickness?

**Comment by demisra** [comment]
> But those dips in the energy deposits correspond to the thinner silicon layers: pad vs. pixel thickness https://github.com/andresailer/ZDC/blob/82adb9fb35eb202eb835e9df59d7e500c0e3fa95/compact/ZDC.xml#L45-L46
> 
> So I don't think there is anything wrong.
> 
> What happens if they have the same thickness?

This is using the standalone geometry at 50GeV with 320um for both pad and pixel layers:
![uniform_thickness](https://user-images.githubusercontent.com/115676845/207949778-1124e5f2-947f-4a27-9059-e6673332c7dd.png)

**Comment by andresailer** [comment]
The position of the energy deposit is the center of the cell. Cell sizes are 3*mm vs 1*cm, right? So if you get a bit of energy in the neighboring cell for the 1cm cells, this gives you a much bigger spread already.

**Comment by andresailer** [comment]
I will take your thumbs up to mean that this issue is understood, and that there was nothing wrong with DD4hep.
