### ISSUE TITLE
parametrized volumes or replica?

### ISSUE THREAD

**Issue by FriederikeBock** [AIDASoft/DD4hep#1033]
Hi,

I was wondering whether there is a plan to create something similar to 
G4PVReplica
or 
G4PVParameterised
also in DD4Hep.  
I am currently implementing a more complex and realistic geometry for the forward hadronic calorimeter in the ePIC-Software stack, however I am running into trouble with the memory quite quickly if I follow the more classical approach of building each module separately. 
The current proposed code can be found here:
https://github.com/eic/epic/pull/317
https://github.com/eic/epic/blob/4bb7ff9b039d221ed0b66d1e63c99a3c5934d367/src/LFHCAL_geo.cpp (geometry implementation)

One problem for simply cloning or copying the original geometry is that within one of the object I have different sensor IDs not both in longitudinal as well as tranversal segmentaiton and I am not sure how to set the volume names/IDs correctly if I simply copy the volumes. In Geant4 based frameworks (i.e. https://github.com/eic/fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4LFHcalDetector.cc for a similar implementation of the same detector), these kind of problems regarding memory usage were usually solved with either replica or parametrized volumes. 

Any idea whether this feature might be implemented or what I could try otherwise?

Regards,
Friederike

**Comment by MarkusFrankATcernch** [comment]
Actually there is something similar.....

parametrized volumes are not present in TGeo (feature is simply not present),
but when the geometry is translated to Geant4, this feature can be enable to possibly benefit from the simulation parametrized volumes. This is claimed to sometimes be more performant.

See examples/ClientTests/compact/ParamVolume?D.xml for the usage.
In these examples, when translated to G4 the volumes become "parametrized volumes".

**Comment by MarkusFrankATcernch** [comment]
@FriederikeBock Was this question answered? Can we close the issue ?
