### ISSUE TITLE
ddsim and opticks

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#1034]
Hi,
I'd like to try to use opticks in the dd4hep ddsim environment.  There is an example of using it in GEANT4 at https://github.com/hanswenzel/CaTS.  However, before I start looking into this, I wanted to know if this has been done yet (no need to re-invent the wheel).
Best
Sarah Eno

**Comment by MarkusFrankATcernch** [comment]
@saraheno As far as I know this integration was never attempted.

- CaTS uses its own machinery, you probably may use DDG4 to translate the geometry, but all other user hooks must then come from CaTS. 
- What probably needs explict implementation here is the mapping between sensitive detectors and volumes. 
- For the output data model written to some file: This will also be managed by CaTS.

**Comment by MarkusFrankATcernch** [comment]
@saraheno What should we do with this issue?
- The only connection between dd4hep and Cats is via GDML files.
- DD4hep will never be integrated in Cats - unless Hans would be interested. 
  DD4hep is here more on the lines of Key4hep.

The only advantage here in using Cats would be as done before: verify GDML files.
So: Should we close this issue, which has no real chance to evolve?

**Comment by veprbl** [comment]
Would it be possible to use optiks but without CaTS?

**Comment by MarkusFrankATcernch** [comment]
@veprbl I have no clue. 
- I do not know about optiks
- What does it do?
- Where are its benefits ?
I somehow read that it is connected to Geant4, but otherwise: where can one find some documentation about it ?

**Comment by veprbl** [comment]
They claim they are able to boost the optical photon simulation speed performance by offloading that process to GPU (NVidia hardware only?).
The docs look complete: https://juno.ihep.ac.cn/~blyth/opticks/

**Comment by MarkusFrankATcernch** [comment]
I had some look into: **opticks/examples/Geant4/CerenkovMinimal**.
To me it looks like opticks and the interface G4Opticks is not a DD4hep issue.
If someone provides the corresponding classes based on such an example supporting the DD4hep factory methods,
**opticks** can very likely be steered and interfaced to DDG4 given,
- DD4hep automatically converts the geometry to Geant4 (G4Opticks then to **opticks**)
- According to the example then a sensitive detector using **opticks** must be instantiated.
- The **opticks** G4VProcesses (CKMScintillation etc.) must be put behine the factory mechanism.
- Probably the tracking and stacking, event, etc. actions as well and be added to the corresponding DDG4 sequences.
That should be grossly speaking most of it. Does not look like too much work.

But I do not think this should be done as part of DD4hep , but rather as some external package.
Alone the dependencies would cause me a major headache.
Hence: I rest my case. This issue should be closed.

**Comment by saraheno** [comment]
You can close it.  I will though look for somebody to find a way to use these gpus with the optical photons while interfacing somehow with geometry built in the  dd4hep environment.  There are many detectors that are light-based, especially all the IDEA calorimeters.  They would benefit from this.
