### ISSUE TITLE
Beginner's question: export root to xml

### ISSUE THREAD

**Issue by arazquinliz** [AIDASoft/DD4hep#1035]
Hello, I am trying to use DD4Hep to export a Geant4 geometry into a xml file. I have a root file already with the geometry, is there a simple way to get an "equivalent" xml with the geometry?

Thank you in advance!

**Comment by MarkusFrankATcernch** [comment]
The only way to export a Geant4 geometry to xml supported by dd4hep is the gdml syntax.
There are several ways possible. See for example:
- `<dd4hep>/examples/CLICSiD/scripts/CLIC_GDML.py`. A script loading a geometry translating it to Geant4
   and then dumping it directly to gdml.
- `<dd4hep>/examples/CLICSiD/Cmakeists.txt` 
   example `CLICSiD_GDML_export_LONGTEST` and `CLICSiD_GDML_import_LONGTEST`. Here the geometry is loaded to ROOT and then dumped to gdml. The gdml file then can be loaded into Geant4. Please note, there were recent developments in ROOT to fix certain problems using G4 units.

**Comment by MarkusFrankATcernch** [comment]
Didi the above answer explain the issue ?
Can this issue be closed ?

**Comment by arazquinliz** [comment]
Yes, sorry for the late reply. Thank you.
