### ISSUE TITLE
add beta to MonteCarloContrib

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#1037]
Hi,
For dual-readout calorimetry studies, it would be useful to have the speed of the track added to the MonteCarloContrib in Geant4Data.h
thanks
Sarah Eno

**Comment by MarkusFrankATcernch** [comment]
@saraheno I'll bring it up in the next developers meeting.

**Comment by MarkusFrankATcernch** [comment]
@saraheno Please check PR #1044 if it satisfies your needs. I added the 3-momentum rather than the beta to the MC contribution.

**Comment by MarkusFrankATcernch** [comment]
@saraheno Please check PR https://github.com/AIDASoft/DD4hep/pull/1044 if it satisfies your needs. I added the 3-momentum rather than the beta to the MC contribution.

**Comment by saraheno** [comment]
Hi Markus,
My semester is about to begin, so my research time will plunge.  However, I am working with a new PhD student, @mekhpar and she will look at it.  She is just learning C++ though, so it may take a bit...

**Comment by MarkusFrankATcernch** [comment]
Considered fixed.
If not, please re-open.
