### ISSUE TITLE
example that shows how to read events into ddsim from a file?

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#1040]
Hi,
Do any of the examples in the examples area show how to read events into ddsim from  a file?  We are looking to use the CRY cosmic-ray shower generator, and I would guess the easiest way to get the events in is via this mechanism?
Thanks
Sarah Eno

**Comment by andresailer** [comment]
The answer to your CRY of help is here https://github.com/AIDASoft/DD4hep/issues/940
Cheers,
Andre

**Comment by saraheno** [comment]
thanks!
