### ISSUE TITLE
`std::pair<double, double> EghtPointSolid::vertex(int which) const`: gcc-10.1+ with C++17 warns a lot on aarch64

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/DD4hep#1043]
- OS version: ubuntu
 - Compiler version: gcc-12.2.0
 - Package version: dd4hep-1.23
 - Goal: use DD4hep in Mac M1/M2 stacks
 - Reproduced by: exact steps to reproduce the problem: checkout, setup environment (Geant4/ROOT version, LCG/iLCSoft/Key4hep release), cmake, build, run...
   - This is a rather heavy minimal example since it requires building a whole HEP stack on aarch64... which I do in qemu and takes many hours... 

The issue is in [Shapes.h](https://github.com/AIDASoft/DD4hep/blob/master/DDCore/include/DD4hep/Shapes.h#L1758), which is included indirectly in all user classes through Detector.h. That results in warnings such as:
```
#42 27.11 In file included from /usr/._local/pngv3ezdlqpfj7bpyjk3r2usgmgqukvs/include/DD4hep/Detector.h:22,
#42 27.11                  from /usr/._local/pngv3ezdlqpfj7bpyjk3r2usgmgqukvs/include/XML/Helper.h:18,
#42 27.11                  from /usr/._local/pngv3ezdlqpfj7bpyjk3r2usgmgqukvs/include/DD4hep/DetFactoryHelper.h:18,
#42 27.11                  from /tmp/det/src/FieldMapBrBz.cpp:4:
#42 27.11 /usr/._local/pngv3ezdlqpfj7bpyjk3r2usgmgqukvs/include/DD4hep/Shapes.h: In member function ‘std::pair<double, double> dd4hep::EightPointSolid::vertex(int) const’:
#42 27.11 /usr/._local/pngv3ezdlqpfj7bpyjk3r2usgmgqukvs/include/DD4hep/Shapes.h:1758:57: note: parameter passing for argument of type ‘std::pair<double, double>’ when C++17 is enabled changed to match C++14 in GCC 10.1
#42 27.11  1758 |     std::pair<double, double> vertex(int which) const   {
#42 27.11       |                                                         ^
```

The underlying issue is https://gcc.gnu.org/gcc-10/changes.html#empty_base (which aarch64 started warning about in gcc-12.2, https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=b243ad1afb7f06ef4ab7649600d900b09b9c6b52). I'm not sure what to do about the call (or whether to just shut it up with a pragma to `-Wno-psabi` for those lines), but it's very noisy since it emits a warning for every detector plugin  :-)

**Comment by wdconinc** [comment]
> which aarch64 started warning about in gcc-12.2

Not exactly the right commit, but it points to the code where gcc emits the warning.

**Comment by MarkusFrankATcernch** [comment]
This is a very bizarre warning. 
Yes a fix would probably be to enclose this very function in something like:
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wno-psabi"
    std::pair<double, double> vertex(int which) const   {
      const double* values = access()->GetVertices();
      return std::make_pair(values[2*which], values[2*which+1]);
    }
#pragma GCC diagnostic pop
```
But I do not understand the reasoning: a problem would only arise if code with different ABI standards would be mixed...
One question is if the warning arises from the inline code (then we could move this code to the cpp) or already from the function declaration. In the header I do not really like the `#pragma` statements, in the cpp it would be tolerable....
We unfortunately also do not really have a testbed for the `aarch64` configuration.

**Comment by wdconinc** [comment]
> We unfortunately also do not really have a testbed for the `aarch64` configuration.

I'm with you there: I don't have an `aarch64` system either :-) All that is on qemu for me... very... very... slowly... (fortunately most of the time it runs just fine on its own on a build farm).

I agree it's a strange warning and not really a problem, per se. But it may prevent people from running with `-Wall -Werror`. I'll try some more things. It is likely that a return type of `std::tuple<double,double>` does not have the same issue, but it would be an API change and be slightly less performant.

**Comment by MarkusFrankATcernch** [comment]
First of all, this is a temporary issue and probably will disappear in a few GCC versions ahead.
Secondly I would suggest to ignore this warning until someone really faces the problem in real ie. is directly affected.

Then we rethink and try to solve together with the guy the problem. I am simply against solving problems which may appear at some time in the future..... At this very moment also the question of the testbed is solved.
BTW. How do you know that this is causing these warnings ? Perhaps you are already our volunteer ;-D

**Comment by andresailer** [comment]
If these kind of changes only happen when new major versions are release (there are no .0 releases?), we don't run into these issues, because everything in our communities is always compiled with the same major version of a compiler, right?

**Comment by MarkusFrankATcernch** [comment]
I was yesterday building on ubuntu with gcc-12 (12.1.0) and I did not see any of these warnings.
There must be something else in addition.......

**Comment by andresailer** [comment]
ubuntu on aarch64?

**Comment by andresailer** [comment]
PS: we are building DD4hep on aarch64 for the lcg stacks, e.g.: /cvmfs/sft.cern.ch/lcg/nightlies/dev4/Tue/DD4hep/01.23/aarch64-centos7-gcc11-opt/logs/DD4hep-01.23-build.log

**Comment by wdconinc** [comment]
> DD4hep on aarch64 for the lcg stacks

I notice the same warning in those logs too.

**Comment by wdconinc** [comment]
I think `-Wno-psabi` as a (gcc-only?) flag in DD4hep would be fine. I'm indeed not worried about actual ABI incompatibility, only about the number of warnings which might mask other warnings.
