### ISSUE TITLE
Propagation of ions

### ISSUE THREAD

**Issue by michael-pitt** [AIDASoft/DD4hep#1051]
In the current version, ion (particles with pdgId = 100AAAZZZI) and status = 1 fail to be appropriately treated by the `ddsim`. 
Keeping the ions and simulating their propagation in G4 is an important feature in studying incoherent processes in eA collisions and beam backgrounds.

Looks like #920 tries to handle with ions, but I not sure if this is the case.

Thanks,
Michael

**Comment by andresailer** [comment]
Hi @michael-pitt 

Yes, #920 should treat ions correctly as long as they are not excited (I==0). And in its current incarnation will treat ions with I>0 the same as if they were not excited. So far we have been unable to understand where to obtain the necessary information from in cases of I>0.
(See also the issue #918. and https://geant4-forum.web.cern.ch/t/g4iontable-findion-with-excitation-level-nullptrs/9224)

**Comment by michael-pitt** [comment]
Hi @andresailer ,
Thanks for quick answer! Do you have an estimate of when #920 can be ready to be merged? Some MC generators for Heavy Ion collisions produce such particles at the final state, and this RP would be essential for a large community.

Regards,
Michael

**Comment by andresailer** [comment]
Hi @michael-pitt 

That really depends how important these excited states are for the correctness of the simulation. At the moment I have no idea how to treat those correctly. Otherwise the simulation runs OK...

Let me try pushing our Geant4 colleagues for an answer...

**Comment by michael-pitt** [comment]
Hi @andresailer.

In the meantime, maybe the current implementation can be merged? Otherwise, we cannot use DD4hep with the eA simulations. This solution for excited ions may be a good approximation for the propagation of ion remnants in a magnet field, as we only use A/Z and ion energy.

**Comment by andresailer** [comment]
OK, I will clean up the merge request and print some warnings when excitation levels cannot be accommodated.

**Comment by andresailer** [comment]
@michael-pitt Would you like to review #920 ?

**Comment by michael-pitt** [comment]
Hi @andresailer, I will try to test it with our simulation software. adding @kkauder @wdconinc maybe they can take a look as well.

Thanks a lot!

**Comment by wdconinc** [comment]
Confirming that #920 works in our context and I think this issue can be considered resolved when #920 is merged. We'll be testing this at scale over the weekend and there may be an appendix if we notice that somehow excited ions are created.
