### ISSUE TITLE
Error in generation of root file using dd_web_display

### ISSUE THREAD

**Issue by yasirali12345** [AIDASoft/DD4hep#1057]
Dear Experts
I am using Ubuntu 22.04 and gcc 12.2.0
I am adding a new volume detector to Lumi it compiles well but When I run   

 dd_web_display --export $DETECTOR_PATH/$DETECTOR_CONFIG.xml  

 it gives this error:      Compact          ERROR ++ FAILED    to convert subdetector: LumiDirectPCAL: Handle_t::child: Element [detector] has no child of type 'module'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Handle_t::child: Element [detector] has no child of type 'module'
Aborted (core dumped)

Both xml and cpp files are attached here
[directPC_xml.txt](https://github.com/AIDASoft/DD4hep/files/10684941/directPC_xml.txt)

[LumiDirect_geo.txt](https://github.com/AIDASoft/DD4hep/files/10684938/LumiDirect_geo.txt)
Please suggest a solution

**Comment by andresailer** [comment]
You are most likely not exporting your library location in the LD_LIBRARY_PATH.

**Comment by yasirali12345** [comment]
may be not with xml but possibly cpp file

**Comment by andresailer** [comment]
can you push your whole project to github? makes it easier to browse.

**Comment by yasirali12345** [comment]
should be git push ~/epic ???

**Comment by andresailer** [comment]
I am sorry, but I am not able to give you a git tutorial here. 
Please have a look at the Epic/EIC resources, and their instructions about developments and integrations.

In your cpp file you are asking for an XML tag `<module>` but there is no such tag in your XML file. So  your cpp and XML have to agree on this structure.
