### ISSUE TITLE
Toroidal magnetic field (ATLAS like)

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/DD4hep#1092]
This is basically meant as a sort of discussion issue on how to best achieve an ATLAS like toroidal magnetic field. Or maybe also to check whether someone has already implemented something like this. Tagging @madbaron as well for more input or questions.

Technically it should be possible to implement a magnetic FieldMap (inheriting from `dd4hep::CartesianField::Object` and implementing the `fieldComponents` method). This would in principle also allow to use a parametrization of the toroidal field directly without. I.e. we would not really need some sort of mapping of 3D position -> 3D field vector, and an interpolation between those if there is an analytical parametrization for this?

Another possibility would be to superpose several simpler constant magnetic fields, but I am not entirely sure if that is possible. From a quick glance into the implementation of the solenoidal field, it looks like this should work:
https://github.com/AIDASoft/DD4hep/blob/23740aa55fc07fae69e58bb66c8c0f67714e1ffa/DDCore/src/FieldTypes.cpp#L61-L64
(at least if I understand the `+=` assignment correctly here). However, here I am not sure how (and if) this works from a compact file. Can we simply define several magnetic fields (with a region?) and the resulting magnetic field will be the sum of all individual ones at a given point?

**Comment by andresailer** [comment]
There are fieldmap plugins in k4geo

https://github.com/key4hep/k4geo/blob/master/detector/other/FieldMapXYZ.cpp
https://github.com/key4hep/k4geo/blob/master/detector/other/FieldMapBrBz.cpp

We could upstream those

**Comment by tmadlener** [comment]
Is there some documentation of how the field map has to be layed out in the root file / TTree for the `FieldMapXYZ`? However, if there is a parameterization for a Toroidal map, it might be easier to just implement a new FieldType directly, instead of going the extra step of producing a field map first and then reading that back in and do interpolation.

**Comment by andresailer** [comment]
I think this is the only documentation for how things can be used...

https://github.com/key4hep/k4geo/blob/c156b6f933ee534eb5e48801078a50d6968d67c5/ILD/compact/ILD_o1_v05/ILD_o1_v05.xml#L594-L627

The fieldmap itself is a tree with columns given by the various varName names

**Comment by MarkusFrankATcernch** [comment]
Question: Can one ignore the contributions or the returns at the ends of the Toroid  to the B field ?
If yes, The individual contributions of each straight section of the toriod could be computed analytically e.g. accrding to
[this explanation](https://phys.libretexts.org/Bookshelves/University_Physics/Book%3A_University_Physics_(OpenStax)/Book%3A_University_Physics_II_-_Thermodynamics_Electricity_and_Magnetism_(OpenStax)/12%3A_Sources_of_Magnetic_Fields/12.03%3A_Magnetic_Field_due_to_a_Thin_Straight_Wire). See the result of the integration (eq 12.3.5 and 12.3.6).

**Comment by MarkusFrankATcernch** [comment]
@tmadlener Can this be closed ?

**Comment by tmadlener** [comment]
Yes. We will re-open if necessary
