### ISSUE TITLE
Viewing event display with multiple events in ddsim

### ISSUE THREAD

**Issue by Mekhpar** [AIDASoft/DD4hep#1096]
Hi,

I am trying to run multiple events in the interactive mode (vis) with ddsim and I would like to reproduce the display for any individual event after they have been run. Where can I access the random numbers associated with any particular event?

Thanks,
Mekhala

**Comment by andresailer** [comment]
Hi @Mekhpar 

Are you fixing the global random seed when running ddsim?
As long as the global random seed (e.g., --random.seed 12354) is fixed, the skipping of events should give you the same result, as when not skipping events.

If you have the full output you should see something related to the random seed
```
DDSim.Helper.Random INFO Choosing random seed for you: 1601811713
```

Cheers,
Andre

**Comment by andresailer** [comment]
I forgot, you need to enable the "event seeder" for ddsim.
```
SIM.random.enableEventSeed = True
```

**Comment by andresailer** [comment]
I think the question was answered, so closing this.
