### ISSUE TITLE
Adjust default output based on compiled format support

### ISSUE THREAD

**Issue by veprbl** [AIDASoft/DD4hep#1101]
```
ddsim --compactFile "$DETECTOR_PATH/$DETECTOR_CONFIG.xml" --enableGun --numberOfEvents 1
```
```
Traceback (most recent call last):
  File "/prefix/bin/.ddsim-wrapped", line 25, in <module>
    RUNNER.run()
  File "/prefix/lib/python3.10/site-packages/DDSim/DD4hepSimulation.py", line 341, in run
    lcOut = simple.setupLCIOOutput('LcioOutput', self.outputFile)
  File "/prefix/lib/python3.10/site-packages/DDG4.py", line 783, in setupLCIOOutput
    evt_lcio = EventAction(self.kernel(), 'Geant4Output2LCIO/' + name, True)
  File "/prefix/lib/python3.10/site-packages/DDG4.py", line 215, in EventAction
    return Interface.createEventAction(kernel, str(nam), shared)
cppyy.gbl.std.runtime_error: static dd4hep::sim::EventActionHandle dd4hep::sim::Geant4ActionCreation::createEventAction(dd4hep::sim::KernelHandle& kernel, const string& name_type, bool shared) =>
    runtime_error: Geant4Handle: Failed to create object of type Geant4Output2LCIO!
```

I think, it would be nice to default to some other supported format (e.g. edm4hep or root) instead.

**Comment by wdconinc** [comment]
Maybe it makes sense to not write any output when it hasn't been requested. We often run `ddsim` just to test the geometry parsing or in visualization mode, and we don't actually care to provide an output file argument.

**Comment by veprbl** [comment]
This also is giving the same error:
`ddsim --compactFile "$DETECTOR_PATH/$DETECTOR_CONFIG.xml" --runType vis`

And `ddsim --compactFile "$DETECTOR_PATH/$DETECTOR_CONFIG.xml" --runType vis --outputFile /dev/null` fails with
`ERROR: Unknown fileformat for file: ['/dev/null']`

**Comment by MarkusFrankATcernch** [comment]
Defaulting to an alternative output format is certainly a no-go.
Simulation is quite at the beginning of the data processing chain and typically all following steps depend on the output format.
Defaulting (instead of failure) almost certainly is the wrong choice.

Can we close this issue?

**Comment by andresailer** [comment]
The current default for ddsim is to write output to dummyOutput.slcio, regardless of how DD4hep was configured. Which is certainly annoying if you do not build with LCIO support. So at least not trying to load the LCIO Output plugin in cases where that doesn't exist isn't going to do any harm.

> Maybe it makes sense to not write any output when it hasn't been requested. We often run ddsim just to test the geometry parsing or in visualization mode, and we don't actually care to provide an output file argument.

There is no output written if no `/run/beamOn` is called, but the outputplugin is still loaded.
