### ISSUE TITLE
getRefChild produces unsilenceable output in cout

### ISSUE THREAD

**Issue by veprbl** [AIDASoft/DD4hep#1102]
- OS version: any
 - Compiler version: any
 - Package version: master
 - Reproduced by: `m_geoSvc->detector()->readout("does not exist").idSpec();`
 - Input:
 - Output:
 - Goal: 

The line
https://github.com/AIDASoft/DD4hep/blob/84f2e45ec8a26efbfb6da07258be895310e652bf/DDCore/src/DetectorImp.cpp#L649-L652
produces lengthy messages like
```
GetRefChild: Failed to find child with name: 'does not exist'. Map foo contains X elements:
<X lines of output here>
```
while this output may be useful for debugging, it is not optimal that a library is producing such output unconditionally. This pollutes output in certain user applications.

I'm not sure how a typical call graph for `getRefChild` looks like, but one generic way to handle such things is to add the `const HandleMap& e` as a context to the exception, so that the end-user application can produce the output as needed. A simpler change could be to print all this stuff into a stringsteam and then add to the `what` parameter of the std::runtime_exception thrown.

**Comment by MarkusFrankATcernch** [comment]
Fixed by PR1106
