### ISSUE TITLE
Allow isotrope generator to throw range around specified (reference) direction

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/DD4hep#1103]
The [DDG4/src/Geant4IsotropeGenerator.cpp](https://github.com/AIDASoft/DD4hep/blob/master/DDG4/src/Geant4IsotropeGenerator.cpp) allows for throwing angular distributions in theta and phi, but these angular distributions are always with respect to the z axis. In collider configurations with beam crossing angles, this works (at most) for one of the sides, but is not ideal for the generation of particles close to the beam axis in the other side.

In particular, at the EIC, where the crossing angle is 25 mrad, some of the far forward detectors (zero degree calorimeters) have an acceptance of 10 mrad around the 25 mrad beam direction. We are not able to generate a distribution of particles that is covering this detector, except by generating a distribution around the z axis (at 0 mrad) with a theta from 15 to 35 mrad, and a phi within a larger range as well. This is clunky and has led to errors already.

The direction is passed to the Geant4IsotropeGenerator (see below for a copy of the code), so it is possible in the lines below to interpret x1, x2, x3 in terms of a rotation with respect to this (reference) direction, not simply overriding the direction with `direction.SetXYZ(x1,x2,x3)`.

There is ambiguity in the definition of phi = 0 when the specified direction is not in the xz plane. phi = 0 could continue to correspond to the global x coordinate direction, but a better choice is probably to define phi = 0 as in the plane defined by the global z axis and the specified direction. This has the annoying unnatural feeling when the specified direction is in the yz plane by even epsilon, since then phi = 0 changes by 90 degrees.

Original code:
```cpp
/// Uniform particle distribution
void Geant4IsotropeGenerator::getParticleDirectionUniform(int, ROOT::Math::XYZVector& direction, double& momentum) const   {
  Geant4Event&  evt = context()->event();
  Geant4Random& rnd = evt.random();
  double phi   = m_phiMin+(m_phiMax-m_phiMin)*rnd.rndm();
  double theta = m_thetaMin+(m_thetaMax-m_thetaMin)*rnd.rndm();
  double x1 = std::sin(theta)*std::cos(phi);
  double x2 = std::sin(theta)*std::sin(phi);
  double x3 = std::cos(theta);

  direction.SetXYZ(x1,x2,x3);
  getParticleMomentumUniform(momentum);
}
```

I'm still wrapping my head around the spherical mechanics of all this, but instead of `direction.SetXYZ` it would be easiest if we can define a suitable rotation based on x1, x2, x3 (or theta and phi), and apply it in place to the direction since the interface is call by reference.

Alternatives considered: `crossingAngleBoost`, but this doesn't quite do the same (and applies a boost as well).

**Comment by andresailer** [comment]
Hi @wdconinc 
Did you have a look at the Geant4 GeneralParticleSource, if that supports the distribution you require?

**Comment by atolosadelgado** [comment]
Hi @andresailer @wdconinc 

After playing with the GPS for a while, I can add that:
* GPS allows to rotate the source, but...
* If no angle distribution (or any other option) is given, a given absolute direction is assumed independently of the rotation of the source, that is, `/gps/pos/rot1` is ignored. I am not sure if this is bug or undocumented feature.
* If `/gps/pos/type/ is not Point, then you can use `/gps/pos/rot1` and `/gps/pos/rot2` to rotate the source, AND `/gps/ang/type user`, `/gps/ang/surfnorm True`, if you want the particles to be perpendicular to the surface. Of course, you can specify a very complicated angular distribution instead, using UI or histograms.

Example of a macro file,

```
/gps/particle geantino

# source
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0. 0. 0. cm
/gps/pos/radius 2. cm
/gps/pos/rot1 1. 0. 0.57735

# angular distribution
/gps/ang/type user
/gps/ang/surfnorm True
```

And this would be a screenshot of the geometry and particles: 
![image](https://github.com/AIDASoft/DD4hep/assets/114166109/492d39b4-4076-4b07-88d3-6d9f1f5b6190)

I hope these comments help :)

Best,
Alvaro

**Comment by MarkusFrankATcernch** [comment]
I am tempted to sort of close this issue due to inactivity. 
In principle this isotrope generator throws ranges.

- I guess shooting ranges in phi has limited use cases unless one want the examine cracks of the detector....
- All collider experiments are typically symmetric around Z (beam axis) hence theta distributions are sufficient.
- The only limit is that the distributions are flat between [min,max]. Sometimes other distributions like gaussian 
   might be favored.

Should we close this issue?

**Comment by wdconinc** [comment]
I think it is fine to close this. If we think of something, we'll submit it as a pull request.

The GPS is an alternative indeed (but we have stayed away from this since that would be the only use of the GPS, and for user learning purposes it not optimal). Generating over half of a phase space doesn't result in simulation coverage that can be interpreted easily and from which efficiencies can be derived.
