### ISSUE TITLE
Segmentation readout

### ISSUE THREAD

**Issue by Gongzi-Zhang** [AIDASoft/DD4hep#1107]
Hi, I am building a calorimeter of the EIC epic ZDC_Sampling type (https://github.com/eic/epic/blob/main/src/ZeroDegreeCalorimeterSampling_geo.cpp), and here is the geometry file:
```
<lccdd>
  <info name="ECal_Prototype" title="ECal Prototype"
        author="EIC ECal Prototype"
	url="https://github.com/eic/epic"
	status="development"
	version="v1 2023-05-01">
  </info>

 <define>
    <constant name="Pi" value="3.14159265359"/>
    <constant name="world_side" value="30*m"/>
    <constant name="world_x" value="world_side"/>
    <constant name="world_y" value="world_side"/>
    <constant name="world_z" value="100*m"/>
    <constant name="tracker_region_zmax" value="10*m"/>
    <constant name="tracker_region_rmax" value="1*m"/>
  </define>

<includes>
    <gdmlFile ref="compact/elements.xml"/>
    <gdmlFile ref="compact/materials.xml"/>
</includes>

  <detectors>
    <detector id="1" name="HCAL1" type="ZDC_Sampling" readout="HCALHits">
      <position x="0*cm" y="0*cm" z="500*cm"/>
      <rotation x="0" y="0" z="0"/>
      <dimensions x="9.48*cm" y="9.48*cm" z="28.2*cm"/>
      <layer repeat="10">
        <slice name="Absorber_slice"  material="Steel235"    thickness="2*cm"  vis="AnlGray"/>
        <slice name="Scint_slice"     material="Polystyrene" thickness="0.3*cm" vis="AnlOrange" sensitive="true"/>
	<slice name="Air_gap"         material="Air"         thickness="0.52*cm" />
      </layer>
    </detector>
  </detectors>

  <readouts>
    <readout name="HCALHits">
      <segmentation type="CartesianGridXY" grid_size_x="4.74 * cm" grid_size_y="4.74 * cm"/>
      <id>system:8,layer:12,slice:12,x:32:-16,y:-16</id>
    </readout>
  </readouts>
</lccdd>
```
The sensitive slice is segmented into 2x2 cells as shown by the segmentation tag. The problem is the a lot of simulated hits locate at the dividing lines (x/y = 0) as shown in the following 2 plots, can you explain why and how to avoid it, thank you.

ps: I am also confused about the `id` in the readout tag, how to setup the id and how (where) they are interpreted? 

![hit_x](https://user-images.githubusercontent.com/35883446/236657694-a28d3a4f-f96d-4ee1-a078-c487b54667ba.png)
![hit_y](https://user-images.githubusercontent.com/35883446/236657700-db6da892-e206-4e71-88b1-e5b1820c03cd.png)

**Comment by veprbl** [comment]
@Gongzi-Zhang This doesn't seem to be an issue with DD4hep. Please ask your question on ~Helpdesk channel of the ePIC Mattermost or on the ePIC SC mailing list. Thank you.

**Comment by MarkusFrankATcernch** [comment]
@veprbl Thanks for pointing this out.
@Gongzi-Zhang Please have a look in the ClientTests examples. There are multiple examples how to define the cell identification using the ID field. Effectively it is the union of multiple bitfields compressed into one 64 bit integer.
One has to be careful with defining the range in a sub-field (module, sensor, etc.). If you overrun exceeding bits are
masked off and never taken into account.

**Comment by Gongzi-Zhang** [comment]
Thank you.
