### ISSUE TITLE
Merging collections with the same name in EDM4hep output

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/DD4hep#1110]
Moving this over from https://github.com/AIDASoft/DD4hep/issues/1111 as this is something that is better handled on the DD4hep side of things. As mentioned there having DD4hep commit the different collections only at the end of an event and keeping an internal map should solve the issue. The main thing to understand is potential multi threading issues.

https://github.com/AIDASoft/DD4hep/pull/1108 is already addressing this I just see.

**Comment by andresailer** [comment]
Transferred #1111 from aidasoft/podio

**Comment by andresailer** [comment]
PS: I hope #1111 eventually shows up in the list of dd4hep issues...
