### ISSUE TITLE
Persist HepMC3 GenRunInfo attributes into metadata tree

### ISSUE THREAD

**Issue by simonge** [AIDASoft/DD4hep#1114]
I would like to be able to save the attributes found in the header of hepmc3 files into the edm4hep output file.

The specific case is to keep track of the EIC beam settings used when creating the events so that the analysis can automatically choose the correct parameters in our reconstruction software.
[https://github.com/eic/epic/issues/433](https://github.com/eic/epic/issues/433)

**Comment by simonge** [comment]
Here's an example header and first event:

HepMC::Version 3.02.05
HepMC::Asciiv3-START_EVENT_LISTING
A ab_afterburner_is_used 1
A ab_crossing_angle 0.025
A ab_hadron_beta_crab_hor 1300000
A ab_hadron_beta_star_hor 800
A ab_hadron_beta_star_ver 71
A ab_hadron_divergence_hor 0.00015
A ab_hadron_divergence_ver 0.00015
A ab_hadron_rms_bunch_length 60
A ab_hadron_rms_emittance_hor 1.8e-05
A ab_hadron_rms_emittance_ver 1.6e-06
A ab_lepton_beta_crab_hor 150000
A ab_lepton_beta_star_hor 590
A ab_lepton_beta_star_ver 57
A ab_lepton_divergence_hor 0.000202
A ab_lepton_divergence_ver 0.000187
A ab_lepton_rms_bunch_length 9
A ab_lepton_rms_emittance_hor 2.4e-05
A ab_lepton_rms_emittance_ver 2e-06
A ab_use_beam_bunch_sim 1
E 0 0 3 @ -6.5024151476483341e-02 -3.2340523959240464e-03 7.2836286194717754e+00 -1.1102591305812023e+01
U GEV MM
P 1 0 11 4.2508796564667828e-03 -5.8584259080712124e-03 -1.7998543314502502e+01 1.7998544777183362e+01 5.1099893142581812e-04 4
P 2 0 2212 -6.9311463844881480e+00 5.4207920991167266e-02 2.7497614467409414e+02 2.7506509088373292e+02 9.3827199999779787e-01 4
P 3 0 11 -3.7399015456729967e-02 9.1181641786588441e-02 -2.9884078204437636e-01 3.1467261129396185e-01 5.1100844990360089e-04 1

The run attributes are added by an afterburner which adds the realistic, randomized beam effects to each event.

**Comment by andresailer** [comment]
There is something that you can do right now by adding something like this to your steering file.
I.e., make a custom user plugin function that just does what edm4hep plugin does, but before that write all the parameters from the ascii file to "meta" so they end up in the runheader.
If you can give up the inputFile setting on the command line, you can also directly add things to the `SIM.meta` section. But there is no other hook at the moment that get's executed at the right time, I think.

```python

def writeRunInformation(dd):
  for inputFile in dd.inputFiles:
    if inputFile.endswith(".hepmc3"):
      with open(inputFile) as hepmcFile:
        for aLine in hepmcFile.readlines():
          if aLine.startswith("A ") and aLine.count(" ") > 1:
            print("Checking a line", aLine.strip())
            _, key, value = aLine.split(" ", 2)
            setattr(dd.meta, key, value.strip())

  from DDG4 import EventAction, Kernel
  kernel = Kernel()
  myOutput = EventAction(kernel, 'Geant4Output2EDM4HEP/' + dd.outputFile, True)
  myOutput.Control = True
  myOutput.Output = dd.outputFile
  myOutput.enableUI()
  myOutput.RunHeader = dd.meta.addParametersToRunHeader(dd)
  outPars = dd.meta.parseEventParameters()
  myOutput.EventParametersString, myOutput.EventParametersInt, myOutput.EventParametersFloat = outPars
  myOutput.RunNumberOffset = dd.meta.runNumberOffset if dd.meta.runNumberOffset > 0 else 0
  myOutput.EventNumberOffset = dd.meta.eventNumberOffset if dd.meta.eventNumberOffset > 0 else 0
  kernel.eventAction().add(myOutput)

SIM.outputConfig.userOutputPlugin = writeRunInformation
```

(It works for LCIO, I am not correctly set up for EDM4hep :/ (actually because LCIO writes the runHeader before the input reader is created, there is no other way, but that shouldn't concern EDM4hep output...))


I am working on extracting the parameters in the plugin

**Comment by simonge** [comment]
Great, thanks a lot!
