### ISSUE TITLE
Change WorldVolume material from Air

### ISSUE THREAD

**Issue by aciarma** [AIDASoft/DD4hep#1116]
Hi,

the WorldVolume is created automatically and it is assigned the material 'Air'.
Is there a way to change this material? (eg. to 'Vacuum')
Because I don't know where to put this attribute, as the creation of this volume is hidden.

I am working on lxplus with key4hep.

Thanks,
Andrea

**Comment by MarkusFrankATcernch** [comment]
Hi,
I think you cannot only set the material, but you have to define externally the world volume.
Please see the test example here: [WorldVolume.xml](https://github.com/AIDASoft/DD4hep/tree/master/examples/ClientTests/compact/WorldVolume.xml)

**Comment by MarkusFrankATcernch** [comment]
@aciarma Hi Andrea,
Did this answer solve your problem?
Markus

**Comment by MarkusFrankATcernch** [comment]
@aciarma Did you update the code and recompile? 
The test is running in the release procedure. There must be some difference.

**Comment by aciarma** [comment]
I am sourcing the latest key4hep release, so DD4hep should be updated?

**Comment by MarkusFrankATcernch** [comment]
Don't know which version key4hep uses. This only works with the dd4hep PR 1126.

**Comment by aciarma** [comment]
Ok thank you very much, so I did a fresh install of DD4hep and the example works.
I expected the key4hep environment to be in sync with DD4hep, as it is an important part of it...

I tried sourcing `thisdd4hep_only.sh` after sourcing the key4hep setup, but I noticed that it does not overwrite the DD4hep env variables somehow, so pointing to the "wrong" ones.
