### ISSUE TITLE
Problem with graphical user in geant4

### ISSUE THREAD

**Issue by fati-sys** [AIDASoft/DD4hep#1118]
i have ubuntu version 20.04 and geant version10 
the tolkit does work with its output but the problem is i can not visualise the geometry i have turn the Qt11 On during my instalation but still same problem please if you can provide any solution for this it would be super helpful for me thank yoy

**Comment by andresailer** [comment]
Dear @fati-sys your bug report is much too vague to even start understand where things go wrong for your. We need _all_ of this information:

 - OS version: e.g. centos7
 - Compiler version: e.g GCC 8.0
 - Package version: tag or commit ID, or GitHub branch
 - Reproduced by: exact steps to reproduce the problem: checkout, setup environment (Geant4/ROOT version, LCG/iLCSoft/Key4hep release), cmake, build, run...
 - Input: link to input files if applicable
 - Output: full build and run log output
 - Goal: A short description of what you are trying to achieve

**Comment by fati-sys** [comment]
> Dear @andresailer here are the informations : Windows 10 Pro
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Package version : Geant4 10.7.4
root version 6.29/01
cmake version 3.16.3
I have instaled WSL version 2 
I tried to run examples of geant4 basic examples and also advanced one by typing the command ./exampleB1 or ./exampleB1 "vis.mac" but none of them worked to show the UI while in (topas) its not the case

**Comment by andresailer** [comment]
Dear @fati-sys 

`./exampleB1` is not part of DD4hep, is it?
And what is "topas"?

Which dd4hep command are you using?

**Comment by fati-sys** [comment]
Dear @andresailer   I don't know what DD4hep is. I mentioned (topas as another software which the user interface worked for it ) the command ./exampleB1 is from instructions to execute  in the 'interactive mode' with visualization

**Comment by andresailer** [comment]
DD4hep is the software in whose Issue tracker you are asking Questions.
So if you don't have a question for DD4hep, then you are in the wrong place.

**Comment by fati-sys** [comment]
Yes, I believe you are right ! Thank you
