### ISSUE TITLE
How to check for overlaps when using DDCAD

### ISSUE THREAD

**Issue by armin-ilg** [AIDASoft/DD4hep#1121]
Hi there

I'm working on the implementation of the IDEA detector in DD4hep and I want to include components from CAD into my vertex detector. 

I import the component as
```
<detectors>
    <detector id="7" name="VertexConicalSupport" type="DD4hep_TestShape_Creator">
        <check>
            <shape type="CAD_MultiVolume"
                ref="VertexSupport_o1_v01.stl"
                unit="mm"
                material="CarbonFiber">
            <material name="Iron"/>
            <volume id="0" name="s1" vis="CarbonFiberVis" material="CarbonFiber"/>
            </shape>
            <position x="0*cm" y="0*cm" z="0*cm"/>
            <rotation x="0" y="-pi/2*rad"  z="0"/>
        </check>
    </detector>
</detectors>
```

together with other detectors that run file in the overlap check. How can I check for overlaps between this CAD shape and the rest?

When running checkOverlaps.py, I get a very convoluted error (see log here: [checkOverlap_DDCAD.log](https://github.com/AIDASoft/DD4hep/files/11625915/checkOverlap_DDCAD.log)):

When running the Geant4 overlap instead (`ddsim --compactFile ./FCCee_IDEA_o1_v01.xml --runType run --macroFile overlap.mac` with `/geometry/test/run exit` in overlap.mac), I get a segmentation violation (see log here:
[ddsim_overlap.log](https://github.com/AIDASoft/DD4hep/files/11625924/ddsim_overlap.log)).
 
So what is the proper way to check for overlaps between shapes imported from CAD and the rest of the detector?

**Comment by armin-ilg** [comment]
Thanks for the answer André. So in principle this should work? Shall I open a bug report in Geant4 or in root or in both or will someone from DD4hep follow up on this?

**Comment by MarkusFrankATcernch** [comment]
@andresailer 
Not so clear if this is really a ROOT/G4 bug.
There is a lot of software convoluted here, which does not origin from ROOT/G4.
If we cannot reproduce this without assimp/dd4hep this will not be accepted as a bug.

**Comment by armin-ilg** [comment]
Hi

I've now put the STL file into a box as suggested in [here](https://github.com/AIDASoft/DD4hep/issues/879#issuecomment-1074165657):
```
<detectors>
    <detector id="0" name="Shape_STL" type="DD4hep_SingleShape" vis="CarbonFiberVis">
            <material name="CarbonFiberConicalSupport"/>
            <box x="10*cm" y="10*cm" z="22*cm" vis="VXDVis"/>
            <shape type="CAD_Shape" ref="Assieme_supporti_carbonio.stl" unit="cm">
                <position x="104.3837*cm"  y="-1.7417*cm"        z="-33.7602*cm"/>
            </shape>
            <position x="0*cm" y="0*cm" z="0*cm"/>
            <rotation phi="0*rad" theta="-pi/2*rad"   psi="0*rad"/>                    
   </detector>
</detectors>
```
and the overlap checker (in ddsim) runs through the other detectors, but then again fails when coming to the DDCAD-imported shape: 
[overlap_DDCAD_new.log](https://github.com/AIDASoft/DD4hep/files/11819640/overlap_DDCAD_new.log)

How could I reproduce this without assimp/dd4hep? What would you need to determine where this problem is coming from?

I'd have to say that usefulness of DDCAD would be severely limited if overlaps cannot be checked and if the material budget cannot be calculated (see other issue being submitted now).

**Comment by MarkusFrankATcernch** [comment]
Tessellated shapes typically consist of 3 vertex facets. To avoid assimp, these facets would have to be fed 
to ROOT from some other source (not a CAD file). How this is feasible I do not know.
Honestly if we do not find a solution to this family of problems, this is truly a hard limit to DDCAD....

**Comment by MarkusFrankATcernch** [comment]
Please see [merge request](https://github.com/AIDASoft/DD4hep/pull/1139)

**Comment by armin-ilg** [comment]
See #1134, this issue is solved. Thank you very much for the help!
