### ISSUE TITLE
DetectorTransformations broken

### ISSUE THREAD

**Issue by andresailer** [AIDASoft/DD4hep#114]
Since PR #84 the detector transformations used in the Surfaces are somehow broken.
@MarkusFrankATcernch is investigating

I.e.: surfaces that should look like this, nicely placed in the middle of the silicon (inner/outer material start with the same amount of silicon)
```
[ DEBUG3 "InnerPlanarDigiProcessor"]    inner material :   Silicon_0.005_Silicon_0.01_Kapton_0.005_Aluminium_0.005_Kapton_0.005_Epoxy_0.01_Kapton_0.01_Aluminium_0.02_Kapton_0.01, A: 19.2691, Z: 9.49079, density: 1.97888, radiationLength: 13.8272, interactionLength: 42.6855  thickness: 0.08
[ DEBUG3 "InnerPlanarDigiProcessor"]    outerMaterial :    Silicon_0.005_Epoxy_0.01_CarbonFiber_0.012_Epoxy_0.01_CarbonFiber_25D_0.002_CarbonFiber_0.012_Water_0.0235_Kapton_0.0068_CarbonFiber_0.003_CarbonFiber_25D_0.002, A: 13.2486, Z: 6.65885, density: 1.30787, radiationLength: 28.505, interactionLength: 40.0035  thickness: 0.0863
```

are looking like this, where the location of the surface center is not where it is supposed to be
```
[ DEBUG3 "InnerPlanarDigiProcessor"]    inner material :   Silicon_0.00815_Silicon_0.01_Kapton_0.005_Aluminium_0.005_Kapton_0.005_Epoxy_0.01_Kapton_0.01_Aluminium_0.02_Kapton_0.00685, A: 19.8394, Z: 9.77251, density: 2.01427, radiationLength: 13.3078, interactionLength: 42.3993  thickness: 0.08
[ DEBUG3 "InnerPlanarDigiProcessor"]    outerMaterial :    Silicon_0.00185_Epoxy_0.01_CarbonFiber_0.012_Epoxy_0.01_CarbonFiber_25D_0.002_CarbonFiber_0.012_Water_0.0235_Kapton_0.0068_CarbonFiber_0.003_CarbonFiber_25D_0.002_Air_0.00315, A: 12.7793, Z: 6.42667, density: 1.2229, radiationLength: 32.0713, interactionLength: 41.3208  thickness: 0.0863
```

**Comment by gaede** [comment]
Do you observe this for all surfaces ? I made a quick check for the ILD_o1_v05 model and could not find any surface that shows this problem...
We do however get the following deprecated warnings in our reconstruction:
```
DD4hepVolumeManager INFO  **** running plugin DD4hepVolumeManager !
VolumeManager    INFO   - populating volume ids - be patient ...
DetElementObject WARN  Deprecated function: 'const TGeoHMatrix& DD4hep::Geometry::DetElementObject::worldTransformation()' use 'DetElement::nominal()' instead.
VolumeManager    INFO   - populating volume ids - done

...
[ DEBUG1 "MyEcalBarrelDigi"] orig/new hit energy: 0.000092 0.618663
DetElement       WARN  Deprecated function: 'bool DD4hep::Geometry::DetElement::localToWorld(const Position&, DD4hep::Geometry::Position&) const' use 'DetElement::nominal()' instead.
DetElement       WARN  Deprecated function: 'const TGeoHMatrix& DD4hep::Geometry::DetElement::worldTransformation() const' use 'DetElement::nominal()' instead.
[ VERBOSE "MyDDMarlinPandora"]     -----------------------------------------

```
that have been introduced in PR #84 and we observe degraded reconstruction (JER) performance since...
@MarkusFrankATcernch  are these problems related and what do we need to do ?

**Comment by andresailer** [comment]
No not all surfaces. The VertexBarrel looks OK. 
The DDPlanarDigitiser fails because hits are not on the surface.

**Comment by andresailer** [comment]
Frank, you are setting ForceHitsOnSurface, that would hide the issue

**Comment by gaede** [comment]
I had only looked at the surfaces w/ dumpdetector and searched for surfaces that are not in the middle of the silicon as you show here and did not find any...
Will also check the digitizer.

**Comment by gaede** [comment]
@MarkusFrankATcernch: I still get the Depreceted warnings with your fix - once in the VolumeManager and once in DDMarlinPandora.  The latter is probably expected, as we call ```DetElement::localToWorld``` there but I would have expected that DD4hep itself does not call the deprecated functions anymore ...

**Comment by MarkusFrankATcernch** [comment]
The changes are committed to the DD4hep head.
Andre, could you please re-run your test job to confirm that the problem disappeared?
Frank, please check if the deprecated messages from DD4hep internal calls disappeared.

**Comment by andresailer** [comment]
I think everything is solved by #115 
Thanks for fixing this so quickly.

**Comment by jlingema** [comment]
Sorry for commenting after the issue was already closed, but the comment in #115 about releases rang an alarm bell :-). Tag 00-20 is *not* affected by this, correct?

**Comment by MarkusFrankATcernch** [comment]
I think you should be safe, but to be sure check DDCore/src/DetectorInterna.cpp
and see if the implementation of worldTransformation() and parentTransformation() 
is local. If yes, things should be fine.

**Comment by gaede** [comment]
The tag v00-20 is not affected by the this !

**Comment by jlingema** [comment]
OK, thanks.
