### ISSUE TITLE
bug report: access private member 

### ISSUE THREAD

**Issue by ufan** [AIDASoft/DD4hep#1149]
https://github.com/AIDASoft/DD4hep/blob/ad3c96d6ff95dca60d510fe78f0cffa25068c81c/DDDigi/io/DigiIO.cpp#L354

Should use getStringMap getFloatMap etc.

**Comment by jmcarcell** [comment]
The `getXMap` are deprecated, see https://github.com/AIDASoft/podio/blob/master/include/podio/GenericParameters.h#L170, and there is no access to private members: `getMap<>` is public. 
The change from `getXMap` to the templated version happened in https://github.com/AIDASoft/DD4hep/pull/1112
