### ISSUE TITLE
Optimization of the Volume manager

### ISSUE THREAD

**Issue by MarkusFrankATcernch** [AIDASoft/DD4hep#116]
Hi folks,

I would like to start here a discussion:

with the invention of the alignment structures (ie. the access to the "nominal" alignment), numerous calls to compute placement matrices should be removed from the DetElement (and its interna).
Same is true for the volume manager.
Out of all stuff stored in the volume manager, which of the following items in the VolumeManagerContext
(one instance per sensitive volume!) is actually used? Is is conceivable to remove more or less everything except the nearest detector element  of the sensitive volume, the volumeID and the world transformation?

Here is the class, of which I think it contains a lot of "historic" data:

    class VolumeManagerContext {
    public:
      typedef std::vector<TGeoNode*> Path;
      typedef PlacedVolume::VolIDs::Base VolIDs;

      /// Placement identifier
      VolumeID identifier;
      /// Ignore mask of the placement identifier
      VolumeID mask;
      /// The placement
      PlacedVolume placement;
      /// Handle to the subdetector element handle
      DetElement detector;
      /// Handle to the closest Detector element
      DetElement element;
      /// The transformation of space-points to the corrdinate system of the closests detector element
      TGeoHMatrix toDetector;
      /// The transformation of space-points to the world corrdinate system
      TGeoHMatrix toWorld;
      /// Volume IDS corresponding to this element
      VolIDs volID;
      /// Path of placements to this sensitive volume
      Path path;
    public:
      /// Default constructor
      VolumeManagerContext();
      /// Default destructor
      virtual ~VolumeManagerContext();
    };

**Comment by andresailer** [comment]
I don't remember ever having knowingly used VolumeManagerContext objects,  but that doesn't mean there aren't functions called that use some information. So how much indirection is there involved when accessing that information?

I've added [[gnu::deprecated]] to the variables and didn't get anything in lcgeo, DDMarlinPandora, FCalClusterer or MarlinTrkProcessors. (I did get warnings about e.g. localToWorld where I also added that attribute  so it is not because I am ignoring warnings from DD4hep headers. )

**Comment by MarkusFrankATcernch** [comment]
This is what I expected.
Another question is: does anyone use VolumeManager::worldTransformation(VolumeID volume_id)
I am not sure this is computed correctly (and if no-one ever used it, no problem would show up).

**Comment by andresailer** [comment]
Updated #117. But didn't see anything in DDKalTest, DDMarlinPandora, lcgeo, FCalClusterer, MarlinTrkProcessors.

@jlingema or someone needs to check for FCC

**Comment by jlingema** [comment]
Just checked, using @andresailer's `addDepr` branch, corresponding to PR #117 and I don't see any deprecation warnings when compiling FCCSW against it. To be certain, I also added the flag to enable `-Wdeprecated-declarations`. So seems to be fine from our side.

**Comment by MarkusFrankATcernch** [comment]
Issue closed. All unused data members in the Volume manager structures were removed from the volume context. At the same time the support for volumes as initially implemented by Frank.
I think this issue is mostly solved and can be closed.
