### ISSUE TITLE
Allow to give CAD files with relative paths similar to importing xml files (DDCAD)

### ISSUE THREAD

**Issue by armin-ilg** [AIDASoft/DD4hep#1166]
Hi

As discussed with @andresailer in https://github.com/key4hep/k4geo/pull/273#discussion_r1316821562, it would be great if CAD files could be imported using DDCAD giving relative paths as it is done for xml files.
So instead of having to give an absolute path:
```
<shape type="CAD_MultiVolume" ref="${K4GEO}/share/k4geo/FCCee/IDEA/compact/IDEA_o1_v01/VertexSupport_o1_v01.obj" unit="mm"/>
```

I would like to give a relative path from the parent xml file:
```
<shape type="CAD_MultiVolume" ref="VertexSupport_o1_v01.obj" unit="mm"/>
```

which should work independently of the current working directory.

In the current DDCAD examples (e.g [Check_Shape_MS3D_jeep.xml](https://github.com/AIDASoft/DD4hep/blob/master/examples/DDCAD/compact/Check_Shape_MS3D_jeep.xml)) there are always absolute paths given.

Let me know if I'm not clear, thank you!

Armin

**Comment by MarkusFrankATcernch** [comment]
See PR: https://github.com/AIDASoft/DD4hep/pull/1175

**Comment by MarkusFrankATcernch** [comment]
Once you have checked that this issue is fixed by PR 1175, please close the issue.

**Comment by armin-ilg** [comment]
It's working, thank you!
