### ISSUE TITLE
DDSim argument gun.energy is actually the total energy, not kinetic energy

### ISSUE THREAD

**Issue by atolosadelgado** [AIDASoft/DD4hep#1177]
Hi,

The DDSim argument gun.energy is actually the total energy (kinetic+mass). However, the text that is displayed says only kinetic.

```
ddsim --help | grep -B 1 kinetic
  --gun.energy GUN.ENERGY
                        The kinetic energy for the particle gun.
```

Would you prefer to change the description of the input parameter, or the behavior of it (summing the mass of the gun particle internally)?

Best,
Alvaro

**Comment by MarkusFrankATcernch** [comment]
Ciao Alvaro,
Please, if you can spare a minute simply fix the printout and submit a MR. 
I think this is easiest and backwards compatible. For most practical purposes the 
kinectic energy in HEP is anyhow way off higher then the mass of (mostly stable) particles.
Thanks!
Markus

**Comment by atolosadelgado** [comment]
Ready, https://github.com/AIDASoft/DD4hep/pull/1179

Maybe it is worth to add an exception, in case someone by mistake try to run an energy below the mass. The simulation simply actually runs if the given energy is below the mass of the particle gun.

**Comment by MarkusFrankATcernch** [comment]
@atolosadelgado Thank you!
