### ISSUE TITLE
Relative include of files inside <plugins> starts from wrong directory

### ISSUE THREAD

**Issue by Zehvogel** [AIDASoft/DD4hep#1180]
It looks like includes like this:
```
        <plugins>
                <include ref="OpenDataDetectorPlugins.xml" />
        </plugins>

```
do not start their path relative to the file containing this inclusion, but from the current directory from which whichever dd4hep using tool was executed.

For instance, building [this version of the opendatadetector](https://gitlab.cern.ch/lreichen/OpenDataDetector/-/tree/fix-plugins) and then doing 
```
 . build/this_odd.sh
teveDisplay xml/OpenDataDetector.xml
```
results in 
```
XercesC          FATAL +++ FATAL Error at file "", Line 0 Column: 0 Message:unable to open primary document entity '/home/lreichen/work/acts/OpenDataDetector/OpenDataDetectorPlugins.xml'
```
while the path of the file should be `[...]/OpenDataDetector/xml/OpenDataDetectorPlugins.xml`

**Comment by MarkusFrankATcernch** [comment]
Just for clarification:
This behavior is only for includes in <plugins/> tags ?

**Comment by Zehvogel** [comment]
As far as I can tell yes, e.g. all the other include statements [here](https://gitlab.cern.ch/lreichen/OpenDataDetector/-/blob/fix-plugins/xml/OpenDataDetector.xml) work flawlessly

**Comment by MarkusFrankATcernch** [comment]
Once you have checked that this issue is fixed by PR 1181, please close the issue.

**Comment by Zehvogel** [comment]
Yes #1181 fixes my issue, thx!
