### ISSUE TITLE
Can not find Python_INCLUDE_DIRS $ Python_LIBARIES

### ISSUE THREAD

**Issue by 3205155853** [AIDASoft/DD4hep#1182]
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python (missing: Python_INCLUDE_DIRS Python_LIBRARIES
  Development Development.Module Development.Embed) (Required is exact
  version "3.6.8")

**Comment by jmcarcell** [comment]
Do you have python 3 installed in a "normal" path like `/usr/bin/python`? The error is complaining that python is not being found, so either you don't have it or it's installed somewhere else. If you don't have it check how to install it in your OS, if it's somewhere else you can use the env variables (you add the paths to the include directory and lib directory respectively to each variable) that it's telling you `Python_INCLUDE_DIRS` and `Python_LIBRARIES` although I think that having the executable in `PATH` and the installation in `CMAKE_PREFIX_PATH` should be enough.

**Comment by 3205155853** [comment]
I have python3.9.16 and I try to write "export PYTHON_INCLUDE_DIRS=/usr/include/python3.9
export PYTHON_LIBRARIES=/usr/lib64/python3.9/site-packages"  into my .bashrc， but it dosen't work.

**Comment by MarkusFrankATcernch** [comment]
DD4hep uses the python setup which comes with the ROOT installation, since pyROOT also uses python and
the python version of DD4hep and ROOT must match.
Please check your ROOT installation. 
The cmake configuration of ROOT must point to the correct python version.

**Comment by 3205155853** [comment]
Ok, I'll try it, thanks a lot.
