### ISSUE TITLE
Seeing deeper hierarchy in teveDisplay

### ISSUE THREAD

**Issue by armin-ilg** [AIDASoft/DD4hep#1186]
Hi

In the [IDEA vertex detector implementation in k4Geo](https://github.com/key4hep/k4geo/blob/master/FCCee/IDEA/compact/IDEA_o1_v02/Vertex_IDEA_o1_v01.xml) I have implemented a hierarchy using Assemblies, that is as follows:
Subdetector -> Layer -> Stave -> Sensors/Flexes/Support -> Volume.
In [teveDisplay](https://github.com/AIDASoft/DD4hep/blob/ff4c726c90084b378cd9dc413ae2114e829002a7/UtilityApps/src/teve_display.cpp#L142) I see that there are the following calls
```
tn->SetVisOption(0) ;
tn->SetVisLevel(4);
```
that limit how deep of a hierarchy can be displayed. Is there a way to change these settings in a running instance of teveDisplay (I tried e.g. `gGeoManager->SetVisOption(7)` and similar but didn't manage to get the volumes displayed (the sensitive surfaces are visible). I'm sure my detector description is fine, since if I remove the additional hierarchy levels to something like Subdetector->Layer->Volume I see the volumes correctly in teveDisplay.

If it's not possible to change this in a running instance of teveDisplay, it would be great if a feature could be implemented to allow for a deeper display of the volume hierarchy.

Thanks!
Armin

**Comment by MarkusFrankATcernch** [comment]
teveDisplay needs a change to see levels higher than 4 - no doubt.

To only see the geometry, you can use:
```
$ geoDisplay -help
Error in <UnknownClass::ReadGitInfo()>: Cannot determine git info: etc/gitinfo.txt not found!
PersistencyIO    INFO  +++ Set Streamer to dd4hep::OpaqueDataBlock
DD4hep           INFO  ++ Using globally Geant4 unit system (mm,ns,MeV)
Info in <TGeoManager>: Changing system of units to Geant4 units (mm, ns, MeV).
Info in <TGeoManager::TGeoManager>: Geometry default, Detector Geometry created
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
geoPluginRun: No geometry input supplied. No geometry will be loaded.
   ------------------------------------------------------------------
  | Welcome to ROOT 6.29/01                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Oct 05 2023, 18:10:00                 |
  | From tag , 21 December 2022                                      |
  | With g++-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0                |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

Usage: -plugin DD4hep_GeometryDisplay  -arg [-arg]                                

     Invoke the ROOT geometry display using the factory mechanism.                

     -detector <string> Top level DetElement path. Default: '/world'                
     -option   <string> ROOT Draw option.    Default: 'ogl'                         
     -level    <number> Visualization level  [TGeoManager::SetVisLevel]  Default: 4 
     -visopt   <number> Visualization option [TGeoManager::SetVisOption] Default: 1
     -load              Only load the geometry. Do not invoke the display          
     -help              Print this help output  
     Arguments given: -help
```
ie. you invoke:

`$> geoDisplay -input <geometry xml file>  -level 6`

This program however, cannot display measurement surfaces (DDRec) and event data.
Hope this helpf for the immediate issues until teveDisplay is fixed.

**Comment by armin-ilg** [comment]
Hi @MarkusFrankATcernch. 

Thank you for your response. Okay, so for the moment there's no way to see the full geometry and surfaces, but that's okay. Indeed I had already used geoDisplay to look at the full geometry.

Cheers,
Armin

**Comment by MarkusFrankATcernch** [comment]
Need to keep open, so that the fix shall not be forgotten.
