### ISSUE TITLE
DDEve cannot be built against ROOT without webgui

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/DD4hep#1197]
Trying to build DD4hep with DDEve enabled against ROOT without webgui fails at CMake stage with:
```
CMake Error at DDEve/CMakeLists.txt:23 (target_link_libraries):
  The link interface of target "DDEve_Interface" contains:

    ROOT::ROOTGeomViewer

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```
because this target is only defined if ROOT is built with webgui enabled ([definition is happens here](https://github.com/root-project/root/blob/44299a000236b7d16a5458917167ebbd306e11c3/geom/webviewer/CMakeLists.txt#L12)).

Not entirely sure if this is a DD4hep bug or a ROOT bug because it should simply define the target in another way if it's not build with webgui.

**Comment by linev** [comment]
Hi,

As I can see from the [DDEve cmake file](https://github.com/AIDASoft/DD4hep/blob/master/DDEve/CMakeLists.txt) it adds 
dependency from `ROOT::ROOTGeomViewer` library.

To use this library one have to enable webgui components building in ROOT.

**Comment by MarkusFrankATcernch** [comment]
@linev Hi Sergei,
Is this dependency desired and necessary or should I open an issue in the ROOT github?

**Comment by linev** [comment]
This library implements web-based geometry viewer.
In REve we plan to use this viewer for more detailed geometry display.
But this library is not used in classical EVE.

**Comment by MarkusFrankATcernch** [comment]
I close this issue, since it is not directly related to dd4hep and seems to be a feature of ROOT.
