### ISSUE TITLE
Help for validation sensitive volumes with ddsim

### ISSUE THREAD

**Issue by dimitra97** [AIDASoft/DD4hep#1220]
Hello developers,

I am new to DD4hep and I am trying to build my own geometry from scratch for the Muon Spectrometer. 
My geometry is simple, where I have the detector (e.g for the barrel), three layers with chambers and tubes inside that correspond to something similar to the MDTs (I made the tubes the sensitive elements) . I managed to run ddsim with this geometry and I get hits and now I am trying to extract the sensitive detector elements (I expect the tubes) using the cellID from the hits. I do it  by loading the geometry and calling the volume manager:
`
Detector &description = Detector::getInstance();
    description.fromXML("../OpenDataDetector/xml/OpenDataDetector.xml");
    SensitiveDetector sd(description.sensitiveDetector("MuonSpectrometerBarrel"));
    VolumeManager vm = description.volumeManager();
`

I loop over the hits of the output root file of ddsim, but when I do:
`vm->lookupDetElement(hit->cellID)`
It throws exception of unknown identifier.
Also my question is do I need to set surfaces for the sensitive parts of the detector? Are they used by ddsim? I am thinking weather this could be the issue that the volume manager cannot find the detector elements. 
Also they way I am creating the sensitive volumes in my factory:

```
PlacedVolume pv0 = chVolume.placeVolume(driftTubeVolume,Transform3D(Position(x,y,z));
	if(x_gas.isSensitive()){

						sens.setType("tracker");
						driftTubeVolume.setSensitiveDetector(sens);
						pv0.addPhysVolID(x_gas.nameStr(), gasNum++);
						DetElement sensTubeEl0(x_gas.nameStr(), gasNum);
						sensTubeEl0.setPlacement(pv0);
}


```

Thank you in advance.
Dimitra

**Comment by MarkusFrankATcernch** [comment]
From what you tell here, not more conclusions can be drawn as what you already say....
- In the ddsim output, are the CellIDs set ? You could e.g. have a look with ROOT. and see the entries in the container.
- In the reading program: is the VolumeManager correctly initialized (ie. was it instantiated AFTER the geometry was built)?
- Last, but not least: If you dump the volume manager entries/hit CellIDs when writing/reading do things match?

**Comment by dimitra97** [comment]
Thank you for the quick response.
1) Yes I see the cellIDs in the root tree that I get as output from ddsim.
2) As far as I understand the volume manager is initialized. I checked it with vm.isValid() after and before doing this: VolumeManager vm = description.volumeManager().
3) How can I retrieve the information of the identifiers that the volume manager has? Could you point me to that if there is an existing example?

**Comment by MarkusFrankATcernch** [comment]
There is a check (replace the path to the compact file and the subdetector name accordingly):
```
geoPluginRun -input ../checkout/examples/ClientTests/compact/MiniTel.xml -volmgr -plugin DD4hep_VolumeDump -detector FiberTubeCalorimeter  -volume_ids -materials -sensirive -volume_ids
```
here you get a more detailed dump of the volume identifiers:
```
VolumeDump       INFO  001    FiberTubeCalorimeter_0 Vol:FiberTubeCalorimeter shape:TGeoBBox 	 S  VolID: system: 6  (0x00000006) 
VolumeDump       INFO  001   ->   Material: Air              A: 14.78  14.78  Z:  7.37   7.37
VolumeDump       INFO  002      layer_0          Vol:layer shape:TGeoBBox 	 S  VolID: system: 6 layer: 1  (0x00000106) 
VolumeDump       INFO  002   ->     Material: Air              A: 14.78  14.78  Z:  7.37   7.37
VolumeDump       INFO  003        scintillator_absorber_0 Vol:scintillator_absorber shape:TGeoTubeSeg 	 S  VolID: system: 6 layer: 1 tube: 1  (0x00100106) 
VolumeDump       INFO  003   ->       Material: Brass            A: 64.01  64.01  Z: 29.25  29.25
VolumeDump       INFO  004          scintillator_hole_0 Vol:scintillator_hole shape:TGeoTubeSeg 	 S  VolID: system: 6 layer: 1 tube: 1 hole: 1  (0x100100106) 
VolumeDump       INFO  004   ->         Material: Air              A: 14.78  14.78  Z:  7.37   7.37
VolumeDump       INFO  005            scintillator_0   Vol:scintillator shape:TGeoTubeSeg 	 S  VolID: system: 6 layer: 1 tube: 1 hole: 1 type: 1  (0x900100106) 
VolumeDump       INFO  005   ->           Material: Polystyrene      A: 11.08  11.08  Z:  5.58   5.58
VolumeDump       INFO  003        quartz_absorber_1 Vol:quartz_absorber shape:TGeoTubeSeg 	 S  VolID: system: 6 layer: 1 tube: 2  (0x00200106) 
```
Now you can check if your volumes have the proper identifiers. It also allows you to cross-check with the vol-ids you get from your hits......

**Comment by dimitra97** [comment]
Thank you very much for the example!
For my case the result is the following (a part of):

```
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003        tube_inner_16    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner: 8  (0x00020015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003        tube_inner_17    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner: 9  (0x00024015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003        tube_inner_20    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:10  (0x00028015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003        tube_inner_21    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:11  (0x0002c015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003        tube_inner_24    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:12  (0x00030015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003        tube_inner_25    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:13  (0x00034015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003        tube_inner_28    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:14  (0x00038015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003        tube_inner_29    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:15  (0x0003c015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003        tube_inner_32    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:16  (0x00040015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003        tube_inner_33    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:17  (0x00044015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003        tube_inner_36    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:18  (0x00048015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003        tube_inner_37    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:19  (0x0004c015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003        tube_inner_40    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:20  (0x00050015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003        tube_inner_41    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:21  (0x00054015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003        tube_inner_44    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:22  (0x00058015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003        tube_inner_45    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:23  (0x0005c015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003        tube_inner_48    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:24  (0x00060015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003        tube_inner_49    Vol:tube_inner shape:TGeoTubeSeg 	 S  VolID: system:21 chamber: 1 tube_inner:25  (0x00064015) 
VolumeDump       INFO  003   ->       Material: ArCO2            A: 26.82  26.82  Z: 12.47  12.47
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
VolumeDump       INFO  003   ->       Material: Aluminum         A: 26.98  26.98  Z: 13.00  13.00
```


But when I loop over the hits I get the following (by doing id.decoder()->valueString(hit->cellID, where id is the idSpec() of the readout , but not sure if this is the correct one to compare with):

**field id:system:5,chamber:1,tube_inner:22,tube_middle:0,tube_outer:0,x:1,y:0**

So i see for example that the system is always 5 from the hits while in the volume manager is 21. This could be the issue of not finding it?

**Comment by MarkusFrankATcernch** [comment]
This is wrong:
```
field id:system:5,chamber:1,tube_inner:22,tube_middle:0,tube_outer:0,x:1,y:0
```
independent of all values.....
It should rather be:
```
field id:system:5,chamber:1,tube:<width>,x:1,y:0
```
1) The sensitive volumes must have all volIDs set. You should not have some with tube_inner, but no tube_middle and tube_outer. Rather define ranges for identifiers of inner, outer and middle.
2) Do the segmentation fields have enough width ? tube_middle:0,tube_outer:0 cannot be correct. width should be at minimum 1 (to store 0 or 1). If you use VolIDs, you must understand the concept. Otherwise problems are inevitable.

**Comment by MarkusFrankATcernch** [comment]
And BTW: "5" is NOT the value of "system", but the width of the bitfield called "system".
"system" is special and must have the same width for all subdetectors of the experiment!

**Comment by dimitra97** [comment]
Thank you very much for the explanation. I changed my segmentation and now works fine!

**Comment by dimitra97** [comment]
Sorry I am opening this again but I would like your help one more time because maybe I am missing something.
My geometry simulates the ATLAS muon spectrometer. I have chambers(as volumes) along z and phi and in the chamber I place the tubes. There may be around 120 tubes per chamber and about 700 chambers . I make the tubes sensitive elements and run the simulation with ddsim. 
Now  I am trying to get the detector element from the volume manager using the cellID as I told you above. The volume manager does find something and returns a detector element, but this is the detector element of the chamber and not of the tube. I would expect the det element that is assigned to the tube that is also my sensitive volume. I do not know if I am missing something with the hierarchy.

This is how I construct the components of the geometry:

```

//loop over the chambers
chamberName = _toString((int)chamberNum, "chamber%d");
DetElement chamberElement(barrelMuonDetector, chamberName, chamberNum);	
auto pv = barrelMuonVolume.placeVolume(chVolume, Transform3D(RotationZ(i*phistep),Position(x,y,z)));
pv.addPhysVolID(x_ch.nameStr(), chamberNum++);
chamberElement.setPlacement(pv);

//loop over the tubes and make children of the chambers
PlacedVolume pv0 = chVolume.placeVolume(driftTubeVolume,Transform3D(x,y,z));
tubeName = _toString((int)gasNum, "tube%d");
	pv0.addPhysVolID("tube", gasNum);
	DetElement sensTubeEl0(tubeName, gasNum++);
	sensTubeEl0.setPlacement(pv0);
	chamberElement.add(sensTubeEl0);	
```
						
Any help would be appreciated. Thank you.
Dimitra

**Comment by MarkusFrankATcernch** [comment]
To me it looks like your sensTubeEl0 is not connected to any parent.
You will have to add it:
`chamberElement.add(sensTubeEl0);`

or better:
construct it directly as a child of the chamber:
`DetElement sensTubeEl0(chamberElement, tubeName, gasNum++);`

**Comment by dimitra97** [comment]
I do it (last line in the code above). The weird thing is that sometimes the volume_magaer->lookupContext(cellID) gives me tubes, but most of the times it returns the chambers. It feels like that it does not look further in the hierarchy? But should it return no sensitive volumes in general?

**Comment by MarkusFrankATcernch** [comment]
You sure you have made the correct volumes "sensitive"?
If you made the chamber sensitive, this is what you would get.....

**Comment by dimitra97** [comment]
Yes I think so..I am doing it like this:
```
Tube driftTubeShape(rtubemin, rtubemax, chBox.z());
Volume driftTubeVolume(x_gas.nameStr(), driftTubeShape, oddd.material(x_gas.materialStr()));
driftTubeVolume.setVisAttributes(oddd,x_gas.visStr());	
if(x_gas.isSensitive()){
			 sens.setType("tracker");
			 driftTubeVolume.setSensitiveDetector(sens);					
}		
```
Another concern is where and how many times I need to construct volumes for sensitive or not sensitive elements? What I do is to construct the chambers and the tubes once for every phi ring (the shape depends on the phi ring they belong to) . And I just place them multiple times along z. But I create detector elements for both chambers and tubes for every placement.

**Comment by MarkusFrankATcernch** [comment]
Yes. But do you also call setSensitiveDetector(...) for the chamber volume ?

**Comment by dimitra97** [comment]
> Yes. But do you also call setSensitiveDetector(...) for the chamber volume ?

No, only for the tubes

**Comment by MarkusFrankATcernch** [comment]
Then you have to use gdb in geant4/ddsim and break when the hit is created. You then have to check where Geant4 volume the hit is created and if things are correct......
