### ISSUE TITLE
CONST properties for optical surfaces missing in DD4hep.

### ISSUE THREAD

**Issue by MarkusFrankATcernch** [AIDASoft/DD4hep#1223]
In Geant4 optical surfaces can be customized also using scalar properties. 
This feature is not present in ROOT and consequently not in DD4hep.
As a consequence the surfaces translated to Geant4 are not customized with these values.

**Comment by andresailer** [comment]
Needs: https://github.com/root-project/root/pull/14617

**Comment by MarkusFrankATcernch** [comment]
Implemented in release tag v01-28
