### ISSUE TITLE
Exception while executing plugin DD4hep_DetectorVolumeDump

### ISSUE THREAD

**Issue by atolosadelgado** [AIDASoft/DD4hep#1224]
Hi,

I was using the plugin DD4hep_DetectorVolumeDump to inspect a subdetector, but it throws the following error message if the option for printing volume ID is used

```
geoPluginRun -input $K4GEO/FCCee/CLD/compact/CLD_o2_v05/CLD_o2_v05.xml -plugin DD4hep_DetectorVolumeDump  --volids
...
RunPlugin        ERROR ++ Exception while executing plugin DD4hep_DetectorVolumeDump:
		dd4hep: Attempt to access invalid handle of type: PlacedVolume
dd4hep: with plugin:DD4hep_DetectorVolumeDump
geoPluginRun: Got uncaught exception: RunPlugin: ++ Exception while executing plugin DD4hep_DetectorVolumeDump:
		dd4hep: Attempt to access invalid handle of type: PlacedVolume
dd4hep: with plugin:DD4hep_DetectorVolumeDump
```

 - OS version: alma9
 - Compiler version: gcc 11.4
 - Reproduced by: I tried with several subdetectors and it fails in the same way in all cases
 ```
source /cvmfs/sw.hsf.org/key4hep/setup.sh
geoPluginRun -input $K4GEO/FCCee/CLD/compact/CLD_o2_v05/CLD_o2_v05.xml -plugin DD4hep_DetectorVolumeDump  --volids
```
 - Goal: Print volume identifiers of placements using this plugin

**Comment by MarkusFrankATcernch** [comment]
You must have a DetElement, which has no placement.

**Comment by MarkusFrankATcernch** [comment]
Fix is included in PR https://github.com/AIDASoft/DD4hep/pull/1226
commit: https://github.com/AIDASoft/DD4hep/pull/1226/commits/e8cba558d758ad2a931ab1ff3335e2f1bf2381d5

**Comment by MarkusFrankATcernch** [comment]
Implemented in release tag v01-28
