### ISSUE TITLE
Extensions got broken with #1226

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/DD4hep#1229]
Originally reported in https://github.com/key4hep/k4geo/issues/319

For ILD there is a **long list* of the following:

```console
[...]
ObjectExtensions::extension ERROR The object has no extension of type FB10DC132C7B13D5.
ObjectExtensions::extension ERROR The object has no extension of type FB10DC132C7B13D5.
ObjectExtensions::extension ERROR The object has no extension of type FB10DC132C7B13D5.
[...]
```

I have tested locally and this appeared after #1226 but was not present before. Things seem to still be running, but I am not yet sure whether the results make sense or whether it's only not crashing.

**Comment by andresailer** [comment]
It is the change in the interface for finding extensions
https://github.com/AIDASoft/DD4hep/pull/1226/files#diff-cf2249365d6741ca0da1d2002a5cd524d3d84ff9c27d4e440c7703aff153fca5L107-R104

**Comment by andresailer** [comment]
I think we need to restore the throwing of exceptions

**Comment by andresailer** [comment]
This kind of code depends on the exception
https://github.com/AIDASoft/DD4hep/blob/c8440a1ed4e97296224af50b16a159e5eef5472c/DDRec/src/DetectorSurfaces.cpp#L37-L42

And it would be very annoying to get that printout?

**Comment by andresailer** [comment]
@tmadlener Can you try with #1230 ?

**Comment by MarkusFrankATcernch** [comment]
I cannot see a functional difference in the code fragments of the change you pointed out above.

-- "except" internally throws an exeption (std::runtime_error). 
-- The "return nullptr" is only there to please the compiler....

Yes you can suppress the exception, but why should this be suddenly be necessary?

**Comment by andresailer** [comment]
The difference is that `except` prints, `throw` before didn't print. Adding `alert=false` silences the printout, and then one has to `nullptr` check instead of catch.

**Comment by MarkusFrankATcernch** [comment]
This is absolutely true.
Is this test only failing because the string "ERROR" is in the output, but properly running otherwise?
Then your argument is very valid.
