### ISSUE TITLE
G4TwistedTubs have 2 constructors but DD4hep calls always the same

### ISSUE THREAD

**Issue by atolosadelgado** [AIDASoft/DD4hep#1232]
Hi,

G4TwistedTubs class has 2 constructors, one that assumes symmetrical shape along Z, and another one that can take arbitrary z points. The signature of the constructors is almost the same, but the behavior is not: 
* in case of symmetrical tube, the radius and angle corresponds to radius on the edge and twisted angle
* in case of asymmetrical tube, the radius and angle corresponds to radius at z=0 and angle corresponds to the stereoangle

Markus and I were discussing that a minimal change can do the trick: when instantiating the G4TwistedTubs, check if the range of Z is symmetrical, if so, instantiate the first G4TwistedTubs constructor, otherwise keep the constructor as it is now.

Thank you for your time.

Best,
Alvaro

**Comment by MarkusFrankATcernch** [comment]
This was fixed in PR https://github.com/AIDASoft/DD4hep/pull/1228
