### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by jmcarcell** [AIDASoft/DD4hep#1234]
We're planning a release in Key4hep with tags before some ongoing changes in EDM4hep, could we get a new tag of DD4hep please?

**Comment by MarkusFrankATcernch** [comment]
@andresailer Hi Andre, will you make a new tag for Key4hep & Co?
Thanks!

**Comment by andresailer** [comment]
Done: https://github.com/AIDASoft/DD4hep/releases/tag/v01-28
