### ISSUE TITLE
The format of command line parameters for ddsim

### ISSUE THREAD

**Issue by TrT-TOT** [AIDASoft/DD4hep#1235]
I'd like to pass ui.commandsConfigure to ddsim but have some problems.
The command I use is 
```
ddsim --compactFile a.xml --runType qt --macroFile ./vis.mac --enableG4GPS --ui.commandsConfigre "/physics_lists/em/SyncRadiation true"
```

I've also tried some other format to pass the parameter `/physics_lists/em/SyncRadiation true` to ddsim, but the output of ddsim is always be:
```
UI               INFO  ++ Executing configure command: '/physics_lists/em/SyncRadiation
UI               FATAL Failed to execute command: '/physics_lists/em/SyncRadiation
```

It seems that ddsim didn't read strings after the space. Could someone help me figure out the correct format of the parameter?

**Comment by andresailer** [comment]
Hi @TrT-TOT 

1) Please use triple tick marks \`\`\` around code blocks, or multi-line txt, or stuff. For example like I edited your post.
2) You have a typo in `commandsConfigre`
3) Please use a steering file for [setting ui commands](https://github.com/AIDASoft/DD4hep/blob/abab2099dcf55540eb52e47a5956aeb96313fdff/DDG4/python/DDSim/Helper/UI.py#L19). 

```
ddsim --dumpSteeringFile > mysteer.py
# edit mysteer.py
ddsim --steeringFile mySteer.py
```
