### ISSUE TITLE
Invalid GDML generated when using boundary surfaces

### ISSUE THREAD

**Issue by tblake00** [AIDASoft/DD4hep#1237]
When exporting the geometry to GDML with the geoConverter plug-ins, invalid GDML is created if the geometry contains boundary surfaces between physical volumes. The GDML for the boundary ends up with two attributes with the same name (`ref`), referencing the two physical volumes.

**Comment by MarkusFrankATcernch** [comment]
Which plugin do you use when creating the GDML ? ROOT otr Geant4 based?

**Comment by andresailer** [comment]
@tblake00 
Please fill the requested information to avoid having to ask for it

 - OS version: e.g. centos7
 - Compiler version: e.g GCC 8.0
 - Package version: tag or commit ID, or GitHub branch
 - Reproduced by: exact steps to reproduce the problem: checkout, setup environment (Geant4/ROOT version, LCG/iLCSoft/Key4hep release), cmake, build, run...
 - Input: link to input files if applicable
 - Output: full build and run log output
 - Goal: A short description of what you are trying to achieve

**Comment by MarkusFrankATcernch** [comment]
Is there a reproducer of this problem?

in the OpticalSurfaces example I get GDML fragments which look correct:
```
  <structure>
    <volume name="Bubble">
      <materialref ref="Air"/>
      <solidref ref="Bubble_shape_0x5587c2904360"/>
    </volume>
    <volume name="Tank">
      <materialref ref="Water"/>
      <solidref ref="Tank_shape_0x5587c2511f50"/>
      <physvol name="Bubble_0" copynumber="0">
        <volumeref ref="Bubble"/>
        <positionref ref="Bubble_0inTankpos"/>
      </physvol>
    </volume>
    <volume name="Enclosure">
      <materialref ref="Air"/>
      <solidref ref="Enclosure_shape_0x5587c2511fd0"/>
      <physvol name="Tank_0" copynumber="0">
        <volumeref ref="Tank"/>
        <positionref ref="Tank_0inEnclosurepos"/>
      </physvol>
    </volume>
    <assembly name="Hall">
      <physvol name="Enclosure_0" copynumber="0">
        <volumeref ref="Enclosure"/>
        <positionref ref="Enclosure_0inHallpos"/>
      </physvol>
    </assembly>
    <bordersurface name="_world_BubbleDevice_HallTank" surfaceproperty="_world_BubbleDevice_WaterSurface">
      <physvolref ref="Tank_0"/>
      <physvolref ref="Enclosure_0"/>
    </bordersurface>
    <bordersurface name="_world_BubbleDevice_TankBubble" surfaceproperty="_world_BubbleDevice_AirSurface">
      <physvolref ref="Bubble_0"/>
      <physvolref ref="Tank_0"/>
    </bordersurface>
  </structure>

```

**Comment by MarkusFrankATcernch** [comment]
@tblake00 No problem with the noise. 
There are not too many users for the surfaces and hence there might be problems.
If you use the DD4hep HEAD, in principle all your requests should be satisfied including the ones we discussed some weeks ago
concerning the CONST properties.
