### ISSUE TITLE
[ddsim] Nicely abort instead of segfault when the argument of --inputFiles does not exist

### ISSUE THREAD

**Issue by BrieucF** [AIDASoft/DD4hep#1246]
Would it be possible to check that the files provided to ddsim with --inputFiles exist and nicely abort in case one of them can not be found? Currently it builds the geometry (which can be long) and then segfaults which confuses a lot of people.

Reproducer:
```
source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
ddsim -I non_existing_file.stdhep -N 10 -O dummy.root --compactFile $K4GEO/FCCee/CLD/compact/CLD_o2_v05/CLD_o2_v05.xml
```

**Comment by andresailer** [comment]
Thanks for pointing out this pain-point!
