### ISSUE TITLE
Remove using namespace from header files

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#129]
I would be good to remove `using namespace` from header files

```
./DDCond/include/DDCond/ConditionsTags.h
./DDCore/include/DD4hep/Dictionary.h
./DDDB/include/DDDB/DDDBConditionPrinter.h
./DDG4/include/DDG4/DDG4Dict.h
./DDRec/include/DDRec/Surface.h
./UtilityApps/src/run_plugin.h
```

**Comment by MarkusFrankATcernch** [comment]
This statement is only true if the global namespace is cluttered.
In our case we only create aliases in sub-namespaces. 

The only way out would be to upgrade consistently thins e.g. from DD4hep::Geometry to DD4hep.
This however would not be backwards compatible and probably a major pain....
