### ISSUE TITLE
recent changes in how scintillation is turned on or handling in DDG4?

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#1295]
Have there been any recent changes in how scintillation is handled?  Suddenly my code is no longer generating scintillation photons, although it is still generating cherenkov photons

**Comment by saraheno** [comment]
My current turn on can be found 
https://github.com/saraheno/DualTestBeam/blob/8931ff7d2b47410b322037e108af269c659cdef5/compact/SCEPCALsteering.py#L446

and
https://github.com/saraheno/DualTestBeam/blob/8931ff7d2b47410b322037e108af269c659cdef5/compact/DRConly.xml#L862

**Comment by MarkusFrankATcernch** [comment]
Not that I am aware of....

**Comment by jmcarcell** [comment]
If it's not too hard to test the Key4hep nightlies are built with the latest commit of DD4hep so if you could pinpoint the day it would be easier to find out why. You can use `-r` like:
```
source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh -r 2024-07-12
```
to go to a specific date, so if you know today it's bad and some time ago it was good you can do a binary search on the day and then one can look at the pull requests that were merged that day or the day before.

**Comment by saraheno** [comment]
so problem solved.  When switching to a new operating system, they chose an afs setup that accessed an old version of GEANT that had a different scintillation parameterization.  When they switched from 
source /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-centos8-gcc11-opt/setup.sh

to
source /cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos8-gcc11-opt/setup.sh

their problems went away.

it would be nice if dd4hep sent a warning if it detected an imcompatibility like this?  using too old a geant version for the current dd4hep code?
