### ISSUE TITLE
Get proper hit/MCParticle relations from Geant4Output2EDM4hep

### ISSUE THREAD

**Issue by BrieucF** [AIDASoft/DD4hep#1305]
### Check duplicate issues.

- [X] Checked for duplicates

### Goal

In some cases, all tracker hits are attached to the primary particle while there was clearly a secondary produced (colors reflect the MCParticle attached to the trackerHit):
![CLD_event_88](https://github.com/user-attachments/assets/a525c307-32a2-4f86-ad98-a03eabd22e2f).

This behavior gets cured when enabling `--part.keepAllParticles`:

<img width="497" alt="CLD_event_88_fixed" src="https://github.com/user-attachments/assets/4f119a85-492d-43eb-9b50-f0031e2785d9">

but the file size becomes too big for practical purposes...

Wanted behavior: if the particle attached to the hit is not kept in the output file, `sth.setParticle(mcp);` should not be called, or should be called in a way that does not make it point to an existing particle. See: https://github.com/AIDASoft/DD4hep/blob/master/DDG4/edm4hep/Geant4Output2EDM4hep.cpp 

This seems related to (but is not a duplicate of) https://github.com/AIDASoft/DD4hep/issues/471 which I guess was opened for lcio output. 

### Operating System and Version

Alma9

### compiler

gcc 11.4.1 

### ROOT Version

6.30/06

### DD4hep Version

master

### Reproducer

```
source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
ddsim --enableGun --gun.distribution uniform --gun.energy "10*GeV" --gun.particle mu- --numberOfEvents 100 --outputFile ddsim_output_edm4hep.root --random.enableEventSeed --random.seed 10 --compactFile $K4GEO/FCCee/CLD/compact/CLD_o4_v05/CLD_o4_v05.xml --gun.thetaMin "89*degree" --gun.thetaMax "89*degree"
python /afs/cern.ch/user/b/brfranco/work/public/k4geo/draw_hits_cld.py ddsim_output_edm4hep.root
display ddsim_output_edm4hep.png
```

If you want to directly use the output rootfile, the pathological behavior can be seen on event 87 (starting to count at 0).

**Comment by andresailer** [comment]
Is this particle scattering back, or created in the tracker?

**Comment by BrieucF** [comment]
It is created in the tracker

**Comment by BrieucF** [comment]
I had a suspicion that the podio python bindings might be causing this, but I see the same behavior in C++

**Comment by andresailer** [comment]
The quality bit points to the hit coming from a different particle. So using that bit you can exclude the hits, which is probably what you aim for if you don't want the particle stored?


    quality bits: [os......]  o: hit from overlay s: hit from secondary not from the MCParticle associated to it

from the slcio output
```
 [00000142] |00000641|00000000|(+5.83e+01, -8.65e+00, -1.87e+00)| 3.31e-05 | 2.31e-01 | 00000000000013  |   unknown         |     n/a     |[ s     ]
        id-fields: (system:1,side:0,layer:5,module:0,sensor:0)

 [00000143] |00000641|00000000|(+5.83e+01, -9.89e+00, -1.31e+01)| 1.23e-04 | 2.71e-01 | 00000000000013  |   unknown         |     n/a     |[ s     ]
        id-fields: (system:1,side:0,layer:5,module:0,sensor:0)

 [00000144] |00123521|00000000|(+5.86e+01, -1.08e+01, -3.83e+01)| 1.03e-06 | 8.54e-01 | 00000000000013  |   unknown         |     n/a     |[ s     ]
        id-fields: (system:1,side:0,layer:5,module:15,sensor:0)

 [00000145] |00123521|00000000|(+5.84e+01, -1.13e+01, -4.23e+01)| 2.64e-06 | 7.40e-01 | 00000000000013  |   unknown         |     n/a     |[ s     ]
        id-fields: (system:1,side:0,layer:5,module:15,sensor:0)

```

I am not sure the PDGCode should be 13 in this case, I was expecting that to be what the actual particle was. And we don't store the momentum at hit, which might help to understand if we hit some threshold  for storing particles.

**Comment by BrieucF** [comment]
Hi Andre, thank you very much for looking into this!

> I am not sure the PDGCode should be 13 in this case, I was expecting that to be what the actual particle was

If we decide that the logic is "if the secondary is not kept, the relation points to the youngest kept mother", then PDG could be 13 to be consistent. But this only for lcio, right (edm4hep::SimTrackerHit does not have this member)?

I am indeed ok with the current behavior. I got mislead by the fact that `isProducedBySecondary` is set to False when the secondary is not kept (though the hit does come from a secondary). Depending on how much flexibility one wants to leave to the user of the `quality` member of `edm4hep::SimTrackerHit` we may document this behavior [here](https://github.com/key4hep/EDM4hep/blob/main/edm4hep.yaml#L342), or in DD4hep.

**Comment by andresailer** [comment]
> though the hit does come from a secondary

No, the hit comes from the particle that caused the hit, not from something it produced. So this sounds technically correct. Otherwise we would essentially always set that bit? If you find the explanation in EDM4hep confusing, you can propose a change there.

**Comment by BrieucF** [comment]
Yeah, agreed. Thanks Andre!
