### ISSUE TITLE
Test t_AlignDet_AlephTPC_load failing in dev4

### ISSUE THREAD

**Issue by andresailer** [AIDASoft/DD4hep#1311]
### Check duplicate issues.

- [X] Checked for duplicates

### Goal

The test should pass
It fails because under the circumstances described below
There is the line
```
12: Info in <TGeoManager::CloseGeometry>: 189 nodes/ 24 volume UID's in Detector Geometry
```

But the test wants, one more node and volume
```
190 nodes/ 25 volume UID's in Detector Geometry
```

### Operating System and Version

el9

### compiler

gcc13

### ROOT Version

6-32-patches

### DD4hep Version

master

### Reproducer

The test fails when building the examples separately from the rest of DD4hep.
But it passes when building DD4hep with DD4HEP_BUILD_EXAMPLES.

```
source /cvmfs/sft.cern.ch/lcg/views/dev4/latest/x86_64-el9-gcc13-opt/setup.sh
git clone https://github.com/aidasoft/dd4hep.git
cd dd4hep
mkdir build
cd build
cmake -GNinja \
              -DDD4HEP_USE_GEANT4=ON \
              -DBoost_NO_BOOST_CMAKE=ON \
              -DDD4HEP_USE_LCIO=ON \
              -DDD4HEP_USE_EDM4HEP=OFF \
              -DDD4HEP_USE_TBB=ON \
              -DDD4HEP_USE_HEPMC3=ON \
              -DDD4HEP_BUILD_DEBUG=OFF \
              -DBUILD_TESTING=ON \
              -DDD4HEP_DEBUG_CMAKE=ON \
              -DDD4HEP_USE_XERCESC=ON \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always" \
              -DCMAKE_CXX_STANDARD=20 ..
ninja install
source ../bin/thisdd4hep.sh
cd ../examples
mkdir build
cd build
cmake -GNinja \
            -DBoost_NO_BOOST_CMAKE=ON \
            -DDD4HEP_USE_XERCESC=ON \
            -DCMAKE_CXX_STANDARD=20 ..
ninja
ctest -V -R t_AlignDet_AlephTPC_load
```

**Comment by andresailer** [comment]
The problem seems to be that the libAlignDetExample.so library is loaded from DD4hep on cvmfs, and not from the examples we build ourselves.

I should probably fix the testing of DD4hep in the LCG stacks, so that it doesn't install the example libraries.

**Comment by MarkusFrankATcernch** [comment]
I think so. If I remember correctly this tast had to be changed after the fixes I introduced for Ben:
https://github.com/AIDASoft/DD4hep/pull/1287
Hence the additional volume actually is an assembly.

**Comment by andresailer** [comment]
Thanks! That explains that, dev4 has DD4hep 01-29.
