### ISSUE TITLE
Error in <Compile>: compilation of TPRegexp

### ISSUE THREAD

**Issue by BrieucF** [AIDASoft/DD4hep#1313]
I re-open an issue regarding the import of CAD files with a path relative to the importing file because it seems to not behave as expected.

The following 

```
source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
git clone https://github.com/AIDASoft/DD4hep
cd DD4hep
ddsim --enableGun --gun.distribution uniform --gun.energy "5*GeV" --gun.particle e- --numberOfEvents 10 --outputFile ddsim_output_edm4hep.root --random.enableEventSeed --random.seed 42 --compactFile examples/DDCAD/compact/Check_Shape_RelativePath.xml
```

gives:

```
Detector         INFO  *********** Created World volume with size:  300  300  300
Info in <TGeoManager::SetTopVolume>: Top volume is world_volume. Master volume is world_volume
Error in <Compile>: compilation of TPRegexp(^(/(?:[[:alpha:][:digit:]-._~!$&'()*+,;=:@]|%[0-9A-Fa-f][0-9A-Fa-f])*)*$) failed at: 25 because invalid range in character class
 *** Break *** segmentation violation
```

While going to the folder `examples/DDCAD/compact/` and running `ddsim --enableGun --gun.distribution uniform --gun.energy "5*GeV" --gun.particle e- --numberOfEvents 10 --outputFile ddsim_output_edm4hep.root --random.enableEventSeed --random.seed 42 --compactFile Check_Shape_RelativePath.xml` works.

Another related thing: it is not easy, from the error message, to know that the problem is finding the cad file...

**Comment by MarkusFrankATcernch** [comment]
This looks very much like the error message I got from ROOT when opening more or less any file.
See here : https://github.com/root-project/root/issues/15986

Maybe they use now regular expressions everywhere ?

**Comment by andresailer** [comment]
The Key4hep stacks recently updated ROOT to the version where this URI method is broken. This is visible in our CI tests.

**Comment by andresailer** [comment]
> So it is not a DD4hep issue and we have to wait for a fixed ROOT version. Correct ?

Correct.

**Comment by andresailer** [comment]
PS: Maybe it is a Key4hep building root against pcre2 issue, but still nothing in DD4hep we can do about this.

**Comment by Zehvogel** [comment]
this should also be gone now :)

**Comment by andresailer** [comment]
Remains the question if relative imports of CAD files is now working. (@BrieucF ?)

**Comment by BrieucF** [comment]
Relative import of CAD files is now working :-)
