### ISSUE TITLE
Another ddsim

### ISSUE THREAD

**Issue by atolosadelgado** [AIDASoft/DD4hep#1321]
Hi,

looking for papers to quote in the FSR, I noticed that there is another ddsim tool, 
https://mqt.readthedocs.io/projects/ddsim/en/v1.20.2/index.html

is it a problem that two programs have the same name? I guess there is no problem if the package name is different (in this case, mqt vs DD4hep), but just in case...

**Comment by MarkusFrankATcernch** [comment]
@andresailer may be better in the legal stuff, 
but I think as long as ddsim is mentioned in the context of DD4hep there should be no problem.

**Comment by andresailer** [comment]
It really doesn't matter. In any case, I believe we have "prior art" with our ddsim?

And there are many more ddsims? https://github.com/search?q=ddsim&type=repositories
