### ISSUE TITLE
Not saving contributions for calorimeter hits

### ISSUE THREAD

**Issue by giovannimarchiori** [AIDASoft/DD4hep#1340]
Dear experts,
Is it possible to write out a root file from ddsim removing all contributions collections (keeping only the hits merged according to the detector granularity) and have the outpuT file still be readable by k4run? 
I tried hacking DDG4 removing this line https://github.com/AIDASoft/DD4hep/blob/4364e5f02a54be880564fbf93a572e590b0e74e3/DDG4/edm4hep/Geant4Output2EDM4hep.cpp#L288 and recompiling but then ddsim was not produced. I tried to modify the output root file removing those collections but then there a a segmentation error when k4run tries to open the new file. Is this feasible at all? I would save a lot of disk space…
Thanks!

**Comment by andresailer** [comment]
Hi @giovannimarchiori ,

What is the steering file if any you are using for ddsim?

Cheers,
Andre

**Comment by giovannimarchiori** [comment]
Hi Andre,
I run with
‘ddsim --enableGun --gun.distribution uniform --gun.momentumMin "%f*GeV" --gun.momentumMax "%f*GeV" --gun.particle %s --numberOfEvents %d --outputFile root/%s_sim.root --random.enableEventSeed --random.seed 4242 --compactFile $K4GEO/FCCee/ALLEGRO/compact/ALLEGRO_o1_v%02d/ALLEGRO_o1_v%02d.xml %s' % (momentumMin, momentumMax, particleType, Nevts, outfile, detectorVersion, detectorVersion)

cheers,
   Giovanni

**Comment by andresailer** [comment]
Hi @giovannimarchiori 

Thanks for the command! I had to check, but there is currently nothing implemented to reduce the number of contributions.


I think this block would have to be replaced by something that creates a single combined contribution for each cell that was hit to keep EDM4hep working.

https://github.com/AIDASoft/DD4hep/blob/cacd26e50a9f7621960677d0f1cb7516be3653c5/DDG4/edm4hep/Geant4Output2EDM4hep.cpp#L567-L585

Something that should depend on the hit_creation_mode

https://github.com/AIDASoft/DD4hep/blob/cacd26e50a9f7621960677d0f1cb7516be3653c5/DDG4/edm4hep/Geant4Output2EDM4hep.cpp#L554

How the contributions are combined into one has a lot of freedom...

Cheers,
Andre

**Comment by giovannimarchiori** [comment]
Hello @andresailer 
thanks, I had indeed found out that this was the place of the code to hack, but I had initially some trouble when compiling DD4hep. I was probably not compiling all subprojects, in particular DDG4. Googling around and reading the docs I found out the proper compilation settings, and looking in the cmake files I found out additional settings I needed to turn on (EDM4HEP..) to have the proper output. Now for my own purposes I set hits energy and time to 0 when not in detailed shower mode and have achieved a > 2x output size reduction thanks to ROOT's compression, and I can run reconstruction on top of it. 
I saw that by default the code allows for three shower info levels, SIMPLE/MEDIUM/DETAILED, maybe this could be implemented for SIMPLE. In any case I have my own fork with this change that I am happy to leave with.
Shall I close this Issue then?
Cheers,
   Giovanni

**Comment by andresailer** [comment]
Hi @giovannimarchiori 

I think it would be nice if you could at least share your implementation, in case other people are interested in a similar feature.

Thanks!

**Comment by giovannimarchiori** [comment]
hi @andresailer 
sure, that's very simple. I put the changes in my fork https://github.com/giovannimarchiori/DD4hep
so I just did
<setup the nightly>
git clone git@github.com:giovannimarchiori/DD4hep.git
cd DD4hep
mkdir build
cd build
cmake -D DD4HEP_USE_EDM4HEP=ON -D DD4HEP_USE_GEANT4=ON -D Boost_NO_BOOST_CMAKE=ON -D DD4HEP_USE_LCIO=ON -D BUILD_TESTING=ON -D CMAKE_CXX_STANDARD=17 -D CMAKE_BUILD_TYPE=Release -D ROOT_DIR=$ROOTSYS -D CMAKE_INSTALL_PREFIX=../install ..
source ../install/bin/thisdd4hep.sh
<compile the other packages - including k4_local_repo to update paths>

and that's it
Now when I run with detailed shower mode I get x/y/z/E/t of the hits, otherwise all these quantities are set to 0.0

**Comment by andresailer** [comment]
Hi @giovannimarchiori 

Thanks!
I was thinking of something such as collapsing all contributions into one with some kind of weighted average, or threshold effect applied as one would want.
Given there is now an example of what to do, if someone else comes along and needs something they can start from here.

I'll close the issue then.
