### ISSUE TITLE
Two sensitive surfaces in a one module. How to debug?

### ISSUE THREAD

**Issue by ybedfer** [AIDASoft/DD4hep#1344]
Hello,

 I am new to DD4hep and I am trying to build a detector module with
two distinct sensitive surfaces, to which I would assign two distinct
ID's.
 I have the following code, where `sens_pv` is a `PlacedVolume&`.
 ```DDSegmentation::BitField64 bf( "sensor:2" );
    const Volume &c_vol = sens_pv.volume();
    VolPlane surf1(c_vol,...); // Instantiation of 1ST sensitive surface
    bf["sensor"] = 0; 
    surf1->setID(bf.getValue());
    VolPlane surf2(c_vol,...); // Instantiation of 2ND sensitive surface
    bf["sensor"] = 1; 
    surf2->setID(bf.getValue());
 ```
(I have modified `DDRec/include/DDRec/Surface.h` to implement
 `VolPlaneImpl::setID`.)
 When I execute `ddsim`, only the 1ST surface is seen and only one hit
is instantiated per incoming particle.
 I have two questions?
I) Do you have any explanation for why it is so?
II) Could you suggest to me a way of debugging the problem? For example,
 would there be a way that I can start `kernel.run()` in
 `DD4hepSimulation.py` under `gdb`?

Thanking you,
Yann Bedfer

**Comment by andresailer** [comment]
Hi @ybedfer 

Welcome to DD4hep!

I) Please post a _complete_ example that could in principle be run by other people.

II) Yes, something like 

```
gdb python `which ddsim` --compactFile
```
works perfectly fine.

**Comment by ybedfer** [comment]
Hello Andre,

 Thank you very much for your `gdb` example. In the mean time,
I had found a solution, viz. raising an interrupt in the source
code. But that's very awkward and your suggestion looks much nicer.

 I made some progress concerning issue (I): I modify `Simple_CLIC.xml`
and `ZPlanarTracker_geo.cpp` in `examples/SimplDetector`. This, together
with the modification I had introduced in `DDRec/include/DDRec/Surface.h`
that allows to set a distinct volumeID to a `VolPlane`.

 It doesn't work. There's a crash when running `ddsim` (which I do not understand):
`VXDHandler       ERROR cellID: failed to access segmentation for VolumeID: 0000000000010001 [65537]  [ BitFieldElement: unknown name: x]`

 But the whole set of modifications conveys the idea I am pursuing, viz.
two sensitive surfaces in a one and same volume. This is to implement
the working of MPGDs (micromegas, GEMs) where the same sensitive gas
volume is read by two distinct readouts. E.g. strip along X and strips
along Y.
 This implies that at some point I need to instantiate *two* hits per
track crossing the detector. It could be at the level of
`Geant4Tracker::Hit` in `DDG4/plugins/Geant4TrackerWeightedSD.cpp`,
where I would have introduced an extra `HitPositionCombination` for a
two-hits-per-track option. Or later on, when the 'Geant4Tracker::Hit' is
converted to a `SimTrackerHit` and then to a `TrackerHit`. Imho,
the former is better, the volumeID could be easily assigned and one
would benefit from all the processing which I guess is done on `Geant4Tracker::Hit`,
such as accumulating several energy deposits from distinct tracks.


 I list my modifications below. I am not so naive that I thought they
would work as is, but as I already said, they convey the whole idea.

```diff --git a/examples/SimpleDetector/compact/Simple_CLIC.xml b/examples/SimpleDetector/compact/Simple_CLIC.xml
index cc9c2346..c450e547 100644
--- a/examples/SimpleDetector/compact/Simple_CLIC.xml
+++ b/examples/SimpleDetector/compact/Simple_CLIC.xml
@@ -120,0 +121,4 @@
+           <segmentation type="MultiSegmentation" key="sensor">
+              <segmentation name="U" type="CartesianGridXY" key_value="0" grid_size_x="1*mm"  grid_size_y="10*mm" />
+              <segmentation name="V" type="CartesianGridXY" key_value="1" grid_size_x="10*mm" grid_size_y="1*mm" />
+           </segmentation>```

```diff --git a/examples/SimpleDetector/src/ZPlanarTracker_geo.cpp b/examples/SimpleDetector/src/ZPlanarTracker_geo.cpp
index ec7a203f..83d3d8c6 100644
--- a/examples/SimpleDetector/src/ZPlanarTracker_geo.cpp
+++ b/examples/SimpleDetector/src/ZPlanarTracker_geo.cpp
@@ -159,0 +160,2 @@ static Ref_t create_element(Detector& description, xml_h e, SensitiveDetector se
+    VolPlane sur2( sens_vol , type , inner_thickness , outer_thickness , u,v,n ) ; //,o ) ;
+
@@ -201 +203,4 @@ static Ref_t create_element(Detector& description, xml_h e, SensitiveDetector se
-
+      DDSegmentation::BitField64 bf( "system:5,side:2,layer:9,module:8,sensor:8" ) ;
+      bf["system"] = x_det.id(); bf["side"] = 0; bf["layer"] = layer_id ; bf["module"] = j;
+      bf["sensor"] = 0; surf->setID(bf.getValue());
+      bf["sensor"] = 0; sur2->setID(bf.getValue());
@@ -206,0 +212 @@ static Ref_t create_element(Detector& description, xml_h e, SensitiveDetector se
+      volSurfaceList( ladderDE )->push_back( sur2 ) ;```

```diff --git a/DDRec/include/DDRec/Surface.h b/DDRec/include/DDRec/Surface.h
index ecb55da8..6f5e9ade 100644
--- a/DDRec/include/DDRec/Surface.h
+++ b/DDRec/include/DDRec/Surface.h
@@ -350 +350,3 @@ namespace dd4hep {
-      
+
+      void setID( dd4hep::CellID id_val ) { _id = id_val ; }
+       ```

**Comment by andresailer** [comment]
Push the changes to your fork.

**Comment by andresailer** [comment]
Why do you want two hits from the same volume? This sounds more like something that should be implemented in "digitisation" after the simulation was done.
If you absolutely positively have to create two hits, then implement this in a sensitive detector.

**Comment by ybedfer** [comment]
Why do I want two hits from the same volume? I have been thinking it is the best solution to my problem of
simulating MPGDs. Two hits, meaning here: two hits with two distinct volumeID's. Each volumeID having a distinct
segmentation.  
In my understanding of DD4hep, which is poor, the volumeID is assigned to `Geant4Tracker::Hit` in
`Geant4TrackerWeightedSD.cpp` encoded in the cellID. And this information is passed
to `SimTrackerHit` and on to `TrackerHit`.
That's true that I will have to do some digitization. Each `TrackerHit` is in fact a cluster of hits, with a
cluster size and a Gaussian distribution of amplitudes. Cluster size and Gaussian are to be parameterized
based on the results of beam tests. But all this I have to do, in my understanding, starting from two
distinct hits, each with its distinctive volumeID.

 I don't understand what you mean by: "implement this in a sensitive detector". I had been thinking
that that's precisely what I am trying to achieve with my two distinct `VolPlane`, each assigned a
distinctive segmentation. Or there is something very basic which escapes my understanding.

 I am preparing the fork with the three modifications listed previously.

**Comment by andresailer** [comment]
> Why do I want two hits from the same volume? I have been thinking it is the best solution to my problem of simulating MPGDs. 

I can guess that is what you think best, but can you elaborate on _why_ you think this is the best approach? (The rest of your comment does not explain to me why you need two hits) What information is contained in the two hits that is not contained in one hit by itself?

**Comment by ybedfer** [comment]
In the final end, I need to have two hits. That's what the realworld detector yields: two hits or rather clusters (let's say an X cluster 
and a Y cluster) per incoming energy deposit.
Now starting from a *single* energy deposit, where does the *two* arise? Is it  `Geant4Tracker::Hit` or `SimTrackerHit` or
`TrackerHit`? I am not sure.
I had been thinking that the *only* option was  `Geant4Tracker::Hit`. But if you tell me that there is a simpler option, I am
willing to opt for it.

**Comment by andresailer** [comment]
I cannot help you if you don't answer my questions.

* why [do] you think this is the best approach? 
* What information is contained in the two hits that is not contained in one hit by itself [when obtained during the simulation]?

**Comment by ybedfer** [comment]
- In fact, I did not think of any other approach.
    - The channel numbers (encoded in the cellID). I eventually need two channel numbers. But I agree one hit contains the position information sufficient to compute the two channel numbers.

**Comment by andresailer** [comment]
So are you going to be fine by calculating the channel numbers at some point during the digitisation?

**Comment by ybedfer** [comment]
Yes.
...But I do not know how to do this.

**Comment by andresailer** [comment]
As far as I understand this will be handled on the digitisation side now. So closing the issue here.
