### ISSUE TITLE
MCParticle parent and daughter values not matching up

### ISSUE THREAD

**Issue by RowanKell** [AIDASoft/DD4hep#1346]
### Check duplicate issues.

- [x] Checked for duplicates

### Goal

I am simulating SIDIS events with a custom geometry and output the results to a edm4hep.root file for analysis. I need the parent and daughter values for matching secondaries to their parent. However, I find that the parent and daughter values do not match in a way that makes sense to me. It seems that each particle has the correct number of daughters (daughter_end - daughter_begin is the right value) but the values of the daughter and parent begin and end fields are wrong.

I have attached a screenshot of the ddsim output (output.part VERBOSE) and the MCParticle bank of the root file from this command: `events->Scan("MCParticles.PDG:MCParticles.parents_begin:MCParticles.parents_end:MCParticles.daughters_begin:MCParticles.daughters_end")`
ddsim output:
![Screenshot from 2024-10-30 19-51-56](https://github.com/user-attachments/assets/579876b3-97ba-4741-9343-49e2c4eb718f)

MCParticle bank in root file:
![Screenshot from 2024-10-30 19-50-30](https://github.com/user-attachments/assets/8e33b7d6-a683-4ff4-b21d-d0598950ee99)

For example, (using the rebased ids) particle id 1 has PDG -2 and according to the ddsim output, it has a daughter of id 6 which is also PDG -2. However, in the root file the MCParticle with id 1 (and PDG -2) has daughter_begin = 3 and daughter_end = 4. The particle with id 3 has PDG 2 and is not the right particle. You can check other examples for example id 12 has parents 7 and 11 according to to the output; in the root file, it says that it has parents 12 and 13, suggesting that it is its own parent.

It seems that the number of parents and daughters is consistent, but the index is wrong and just increments starting at 0. I am not sure how to fix this but I the ddsim output shows the correct values so I assume there is just a small issue.

### Operating System and Version

Ubuntu 22.04.5 LTS

### compiler

GCC 12.3.0

### ROOT Version

6.30/02

### DD4hep Version

master branch

### Reproducer

The issue was present in the ddsim installation in the eic-shell I was using, but I tried installing from source as well. 
1. I cloned a fork of the master branch of DD4hep. 
2. I compiled with this cmake command `cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=OFF -DBUILD_TESTING=ON -DROOT_DIR=$ROOTSYS -D CMAKE_BUILD_TYPE=Release .. -DCMAKE_INSTALL_PREFIX=~/eic/DD4hep`
3. I am using the compact file `epic_klmws_only.xml` from the `sector_scint_segmented` branch of this repo:  https://github.com/simons27/epic_klm (I don't think that the geometry matters, though)
4. I open the eic shell with `eic-shell` to use that installation of ROOT
5. I source the geometry install setup path: `source epic_klm/install/setup.sh`
6. I ran this ddsim command: `ddsim --compactFile ./epic_klm/epic_klmws_only.xml --numberOfEvents 1 --inputFiles pythia8DIS.hepmc --outputFile test.edm4hep.root --output.part VERBOSE --part.userParticleHandler=""`
7. I open the root file with `root test.edm4hep.root`
8. I scan the MCParticle bank: `events->Scan("MCParticles.PDG:MCParticles.parents_begin:MCParticles.parents_end:MCParticles.daughters_begin:MCParticles.daughters_end")`

The hepmc file I used is on the same github as the geometry here: https://github.com/simons27/epic_klm/blob/sector_scint_segmented/pythia8DIS.hepmc

### Additional context

FYI I forked DD4HEP from the master branch of the github repo to see if I could investigate the issue but I have not figured anything out; the issue happens both in my local installation and the eic-shell installation.

**Comment by andresailer** [comment]
please see here https://github.com/key4hep/k4geo/issues/399#issuecomment-2382481636

**Comment by andresailer** [comment]
If podio-dump gives the correct results, then the correct data is stored, then ddsim (or rather Geant4Output2EDM4hep) does the right thing, doesn't it?

**Comment by andresailer** [comment]
use `_MCParticles_daughters.index`

```
root [1] events->Scan("_MCParticles_daughters.index:MCParticles.daughters_begin:MCParticles.daughters_end")
***********************************************************
*    Row   * Instance * _MCPartic * MCParticl * MCParticl *
***********************************************************
*        0 *        0 *         1 *         0 *         3 *
*        0 *        1 *         2 *         3 *         4 *
*        0 *        2 *         3 *         4 *         8 *
*        0 *        3 *         6 *         8 *         9 *
*        0 *        4 *        14 *         9 *        10 *
*        0 *        5 *        15 *        10 *        12 *
*        0 *        6 *        16 *        12 *        14 *
*        0 *        7 *        17 *        14 *        16 *
*        0 *        8 *         7 *        16 *        17 *
*        0 *        9 *         5 *        17 *        30 *
*        0 *       10 *         8 *        30 *        31 *
*        0 *       11 *         9 *        31 *        33 *
*        0 *       12 *         8 *        33 *        33 *
*        0 *       13 *         9 *        33 *        33 *
*        0 *       14 *        12 *        33 *        33 *
*        0 *       15 *        13 *        33 *        33 *
*        0 *       16 *        10 *        33 *        33 *
*        0 *       17 *        18 *        33 *        33 *
*        0 *       18 *        19 *        33 *        35 *
```

**Comment by RowanKell** [comment]
Ah, I understand now. Thank you for your help.
