### ISSUE TITLE
DDCMS: Linker error related to Geant4 library location

### ISSUE THREAD

**Issue by maxaehle** [AIDASoft/DD4hep#1354]
### Check duplicate issues.

- [X] Checked for duplicates

### Goal

build without errors

### Operating System and Version

Rocky Linux 8.10

### compiler

GCC 14.2.0

### ROOT Version

6-32-06 built from source

### DD4hep Version

a39add61ba8821ecf6952d1152b34127597fdfb9

### Reproducer

```bash
cmake -DCMAKE_INSTALL_PREFIX=$PWD/../install ../src \
 -DDD4HEP_USE_GEANT4=ON \ -DBoost_NO_BOOST_CMAKE=ON
 -DDD4HEP_USE_LCIO=ON \
 -DBUILD_TESTING=ON \
 -DDD4HEP_BUILD_EXAMPLES=ON \
 -DCMAKE_BUILD_TYPE=Release \
 -DDD4HEP_IGNORE_GEANT4_TLS=True
make VERBOSE=1
```
gives a linker error
```
[ 88%] Linking CXX shared library lib/libDDCMS.so
cd [...]/DD4hep/build/examples/DDCMS && /usr/bin/cmake -E cmake_link_script CMakeFiles/DDCMS.dir/link.txt --verbose=1
/software/gcc/14.2.0/bin/g++ [...] -L[...]/geant4/install/lib64/cmake/Geant4/.. [...] -o lib/libDDCMS.so CMakeFiles/DDCMS.dir/src/DDCMS.cpp.o [...] -lG4clhep [...]
/usr/bin/ld: cannot find -lG4clhep
```
The library directory passed with `-L` is wrong. On my system, `libG4clhep.so` and all the other G4 libraries are contained in `[...]/geant4/install/lib64/` not `[...]/geant4/install/lib64/cmake/`. This can be fixed in [examples/DDCMS/CMakeLists.txt](https://github.com/AIDASoft/DD4hep/blob/a39add61ba8821ecf6952d1152b34127597fdfb9/examples/DDCMS/CMakeLists.txt#L61) by 
```diff
- target_link_options(DDCMS PRIVATE -L${Geant4_DIR}/..)
+ target_link_options(DDCMS PRIVATE -L${Geant4_DIR}/../..)
```
Can others confirm whether the above build command works and what `Geant4_DIR` evaluates to. To find this out, e.g. insert `message("Geant4_DIR is ${Geant4_DIR}")` near the `target_link_options` command and run make again.

Of course, ideally, the library directory would somehow be inferred from the CMake configuration of the Geant4 package but I don't know how to do this.

### Additional context

trying to build DD4hep with @tungcg1906

**Comment by andresailer** [comment]
Hmm, Geant4::Interface should already be linked against?

1) How did you build Geant4?
2)  `-DDD4HEP_IGNORE_GEANT4_TLS=True` this is a bad idea. If this is really necessary you are on your own if things fail at runtime.
3) Can we get the full log for cmake from DD4hep
4) Can we get the full log, and at least the unedited command that fails from `make VERBOSE=1`

**Comment by andresailer** [comment]
Hi @maxaehle 

Please try with the latest HEAD of DD4hep.
