### ISSUE TITLE
Problem with DetectorMap field maps in lcgeo

### ISSUE THREAD

**Issue by luisaleperez** [AIDASoft/DD4hep#136]
Hello all,

I am working for ILC developing the a code to read the anti-DID field map. For this I implemented a code called FieldMapXYZ  inside the lcgeo package (inside detector/include and detector/other). 

You can take a look of my private lcgeo version at desy here,

/afs/desy.de/user/l/laperez/ILC_Developments/6Mar2017/ILCSoft/lcgeo/HEAD-2017–02-23

The FieldMapXYZ DetectorMap is (FieldXYZ) called in the xml detector model file

ILD/compact/ILD_o1_v05/ILD_o1_v05.xml

between the lines 578 and 612, where you can see the Solenoid and antiDID field maps, respectively. 

The new code compiles OK. But there is an issue when I run ddsim. It seems that the system only read the 1st one of the DetectorMap specified in the detector model xml file, instead of reading them both and adding them together to build a total B-field.

You can see this in the attached log file,
[log_solenoidOnly.txt](https://github.com/AIDASoft/DD4hep/files/875761/log_solenoidOnly.txt)

where only the DetectorMap FieldBrBz is created. But, if I comment out the solenoidal field in the .xml file I successfully create the DetectorMap FieldXYZ as you can see in the log file below.

[log_DIDOnly.txt](https://github.com/AIDASoft/DD4hep/files/875765/log_DIDOnly.txt)

Can anyone give a hint about where to fix this problem, or if I am doing something wrong. Let me know if you need more info from my side.

Best regards,

  Alejandro

**Comment by andresailer** [comment]
Can you just push your branch to github and  link to the files, that would avoid the afs permissions problem.

**Comment by andresailer** [comment]
I mean doing this, for example:
https://github.com/luisaleperez/lcgeo/blob/AntiDIDFieldMap/ILD/compact/ILD_o1_v05/ILD_o1_v05.xml#L572

**Comment by luisaleperez** [comment]
Ok. Now you can see it. What I have in my private version is the same that you can see in the AntiDIDFieldMap branch. Do you still need me to link some files for you?

**Comment by andresailer** [comment]
I think you just need to give these things different names:
https://github.com/luisaleperez/lcgeo/blob/AntiDIDFieldMap/ILD/compact/ILD_o1_v05/ILD_o1_v05.xml#L595
Both are called "DetectorMap" at the moment.

**Comment by luisaleperez** [comment]
You were right. It is working now. If will do some further checks and then perform a pull request.

Many thansks

**Comment by andresailer** [comment]
I think DD4hep should give an error if fields with the same name are given, because what it is doing right now is not correct.
