### ISSUE TITLE
Rotated coordinate system on a measurement surface

### ISSUE THREAD

**Issue by ybedfer** [AIDASoft/DD4hep#1363]
Hello,

I would to like implement a UV measurement, _i.e._  not along the volume (a box) axes but at an angle (45°) w.r.t. them.
In order to do this, I created a `VolPlane` with `Vector3D u,v` arguments rotated. 
```
    Vector3D u(-1/sqrt(2.), -1/sqrt(2.), 0.);
    Vector3D v( 1/sqrt(2.), -1/sqrt(2.), 0.);
    Vector3D n(0., 0., 1.);
```
And I was expecting the local coordinates fed to my segmentation `cellID` method to be the rotated ones.
I my mind, this would be done in `Geant4Sensitive::cellID` (see `DDG4/src/Geant4SensDetAction.cpp`).
But it does not work.
And when I print out the tranform from global to local:
```
    const G4AffineTransform &transform = h.preTouchable()->GetHistory()->GetTopTransform();
    const G4RotationMatrix &rot = transform.NetRotation();
    std::cout<<rot<<std::endl;
```
I get the following:
```
  [ (          -1   -1.22465e-16             0)
    (  7.4988e-33   -6.12323e-17            -1)
    ( 1.22465e-16            -1   6.12323e-17) ]
```
What did I miss?

**Comment by andresailer** [comment]
Hi @ybedfer ,

There are not enough details to understand what you are trying to do, or how you are doing it.
Please point to your implementation, and to actual lines of code you are referring to.
And what does it mean to make a measurement along an angle? Where do you create the VolPlane? How is it used with anything?

**Comment by ybedfer** [comment]
Hello,
Thank you for your quick reply.
It's a a simple enough problem, in fact: I must have expressed myself too vaguely. Below is another view at it. And further down I 
try to answer your request.

- I have a detector in the shape of a box. Associated to this detector, a readout.  A simple case is when the segmentation of the readout is along two of the axes of the box, X and Y.  I can then use the `CartesianGridXY` segmentation class to simulate it. 
- Now my segmentation is along the axes U and V, rotated w.r.t. X and Y by 45°. And this not only a matter of numbering the cells of the grid: the cells are not symmetric: they are elongated  (along U, let's say). 
- I could invent yet another segmentation class ( `CartesianStereoGrid`) class to simulate this. With a `RotationZ` introduced in the `cellID` and `position` member methods.
- But I am wondering whether there is not a more straightforward way to go.

- My implementation of the sensitive surface is the following:
```    
        Volume vol; SensitiveDetector sens;
        vol.setSensitiveDetector(sens);

        Vector3D u(-1., 0., 0.);
        Vector3D v(0., -1., 0.);
        Vector3D n(0., 0., 1.);

        SurfaceType type(rec::SurfaceType::Sensitive);
        VolPlane surf(vol, type, inner_thickness, outer_thickness, u, v, n); //,o ) ;
        volplane_surfaces[name].push_back(surf);
```
- What I have been trying to change:
```
        Vector3D u(-1/sqrt(2.), -1/sqrt(2.), 0.);
        Vector3D v( 1/sqrt(2.), -1/sqrt(2.), 0.);
        Vector3D n(0., 0., 1.);
```
- This hoping that the this rotation by 45° would be applied in `Geant4Sensitive::cellID` (see `Geant4SensDetAction.cpp`). So that the `const Vector3D& localPosition` argument to the `cellID` method would be expressed in the U,V frame.

**Comment by andresailer** [comment]
The sensitive type for the surface is a flag for, e.g., a Kalman filter to expect a hit on this surface, it is _not_ a hint for any sensitive detector actions (as far as I remember).

**Comment by ybedfer** [comment]
OK. I did not know.
But the `VolPlane` itself is the standard way to implement a  measurement surface and make it available to the reocnstruction code. This is how it's presented in the DDRec manual:
```
The surfaces that should be available in the reconstruction code, have to be assigned to their corre-
sponding volume and detector element by the user in the detector geometry construction code. This is
done by specifying the coordinate system and orientation of the surface inside the volume with vectors
o,n,u and v and then instantiating one of the two types VolCylinder or VolPlane for a given volume.
```

**Comment by andresailer** [comment]
It seems to be pretty clear about being part of reconstruction code though?


Probably a sked coordinate system segmentation is the thing to do then?

**Comment by ybedfer** [comment]
Yes, indeed a "skewed coordinate system segmentation" is a solution.
But it is yet another segmentation class, next to the so many already available.
I have been thinking that I could get along w/o it.
And then I was wondering what could be the use of the  Vector3D `u` and `v` , if rotating them by 45° does not make any change (which is what am I observing).

**Comment by andresailer** [comment]
The surface you create is totally independent of the Geant4 geometry. Geant4 does never know anything about this. So of course it does not make a difference? The use is in _reconstruction_ code. (Unless someone implements a sensitive detector that makes use of the ddrec::surfaces).

**Comment by ybedfer** [comment]
Yes. I have eventually understood this.
I have remembered only lately that I already noticed that `VolPlane` is part of `DDRec`.
Thank you.
