### ISSUE TITLE
Wrong location to search for LCIO cmake macro

### ISSUE THREAD

**Issue by ggrenier** [AIDASoft/DD4hep#144]
If you install lcio (v02-07-04) in a directory which is not the lcio source directory then the cmake macro for LCIO are installed in LCIO_INSTALL_DIR/lib/cmake   while the DD4Hep CMake configuration looks for these files under   LCIO_INSTALL_DIR/cmake .

**Comment by andresailer** [comment]
Could you tell us:
 * Operating System
 * Command used
 * Full output from cmake

**Comment by ggrenier** [comment]
Hi,

By looking at it more carefully, it might be a problem with lcio rather 
than DD4hep. Full cmake output is listed below.

1/4) Operating System : Ubuntu 16.04 LTS

2/4) Command Used : I have used the ilcsoft-install python script  ( 
https://github.com/iLCSoft/iLCInstall ) in its version v01-19-01


3/4) Temporary fix :
Since the error message was
CMake Error at 
/data/software/binaries/ilcsoft/v01-19-01/lcio/v02-07-04/LCIOConfig.cmake:46 
(INCLUDE):
   include could not find load file:

/data/software/binaries/ilcsoft/v01-19-01/lcio/v02-07-04/cmake/MacroCheckPackageLibs.cmake

and that the missing cmake files were in
/data/software/binaries/ilcsoft/v01-19-01/lcio/v02-07-04/lib/cmake/ 
directory,

I've bypassed the problem by doing :

cd /data/software/binaries/ilcsoft/v01-19-01/lcio/v02-07-04/ ; ln -s 
lib/cmake



4/4) Full output from cmake :

loading initial cache file 
/data/software/binaries/ilcsoft/v01-19-01/ILCSoft.cmake
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- INCLUDING DD4hepBuild.... c++11:ON c++14:
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- CMAKE_INSTALL_PREFIX is 
/data/software/binaries/ilcsoft/v01-19-01/DD4hep/v00-20 - overwrite with 
-D CMAKE_INSTALL_PREFIX
-- dd4hep_configure_output: set CMAKE_INSTALL_PREFIX to 
/data/software/binaries/ilcsoft/v01-19-01/DD4hep/v00-20
-- ROOT_VERSION: 6.08.02
-- Performing Test CXX_FLAG_WORKS_-Wall
-- Performing Test CXX_FLAG_WORKS_-Wall - Success
-- Adding -Wall to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS_-Wextra
-- Performing Test CXX_FLAG_WORKS_-Wextra - Success
-- Adding -Wextra to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS_-pedantic
-- Performing Test CXX_FLAG_WORKS_-pedantic - Success
-- Adding -pedantic to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS_-Wshadow
-- Performing Test CXX_FLAG_WORKS_-Wshadow - Success
-- Adding -Wshadow to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS_-Wformat-security
-- Performing Test CXX_FLAG_WORKS_-Wformat-security - Success
-- Adding -Wformat-security to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS_-Wno-long-long
-- Performing Test CXX_FLAG_WORKS_-Wno-long-long - Success
-- Adding -Wno-long-long to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS_-Wdeprecated
-- Performing Test CXX_FLAG_WORKS_-Wdeprecated - Success
-- Adding -Wdeprecated to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS_-fdiagnostics-color=auto
-- Performing Test CXX_FLAG_WORKS_-fdiagnostics-color=auto - Success
-- Adding -fdiagnostics-color=auto to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS_C++14
-- Performing Test CXX_FLAG_WORKS_C++14 - Success
-- Performing Test CXX_FLAG_WORKS_C++11
-- Performing Test CXX_FLAG_WORKS_C++11 - Success

-- Performing Test CXX_FLAG_WORKS_FTLS_global-dynamic
-- Performing Test CXX_FLAG_WORKS_FTLS_global-dynamic - Success
-- Boost version: 1.58.0
-- CMAKE_INSTALL_PREFIX is 
/data/software/binaries/ilcsoft/v01-19-01/DD4hep/v00-20 - overwrite with 
-D CMAKE_INSTALL_PREFIX
-- +------------------------------------------- <<<< PACKAGE DDCore >>>> 
Version: ( 0.20.0 )
-- |    Package[DDCore]  ...optional: Skip optional XERCESC [XERCESC Not 
defined]
-- |++> Package[DDCore] Uses: ROOTDDSegmentation
-- |++> Dictionary[DDCore] -> G__DD4hep Building dictionary ...
-- |++> Dictionary[DDCore] -> G__DD4hep Uses  DEFAULTS
-- |++        exclude: 
/data/software/binaries/ilcsoft/v01-19-01/DD4hep/v00-20/DDCore/include/DD4hep/DetFactoryHelper.h
-- |++        exclude: 
/data/software/binaries/ilcsoft/v01-19-01/DD4hep/v00-20/DDCore/include/DD4hep/Factories.h
-- |++        exclude: 
/data/software/binaries/ilcsoft/v01-19-01/DD4hep/v00-20/DDCore/include/DD4hep/Plugins.h
-- |++        exclude: 
/data/software/binaries/ilcsoft/v01-19-01/DD4hep/v00-20/DDCore/include/DD4hep/SurfaceInstaller.h
-- |++        exclude: 
/data/software/binaries/ilcsoft/v01-19-01/DD4hep/v00-20/DDCore/include/XML/UnicodeValues.h
-- |++        exclude: 
/data/software/binaries/ilcsoft/v01-19-01/DD4hep/v00-20/DDCore/include/XML/tinyxml.h
-- Boost version: 1.58.0
-- |    Package library[DDCore] -> DDParsers  ...optional: ADD sources 
src/parsers/*.cpp [dependent on BOOST]
-- |++> Package library[DDCore] -> DDParsers Uses: BOOST
-- |++> Package library[DDCore] -> DDCore Uses  DEFAULTS
-- |++> Plugin[DDCore] -> DDCorePlugins Uses  DEFAULTS
-- +------------------------------------------- <<<< PACKAGE DDSurfaces 
 >>>> Version: ( 0.20.0 )
-- |++> Package[DDSurfaces] Uses  DEFAULTS
-- +------------------------------------------- <<<< PACKAGE DDRec >>>> 
Version: ( 0.20.0 )
-- |++> Package[DDRec] Uses: DDCoreDDSurfacesROOT
-- Check for GEAR (1.6.1)
-- Check for GEAR_LIBRARIES: gearsurf;gear;gearxml
-- Check for GEAR_COMPONENT_LIBRARIES: geartgeo
-- Check for GEAR_GEARSURF_LIBRARY: 
/data/software/binaries/ilcsoft/v01-19-01/gear/v01-06-01/lib/libgearsurf.so 
-- ok
-- Check for GEAR_GEAR_LIBRARY: 
/data/software/binaries/ilcsoft/v01-19-01/gear/v01-06-01/lib/libgear.so 
-- ok
-- Check for GEAR_GEARXML_LIBRARY: 
/data/software/binaries/ilcsoft/v01-19-01/gear/v01-06-01/lib/libgearxml.so 
-- ok
-- Check for GEAR_GEARTGEO_LIBRARY: 
/data/software/binaries/ilcsoft/v01-19-01/gear/v01-06-01/lib/libgeartgeo.so 
-- ok
-- Found GEAR: /data/software/binaries/ilcsoft/v01-19-01/gear/v01-06-01
-- |    Package library[DDRec] -> DDRec  ...optional: ADD sources 
src/gear/DDGear.cpp [dependent on GEAR]
-- |++> Package library[DDRec] -> DDRec Uses: GEAR
-- Check for GEAR (1.6.1)
-- Check for GEAR_LIBRARIES: gearsurf;gear;gearxml
-- Check for GEAR_GEARSURF_LIBRARY: 
/data/software/binaries/ilcsoft/v01-19-01/gear/v01-06-01/lib/libgearsurf.so 
-- ok
-- Check for GEAR_GEAR_LIBRARY: 
/data/software/binaries/ilcsoft/v01-19-01/gear/v01-06-01/lib/libgear.so 
-- ok
-- Check for GEAR_GEARXML_LIBRARY: 
/data/software/binaries/ilcsoft/v01-19-01/gear/v01-06-01/lib/libgearxml.so 
-- ok
-- |    Plugin[DDRec] -> DDRecPlugins  ...optional: ADD sources 
src/gear/createGearForILD.cppsrc/gear/createGearForCLIC.cpp [dependent 
on GEAR]
-- |++> Plugin[DDRec] -> DDRecPlugins Uses: GEAR
-- Check for GEAR (1.6.1)
-- Check for GEAR_LIBRARIES: gearsurf;gear;gearxml
-- Check for GEAR_COMPONENT_LIBRARIES: geartgeo
-- Check for GEAR_GEARSURF_LIBRARY: 
/data/software/binaries/ilcsoft/v01-19-01/gear/v01-06-01/lib/libgearsurf.so 
-- ok
-- Check for GEAR_GEAR_LIBRARY: 
/data/software/binaries/ilcsoft/v01-19-01/gear/v01-06-01/lib/libgear.so 
-- ok
-- Check for GEAR_GEARXML_LIBRARY: 
/data/software/binaries/ilcsoft/v01-19-01/gear/v01-06-01/lib/libgearxml.so 
-- ok
-- Check for GEAR_GEARTGEO_LIBRARY: 
/data/software/binaries/ilcsoft/v01-19-01/gear/v01-06-01/lib/libgeartgeo.so 
-- ok
-- Found GEAR: /data/software/binaries/ilcsoft/v01-19-01/gear/v01-06-01
-- |++> Executable[DDRec] -> convertToGear Uses: GEAR
-- +------------------------------------------- <<<< PACKAGE DDDetectors 
 >>>> Version: ( 0.20.0 )
-- |++> Package[DDDetectors] Uses: DDRec
-- |++> Plugin[DDDetectors] -> DDDetectors Uses  DEFAULTS
-- Found CLHEP Version 2.3.4.3
-- Found CLHEP: /data/software/binaries/clhep/2.3.4.3/lib/libCLHEP.so 
(Required is at least version "2.3.4.3")
-- Boost version: 1.58.0
-- +------------------------------------------- <<<< PACKAGE DDG4 >>>> 
Version: ( 0.20.0 )
-- |    Package[DDG4]  ...optional: Skip optional sources  [XERCESC Not 
defined]
-- |++> Package[DDG4] Uses: GEANT4BOOSTDDCoreCLHEP
-- |++> Package library[DDG4] -> DDG4 Uses  DEFAULTS
-- |++> Plugin[DDG4] -> DDG4Legacy Uses  DEFAULTS
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
-- |++> Dictionary[DDG4] -> G__DDG4 Building dictionary ...
-- |++> Dictionary[DDG4] -> G__DDG4 Uses  DEFAULTS
-- |++> Plugin[DDG4] -> DDG4Plugins Uses  DEFAULTS
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
-- |++> Dictionary[DDG4] -> G__DDG4Python Building dictionary ...
-- Found PythonInterp: 
/data/software/binaries/ilcsoft/v01-19-01/mysql/usr/bin/python (found 
version "2.7.12")
-- Found PythonLibs: 
/data/software/binaries/ilcsoft/v01-19-01/xercesc/x86_64-linux-gnu/libpython2.7.so 
(found version "2.7.12")
-- Found PYTHON: 
/data/software/binaries/ilcsoft/v01-19-01/mysql/usr/include/python2.7
-- |    Dictionary[DDG4] -> G__DDG4Python  ...optional: ADD sources  
[dependent on PYTHON]
-- |++> Dictionary[DDG4] -> G__DDG4Python Uses: PYTHON
-- |++> Dictionary[DDG4] -> G__DDPython Building dictionary ...
-- |    Dictionary[DDG4] -> G__DDPython  ...optional: ADD sources  
[dependent on PYTHON]
-- |++> Dictionary[DDG4] -> G__DDPython Uses: PYTHON
-- |    Package library[DDG4] -> DDPython  ...optional: ADD sources 
tpython/DDPython.cpp [dependent on PYTHON]
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
-- |++> Package library[DDG4] -> DDPython Uses: ROOTPYTHON
-- |    Plugin[DDG4] -> DDG4Python  ...optional: ADD sources 
src/python/*.cpp [dependent on PYTHON]
-- |++> Plugin[DDG4] -> DDG4Python Uses: PYTHON
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
CMake Error at 
/data/software/binaries/ilcsoft/v01-19-01/lcio/v02-07-04/LCIOConfigVersion.cmake:14 
(INCLUDE):
   include could not find load file:

/data/software/binaries/ilcsoft/v01-19-01/lcio/v02-07-04/cmake/MacroCheckPackageVersion.cmake
Call Stack (most recent call first):
   cmake/DD4hepBuild.cmake:395 (find_package)
   cmake/DD4hepBuild.cmake:486 (dd4hep_find_packageEx)
   cmake/DD4hepBuild.cmake:688 (dd4hep_find_package)
   cmake/DD4hepBuild.cmake:983 (dd4hep_handle_optional_sources)
   cmake/DD4hepBuild.cmake:1133 (dd4hep_add_library)
   DDG4/CMakeLists.txt:44 (dd4hep_add_plugin)


-- Check for LCIO (2.7.4)
CMake Error at 
/data/software/binaries/ilcsoft/v01-19-01/lcio/v02-07-04/LCIOConfig.cmake:46 
(INCLUDE):
   include could not find load file:

/data/software/binaries/ilcsoft/v01-19-01/lcio/v02-07-04/cmake/MacroCheckPackageLibs.cmake
Call Stack (most recent call first):
   cmake/DD4hepBuild.cmake:395 (find_package)
   cmake/DD4hepBuild.cmake:486 (dd4hep_find_packageEx)
   cmake/DD4hepBuild.cmake:688 (dd4hep_find_package)
   cmake/DD4hepBuild.cmake:983 (dd4hep_handle_optional_sources)
   cmake/DD4hepBuild.cmake:1133 (dd4hep_add_library)
   DDG4/CMakeLists.txt:44 (dd4hep_add_plugin)


-- Check for LCIO_LIBRARIES: lcio;sio
-- Check for LCIO_LCIO_LIBRARY: 
/data/software/binaries/lcio/root-6.08.02/v02-07-04/lib/liblcio.so -- ok
-- Check for LCIO_SIO_LIBRARY: 
/data/software/binaries/lcio/root-6.08.02/v02-07-04/lib/libsio.so -- ok
-- Found LCIO: /data/software/binaries/lcio/root-6.08.02/v02-07-04
-- |    Plugin[DDG4] -> DDG4LCIO  ...optional: ADD sources lcio/*.cpp 
[dependent on LCIO]
-- |++> Plugin[DDG4] -> DDG4LCIO Uses: LCIO
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
-- |    Plugin[DDG4] -> DDG4Reco  ...optional: ADD sources reco/*.cpp 
[dependent on DDREC]
-- |++> Plugin[DDG4] -> DDG4Reco Uses: DDRECDDCoreDDSurfacesROOT
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
-- |++> Executable[DDG4] -> g4gdmlDisplay Uses  DEFAULTS
-- |++> Executable[DDG4] -> g4FromXML Uses  DEFAULTS
-- |++> Executable[DDG4] -> dd_sim Uses  DEFAULTS
-- |    Executable[DDG4] -> pyddg4  ...optional: ADD sources pyddg4.cpp 
[dependent on PYTHON]
-- |++> Executable[DDG4] -> pyddg4 Uses: ROOTPYTHON
-- +------------------------------------------- <<<< PACKAGE DDCond >>>> 
Version: ( 0.20.0 )
-- |++> Package[DDCond] Uses: BOOSTDDCore
-- |++> Package library[DDCond] -> DDCond Uses  DEFAULTS
-- |++> Plugin[DDCond] -> DDCondPlugins Uses  DEFAULTS
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
-- +------------------------------------------- <<<< PACKAGE DDAlign 
 >>>> Version: ( 0.20.0 )
-- |++> Package[DDAlign] Uses: DDCoreDDCond
-- |++> Package library[DDAlign] -> DDAlign Uses  DEFAULTS
-- |++> Plugin[DDAlign] -> DDAlignPlugins Uses  DEFAULTS
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
-- +------------------------------------------- <<<< PACKAGE DDEve >>>> 
Version: ( 0.20.0 )
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
-- |++> Package[DDEve] Uses: DDCoreROOT
-- |++> Dictionary[DDEve] -> G__DDEve Building dictionary ...
-- |++> Dictionary[DDEve] -> G__DDEve Uses  DEFAULTS
-- |    Plugin[DDEve] -> DDEve  ...optional: ADD sources 
lcio/LCIOEventHandler.cpp [dependent on LCIO]
-- |++> Plugin[DDEve] -> DDEve Uses: LCIO
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
-- |++> Dictionary[DDEve] -> G__DDG4IO Building dictionary ...
-- |    Dictionary[DDEve] -> G__DDG4IO  ...optional: ADD sources 
[dependent on DDG4]
-- |++> Dictionary[DDEve] -> G__DDG4IO Uses: DDG4GEANT4BOOSTDDCoreCLHEP
-- |    Package library[DDEve] -> DDG4IO  ...optional: ADD sources  
[dependent on DDG4]
-- |++> Package library[DDEve] -> DDG4IO Uses: DDG4GEANT4BOOSTDDCoreCLHEP
-- +------------------------------------------- <<<< PACKAGE DDDB >>>> 
Version: ( 0.20.0 )
-- |++> Package[DDDB] Uses: DDCoreDDAlignDDCond
-- |++> Plugin[DDDB] -> DDDB Uses: DDCoreDDAlignDDCond
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
-- |++> Enable CTest environment....BUILD:ON DIRS: DDTest
-- +------------------------------------------- <<<< PACKAGE DDTest >>>> 
Version: ( 0.20.0 )
-- |++> Package[DDTest] Uses: DDCoreDDRecDDG4GEANT4BOOSTCLHEP
-- |++> Executable[DDTest] -> test_example Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_units Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_surface Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_bitfield64 Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_DetType Uses  DEFAULTS
-- |++> Executable[DDTest] -> test_PolarGridRPhi2 Uses DEFAULTS
-- |++> Executable[DDTest] -> test_cellDimensions Uses DEFAULTS
-- |++> Executable[DDTest] -> test_cellDimensionsRPhi2 Uses DEFAULTS
-- |++> Executable[DDTest] -> test_segmentationHandles Uses DEFAULTS
-- |++> Executable[DDTest] -> test_EventReaders Uses  DEFAULTS
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
-- +------------------------------------------- <<<< PACKAGE UtilityApps 
 >>>> Version: ( 0.20.0 )
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
-- |++> Package[UtilityApps] Uses: DDSegmentationDDCoreROOT
-- |++> Executable[UtilityApps] -> geoDisplay Uses  DEFAULTS
-- |++> Executable[UtilityApps] -> geoConverter Uses  DEFAULTS
-- |++> Executable[UtilityApps] -> geoPluginRun Uses  DEFAULTS
-- |++> Executable[UtilityApps] -> print_materials Uses: DDRec
-- |++> Executable[UtilityApps] -> materialScan Uses: DDRec
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
-- |++> Executable[UtilityApps] -> graphicalMaterialScan Uses: DDRecROOT
-- |    Executable[UtilityApps] -> dumpdetector  ...optional: ADD 
sources src/dumpdetector.cpp [dependent on GEANT4]
-- |++> Executable[UtilityApps] -> dumpdetector Uses: DDRecGEANT4
-- |    Executable[UtilityApps] -> test_surfaces  ...optional: ADD 
sources src/test_surfaces.cpp [dependent on LCIO]
-- |++> Executable[UtilityApps] -> test_surfaces Uses: DDRecDDTestLCIO
-- |++> Dictionary[UtilityApps] -> G__eve Building dictionary ...
-- |++> Dictionary[UtilityApps] -> G__eve Uses  DEFAULTS
-- |++> Dictionary[UtilityApps] -> G__eve1 Building dictionary ...
-- |++> Dictionary[UtilityApps] -> G__eve1 Uses  DEFAULTS
-- Found ROOT CMake configuration in 
/data/software/binaries/root/6.08.02/cmake
-- |++> Executable[UtilityApps] -> teveLCIO Uses: ROOTLCIODDRec
-- |++> Executable[UtilityApps] -> teveDisplay Uses: ROOTDDRec
-- Found global svn revision to be Répertoire non versionné
-- Found Doxygen: 
/data/software/binaries/ilcsoft/v01-19-01/mysql/usr/bin/doxygen (found 
version "1.8.11")
-- 
-- 
-------------------------------------------------------------------------------
-- Change values with: cmake -D<Variable>=<Value>
-- CMAKE_INSTALL_PREFIX = 
/data/software/binaries/ilcsoft/v01-19-01/DD4hep/v00-20
-- CMAKE_BUILD_TYPE = RelWithDebInfo
-- BUILD_TESTING = ON
-- INSTALL_DOC = ON
-- CMAKE_PREFIX_PATH =
--    /data/software/binaries/ilcsoft/v01-19-01/lccd/v01-03-01;
--    /data/software/binaries/ilcsoft/v01-19-01/Marlin/v01-10;
--    /data/software/binaries/ilcsoft/v01-19-01/MarlinDD4hep/v00-03;
-- /data/software/binaries/ilcsoft/v01-19-01/DDMarlinPandora/v00-05;
-- /data/software/binaries/ilcsoft/v01-19-01/MarlinUtil/v01-12-01;
--    /data/software/binaries/ilcsoft/v01-19-01/MarlinReco/v01-17;
-- /data/software/binaries/ilcsoft/v01-19-01/PandoraAnalysis/v01-02-01;
-- /data/software/binaries/ilcsoft/v01-19-01/PandoraPFANew/v03-01-02;
-- /data/software/binaries/ilcsoft/v01-19-01/LCFIVertex/v00-07-02;
--    /data/software/binaries/ilcsoft/v01-19-01/CEDViewer/v01-12;
--    /data/software/binaries/ilcsoft/v01-19-01/Overlay/v00-16;
-- /data/software/binaries/ilcsoft/v01-19-01/FastJetClustering/v00-03;
-- /data/software/binaries/ilcsoft/v01-19-01/MarlinFastJet/v00-03;
--    /data/software/binaries/ilcsoft/v01-19-01/LCTuple/v01-06;
--    /data/software/binaries/ilcsoft/v01-19-01/MarlinKinfit/v00-04;
--    /data/software/binaries/ilcsoft/v01-19-01/MarlinTrk/v02-02;
--    /data/software/binaries/ilcsoft/v01-19-01/KiTrack/v01-07;
-- /data/software/binaries/ilcsoft/v01-19-01/KiTrackMarlin/v01-09;
-- /data/software/binaries/ilcsoft/v01-19-01/MarlinTrkProcessors/v02-05;
-- /data/software/binaries/ilcsoft/v01-19-01/MarlinKinfitProcessors/v00-02;
-- /data/software/binaries/ilcsoft/v01-19-01/ILDPerformance/v01-01;
--    /data/software/binaries/ilcsoft/v01-19-01/Clupatra/v00-14;
--    /data/software/binaries/ilcsoft/v01-19-01/Physsim/v00-03;
--    /data/software/binaries/ilcsoft/v01-19-01/Physsim/v00-03;
-- /data/software/binaries/ilcsoft/v01-19-01/FCalClusterer/v00-03;
--    /data/software/binaries/ilcsoft/v01-19-01/LCFIPlus/v00-06-05;
-- /data/software/binaries/ilcsoft/v01-19-01/ForwardTracking/v01-10;
--    /data/software/binaries/ilcsoft/v01-19-01/LICH/v00-01;
-- /data/software/binaries/ilcsoft/v01-19-01/pathfinder/v00-06-01;
--    /data/software/binaries/ilcsoft/v01-19-01/MarlinTPC/v01-02;
--    /data/software/binaries/ilcsoft/v01-19-01/bbq/v00-01-03;
--    /data/software/binaries/ilcsoft/v01-19-01/Garlic/v3.0.4;
--    /data/software/binaries/ilcsoft/v01-19-01/RAIDA/v01-07;
--    /data/software/binaries/ilcsoft/v01-19-01/KalTest/v02-02-01;
--    /data/software/binaries/ilcsoft/v01-19-01/KalDet/v01-13-03;
--    /data/software/binaries/ilcsoft/v01-19-01/GBL/V01-17-01;
-- /data/software/binaries/ilcsoft/v01-19-01/xercesc/x86_64-linux-gnu;
--    /data/software/binaries/ilcsoft/v01-19-01/DD4hep/v00-20;
--    /data/software/binaries/ilcsoft/v01-19-01/lcgeo/v00-10;
--    /data/software/binaries/ilcsoft/v01-19-01/aidaTT/v00-05;
--    /data/software/binaries/ilcsoft/v01-19-01/DDKalTest/v01-01;
-- /data/software/binaries/ilcsoft/v01-19-01/DD4hepExamples/v00-20;
--    /data/software/binaries/ilcsoft/v01-19-01/CED/v01-09-02;
--    /data/software/binaries/ilcsoft/v01-19-01/lcio/v02-07-04;
--    /data/software/binaries/ilcsoft/v01-19-01/gear/v01-06-01;
--    /data/software/binaries/ilcsoft/v01-19-01/FastJet/3.2.0;
--    /data/software/binaries/root/6.08.02;
--    /data/software/binaries/clhep/2.3.4.3;
--    /data/software/binaries/ilcsoft/v01-19-01/gsl/2.1;
--    /data/software/binaries/geant/4.10.3;
-- 
/data/software/binaries/ilcsoft/v01-19-01/CondDBMySQL/CondDBMySQL_ILC-0-9-6;
--    /data/software/binaries/ilcsoft/v01-19-01/mysql/usr;
--    /data/software/binaries/ilcsoft/v01-19-01/ilcutil/v01-03;
--    /usr;
-- CMAKE_MODULE_PATH =
--    /data/software/binaries/ilcsoft/v01-19-01/DD4hep/v00-20/cmake;
-- /data/software/binaries/geant/4.10.3/lib/Geant4-10.3.0/Modules;
-- 
-------------------------------------------------------------------------------
-- 
-- Configuring incomplete, errors occurred!
See also 
"/data/software/binaries/ilcsoft/v01-19-01/DD4hep/v00-20/build/CMakeFiles/CMakeOutput.log".
See also 
"/data/software/binaries/ilcsoft/v01-19-01/DD4hep/v00-20/build/CMakeFiles/CMakeError.log".
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
make: *** Aucune règle pour fabriquer la cible « install ». Arrêt.
####################################################################################################
########## FINISHED BUILDING DD4hep
####################################################################################################

**Comment by gaede** [comment]
Hi Gerald,
this is indeed an LCIO issue, rather than DD4hep.
The problem seems to be that you try 'out-of-source' builds with iLCSoft, which is not really supported fully at the moment.
However, If you are using ilcinstall, everything should be installed in its source directory and the file $LCIO/cmake/MacroCheckPackageLibs.cmake will be found.
Unless you specified a CMAKE_INSTALL_PREFIX, if so: can you try again with default configuration, i.e. without specifying a CMAKE_INSTALL_PREFIX ?
Cheers, Frank.

PS: I'll create an issue for LCIO as this should be fixed, nevertheless.

**Comment by gaede** [comment]
@ggrenier just to let you know that we already had fixed the issue in LCIO but after v01-19-01 was released. So for that one you really have to use in-source builds.
