### ISSUE TITLE
LCIOFileReader requires a collection with the name MCParticle

### ISSUE THREAD

**Issue by jstrube** [AIDASoft/DD4hep#147]
I've tried to run ddsim on a file that contains an MCParticle list with a name that is not MCParticle. I couldn't find a way to do this. 
Is an option to run over an arbitrarily named collection implemented?

**Comment by andresailer** [comment]
You can adapt the LCIOFileReader
The name of the MCParticle collection is currently hard-coded:
https://github.com/AIDASoft/DD4hep/blob/master/DDG4/lcio/LCIOFileReader.cpp#L118
To pick up a parameter for the LCIO inputCollection add a parameter like it is done in this function in the GuineaPigReader
https://github.com/AIDASoft/DD4hep/blob/master/DDG4/plugins/Geant4EventReaderGuineaPig.cpp#L96

And in lcgeo/ddsim:
https://github.com/iLCSoft/lcgeo/blob/master/DDSim/DDSim/Helper/GuineaPig.py
