### ISSUE TITLE
Why does thisdd4hep try to set up env for external libraries?

### ISSUE THREAD

**Issue by decibelCooper** [AIDASoft/DD4hep#162]
In my opinion, this should not happen.  On my system, it also fails to set up properly unless I remove the external library setup lines, making it even more annoying.

**Comment by gaede** [comment]
@decibelCooper can you be bit more specific what exactly you think should not happen and what fails on your system ?

**Comment by decibelCooper** [comment]
@gaede thanks for the response.  For example at [https://github.com/AIDASoft/DD4hep/blob/master/cmake/thisdd4hep.sh#L69](url), hardcodes a compile-time variable to set ROOTSYS if it is not set.  In my system, this script (along with the environment setup scripts for ROOT, GEANT4, etc) is loaded by a reference in /etc/profile.d, where the order that the scripts are loaded in is not guaranteed.  Since the order is not guaranteed, this script can be (and is) sourced before the ROOT environment is set up.  So this script sets ROOTSYS, and ultimately confuses the ROOT setup script which garbles my LD_LIBRARY_PATH.

I believe that in principle the setup script (or at least a setup script) should not assume the order that the environment is set up, and I would even go as far as to say that it should not attempt to set up the environment for external libraries at all.  To avoid problems such as the one stated above, I suggest that at a minimum the setup script should be split into multiple scripts, where one script does not attempt to set up external libraries (as is done in lines 66-107 in [https://github.com/AIDASoft/DD4hep/blob/master/cmake/thisdd4hep.sh](url)).

**Comment by petricm** [comment]
The developers have discussed you request however the current version of `thisdd4hep.sh` is already a compromise between several approaches and a lot of other stuff depends on this behavior. Additionally there is no requirement that users have to use `thisdd4hep.sh`, this is just a helper. Subsequently we will not change this behavior, but we are open to include a `thisdd4hep_only.(c)sh` if you provide it.

**Comment by decibelCooper** [comment]
@petricm fair enough, thanks for giving it some thought.
