### ISSUE TITLE
Future developments for DD4hep 1.0

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#166]
Based on the discussion of the DD4hep developers meeting from 16th June we have decided:
1. all namespaces will be lower case and shorter
    * rename namespace `DD4hep` -> `dd4hep`
    * rename namespace `DD4hep::DDRec` -> `dd4hep::rec`
    * rename namespace `DD4hep::Simulation` -> `dd4hep::sim`
    * rename namespace `XML` -> `xml` and `JSON` -> `json`
    * rename all other namespaces according to this pattern
2. The namespace `DD4hep::Geometry::` will be incorporated into `dd4hep::`
3. All utilities will be moved `dd4hep::detail`
4. `LCDD` will be renamed to `Detector` and current `Detector.h` will be renamed to `DetElement.h`
8. Examine if `DDSegmentation` can be incorporated into `DDCore` and make it volume aware
    * If this this cannot be achieved in whole place `DDSegmentation` into the right namespace

**Comment by petricm** [comment]
We wanted to open point this several times, but could we add to this list also externalization of DDParsers into a separate project or enable an option to build DD4hep with pre-compiled parsers e.g. `cmake -DDDPARSERS_PATH=...`

**Comment by gaede** [comment]
One more suggestion/proposal:
- can we add an inline namespace `core` to  `dd4hep` ?
- this would contain the public API, i.e. everything that is in `DD4hep::Geometry` now  plus the new `dd4hep::Detector` class 
- as this namespace would be *inline* it would be 'invisible' in user code, i.e. all classes are directly available in `dd4hep` but they would be nicely grouped, e.g. in the doxygen as *core-API* classes
- in a second or parallel step one could put everything else in the inline namespace `detail` in order to allow for a smooth transition to making this a proper namespace eventually ( everything in an inline namespace can be access either directly or using the namespace ...)

**Comment by petricm** [comment]
I am not particularly in favor of this as this violates _There should be one and only one obvious way to do it_. Somebody looks into doxygen and sees `dd4hep::core:XYZ` and will write like this, somebody else will just go `dd4hep::XYZ`. Doxygen should reflect the actual namespace structure. As far as the introduction of a `core` namespace, I have nothing against it.

**Comment by MarkusFrankATcernch** [comment]
Not a good idea Frank.
We'll do as said in post #2. Point 5) shall be postponed until we find someone interested.
We should stop these semi-offline discussions. We agreed during the meeting. I cannot really see any benefit in this proposal.

**Comment by MarkusFrankATcernch** [comment]
Work is over and committed. You can see here:
https://github.com/MarkusFrankATcernch/DD4hep/tree/ns_reorganization
Next week I shall ask Andre for some help to merge, since this shall be a pain....

**Comment by andresailer** [comment]
@gaede : if you want to group things in doxygen, use doxygen commands, like \addtogroup http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdaddtogroup

**Comment by gaede** [comment]
@petricm there is no such rule as _There should be one and only one obvious way to do it_ in C++ or in DD4hep for that matter. Language features like inline namespaces, using declarations, typedefs and namespace aliasing all 'violate' this 'rule' pretty much whenever they are used.
But at least you seem to agree that introducing a namespace `core` for consistency would not be a bad thing to do.
@MarkusFrankATcernch  
> I cannot really see any benefit in this proposal.

Well, than there is not much I can argue against. For me adding this extra namespace ( as inline) would have added extra clarity to the API, would have made things consistent with the other namespaces that we introduced and would not have changed anything for the users that we decided in our meeting on Friday. It would also, as a side effect have made the doxygen more useful. So from my point of view quite a number of benefits - at zero cost ...

@andresailer I wasn't really looking at a way to group things in doxygen - this would have been just one positive side effect of my proposal. But now that Markus has decided that he does not want it:
please feel free to group things in doxygen in a more meaningful way.

**Comment by petricm** [comment]
Resolved with #167 #175 #177 #178 #179 #180 #181 #182 #183
