### ISSUE TITLE
Review DDSegmentation API

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#187]
Based on iLCSoft/lcgeo#113 where it is stated:

_Markus has changed the signature of Segmentation::decoder() from BitField64* decoder() const; to const BitField64* decoder() const; this is why this extra const_cast is needed now.
The other ones where there before.
Eventually, we should review both - might be a problem in the API ..._

**Comment by gaede** [comment]
Ok, then we should try and change the signature of the BitField64 to be able to write code like this:

```
BitFiled64 decoder("system:5:module:4:layer:8") ;

int layer = decoder( cellid, "layer" ) ;
```
will look into this ...

**Comment by gaede** [comment]
Done in #238.
