### ISSUE TITLE
The void* problem

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#189]
This is not an important issue but I think it should be addressed. I have noticed a heavy usage of  `void*`  and wanted to share [this link](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#i4-make-interfaces-precisely-and-strongly-typed).

**Comment by MarkusFrankATcernch** [comment]
Hi Whit,
please be a bit more concrete. 
Where are exactly problems with void*?
AFAIK there are now void* exposed to the clients.
What is internally used is another story, but except for the XML conversion there should not be many.

Markus

**Comment by whit2333** [comment]
Hi Markus,

You are right. I got really confused when trying to navigate the internal code. The plugin parts are also rather hard to navigate. BTW have you considered dropping root5 support? Is it really necessary?

Cheers
