### ISSUE TITLE
Better ID documentation

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#190]
**BitField64 values start counting at 1?!?**

This should be better documented and emphasized everywhere it is possible. This goes against every instinct I have as a non-fortran user.

**Comment by gaede** [comment]
Can you be a bit more specific, which piece of code or documentation you are referring to ?

**Comment by whit2333** [comment]
The BitField64 values. If you start counting at "0", there is degeneracy between the mother element and their first child element. I don't know if I am using the right lingo here.

For example, SiTrackerEndCap allows for [only 2 sensors](https://github.com/AIDASoft/DD4hep/blob/master/DDDetectors/src/SiTrackerEndcap2_geo.cpp#L71). But why? There are [two bits allocated to the sensor](https://github.com/AIDASoft/DD4hep/blob/master/DDDetectors/compact/SiD/SiD_TrackerConfig.xml#L29), so there should be 4 values allowed. Why isn't this only a single bit instead of 2 bits?
 
Note that `n_sensor` is [initialized to 0](https://github.com/AIDASoft/DD4hep/blob/master/DDDetectors/src/SiTrackerEndcap2_geo.cpp#L36) and then [later set to 1](https://github.com/AIDASoft/DD4hep/blob/master/DDDetectors/src/SiTrackerEndcap2_geo.cpp#L61).

**Comment by gaede** [comment]
There is no requirement that any value in a BitField64 is non-zero, except for the SystemID. The only real requirement is, that the the resulting volumeIDs are **unique** in a given detector.
We use for our (ILD) trackers: ` <id>system:5,side:2,layer:9,module:8,sensor:8</id>` and start counting from 0 for layer, module and sensor - no problem.
I believe the code you are looking at [here](https://github.com/AIDASoft/DD4hep/blob/master/DDDetectors/src/SiTrackerEndcap2_geo.cpp#L71) is a historical leftover from the early days, where Markus implemented some stuff from the old SiD/SLIC world, and there they had the *convention* that all ID fields start from 1 to distinguish them from sth. not set (I personally found that odd for the same reason you do ...)
