### ISSUE TITLE
Do we need "#include <memory>" for unique_ptr?

### ISSUE THREAD

**Issue by shaojunlu** [AIDASoft/DD4hep#207]
I do not know how the code current pass the build here.
But I could not build it with "CXX_FLAGS = -std=c++11" on sl6 by gcc4.9

Should we add "#include <memory>" in this code for  unique_ptr, auto, and so on?
https://github.com/AIDASoft/DD4hep/blob/master/DDCore/src/DD4hepRootPersistency.cpp#L75
https://github.com/AIDASoft/DD4hep/blob/master/DDCore/src/DD4hepRootPersistency.cpp#L79

**Comment by gaede** [comment]
Yes, the smart pointers are defined in <memory> and it needs to be included for some compilers.
Can you please create a PR.

**Comment by shaojunlu** [comment]
Done in PR #208 .
