### ISSUE TITLE
bug in calorimeter hit positions

### ISSUE THREAD

**Issue by gaede** [AIDASoft/DD4hep#223]
The global position of calorimeter hits is off by ~half a cell size.

See attached plots that shows the distance in x-y of the global step position as given by Geant4 and the global hit position that we create in `Geant4SensitiveAction<Geant4Calorimeter>`

[ddsim_calo_hits_position.pdf](https://github.com/AIDASoft/DD4hep/files/1278216/ddsim_calo_hits_position.pdf)

- the positions are systematically wrong by [0,1] cell dimension (5*mm) most of the time
  ( expected would be [0.,0.5] cell dimensions)

[ddsim_calo_hits_position_logy.pdf](https://github.com/AIDASoft/DD4hep/files/1278218/ddsim_calo_hits_position_logy.pdf)

- there are spurious hits where the difference is a few cell dimensions
 
- plots are created with this debug code:
https://github.com/gaede/DD4hep/blob/debug_cell_positions/DDG4/plugins/Geant4SDActions.cpp#L145-L150
and particle gun (10 GeV photons, ILD Ecal (5mm*5mm cells)).

**Comment by danieljeans** [comment]
I may have a explanation and fix; confirming...

**Comment by andresailer** [comment]
Fixed by #227 ?

**Comment by danieljeans** [comment]
yes, this should be fixed
