### ISSUE TITLE
GDML produced by geoConverter is corrupted

### ISSUE THREAD

**Issue by chekanov** [AIDASoft/DD4hep#224]
Hello,

I'm using geoConverter -compact2gdml converter to make a GDML file for the CLIC detector (CLIC_o3_v13 geometry) using  iLCSoft/builds/2017-08-23/x86_64-slc6-gcc62-opt. The GDML file gets created from the compact.xml  file, but I cannot read it with ROOT 6.08:

```bash
root [0] TBrowser a
root [1] TGeoManager::Import("CLIC_o3_v13.dgml");
Info in <TGeoManager::Import>: Reading geometry from file: CLIC_o3_v13.dgml
Error in <TFile::Init>: CLIC_o3_v13.dgml not a ROOT file
Error in <TGeoManager::Import>: Cannot open file
```
I also tried different detector versions, so it looks like this is dd4hep issue.
Do you know, what can be wrong with it?

best, Sergei

**Comment by petricm** [comment]
Dear  @chekanov 
I cannot really reproduce this, what exactly did you do to get this. But if you want to load gdml file do this, this I just checked and it works

```cpp
TGeoManager *aManager = new TGeoManager()
aManager->Import("CLIC_o3_v13.dgml")
```

Could you please also explain what do you want to achieve, why do you want do convert CLIC to gdml?

**Comment by chekanov** [comment]
Hi, Marco

No, I still cannot view this file by doing. I 've got this error.

`
Info in <TGeoManager::Import>: Reading geometry from file: CLIC_o3_v13.dgml
Error in <TFile::Init>: CLIC_o3_v13.dgml not a ROOT file
Error in <TGeoManager::Import>: Cannot open file
(class TGeoManager*)0x0
`
I simply want to open this GDML file and look at this detector using the EVE display in ROOT. This is how I've made this file  on lxplus:

`
source  /cvmfs/clicdp.cern.ch/compilers/gcc/6.2.0/x86_64-slc6/setup.sh
source /cvmfs/clicdp.cern.ch/iLCSoft/builds/2017-08-23/x86_64-slc6-gcc62-opt/init_ilcsoft.sh
geoConverter -compact2gdml -input /cvmfs/clicdp.cern.ch/iLCSoft/builds/2017-08-23/x86_64-slc6-gcc62-opt/lcgeo/HEAD/CLIC/compact/CLIC_o3_v13/CLIC_o3_v13.xml -output CLIC_o3_v13.dgml
`
best, Sergei

**Comment by petricm** [comment]
Hi @chekanov 
you have a typo change `-output CLIC_o3_v13.dgml` to `-output CLIC_o3_v13.gdml` root needs the proper extension.
Cheers,
Marko

**Comment by petricm** [comment]
However I would be still curious what do you want to achieve?

**Comment by chekanov** [comment]
Thanks ! This was indeed my problem

**Comment by chekanov** [comment]
Hi, Marco

  This time I wanted to study the geometry with EVE, since "ced2go" did 
not work for me (missing libGL.so library). I was following this 
instruction for CED:


  https://twiki.cern.ch/twiki/bin/view/CLIC/CLICDD4hep


best, Sergei



       Sergei Chekanov           | http://www.hep.anl.gov/chekanov/
       ===============           | Email: chekanov@anl.gov
      HEP Division, ANL          | Tel  : +01-630-252 6541
9700 S.Cass,Lemont, IL60439,USA | Fax  : +01-630-252-5782

**Comment by petricm** [comment]
`ced2go` does not really work well with the current models (even if you resolve the library dependencies). But if you want just to look at the geometry you can use this
```
teveDisplay __path_to__/CLIC_o3_v13.xml
``` 
this will convert the geometry from XML to TEve, there is no need to export to gdml and re-load to root.
