### ISSUE TITLE
LCIOEventReader discards daughters of documentation particles

### ISSUE THREAD

**Issue by decibelCooper** [AIDASoft/DD4hep#226]
At https://github.com/AIDASoft/DD4hep/blob/b0793072867d0321603375afdf3448d749c3c230/DDG4/lcio/LCIOEventReader.cpp#L155, the LCIOEventReader discards daughters of documentation particles.  This is clearly based on the assumption that documentation particles cannot or should not have final state descendants.  However, this causes a problem with generators such as Pythia8.

I believe that this `else` line should be removed.  Its removal has functioned properly in my testing.

**Comment by gaede** [comment]
This code indeed needs reviewing. We have seen similar problems with the latest version of Whizard and lcio files. However, I don't think that simply removing the else here is really correct in all cases and for all generators, as this would simply add all particles without parents (including documentation particles, e.g. the incoming particles) to the event...

**Comment by decibelCooper** [comment]
I disagree that this "would simply add all particles without parents to the event."  By my understanding, the particles actually thrown in Geant4 are determined by https://github.com/AIDASoft/DD4hep/blob/987f752486c026985e25c9a0785952bfe6546021/DDG4/src/Geant4InputHandling.cpp#L358-L414.  Adding particles in `vtx->out` causes relevant descendants to be gathered from them at https://github.com/AIDASoft/DD4hep/blob/987f752486c026985e25c9a0785952bfe6546021/DDG4/src/Geant4InputHandling.cpp#L452.  Only then are the particles added to a G4PrimaryVertex at https://github.com/AIDASoft/DD4hep/blob/987f752486c026985e25c9a0785952bfe6546021/DDG4/src/Geant4InputHandling.cpp#L460.  I fail to see the drawback to adding primary documentation particles, as they are not thrown.

**Comment by andresailer** [comment]
@decibelCooper : Could you link to the input file you used for your tests, please?

**Comment by decibelCooper** [comment]
Hi @andresailer 

Here is a simple example that I have used in testing.  It is a simple single-particle generator with documentation parents...

https://drive.google.com/open?id=0B5xHMP_V-NlFSEpydTl5bTBCN0E

Also, here is a Pythia8 DIS file that exhibits the problem (also used in testing)...

https://drive.google.com/open?id=0B5xHMP_V-NlFcnFfbHlKbTI0djQ

**Comment by andresailer** [comment]
Assigning @gaede per his comment in #229
