### ISSUE TITLE
Remove deprecated classes and/or add reference to replacement. 

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#250]
Hello,

I have a small issue. Reading the code is made difficult by deprecated code floating around which also does not help by pointing to the relevant maintained code. 

For example 
https://github.com/AIDASoft/DD4hep/blob/master/DDG4/include/DDG4/Geant4SensitiveDetector.h

Where should I go for the relevant sensitive detector code?
Could this code be removed? If no, can the deprecated code refer to the maintained code?

Cheers

**Comment by MarkusFrankATcernch** [comment]
This file is legacy. It is outdated since a very long time. However,
it cannot really be removed, because there are clients using it.
