### ISSUE TITLE
Access daughters of a `PlacedVolume`

### ISSUE THREAD

**Issue by vvolkl** [AIDASoft/DD4hep#267]
Hello,

`PlacedVolume` (http://test-dd4hep.web.cern.ch/test-dd4hep/doxygen/html/classdd4hep_1_1_placed_volume.html) exposes the `GetVolume` and `GetMotherVolume` methods of the underlying `TGeoNode`, but not `GetDaughter`. I wonder if this is by design or could be added?

**Comment by MarkusFrankATcernch** [comment]
Hi,

per definition ALL methods of the TGeoNode are exposed.
This was the whole aim of using the handles with public exposure in DD4hep.
By definition we did not want to expose the entire interface of the TGeoObjects-
the reasonsimply being that aone-to0one mapping is not very useful and 
causes confusion. The methods wrapped typically check internally
the validity of the underlying pointer.
Otherwie: Just use the operator->.

Example:

PlacedVolume pv = ...;
for(int i=0; i<pv->GetNdaughter(); ++i)  {
  PlacedVolume daughter = pv->GetDaughter(i);
    ....
}

**Comment by vvolkl** [comment]
Thanks for this quick clarification!
