### ISSUE TITLE
A propos: https://github.com/AIDASoft/DD4hep/pull/260, Fields.h

### ISSUE THREAD

**Issue by MarkusFrankATcernch** [AIDASoft/DD4hep#269]
Folks,

I expect you to remove the move operators in the return statements,
This is counter productive and inefficient and BTW causes compile warnings on some MACs. 
It is better to rely on the compiler - which directly maps the return address
into the callers address space rather than fiddling around in the callee.

I cannot inspect all code which is committed....
Please change this asap.

Cheers,

Markus

**Comment by petricm** [comment]
A complete list of warnings pertaining to this can be seen [here](https://travis-ci.org/AIDASoft/DD4hep/jobs/303015178)

**Comment by andresailer** [comment]
@MarkusFrankATcernch 
There are just a handful of warnings left, which should be easy to fix (unused variables)
Should we add "-Werror" to the CI builds and disallow merging when someone introduces warnings?
