### ISSUE TITLE
Nightmares about installing DD4hep -- PART 2

### ISSUE THREAD

**Issue by MarkusFrankATcernch** [AIDASoft/DD4hep#284]
This is the second section of a history what all could possibly go wrong installing DD4hep.
The first round can be found here:
https://github.com/AIDASoft/DD4hep/issues/283

This is the history of an innocent guy trying to install dd4hep and hitting about any 
problem one can find.
I put it here to document all sorts of failures one can possible hit -- also because
my knowledge is limited and I have no clue anymore what to do....

**Comment by MarkusFrankATcernch** [comment]
![ddeve](https://user-images.githubusercontent.com/8831087/33985361-a554f766-e0ba-11e7-872a-320d5e02a608.PNG)
[root-DDEve-output.txt](https://github.com/AIDASoft/DD4hep/files/1558573/root-DDEve-output.txt)
[python-G4-examples-output.txt](https://github.com/AIDASoft/DD4hep/files/1558574/python-G4-examples-output.txt)
[geoDisplay-compact-output.txt](https://github.com/AIDASoft/DD4hep/files/1558575/geoDisplay-compact-output.txt)




Hi Markus,

I'm very sorry to disturb you again, but I still need you help.
I have installed the cvmfs, and Probing /cvmfs/clicdp.cern.ch... OK.

But after source /cvmfs/clicdp.cern.ch/iLCSoft/builds/2017-11-15/x86_64-slc6-gcc7-opt/DD4hep/HEAD/bin/thisdd4hep.sh,
I can't run any examples..
geoDisplay examles/ClientTests/compact/*.xml,
python examles/DDG4/examles/*.py,
and even run DDEve  root.exe examples/DDEve/DDEve.C.
All the output in the attachment.

I also try to install dd4hep by source .dd4hep-ci.d/init_x86_64.sh, then continue next install setps.
I can run geoDisplay examles/ClientTests/compact/*.xml, root.exe examples/DDEve/DDEve.C. 
But python examles/DDG4/examles/*.py also have error: cling::DynamicLibraryManager::loadLibrary(): dlopen: cannot load any more object with static TLS, Failed to load the DDG4 library libDDG4Plugins.

But when I restart my system, geoDisplay examles/ClientTests/compact/*.xml is ok, root.exe examples/DDEve/DDEve.C failure, the output same as run in cvmfs.

Another problem is when i run DDEve, open DDeve.xml is ok, but open CLICSiD_Events.root nothing to do, open predifine views, the new window is "Free Window Slot",  and event control table doesn't work. I see the terminal is "*** Break *** segmentation violation".

BTW, does cvmfs relate to my system?

Thanks,
Kaijie Li

**Comment by andresailer** [comment]
One has to source the full environment:
```
/cvmfs/clicdp.cern.ch/iLCSoft/builds/2017-11-15/x86_64-slc6-gcc7-opt/init_ilcsoft.sh
```
To use the CVMFS based installation. Not just the dd4ep init.

**Comment by petricm** [comment]
I thought that Matevz patched TEve issues

https://github.com/root-project/root/pull/582/files
https://github.com/root-project/root/pull/906/files

but it seems that not entirely. Please use the GCC 6.2 release
```
/cvmfs/clicdp.cern.ch/iLCSoft/builds/2017-11-15/x86_64-slc6-gcc62-opt/init_ilcsoft.sh
```
not GCC7 as this is in evaluation phase.

**Comment by petricm** [comment]
I think there is a problem with TEve in the new version of ROOT - 6.12 (this corresponds to the GCC7 builds), I am investigating...

**Comment by KaijieLi** [comment]
I use GCC6.2 release to install, run DDEve is ok, no problem about liblcio, but GCC7 have error do not have liblcio.
But has the same problem when i try to open predifine views, the new window is "Free Window Slot", nothing display, and event control table doesn't work.
When i want to run examples, python examles/DDG4/examles/*.py also has the error:
cling::DynamicLibraryManager::loadLibrary(): dlopen: cannot load any more object with static TLS
+--------------------------------------------------------------------------------------------------------+
|  Failed to load DDG4 library:                                                                          |
|  DDG4.py: Failed to load the DDG4 library libDDG4Plugins: No such file or directory                    |
+----------------------------------------------------------------------------------------------------

I load libDDG4Plugins from root is ok. 

$ root
   ------------------------------------------------------------
  | Welcome to ROOT 6.08/00                http://root.cern.ch |
  |                               (c) 1995-2016, The ROOT Team |
  | Built for linuxx8664gcc                                    |
  | From tag v6-08-00, 4 November 2016                         |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q' |
   ------------------------------------------------------------

root [0] gSystem->Load("libDDG4Plugins")
(int) 0

But from python is failure.

$ python
Python 2.7.12 (default, Nov  7 2016, 13:06:03) 
[GCC 6.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> ROOT.gSystem.Load("libDDG4Plugins")
cling::DynamicLibraryManager::loadLibrary(): dlopen: cannot load any more object with static TLS
-1

**Comment by KaijieLi** [comment]
I use GCC6.2 release to install, run DDEve is ok, no problem about liblcio, but GCC7 have error do not have liblcio.
But has the same problem when i try to open predifine views, the new window is "Free Window Slot", nothing display, and event control table doesn't work.
When i want to run examples, python examles/DDG4/examles/*.py also has the error:
cling::DynamicLibraryManager::loadLibrary(): dlopen: cannot load any more object with static TLS
+--------------------------------------------------------------------------------------------------------+
| Failed to load DDG4 library: |
| DDG4.py: Failed to load the DDG4 library libDDG4Plugins: No such file or directory |
+----------------------------------------------------------------------------------------------------

I load libDDG4Plugins from root is ok.

$ root
-----------------------------------------------------------
  | Welcome to ROOT 6.08/00                http://root.cern.ch |
  |                               (c) 1995-2016, The ROOT Team |
  | Built for linuxx8664gcc                                    |
  | From tag v6-08-00, 4 November 2016                         |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q' |
   ------------------------------------------------------------
root [0] gSystem->Load("libDDG4Plugins")
(int) 0

But from python is failure.
$ python
Python 2.7.12 (default, Nov 7 2016, 13:06:03)
[GCC 6.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.

import ROOT
ROOT.gSystem.Load("libDDG4Plugins")
cling::DynamicLibraryManager::loadLibrary(): dlopen: cannot load any more object with static TLS
-1

**Comment by KaijieLi** [comment]
I use the GCC 6.2 release  
/cvmfs/clicdp.cern.ch/iLCSoft/builds/2017-11-15/x86_64-slc6-gcc62-opt/init_ilcsoft.sh
to install dd4hep, and run DDEve have no issue do not found liblcio,GCC7 have this issue.
But has the same problem when i try to open predifine views, the new window is "Free Window Slot", and event control table doesn't work.

The problem about run example, python examles/DDG4/examles/.*py also exist.
cling::DynamicLibraryManager::loadLibrary(): dlopen: cannot load any more object with static TLS
+--------------------------------------------------------------------------------------------------------+
|  Failed to load DDG4 library:                                                                          |
|  DDG4.py: Failed to load the DDG4 library libDDG4Plugins: No such file or directory                    |
+--------------------------------------------------------------------------------------------------------+

I can load libDDG4Plugins from root.

$ root -l
root [0] gSystem->Load("libDDG4Plugins")
(int) 0

But from python is failure.
$ python
Python 2.7.12 (default, Nov  7 2016, 13:06:03) 
[GCC 6.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> ROOT.gSystem.Load("libDDG4Plugins")
cling::DynamicLibraryManager::loadLibrary(): dlopen: cannot load any more object with static TLS
-1

**Comment by KaijieLi** [comment]
I use the GCC 6.2 release
/cvmfs/clicdp.cern.ch/iLCSoft/builds/2017-11-15/x86_64-slc6-gcc62-opt/init_ilcsoft.sh
to install dd4hep, and run DDEve have no issue do not found liblcio,GCC7 have this issue.
But has the same problem when i try to open predifine views, the new window is "Free Window Slot", and event control table doesn't work.

The problem about run example, python examles/DDG4/examles/.*py also exist.
cling::DynamicLibraryManager::loadLibrary(): dlopen: cannot load any more object with static TLS
+--------------------------------------------------------------------------------------------------------+
| Failed to load DDG4 library: |
| DDG4.py: Failed to load the DDG4 library libDDG4Plugins: No such file or directory |
+--------------------------------------------------------------------------------------------------------+

I can load libDDG4Plugins from root.

$ root -l
root [0] gSystem->Load("libDDG4Plugins")
(int) 0

But from python is failure.
$ python
Python 2.7.12 (default, Nov 7 2016, 13:06:03)
[GCC 6.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.

>>>import ROOT
>>>ROOT.gSystem.Load("libDDG4Plugins")
>>>cling::DynamicLibraryManager::loadLibrary(): dlopen: cannot load any more object with static TLS
-1

**Comment by petricm** [comment]
Can you post exactly what you do, as I cannot reproduce the problem
```
2017-12-15 09:49 mpetric@pclcd24:~$ source /cvmfs/clicdp.cern.ch/iLCSoft/builds/2017-11-15/x86_64-slc6-gcc62-opt/init_ilcsoft.sh
----------------------------------------------
Build created on Wed Nov 15 15:54:13 UTC 2017
----------------------------------------------
2017-12-15 09:49 mpetric@pclcd24:~$ python
Python 2.7.12 (default, Nov  7 2016, 13:06:03) 
[GCC 6.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> ROOT.gSystem.Load("libDDG4Plugins")
0
```

**Comment by andresailer** [comment]
@KaijieLi 
the static "Thread Local Storage" (TLS) is a problem when graphics and python come together, that is why the load works in ROOT but fails in pyROOT. When the libglapi is loaded before anything else a larger static TLS is created, which avoids the problem. This is why one has to first load the libglapi before anything else in the same python execution. Just loading the libDDG4Plugins, as you are doing, is expected to fail in python.
In your case it could be that the libglapi is not found, or the 32bit version is found before the 64bit version when you are trying to run the DD4hep examples.

Please run (after sourcing the init script).
```
ldd /cvmfs/clicdp.cern.ch/iLCSoft/builds/2017-11-15/x86_64-slc6-gcc62-opt/DD4hep/HEAD/lib/libDDG4Plugins.so
echo $LD_LIBRARY_PATH
python -c "import ROOT; print ROOT.gSystem.Load('libglapi'); print ROOT.gSystem.Load('libDDG4Plugins')"
```
And post the output.

**Comment by petricm** [comment]
It has been confirmed by Matevz and Philippe that there is a bug in TEve in ROOT 6.10 and 6.12 that is causing the crashes of DDEve, teveDispaly,... but on the other hand 6.08 is suffering from the issues in the display list cache which causes issues in ssh -X sessions (this can be patched and is done in `/cvmfs/clicdp.cern.ch/iLCSoft/builds/` installations) . So there is no version of ROOT at the moment on which visualization works seamlessly.

**Comment by KaijieLi** [comment]
@petricm
I opened a new terminal to do the fllowing as you do:
$ source /cvmfs/clicdp.cern.ch/iLCSoft/builds/2017-11-15/x86_64-slc6-gcc62-opt/init_ilcsoft.sh
----------------------------------------------
Build created on Wed Nov 15 15:54:13 UTC 2017
----------------------------------------------
$ python
Python 2.7.12 (default, Nov  7 2016, 13:06:03) 
[GCC 6.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> ROOT.gSystem.Load("libDDG4Plugins")
cling::DynamicLibraryManager::loadLibrary(): dlopen: cannot load any more object with static TLS
-1

 
 
------------------ Original ------------------

**Comment by KaijieLi** [comment]
@andresailer
$ source /cvmfs/clicdp.cern.ch/iLCSoft/builds/2017-11-15/x86_64-slc6-gcc62-opt/init_ilcsoft.sh
----------------------------------------------
Build created on Wed Nov 15 15:54:13 UTC 2017
----------------------------------------------
$ source /cvmfs/clicdp.cern.ch/iLCSoft/builds/2017-11-15/x86_64-slc6-gcc62-opt/DD4hep/HEAD/bin//thisdd4hep.sh 
$ python -c "import ROOT; print ROOT.gSystem.Load('libglapi'); print ROOT.gSystem.Load('libDDG4Plugins')"
0
cling::DynamicLibraryManager::loadLibrary(): dlopen: cannot load any more object with static TLS
-1





 
 
------------------ Original ------------------

**Comment by KaijieLi** [comment]
@andresailer 
$ python -c "import ROOT; print ROOT.gSystem.Load('libglapi'); print ROOT.gSystem.Load('libDDG4Plugins')"
0
cling::DynamicLibraryManager::loadLibrary(): dlopen: cannot load any more object with static TLS
-1

[ldd-output.txt](https://github.com/AIDASoft/DD4hep/files/1567090/ldd-output.txt)
[libpath.txt](https://github.com/AIDASoft/DD4hep/files/1567091/libpath.txt)

**Comment by petricm** [comment]
@KaijieLi I have difficulties reproducing your results 

```
2017-12-19 16:20 mpetric@pclcd24:~$  source /cvmfs/clicdp.cern.ch/iLCSoft/builds/2017-11-15/x86_64-slc6-gcc62-opt/init_ilcsoft.sh
----------------------------------------------
Build created on Wed Nov 15 15:54:13 UTC 2017
----------------------------------------------
2017-12-19 16:21 mpetric@pclcd24:~$ python -c "import ROOT; print ROOT.gSystem.Load('libglapi'); print ROOT.gSystem.Load('libDDG4Plugins')"
0
0
```

Can you try ssh to your machine **without -X or -Y** and try to execute again the two test cases.

**Comment by andresailer** [comment]
@KaijieLi 
please run 
```
locate libglapi.so
```
also add `/lib64` to your `LD_LIBRARY_PATH`
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib64
```
and again run
```
python -c "import ROOT; print ROOT.gSystem.Load('libglapi'); print ROOT.gSystem.Load('libDDG4Plugins')"
```

**Comment by andresailer** [comment]
@KaijieLi have you tried what I proposed to do?

**Comment by petricm** [comment]
Given no response I close this issue, if you still need help please reopen.
