### ISSUE TITLE
Detector::fromXML() with in-memory string

### ISSUE THREAD

**Issue by decibelcooper** [AIDASoft/DD4hep#288]
Could this be an option?  This would be useful for a scenario where a compact description can be stored as metadata in the same file as events to be processed.

**Comment by petricm** [comment]
It has been decided on the developers meeting that we will take a look into adding metadata.

**Comment by decibelcooper** [comment]
Thanks for the update.  FYI, I bring this up because in my project I am using my own IO implementation in which I can easily add metadata ([proio](https://github.com/decibelcooper/proio)).  I hope that any solution to this is general to the point where it applies to user IO plugins.

**Comment by MarkusFrankATcernch** [comment]
See https://github.com/AIDASoft/DD4hep/pull/289

**Comment by decibelcooper** [comment]
Much appreciated!
