### ISSUE TITLE
Unused class rule

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#290]
When generating dictionaries warnings appear (since ROOT 6.12/04)

```cpp
[63/559] Generating G__DD4hepProperties.cxx
Warning: Unused class rule: PropertyConfigurable
Warning: Unused class rule: PropertyManager
Warning: Unused class rule: dd4hep::PropertyValue<std::set<std::string> >
Warning: Unused class rule: dd4hep::PropertyValue<std::set<double> >
Warning: Unused class rule: dd4hep::PropertyValue<std::set<float> >
Warning: Unused class rule: dd4hep::PropertyValue<std::set<int> >
```
for details see [here](https://travis-ci.org/AIDASoft/DD4hep/jobs/331931785#L951)

**Comment by MarkusFrankATcernch** [comment]
Fixed. Apparently rootcling expects for dictionary steering headers a class with the same name.
Added dummy anonymous classes. See https://github.com/AIDASoft/DD4hep/pull/292.
This issue can be closed.
