### ISSUE TITLE
ROOT support for next release

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#299]
Make sure before next release that code is ROOT 6.10 and 6.12 compatible at least here is a need for an IF

https://github.com/AIDASoft/DD4hep/blob/ea370e961431697d6cc08d6b1cd8ec75cf3a4b1b/DDCore/CMakeLists.txt#L71-L75

Or we decide to drop for the next release support for 6.10, once 6.12 is stable.

**Comment by gaede** [comment]
We should really not force root 6.12 on DD4hep users unless there is a very good reason to do so.
So yes, please make it compatible w/ 6.10 and 6.12.

**Comment by petricm** [comment]
The main issue for me is that with 6.12 you have the updated/harmonized RadLen in IntLen formulas, so you might get different numbers for reco from DD4hep if you take one or the other ROOT version.

**Comment by gaede** [comment]
I am aware of that and we will probably move to ROOT 6.12 - but we should not make this mandatory. These differences are small anyhow and we also can never guarantee the same number for different Geant4 versions and don't enforce a certain Geant4 version to be used w/ DD4hep.

**Comment by petricm** [comment]
With the upcoming units update this discussion becomes obsolete.
