### ISSUE TITLE
DDG4 : pass LCEvent input parameters to LCEvent output

### ISSUE THREAD

**Issue by rete** [AIDASoft/DD4hep#309]
Hi all,

I'm looking for an (elegant) way to pass data from the LCIO event reader : 
https://github.com/AIDASoft/DD4hep/blob/master/DDG4/lcio/LCIOEventReader.h
to the LCIO event writer : 
https://github.com/AIDASoft/DD4hep/blob/master/DDG4/lcio/Geant4Output2LCIO.cpp
We would like to pass the following input LCEvent parameters : 
- event number
- run number
- event parameter maps

to the output LCEvent.

I've started to look a bit in the available DD4hep classes and I've found that maybe we can use the `Geant4Action::context()` method in the reader or in the writer to make a communication between the two, as it is used here to get the geometry description : 
- Example : https://github.com/AIDASoft/DD4hep/blob/master/DDG4/lcio/Geant4Output2LCIO.cpp#L229
- G4 Context class : https://github.com/AIDASoft/DD4hep/blob/master/DDG4/include/DDG4/Geant4Context.h#L237

I'm not sure what to look for then.
Pinging @gaede for eventual additional information.

**Comment by petricm** [comment]
You can use this:
https://github.com/AIDASoft/DD4hep/blob/master/DDG4/src/Geant4ParticleHandler.cpp#L176

**Comment by rete** [comment]
I've found a solution in the meantime. I have modified the Geant4EventReader and Geant4InputAction to make the event reader aware of the context from the input action. See #321 for more details.

**Comment by MarkusFrankATcernch** [comment]
You already found the solution:

context()->event().addExtension(any);  ... is your friend.

However, it also requires changes to the LCIO reader and Writer, which are currently not present.
