### ISSUE TITLE
Built-in Exceptions for Python3

### ISSUE THREAD

**Issue by epilicer** [AIDASoft/DD4hep#318]
> python -V
Python 3.5.2

========================================================================

> python LHeDScan.py 
Traceback (most recent call last):
  File "LHeDScan.py", line 50, in <module>
    run()
  File "LHeDScan.py", line 10, in run
    import os, sys, logging, DDG4, SystemOfUnits
  File "/home/ercan/softwares/DD4hep/install/python/DDG4.py", line 12, in <module>
    from DD4hep import *
  File "/home/ercan/softwares/DD4hep/install/python/DD4hep.py", line 74
    except Exception,X:
                    ^
SyntaxError: invalid syntax

========================================================================

> python LHeDScan.py 
PersistencyIO    INFO  +++ Set Streamer to dd4hep::OpaqueDataBlock
PersistencyIO    INFO  +++ Patching TGeoVolume.fUserExtension to persistent
PersistencyIO    INFO  +++ Patching TGeoNode.fUserExtension to persistent
Info in <TGeoManager::TGeoManager>: Geometry world, Detector Geometry created
Traceback (most recent call last):
  File "LHeDScan.py", line 50, in <module>
    run()
  File "LHeDScan.py", line 16, in run
    kernel.loadGeometry("file:/home/ercan/dd4hep_workdir/examples/LHeD/compact/compact.xml")
  File "/home/ercan/softwares/DD4hep/install/python/DDG4.py", line 124, in _getKernelProperty
    import exceptions
  File "/home/ercan/softwares/root/root-6.12.06/lib/ROOT.py", line 318, in _importhook
    return _orig_ihook( name, *args, **kwds )
ImportError: No module named 'exceptions'

========================================================================

Modifying those files for Python3

- DD4hep/DDG4/python/DD4hep.py
- DD4hep/DDG4/python/DDG4.py

**Comment by petricm** [comment]
Could you please fill out the issue template that you have seen once you opened the issue, it reads like this:

> !!!IMPORTANT!!!: To facilitate faster and easier response to your issue please provide in addition to the description of the issue also the following information
> 
>  - OS version: e.g. SLC6
>  - Compiler version: e.g GCC 6.2
>  - DD4hep version: tag or commit ID, or GitHub branch
>  - Reproduced by: exact steps to reproduce the problem: checkout, setup environment (Geant, ROOT versions, iLCSoft release), cmake, build, run...
>  - Input: link to input files if applicable
>  - Output: full build and run log output
>  - Goal: A short description of what you are trying to achieve
> 

Without this we can hardly help you solve your issue.

**Comment by epilicer** [comment]
Hi, this is the environment;
ubuntu 16.04
gcc-7.2
python-3.5.2
root-6.12.06
geant4.10.04

**Comment by petricm** [comment]
And I presume you wanted to run DD4hep with python3? Or what is your general objective?
In any case at present DD4hep does not support python3. Also geant4.10.04 support is also not finished.

**Comment by epilicer** [comment]
Yes, compiled DD4hep without any problem by using above versions
