### ISSUE TITLE
Negative value in readout id not working

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#32]
Negative values in readout id are not recognized properly. Usage of negative value in readout id will most probably result in duplicate volume (e.g. forward vs. backward tracker module).

**Comment by gaede** [comment]
For example in the ILD models in lcgeo (ILD_o1_v05 etc.) we use:
~~~
        <readout name="VXDCollection">
	  <!-- fixme: for now DD4hep cannot handle signed values - side should actually be "-2" -->
            <id>system:5,side:2,layer:9,module:8,sensor:8</id>
        </readout>
 ~~~
whereas it should be 
~~~
        <readout name="VXDCollection">
            <id>system:5,side:-2,layer:9,module:8,sensor:8</id>
        </readout>
 
~~~
interestingly enough, setting in the code

~~~
pv..addPhysVolID("side", 1 )   
pv..addPhysVolID("side", -1 ) 
~~~

produces the correct bit values that can lter in reconstruction be interpreted with a signed value for the side field.
  
~~~

**Comment by MarkusFrankATcernch** [comment]
Should be working now in the git master.
