### ISSUE TITLE
SetMaxAllowedStep vs SetUserMaxTrackLength in Geant4Converter.cpp?

### ISSUE THREAD

**Issue by shaojunlu** [AIDASoft/DD4hep#324]
For the "G4UserLimits",
Do we really want to "SetMaxAllowedStep" for "track_length_max"?
Or do we want to "SetUserMaxTrackLength" for " track_length_max" here?
https://github.com/AIDASoft/DD4hep/blob/master/DDG4/src/Geant4Converter.cpp#L867

"SetMaxAllowedStep" for "step_length_max" has been taken care at line 864, right?

**Comment by gaede** [comment]
Yes, you are right. Markus will fix it.

**Comment by shaojunlu** [comment]
This issue has been fixed with PR#329 by Markus.
