### ISSUE TITLE
Empty collections in simulation

### ISSUE THREAD

**Issue by shaojunlu** [AIDASoft/DD4hep#330]
- OS version: e.g. SLC6
 - Compiler version: e.g GCC 4.9
 - DD4hep version: nightly build from GitHub master
 - lcgeo version: nightly build from GitHub master
 - Reproduced by: ILDConfig GitHub master
 - Input: on GRID: /ilc/prod/ilc/mc-dbd/generated/1000-B1b_ws/6f/E1000-B1b_ws.Pvvxyyx.Gwhizard-1.95.eL.pR.I35867.001.stdhep
 - Output: 3 events test as README.md in ILDConfig just replace the input by above input
https://github.com/iLCSoft/ILDConfig/blob/master/StandardConfig/production/README.md#2-run-the-lcgeoddsim-simulation-the-3-ttbar-example
 - anajob output slcio: MCParticle collection is there, but all other collections are empty

```shell
///////////////////////////////////
EVENT: 2
RUN: 0
DETECTOR: ILD_l5_v02
COLLECTIONS: (see below)
///////////////////////////////////

---------------------------------------------------------------------------
COLLECTION NAME               COLLECTION TYPE          NUMBER OF ELEMENTS  
===========================================================================
BeamCalCollection             SimCalorimeterHit                0
ECalBarrelScHitsEven          SimCalorimeterHit                0
ECalBarrelScHitsOdd           SimCalorimeterHit                0
ECalBarrelSiHitsEven          SimCalorimeterHit                0
ECalBarrelSiHitsOdd           SimCalorimeterHit                0
ECalEndcapScHitsEven          SimCalorimeterHit                0
ECalEndcapScHitsOdd           SimCalorimeterHit                0
ECalEndcapSiHitsEven          SimCalorimeterHit                0
ECalEndcapSiHitsOdd           SimCalorimeterHit                0
EcalEndcapRingCollection      SimCalorimeterHit                0
FTDCollection                 SimTrackerHit                    0
HCalBarrelRPCHits             SimCalorimeterHit                0
HCalECRingRPCHits             SimCalorimeterHit                0
HCalEndcapRPCHits             SimCalorimeterHit                0
HcalBarrelRegCollection       SimCalorimeterHit                0
HcalEndcapRingCollection      SimCalorimeterHit                0
HcalEndcapsCollection         SimCalorimeterHit                0
LHCalCollection               SimCalorimeterHit                0
LumiCalCollection             SimCalorimeterHit                0
MCParticle                    MCParticle                     232
SETCollection                 SimTrackerHit                    0
SITCollection                 SimTrackerHit                    0
TPCCollection                 SimTrackerHit                    0
TPCLowPtCollection            SimTrackerHit                    0
TPCSpacePointCollection       SimTrackerHit                    0
VXDCollection                 SimTrackerHit                    0
YokeBarrelCollection          SimCalorimeterHit                0
YokeEndcapsCollection         SimCalorimeterHit                0
---------------------------------------------------------------------------
```

**Comment by gaede** [comment]
As far as I understand, this problem occurs only, if the incoming beam particles are in the generator file - then nothing gets simulated. Our 3 ttbar event test (using an older stdhep file w/o incoming particles works fine). 
My prime suspects for this problem would be #310 and #315 as they both deal with the treatment of the MCParticle collections and we have not observed this problem before.
@MarkusFrankATcernch  and @andresailer could you please have a look ?

**Comment by shaojunlu** [comment]
@rete @gaede  @MarkusFrankATcernch @andresailer @danieljeans 

Jakob is working on this input file. 
Jakob said, these empty collections have not been seen with ilcsoft release v01-19-05.

**Comment by gaede** [comment]
@andresailer do you run regular simulation tests for CLIC with *newer* stdhep or lcio input files ?

**Comment by andresailer** [comment]
We just started using whizard2 now to create samples for simulation. Other samples were produced with pythia6 or whizard 1.9.5
