### ISSUE TITLE
libGLU.so not found

### ISSUE THREAD

**Issue by jstrube** [AIDASoft/DD4hep#332]
I'm trying to build DD4HEP from source, but I'm failing with:
```
make[2]: *** No rule to make target `/usr/lib64/libGL.so', needed by `lib/libDDG4.so.1.5'.  Stop.
make[1]: *** [DDG4/CMakeFiles/DDG4.dir/all] Error 2
```
Similarly for `libGLU.so`. The packages are installed, and I can find, e.g. `/usr/lib64/libGLU.so.1`, but `libGLU.so` without the `.1` is in fact not there.
It seems that cmake should figure this out, but obviously it doesn't.

The steps to reproduce are listed here
https://github.com/iLCSoft/lcgeo/issues/205#issuecomment-370343144
This works on KEKCC, which is a 
- Linux cw11.cc.kek.jp 2.6.32-696.18.7.el6.x86_64

but for some reason this fails on this system:

 - Linux scientific1 2.6.32-696.20.1.el6.x86_64

It looks like the path to the non-existing `.so` is hard-wired into the many `.make` files that cmake creates,. so it looks to me like a mis-configuration there.

Edit: @andresailer fixed formatting

**Comment by petricm** [comment]
Sorry but I cannot reproduce this on kekcc, I was able to successfully build on kekcc DD4hep against the desy cvmfs (@rete instructions) and also against the clic cvmfs.

**Comment by MarkusFrankATcernch** [comment]
Hi Jan,
you want to ensure your machine is capable of running ROOT.
If you follow the prerequisites, you see, that these libraries are required by ROOT:
https://root.cern.ch/build-prerequisites

Here it says e.g. xlibmesa-glu-dev must be installed. and then the link 
/usr/lib64/libGLU.so --> /usr/lib64/libGLU.so.1 should also be present.

Cheers,
Markus

**Comment by petricm** [comment]
That link is present on cw11
```sh
[@cw11 ~]$ ll /usr/lib64/libGLU.so
lrwxrwxrwx. 1 root root 15 Jun  7  2016 /usr/lib64/libGLU.so -> libGLU.so.1.3.1*

```

**Comment by jstrube** [comment]
@MarkusFrankATcernch 
ah indeed. `yum provides` to the rescue.
```
yum provides /usr/lib64/libGLU.so
Loaded plugins: refresh-packagekit, security
mesa-libGLU-devel-11.0.7-4.el6.x86_64 : Mesa libGLU development package
Repo        : sl
Matched from:
Filename    : /usr/lib64/libGLU.so
```
I thought that machine was running root, but I don't know how that was installed.
Thanks.
