### ISSUE TITLE
System of units in DDRec

### ISSUE THREAD

**Issue by rete** [AIDASoft/DD4hep#346]
- OS version: any
 - Compiler version: any
 - DD4hep version: master

 - Goal: Use DD4hep units in a python script with DDRec
 - Reproduced by: 

```shell
source /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/init_ilcsoft.sh
python
```

then in the python shell
```python
import SystemOfUnits as DDUnits
print DDUnits.mm
# > output 1.0
```

But I was expecting `mm` to 0.1.

After digging in DD4hep, I have found two different files called SystemOfUnits.py. One in `DDCore/python/SystemOfUnits.py` and one in `DDG4/python/SystemOfUnits.py`. Both files have different units, as the DDG4 one uses the CLHEP units (mm) and the DDCore one uses the ROOT one (cm).
The problem now is that both files are installed on `make install` in the same python directory. The one in use is the DDG4 one and then can't be used in any DDRec python script (requires mm to be 0.1).

As a temporary workaround, I can copy the file with the units I want in my local code and import it, but this is not a correct long term solution I guess.

**Comment by petricm** [comment]
The file `DDCore/python/SystemOfUnits.py` is gone and the remaining file in DDG4 is deprecated
```py
print 'DEPRECATION WARNING  The namespace "SystemOfUnits" is deprecated. Please use "g4units" instead.'
```
The python units file is automatically generated from the `DD4hepUnits.h`
