### ISSUE TITLE
How can I get the layer ID from the Volume ID?

### ISSUE THREAD

**Issue by nalipour** [AIDASoft/DD4hep#347]
Dear All, 

I am working on the implementation of the drift chamber in FCCSW using DD4hep.
The geometry consists of hyperboloid volumes of (sensitive) gas layers. Each layer has some sensitive wires (acquiring the signal from the gas) and the number of the wires varies as a function of layer. I do not place physical volumes for the wires but the segmentation contains the information on the number of wires, as well as their positions.

In the geometry description, I give a layer ID to each gas layer:
https://github.com/nalipour/FCCSW/blob/403f3ec9d344eb101b3f7b15fccfd9eb5f1738c6/Detector/DetCommon/src/parametrised_DriftChamber.cpp#L119

In the geometry description, for each layer I set the parameters of the segmentation for each layer :
https://github.com/nalipour/FCCSW/blob/403f3ec9d344eb101b3f7b15fccfd9eb5f1738c6/Detector/DetCommon/src/parametrised_DriftChamber.cpp#L116 

where ```DCHseg->setGeomParams(...)``` creates a map relating the layer_id to the number of wires and their position:
https://github.com/nalipour/FCCSW/blob/403f3ec9d344eb101b3f7b15fccfd9eb5f1738c6/Detector/DetSegmentation/DetSegmentation/GridDriftChamber.h#L53

When, I would like to associate a cellID to a hit position, the vID is not the same as the layerID and all my computations are wrong because I can not retrieve the correct parameters of the layer:
https://github.com/nalipour/FCCSW/blob/403f3ec9d344eb101b3f7b15fccfd9eb5f1738c6/Detector/DetSegmentation/src/GridDriftChamber.cpp#L60

And of course, in FCCSW, for the moment, we are using an older version of DD4hep where I can not just simply do (as André has kindly suggested):
```cpp
int layerID = _decoder->get(volumeID, "layer");
```

```sh
error: ‘class dd4hep::DDSegmentation::BitField64’ has no member named ‘ge’
     int layerID = _decoder->get(vID, "layer");
```

Could you please tell me how I can get the layer_id from the volumeID?

Thank you in advance for considering my issue,
Best regards,
Nilou

**Comment by MarkusFrankATcernch** [comment]
Is the "old" way (ie. before getting things multi-threaded) of deducing the fields not like this:
_decoder->setValue(vID);
int layerID = _decoder->get("layer");

Then you should end up with the same result as with Andre's suggestion.

**Comment by nalipour** [comment]
Dear Markus,

```dd4hep::DDSegmentation::BitField64``` does not have a member ```get```.

I still get the same error.

Thanks,
Nilou

**Comment by vvolkl** [comment]
Hi Nilou,

for the "old" usage, see my example at https://github.com/HEP-FCC/FCCSW/blob/master/Test/TestReconstruction/src/CompareTrackHitPositionAndCellId.cpp#L69

you can also already use the new dd4hep version, the needed changes (to the init script and code) are here:
https://github.com/HEP-FCC/FCCSW/pull/303
and will be merged as soon as we have a new installation :)

**Comment by nalipour** [comment]
Hi Valentin, 

Thanks for the tip. It works well.

Cheers,
Nilou
