### ISSUE TITLE
Forward TGeo units to DD4hep

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#352]
Redefine units in DD4hep using the [units from ROOT](https://root.cern.ch/doc/master/namespaceTGeoUnit.html)

**Comment by MarkusFrankATcernch** [comment]
Solved.
Please see merge requests:
https://github.com/AIDASoft/DD4hep/pull/353 and 
https://github.com/AIDASoft/DD4hep/pull/355
