### ISSUE TITLE
BIBER_COMPILER check

### ISSUE THREAD

**Issue by shaojunlu** [AIDASoft/DD4hep#363]
Some system has LATEX_COMPILER only, but do not have BIBER_COMPILER.
It will not work for the update in "usermanuals/DD4hep" in Update DD4hepManual #362.
Would you please add this check?
Or you have better solution for the BIBER_COMPILER check.

doc/CMakeLists.txt

    IF(BIBER_COMPILER)
        ADD_SUBDIRECTORY(usermanuals/DD4hep)
    ENDIF(BIBER_COMPILER)

**Comment by petricm** [comment]
Hi, thank you for pointing this out, there are a few possibilities to solve this, but can you give me first a log output from such a system.

**Comment by shaojunlu** [comment]
**CMake Error at cmake/LATEX.cmake:1585 (message):
  I need the biber command.**


```shell
COMPILER_PATH=/afs/cern.ch/sw/lcg/contrib/gcc/4.9.3/x86_64-slc6/lib/gcc/x86_64-unknown-linux-gnu/4.9.3
CC=gcc
----- END OF ENVIRONMENT SNAPSHOT -----
loading initial cache file /scratch/nbuilds/gcc49/2018-04-13/ILCSoft.cmake
-- CMAKE_INSTALL_PREFIX is /scratch/nbuilds/gcc49/2018-04-13/DD4hep/HEAD - overwrite with -D CMAKE_INSTALL_PREFIX
-- Found Doxygen: /usr/bin/doxygen (found version "1.6.1") 
-- Found LATEX: /usr/bin/latex   
-- Found LaTeX compiler.
-- Found UnixCommands: /bin/bash  
-- I could not find the htlatex command.
-- I could not find the biber command.
CMake Error at cmake/LATEX.cmake:1585 (message):
  I need the biber command.
Call Stack (most recent call first):
  cmake/LATEX.cmake:1892 (add_latex_targets_internal)
  doc/usermanuals/DD4hep/CMakeLists.txt:2 (ADD_LATEX_DOCUMENT)


-- The CXX compiler identification is GNU 4.9.3
-- Check for working CXX compiler: /afs/cern.ch/sw/lcg/contrib/gcc/4.9.3/x86_64-slc6/bin/g++
-- Check for working CXX compiler: /afs/cern.ch/sw/lcg/contrib/gcc/4.9.3/x86_64-slc6/bin/g++ -- works
```

**Comment by shaojunlu** [comment]
By the way, you did not detect this before you merge it, because there is no latex.
https://travis-ci.org/AIDASoft/DD4hep/jobs/365788563#L700-L701

**Comment by petricm** [comment]
Of course I tested this 
https://gitlab.cern.ch/mpetric/DD4hep/pipelines/355856
I just don't test with such an old version of LaTeX

**Comment by shaojunlu** [comment]
I am not aware that I am using an old version of LaTeX.
I am running the integration check on SL6 machine.
I know that DESY has CentOS7, and I did not find "biber" command either.
I will check with our IT. Thank you for the information.
