### ISSUE TITLE
macOS problem with filenames

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#365]
These two files
`DDCore/python/DD4hep.py`
and
`DDCore/python/dd4hep.py`
cannot be distinguished on masOS due to the fact that by default Apple File System is case insensitive. 

This will cause a developer on a mac to always see a change in this file when he want to commit with git.

**Comment by MarkusFrankATcernch** [comment]
Must stay like this for some time for backwards compatibility.
Then DD4hep.py must disappear.

**Comment by petricm** [comment]
Then `DD4hep.py` must go immediately after next release
