### ISSUE TITLE
sparse tracker hits located outside of SD silicon layer

### ISSUE THREAD

**Issue by shaojunlu** [AIDASoft/DD4hep#366]
There are sparse tracker hits which have be located outside of SD silicon layers.
The driver, which is used for the silicon sensitive detectors, is "Geant4TrackerWeightedAction".
@petricm CLICdp uses it for silicon detectors too? 

https://github.com/AIDASoft/DD4hep/blob/master/DDG4/plugins/Geant4TrackerWeightedSD.cpp#L284-L289

I have suspicion that the code want to do something with "postSD == thisSD", but both postSD and thisSD are always identical for SD.

By chance, a task was assigned to me to check our background simulation.
I have a look at the SimTrackerHits distribution for VXD, there are **62484926 VXD hits** from 98968 events of seeablepairs background simulation.

By the way, It is hardly to see the sparse hits with order 59740 hits statistic in VXD.

Maybe,  the G4VPhysicalVolume have to be used here, like prePV, postPV and thisPV.
Or you want to provide the preSD, postSD and thisSD in lower level core codes part.

I generate an issue here to report this information. I think that you want to review and fix it in future.  

@MarkusFrankATcernch 
In the plots, we expect/should see only **three circles** with only **double layers**.

**62484926 VXD hits in this plots**

![simcalorimeterhits_distribution_seeablepairs_vxd_xy](https://user-images.githubusercontent.com/22344326/38732659-48989a96-3f1f-11e8-9db6-1f609d29df78.png)

**Comment by shaojunlu** [comment]
Dear @MarkusFrankATcernch and all,

To be honest, I have not yet fully understood the logic.
Maybe There's something else behind.

**Comment by shaojunlu** [comment]
Try to understand the design:
 - Is this "postSD == thisSD" used to make sure this G4Step come from VXD, and this G4Step the "postSD" does not come from SIT or FTD ... others Silicon detectors?
  - Is this "post_inside == kInside" used to make sure the current processing G4Step still inside the same Silicon layer volume? 
      - The design to update with this G4Step, which come from **same silicon layer** of VXD?
      - For example, The pre position from start(G4Step) in silicon layer 1, and the post position from last update(G4Step) should in silicon layer 1, too. not come from layer 2,3,4 .....
   

https://github.com/AIDASoft/DD4hep/blob/master/DDG4/plugins/Geant4TrackerWeightedSD.cpp#L251-L256

**Comment by petricm** [comment]
Have you checked that this change really fixes your problem?

**Comment by MarkusFrankATcernch** [comment]
Hi Shaojun,

Thanks for the work!
Logically your suggestion sounds correct. We collect (and accumulte hit contributions) according to volumes, which has a finer granularity than sub-detectors.

Having said this, I would think that the very same bug/feature is present in the if-clauses
for 3, 4, 5 as well and the check of the subdetectors should be replaced by the check of physical volumes or do I miss here something?

Cheers,
Markus

**Comment by shaojunlu** [comment]
@petricm 
No, it is not so simple to fix this problem.
We have to understand the original design, then to find the proper fix.
I just try to figure out what may cause this problem.
Some expert may fix it in the proper way.

**Comment by petricm** [comment]
@shaojunlu can you not just recompile DD4hep with your proposed solution re-simulare and see if the hits move into the rights position?

**Comment by shaojunlu** [comment]
@MarkusFrankATcernch 
If I find something, I will let you know.
After the Monday meetings here, I may try more check/test.

**Comment by shaojunlu** [comment]
@petricm @MarkusFrankATcernch  @gaede @danieljeans 
Dear All,
I think that I have understood this a little bit more.
Thank you very much for you help.

I think, **I should not expect** all the hits on the SD layer.
When the G4Step pre position inside the SD and the post position in the Air or support or envelop, this kind of hit may be placed outside of SD, because the contribution include the dead material.

And further more, this sparse hit should be filtered out by the following reconstruction.
I agree, we should save this kind sparse hit in the simulation, and the reconstruction will take care of them.


There is no issue, I think, I just did not understand what I have seen.
Thank you very much for your time.

I would like to close this issue.
Shaojun

**Comment by andresailer** [comment]
The sensitive detector is always associated to a volume. If a step reaches a volume boundary it will always end the step. So PreStep and PostStep position are always in the same volume. So unless the volume is non-convex the average step position should also be inside the volume. And thus all hits for a sensitive detector should be inside the volume as well.

**Comment by shaojunlu** [comment]
Dear All,
  - For the Silicon sensor tracker simulation, if the **sensor thickness 50 um > sensor point resolution 3 um x3 um**,
    - should accumulate the G4Step within the volume?
    - may the accumulation shift the fired sensor point position larger that the point resolution itself?
  

**to accumulate the G4Step within the same volume (same sensitive layer), will it bias the hardware fired sensor point position? because 50.0/3.0 =~16**

  - **should collect single deposition because 50 um > 3um?**
https://github.com/iLCSoft/ILDConfig/blob/master/StandardConfig/production/ddsim_steer.py#L82
change CollectSingleDeposits to True.
```python
SIM.action.tracker = ('Geant4TrackerWeightedAction', {'HitPositionCombination': 2, 'CollectSingleDeposits': True})
```

  - I made a lot of check/test. I tried to accumulate the G4Step within the same volume, but I got the bias on my track fitting for the D0 resolution, and pull distributions ... **I may still use prePV, postPV and thisPV in the wrong logic locally.**
  - But I did not see the bias for my track fitting on D0, pull with "CollectSingleDeposits == True" and no  sparse tracker hits locate outside of SD silicon layer .



**541989 hits in this plot from 1000 ttbar events**

![vxd_collectsingledeposits_true](https://user-images.githubusercontent.com/22344326/38938251-61a57194-4325-11e8-9d74-36f2120b329d.png)

It is not possible to see any difference on the track final reconstruction from the sparse hits by comparing with the above simulation (CollectSingleDeposits == True). 
If the sparse hits have been filtered out by Digi/Reco, they look like the hardware inefficiency, which have been simulated by chance.

**Comment by shaojunlu** [comment]
@petricm For this moment, we did not find any better solution to put the sparse tracker hits back onto the SD silicon layer.
I am not sure about this. you may close it.
I know this issue number. I will find time in the future to come back to this point if I could find better solution, and I will let you all know.

**Comment by gaede** [comment]
We should leave this open, as it is still an unsolved issue - even though not critical....

**Comment by shaojunlu** [comment]
Close this issue with PR #412
