### ISSUE TITLE
DD4Hep Licence Question

### ISSUE THREAD

**Issue by ianna** [AIDASoft/DD4hep#368]
Do you intend to move to LGPL and have the copyright owned by CERN?

**Comment by petricm** [comment]
We have never discussed a move to LGPL, so a present there is no intent. 
Does CMS have problems with GPLv3?

**Comment by ianna** [comment]
Yes, but as an external. The problem comes with the DDCMS example code. If we (CMS) want to import the code in CMSSW and make a production version, we cannot have AIDA copyright there.

**Comment by ianna** [comment]
no problem, let's discuss it then

**Comment by ianna** [comment]
BTW, CMS uses hepmc v 2.06.07

**Comment by ianna** [comment]
http://www.gnu.org/licenses/gpl-faq.html#AllCompatibility

**Comment by petricm** [comment]
Agreed to move to LGPLv3
