### ISSUE TITLE
Non-cylindrical tracking region

### ISSUE THREAD

**Issue by protopopescu** [AIDASoft/DD4hep#371]
I wonder if it is possible to define the tracking region in the same way that we define envelopes for example. At the moment, for SiD, the tracking region is a **cylinder**, defined by 

 ```xml
<constant name="tracker_region_rmax" value="some_r_value"/>
 <constant name="tracker_region_zmax" value="some_z_value"/>
```
And I would like to be able to exclude the LumiCal.

![trackers lumical](https://user-images.githubusercontent.com/23111675/39246997-0d726972-4890-11e8-91f9-2dea1f967a11.png)

**Comment by MarkusFrankATcernch** [comment]
As it is now, there is no tracking volume defined... the code is all #ifdef'ed out.
ie. now any xml declaration is simply ignored ....

In principle I like this idea - cylindrical tracking regions are only valid for cylinder symmetric
experiments. The only question is how to formulate this in xml.

If you would have a generic, more explicit proposal I would appreciate it would be nice.

**Comment by protopopescu** [comment]
What if we could define something like this?

```
<tracking_region>
    <shape type="Tube" rmin="ForwardTracker_outer_radius" rmax="SiTracker_outer_radius" dz="SiTracker_half_length"/>
    <shape type="Tube" rmin="0" rmax="ForwardTracker_outer_radius" dz="ForwardTracker_half_length"/>
</tracking_region>
```

**Comment by MarkusFrankATcernch** [comment]
I will have to see with Marko. Ideally I would like to keep the same recursive syntax to incorporate boolean shapes as it is done for the envelopes. There is one caveat though to be sorted out: this tracking volume should not participate in the Geant4 conversion since there are no daughters attached.
Or do I mis-interpret here something?

**Comment by petricm** [comment]
What do you mean it's all #ifdef'ed out? The MC record is different for particles inside and outside the tracking volume.

**Comment by MarkusFrankATcernch** [comment]
It is ifdef'ed out. The MC truth checks only if the hit is within a cylinder with dimesions given in the define section - not for a concrete volume. Checking if a hit is inside a volume is more complicated and also much slower.

**Comment by protopopescu** [comment]
Something like this?
```
<tracking_region>
     <shape type="BooleanShape" operation="Subtraction" material="Air">
                <shape type="Tube" rmin="0" rmax="SiTracker_outer_radius" dz="SiTracker_half_length"/>
                <shape type="BooleanShape" operation="Subtraction">
                    <shape type="Tube" rmin="0" rmax="ForwardTracker_outer_radius" dz="SiTracker_half_length"/>
                    <shape type="Tube" rmin="0" rmax="ForwardTracker_outer_radius" dz="ForwardTracker_half_length"/>
                </shape>
       </shape>
</tracking_region>
```

**Comment by MarkusFrankATcernch** [comment]
Yes. I suppose this is more or less what I thought of.....

**Comment by gaede** [comment]
Maybe we could use the Geant4 Readout Geometry. This runs parallel to the normal G4 geometry.
However it seems that this would have to be associated to a sensitive detector. To be investigated....

**Comment by gaede** [comment]
Another option would be to add the property 'insidetrackingVolume'  to envelopes. Then of course all tracking detectors would have to have envelope volumes. Caveat: region between tracking envelopes would not be considered 'tracking region' ....

**Comment by MarkusFrankATcernch** [comment]
Or we flag the volumes in TGeo and do not translate them to Geant4 at all.
Corollary is that 
1) these volumes do not have any daughters participating in the simulation. 
2) the material is more or less equivalent to vacuum.

**Comment by petricm** [comment]
As there are several proposed ideas as hot to solve this I propose we put on the agenda of the next meeting and discuss the solution in person?

**Comment by petricm** [comment]
[WIP] Decided that implementation should have a second world volume/ dangling tree that houses the "readout geometry" as not to interfere with the actual detector geometry.
