### ISSUE TITLE
Assemblies, regions and production cuts

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#373]
@jhrdinka
> I would like to set Regions in Geant4. In general this is done in FCCSW after the geometry is translated with a search for certain names in the list of daughters of the world volume (e.g. [here](https://github.com/HEP-FCC/FCCSW/blob/2c39fce349681217f6771081085be6e500c317b6/Sim/SimG4Full/src/components/SimG4UserLimitRegion.cpp#L35)). In the tracker we use assemblies for the endcaps thus this is getting more complicated, since each disk is translated separately.
> 
> Thus my question: Is there en elegant solution? How do you treat assemblies and regions in Geant4?

@MarkusFrankATcernch 
> Normally the region identifier is set to the volume(s) in the detector constructor. The region object is constructed at the time when compact gets interpreted.
> 
> When the whole thing is translated to Geant4, the regions are created and associated to the G4-volumes the same way.
> 
> Hence, if thins are properly setup in compact, it should simply be propagated to Geant4.
> 
> You should also read: #327 to enable the whole machinery properly.

@jhrdinka
> thanks for you answer. Sorry, the example I was sending was maybe misleading, because I currently want to implement a new tool which sets limits on production cuts, not on tracking cuts.
> 
> However is there a way to define regions already in the DD4hep geometry description?

@MarkusFrankATcernch 
> Yes. See the [CLICSid](https://github.com/AIDASoft/DD4hep/blob/568e043a3d0bdb5e37b1b53139d5982ae7c7bf59/DDDetectors/compact/SiD.xml) example.

@jhrdinka
> thanks. I found here that you define a [region](https://github.com/AIDASoft/DD4hep/blob/master/DDDetectors/compact/SiD.xml#L194) and that it is possible to set some production [cut](https://github.com/AIDASoft/DD4hep/blob/master/DDG4/src/Geant4Converter.cpp#L834), if I understood correctly? Which is basically what I need. 
>
> another question: do I understand correctly, that I need to set the region for every volume in the dd4hep constructor? 

@MarkusFrankATcernch 
> Usage is exactly as in Geant4;
> The exact same volumes having set the attribute are connected in Geant4 to a G4Region. If this is only the mother volume, then also in G4 only the mother volume is connected.

@jhrdinka
> thanks. I can now apply the cut. I have another question: it seems to me, that with this setup I can only apply one cut for all e-,e+,gamma. I need to apply different cuts for gamma and e+-. Did you ever have this case as well?

@MarkusFrankATcernch 
> ```xml
>  <limits>
>    <limitset  name="minitel_limits">
>      <limit  name="step_length_max"  particles="e[+-]"  value="1.0"  unit="mm"  />
>      <limit  name="step_length_max"  particles="mu[+-]"  value="3.0"  unit="mm"  />
>      <limit  name="step_length_max"  particles="*"  value="5.0"  unit="mm"  />
>    </limitset>
>  </limits>
> ```
> 
> You can set individual limits to the particles identified by the regex `particles="e[+-]"`
> Only if `particles="*"` they apply to all.
> 
> For e+,e-,gamma you want:
> ```xml
>    <limitset  name="minitel_limits">
>      <limit  name="step_length_max"  particles="e[+-]"  value="1.0"  unit="mm"  />
>      <limit  name="step_length_max"  particles="gamma"  value="5.0"  unit="mm"  />
>    </limitset>
> ```

**Comment by jhrdinka** [comment]
thanks. However this only seems to set the tracking cuts in Geant4. I would like to set also a production threshold which is different for gamma and e+- as done e.g. [here](http://geant4-userdoc.web.cern.ch/geant4-userdoc/UsersGuides/ForApplicationDeveloper/BackupVersions/V10.3/html/ch05s05.html).

**Comment by MarkusFrankATcernch** [comment]
This indeed is not part of dd4hep compact notation nor is this implemented in ddg4.
We should discuss it during the meeting next Wednesday to at least collect all necessary requirements
and the interaction with regions etc.

**Comment by petricm** [comment]
Decided to add it to the limits set
