### ISSUE TITLE
PseudoTrap shape dZ

### ISSUE THREAD

**Issue by ianna** [AIDASoft/DD4hep#396]
dZ is interpreted as a full length along Z in PseudoTrap ( a Trapezoid with a bump ), while it should be half length. The same shape as interpreted by CMS DD - first snapshot, second - from DD4Hep:
```
    <PseudoTrap name="ptrap1" dx1="10*cm" dx2="3*cm" dy1="30*cm" dy2="10*cm" dz="30*cm" radius="10*cm" atMinusZ="false"/>
    <PseudoTrap name="ptrap2" dx1="10*cm" dx2="3*cm" dy1="30*cm" dy2="10*cm" dz="30*cm" radius="10*cm" atMinusZ="true"/>

```
![screenshot 2018-05-30 15 01 27](https://user-images.githubusercontent.com/1390682/40721652-691697e4-641a-11e8-8ca9-72f458202426.png)
![screenshot 2018-05-30 15 01 53](https://user-images.githubusercontent.com/1390682/40721661-765cb9d8-641a-11e8-9ff2-efbd9b0d84bc.png)

**Comment by MarkusFrankATcernch** [comment]
We have to wait for the confirmation of Yana.

**Comment by ianna** [comment]
@MarkusFrankATcernch - thanks! It's fixed.
<img width="951" alt="screen shot 2018-06-01 at 09 03 00" src="https://user-images.githubusercontent.com/1390682/40826445-e74d2cc0-657a-11e8-830f-46f280d853aa.png">
