### ISSUE TITLE
TruncTubs Shape

### ISSUE THREAD

**Issue by ianna** [AIDASoft/DD4hep#401]
DD CMS TruncTube defined as:
```
<TruncTubs name="trunctubs2" rMin="6.9551*m" rMax="9*m" cutAtStart="6.9551*m" cutAtDelta="7.20045*m" cutInside="true" startPhi="0*deg" deltaPhi="15*deg" zHalf="6.57005*m"/>
```
and translated:
```
<Translation z="-28.9*m" y="5.9*m" x="0."/>
```
DD CMS to G4 conversion:
https://cmssdt.cern.ch/lxr/source/SimG4Core/Geometry/src/DDG4SolidConverter.cc#0424

DD CMS to TGeo conversion:
https://cmssdt.cern.ch/lxr/source/Fireworks/Geometry/src/TGeoMgrFromDdd.cc#0513

DD CMS - left, the same in DD4Hep - right:
![screenshot 2018-06-04 09 59 11](https://user-images.githubusercontent.com/1390682/40905394-171dbf0e-67de-11e8-85ec-449721ef83ac.png)

![screenshot 2018-06-04 10 16 34](https://user-images.githubusercontent.com/1390682/40906220-79c29498-67e0-11e8-85d4-01f61e7c07f8.png)

**Comment by MarkusFrankATcernch** [comment]
There is an inconsistency in the CMS code:

https://cmssdt.cern.ch/lxr/source/SimG4Core/Geometry/src/DDG4SolidConverter.cc#0424
0482 
0483   G4ThreeVector trans(xBox,0.,0.);
0484   LogDebug("SimG4CoreGeometry") << "trans=" << trans;
0485 
0486   G4VSolid * box = new G4Box(name,boxX,boxY,boxZ);
0487   result = new G4SubtractionSolid(name,tubs,box,rot,trans);

vs.

https://cmssdt.cern.ch/lxr/source/Fireworks/Geometry/src/TGeoMgrFromDdd.cc#0513
0578 std::auto_ptr<TGeoShape> box( new TGeoBBox( name.c_str(), boxX/cm, boxZ/cm, boxY/cm ));
0579

Z and Y are exchanged.
I suppose the upper is correct. Based on this assumption I updated the repository head and get now something that looks like your image. Please test.

Markus

**Comment by ianna** [comment]
@MarkusFrankATcernch - thanks! I'm not surprised that there are bugs in CMS code :-)

**Comment by ianna** [comment]
The dimensions are fine, but a cut plane is not (left CMS DD, right DD4Hep):
![screenshot 2018-06-06 11 33 33](https://user-images.githubusercontent.com/1390682/41030022-a4488274-697d-11e8-9ad1-06ffed35ebfb.png)

**Comment by ianna** [comment]
![slide1](https://user-images.githubusercontent.com/1390682/41044065-a0689338-69a5-11e8-879c-90a69f9d9634.jpg)
![slide2](https://user-images.githubusercontent.com/1390682/41044066-a0a6e48a-69a5-11e8-9c51-b5ef932542e5.jpg)
![slide3](https://user-images.githubusercontent.com/1390682/41044067-a0d71ed4-69a5-11e8-8437-67e72babc581.jpg)

**Comment by ianna** [comment]
Thanks, it's fixed.
![screenshot 2018-06-08 09 55 22](https://user-images.githubusercontent.com/1390682/41146017-3891d982-6b02-11e8-99f5-27ed58cf7c78.png)
