### ISSUE TITLE
Not all examples work when built out of the box

### ISSUE THREAD

**Issue by gordonwatts** [AIDASoft/DD4hep#410]
A number of examples fail out of the box. All the failures are due to missing data files. For example (copied from #406):

    ----------------------------------------------------------
     ### running test :  'geoPluginRun  -volmgr -destroy -plugin DD4hep_AlignmentExample_populate -input file:/root/install/examples/AlignDet/compact/Telescope.xml -iovs 10'
    PersistencyIO    INFO  +++ Set Streamer to dd4hep::OpaqueDataBlock
    PersistencyIO    INFO  +++ Patching TGeoVolume.fUserExtension to persistent
    Info in <TGeoManager::TGeoManager>: Geometry world, Detector Geometry created
    PersistencyIO    INFO  +++ Patching TGeoNode.fUserExtension to persistent
    geoPluginRun: No geometry input supplied. No geometry will be loaded.
    DD4hepVolumeManager INFO  **** running plugin DD4hepVolumeManager !
    VolumeManager    INFO   - populating volume ids - be patient ...
    VolumeManager    INFO   - populating volume ids - done. 0 nodes.
    VolumeManager    INFO  +++ Volume manager populated and loaded.
    XercesC          FATAL +++ FATAL Error at file "", Line 0 Column: 0 Message:unable to open primary document entity '/root/install/examples/AlignDet/compact/Telescope.xml'
    RunPlugin        ERROR ++ Exception while executing plugin DD4hep_AlignmentExample_populate:
                    Document::root: Invalid handle!
    dd4hep: while parsing file:/root/install/examples/AlignDet/compact/Telescope.xml
    dd4hep: with plugin:DD4hep_AlignmentExample_populate
    geoPluginRun: Got uncaught exception: RunPlugin: ++ Exception while executing plugin DD4hep_AlignmentExample_populate:
                    Document::root: Invalid handle!
    dd4hep: while parsing file:/root/install/examples/AlignDet/compact/Telescope.xml
    dd4hep: with plugin:DD4hep_AlignmentExample_populate
    <end of output>
    Test time =   0.37 sec
    ----------------------------------------------------------

This particular failure can be fixed by updating the CMakeLists.txt file in exampls/AlignDet by replacing the line:

    dd4hep_install_dir( compact DESTINATION examples/AlignDet )

with

    dd4hep_install_dir( compact DESTINATION ${DD4hep_DIR}/examples/AlignDet )

The rest of the test failures can be fixed with similar modifications. The CMakeLists.txt files in Conditionss and DDDB need to be similarly updated. The CMakeLists.txt in DDDB is slightly different and the one line must be updated to look like:

    install ( FILES    data/DDDB.tar.gz DESTINATION ${DD4hep_DIR}/examples/DDDB)

I do not know the DD4hep cmake code well enough to know if this is a bug in the script copying over, or is the above code changes are the proper ones to fix. But, certainly, after these changes are made to the three files all tests build in the examples directory.

Using Ubuntu, Xenial, and working off the release 1.07 branch.

**Comment by MarkusFrankATcernch** [comment]
Please see: https://github.com/AIDASoft/DD4hep/pull/409

**Comment by gordonwatts** [comment]
Ah, that looks like it should fix it!

**Comment by MarkusFrankATcernch** [comment]
It worked for me on my box....the "official" tests are not (yet) updated to check this.

**Comment by gordonwatts** [comment]
The latest version of the head seems to work well in my personal testing (e.g. built in a docker container):

- All tests build out of the box
- All examples build out of the box
- It is now possible to set the install directory for the examples tests in another location, and everything all works properly there.
