### ISSUE TITLE
memcpy@GLIBC_2.14

### ISSUE THREAD

**Issue by jstrube** [AIDASoft/DD4hep#422]
I am trying to build master@dfd976098a2dd54ee737c0bc3101a8acce6d2e0c
After checking out, I `source /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v02-00-01/init_ilcsoft.sh`
Then 
```
cd DD4HEP
mkdir build
cd build
cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=ON -DBUILD_TESTING=ON -DGeant4_DIR=/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v02-00-01/geant4/10.03.p02/lib64/Geant4-10.3.2/ -DROOT_DIR=$ROOTSYS ..
make -j 4
```
This fails with the following message:
```
[ 69%] Linking CXX executable ../bin/g4FromXML
/usr/lib64/libSM.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/g4FromXML] Error 1
make[1]: *** [DDG4/CMakeFiles/g4FromXML.dir/all] Error 2
make: *** [all] Error 2
```
This is on the following kind of system: 
```
uname -a
Linux scientific1 2.6.32-696.20.1.el6.x86_64 #1 SMP Thu Jan 25 08:47:49 CST 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Am I missing any steps? Is this no longer compatible with gcc4.9?

I also get errors of the following type:
```
ERROR: failed to load libDDEve.so
libDDEve.so: failed to map segment from shared object: Operation not permitted
```
This is for several .so files, but the build marches on, so I am assuming this is not actually an error.

**Comment by andresailer** [comment]
What is your operating system? 
Where does the libSM.so come from, how did you install it?
What is the version of libc that is installed?

On ScientificLinux 6 the version of glibc is 2.12, your libSM seems to have been compiled against GLIBC2.14

```
$ yum provides /lib64/libc.so.6 |tail
glibc-2.12-1.212.el6.x86_64 : The GNU libc libraries
Repo        : installed
Matched from:
Other       : Provides-match: /lib64/libc.so.6
$ uname -a
Linux pclcd50.dyndns.cern.ch 2.6.32-696.23.1.el6.x86_64 #1 SMP Wed Mar 14 11:28:37 CET 2018 x86_64 x86_64 x86_64 GNU/Linux
$ yum provides /usr/lib64/libSM.so | tail
libSM-devel-1.2.1-2.el6.x86_64 : X.Org X11 SM development package
Repo        : installed
Matched from:
Other       : Provides-match: /usr/lib64/libSM.so
```

**Comment by jstrube** [comment]
I suspect this is right. Looks like libSM wasn't installed correctly. 
Re-installing the package fixes it. Sorry for the noise.
