### ISSUE TITLE
Support for optical surfaces

### ISSUE THREAD

**Issue by MarkusFrankATcernch** [AIDASoft/DD4hep#440]
Develop support for optical surfaces in DD4hep
- [x] Define surfaces in ROOT/TGeo
- [x] in their DD4hep counterparts
- [x] implement conversion to Geant4

**Comment by dannielliu** [comment]
Dear developers, 
I try to run the example of optical surface in DD4hep. There are some problems when I convert the compact description to gdml file. One is that many properties are empty in the gdml file, which means the value of matrix is "". The content of output gdml file can be found below. When I try to input it to a Geant4 standalone program, there are some errors. Are there solutions for this problem?

Thank you!
Best regards,
Dong LIU

*****************************************************************************************************
### The gdml file
**************************************************************
<?xml version="1.0"?>
<gdml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://service-spi.web.cern.ch/service-spi/app/releases/GDML/schema/gdml.xsd">
  <define>
    <matrix name="RINDEX__Air" coldim="2" values=""/>
    <matrix name="RINDEX__Water" coldim="2" values=""/>
    <matrix name="ABSLENGTH__Water" coldim="2" values=""/>
    <matrix name="FASTCOMPONENT__Water" coldim="2" values=""/>
    <matrix name="SLOWCOMPONENT__Water" coldim="2" values=""/>
    <matrix name="MIEHG__Water" coldim="2" values=""/>
    <matrix name="REFLECTIVITY__0x7ff9ddb9d170" coldim="2" values="REFLECTIVITY"/>
    <matrix name="EFFICIENCY__0x7ff9ddb9d3c0" coldim="2" values="EFFICIENCY"/>
    <position name="Bubble_0inTankpos" x="0" y="0" z="0" unit="cm"/>
    <position name="Tank_0inDetpos" x="0" y="0" z="0" unit="cm"/>
    <position name="Det_0inworld_volumepos" x="0" y="0" z="0" unit="cm"/>
  </define>
  <materials>
    <element name="NITROGEN_elm" formula="N" Z="7">
      <atom unit="g/mole" value="14.006740000000001"/>
    </element>
    <element name="OXYGEN_elm" formula="O" Z="8">
      <atom unit="g/mole" value="15.9994"/>
    </element>
    <element name="ARGON_elm" formula="AR" Z="18">
      <atom unit="g/mole" value="39.948"/>
    </element>
    <material name="Air">
      <D unit="g/cm3" value="0.0011999999999999999"/>
      <fraction n="0.012000000104308128" ref="ARGON_elm"/>
      <fraction n="0.75400000810623169" ref="NITROGEN_elm"/>
      <fraction n="0.23399999737739563" ref="OXYGEN_elm"/>
      <property name="RINDEX" ref="RINDEX__Air"/>
    </material>
    <material name="Vacuum">
      <D unit="g/cm3" value="1e-10"/>
      <fraction n="0.012000000104308128" ref="ARGON_elm"/>
      <fraction n="0.75400000810623169" ref="NITROGEN_elm"/>
      <fraction n="0.23399999737739563" ref="OXYGEN_elm"/>
    </material>
    <element name="HYDROGEN_elm" formula="H" Z="1">
      <atom unit="g/mole" value="1.0079400000000001"/>
    </element>
    <material name="Water">
      <D unit="g/cm3" value="1"/>
      <fraction n="0.11189834773540497" ref="HYDROGEN_elm"/>
      <fraction n="0.88810163736343384" ref="OXYGEN_elm"/>
      <property name="RINDEX" ref="RINDEX__Water"/>
      <property name="ABSLENGTH" ref="ABSLENGTH__Water"/>
      <property name="FASTCOMPONENT" ref="FASTCOMPONENT__Water"/>
      <property name="SLOWCOMPONENT" ref="SLOWCOMPONENT__Water"/>
      <property name="MIEHG" ref="MIEHG__Water"/>
    </material>
  </materials>
  <solids>
    <box name="world_volume_shape_0x7ff9ddba7110" x="100" y="100" z="100" lunit="cm"/>
    <box name="Det_shape_0x7ff9ddb43df0" x="200.02000000000001" y="200.02000000000001" z="200.02000000000001" lunit="cm"/>
    <box name="Tank_shape_0x7ff9ddb43e70" x="200" y="200" z="200" lunit="cm"/>
    <box name="Bubble_shape_0x7ff9ddbfa310" x="100" y="100" z="100" lunit="cm"/>
    <opticalsurface name="/world/BubbleDevice#WaterSurface" model="dichoic" finish="groundvm2000glue" type="x_ray" value="1"/>
    <opticalsurface name="/world/BubbleDevice#AirSurface" model="glisur" finish="polished" type="dielectric_dielectric" value="1">
      <property name="REFLECTIVITY" ref="REFLECTIVITY__0x7ff9ddb9d170"/>
      <property name="EFFICIENCY" ref="EFFICIENCY__0x7ff9ddb9d3c0"/>
    </opticalsurface>
  </solids>
  <structure>
    <volume name="Bubble">
      <materialref ref="Air"/>
      <solidref ref="Bubble_shape_0x7ff9ddbfa310"/>
    </volume>
    <volume name="Tank">
      <materialref ref="Water"/>
      <solidref ref="Tank_shape_0x7ff9ddb43e70"/>
      <physvol name="Bubble_0" copynumber="0">
        <volumeref ref="Bubble"/>
        <positionref ref="Bubble_0inTankpos"/>
      </physvol>
    </volume>
    <volume name="Det">
      <materialref ref="Vacuum"/>
      <solidref ref="Det_shape_0x7ff9ddb43df0"/>
      <physvol name="Tank_0" copynumber="0">
        <volumeref ref="Tank"/>
        <positionref ref="Tank_0inDetpos"/>
      </physvol>
    </volume>
    <volume name="world_volume">
      <materialref ref="Air"/>
      <solidref ref="world_volume_shape_0x7ff9ddba7110"/>
      <physvol name="Det_0" copynumber="0">
        <volumeref ref="Det"/>
        <positionref ref="Det_0inworld_volumepos"/>
      </physvol>
    </volume>
    <bordersurface name="/world//world/BubbleDevice#HallTank" surfaceproperty="/world/BubbleDevice#WaterSurface">
      <physvolref ref="Tank_0" ref="Det_0"/>
    </bordersurface>
    <bordersurface name="/world//world/BubbleDevice#TankBubble" surfaceproperty="/world/BubbleDevice#AirSurface">
      <physvolref ref="Bubble_0" ref="Tank_0"/>
    </bordersurface>
  </structure>
  <setup name="default" version="1.0">
    <world ref="world_volume"/>
  </setup>
</gdml>

*****************************************************************************************************
### Geant4 output when importing the gdml file 
*****************************************************************************************************

**************************************************************
 Geant4 version Name: geant4-10-04-patch-01    (28-February-2018)
                       Copyright : Geant4 Collaboration
                      References : NIM A 506 (2003), 250-303
                                 : IEEE-TNS 53 (2006), 270-278
                                 : NIM A 835 (2016), 186-225
                             WWW : http://geant4.org/
**************************************************************

G4GDML: Reading 'OpNovice.gdml'...
G4GDML: VALIDATION ERROR! element 'property' is not allowed for content model '((property+),(RL|RLref),(AL|ALref),(T|Tref),(P|Pref),(MEE|MEEref),(D|Dref),(atom|composite+|fraction+))' at line: 39
G4GDML: VALIDATION ERROR! element 'property' is not allowed for content model '((property+),(RL|RLref),(AL|ALref),(T|Tref),(P|Pref),(MEE|MEEref),(D|Dref),(atom|composite+|fraction+))' at line: 52
G4GDML: VALIDATION ERROR! value '/world/BubbleDevice#AirSurface' is invalid NCName at line: 58
G4GDML: VALIDATION ERROR! value '/world/BubbleDevice#TankBubble' is invalid NCName at line: 84
G4GDML: VALIDATION ERROR! attribute 'ref' is already specified for element 'physvolref' at line: 85
G4GDML: Reading definitions...

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : InvalidSize
      issued by : G4GDMLEvaluator::DefineMatrix()
Matrix 'RINDEX__Air' is not filled correctly!
*** Fatal Exception *** core dump ***
-------- EEEE -------- G4Exception-END --------- EEEE -------


*** G4Exception: Aborting execution ***

**Comment by MarkusFrankATcernch** [comment]
How did you generate the gdml file? using Geant4 or ROOT?

**Comment by dannielliu** [comment]
using ROOT
geoPluginRun -input file:compact/OpNovice.xml -print WARNING -destroy -volmgr
-plugin DD4hep_ROOTGDMLExtract -output OpNovice.gdml -path /world

**Comment by MarkusFrankATcernch** [comment]
Bug is acknowledged. ROOT does not export values of property tables to GDML.
Besides this, there are additional doubts about the XML content of the generated GDML file.

**Comment by MarkusFrankATcernch** [comment]
Hi Dong,

this issue turns out to be much more complicated than I initially thought.

- Is this urgent?
- Can't you populate Geant4 from the memory image rather than GDML?
   This problem should then disappear.
- In any case: I have to think a bit before changing the GDML writing in ROOT.

Cheers,
Markus

**Comment by MarkusFrankATcernch** [comment]
Dear Dong,
could you please provide me with the python script to load the GDML file into Geant4 ?
Saves me some time....Thanks!

**Comment by dannielliu** [comment]
Dear Markus,

This problem is not very urgent now, since I try to export gdml file using "Geant4GDMLWriteAction".
I am not using the python script to load gdml, but with some modification on Geant4 example, "Geant4-10.4.1/examples/extended/optical/OpNovice". The modification is in the DetectorConstruction source code, replacing the content of function "Construct()" with flowing content

  G4GDMLParser parser;
  parser.Read("OpNovice.gdml");
  //always return the physical World
  return parser.GetWorldVolume(); 

For you suggestion to populate Geant4 from the memory image, I think it's a good idea. I know it can do with DDG4, but I am not sure how to realize it directly with a Geant4 application. Any examples?  

Thank you!

best regards,
Dong LIU

**Comment by MarkusFrankATcernch** [comment]
There are 2 parts:

- The relevant code to convert the geometry from TGeo/DD4hep to Geant4 is in
DDG4/plugins/Geant4DetectorGeometryConstruction.cpp 
in Geant4DetectorGeometryConstruction::constructGeo(...)
This you probably could use rather directly by copying the relevant lines.
This creates you also a map between the TGeo- and the Geant4-Volumes.
This should also translate the optical / material properties tables correctly including 
the correct units - unless there is a bug (and remember, this is new code).
Watch out what is done with the Geant4Converter.

- To attach sensitive detectors, you have to get inspired by
  DDG4/plugins/Geant4DetectorSensitivesConstruction.cpp
  Geant4DetectorSensitivesConstruction::constructSensitives(...)
  If you do not use DDG4, you will have to attach G4VSensitiveDetector
  instances to the Geant4 volumes.

**Comment by dannielliu** [comment]
Dear Markus,

There is another doubt we found when using the example. The problem is that the simulation with a geometry built by DD4hep is slower than what we do directly with the geometry built by Geant4.
Then we tried to export the geometry to a gdml file to figure out the problem and something is abnormal.

in compact description, the reflectivity is defined with value at several "eV", which looks like flowing:

<opticalsurface name="/world/BubbleDevice#AirSurface" finish="polished" model="glisur" type="dielectric_dielectric">
      <property name="REFLECTIVITY"            coldim="2" values="2.034*eV  0.3   4.136*eV  0.5"/>
      <property name="EFFICIENCY"              coldim="2" values="2.034*eV  0.8   4.136*eV  1.0"/>
</opticalsurface>

When export to gdml, it looks like this

 <matrix coldim="2" name="REFLECTIVITY0x7f7fd359c6f0" values="2.034e-09 0.3 4.136e-09 0.5"/>
    <matrix coldim="2" name="EFFICIENCY0x7f7fd32c38e0" values="2.034e-09 0.8 4.136e-09 1"/>

The energy is at level 10-9. which is 3 orders smaller than other properties (10-6). 
Is this a problem with DD4hep, or with ROOT?

Thank you!
Dong LIU

**Comment by MarkusFrankATcernch** [comment]
Hi Dong,

thanks for reporting this. The optical property tables (opposite to the material tables) were not converted from TGeo to Geant4 units. See pull request https://github.com/AIDASoft/DD4hep/pull/553 for the fix.
If you set in DDG4
  # Configure G4 geometry setup
  seq,act = geant4.addDetectorConstruction("Geant4DetectorGeometryConstruction/ConstructGeo")
  act.DebugMaterials = True
  act.DebugSurfaces  = True

The tables get printed to stdout.

If you could do me a favor please: 
The units of these optical/material property tables are not terribly good documented. 
Could you please check the conversion constants in 
DDG4/src/Geant4Converter.cpp : line 267 - 356 (g4PropertyConversion , g4ConstPropertyConversion) ?

Thank you!

**Comment by dannielliu** [comment]
Dear Markus,

Thank you very much for the fix.
I am also not so familiar the units of some optical/material properties. Still, I have tried to understand the units, and here are some suggestions.
In g4PropertyConversion, the unit of kGROUPVEL should be a unit of velocity (m/s).
In g4ConstPropertyConversion, the unit of kSURFACEROUGHNESS should be a unit of length (also for kMR_RRMS) (refer to processes/optical/src/G4OpBoundaryProcess.cc in Geant4 source code)
The unit of kISOTHERMAL_COMPRESSIBILITY is m3/MeV (refer to processes/optical/src/G4OpRayleigh.cc in Geant4 source code)

Best regards,
Dong LIU

**Comment by petricm** [comment]
If there are any more question regarding this please reopen an issue
