### ISSUE TITLE
TruncatedTube    ERROR ++ startPhi != 0 not supported!

### ISSUE THREAD

**Issue by ianna** [AIDASoft/DD4hep#464]
An exception is thrown when a TruncatedTube with a startPhi != 0 is defined:
```
<TruncTubs name="trunctubs1" zHalf="50*cm" rMin="20*cm" rMax="40*cm" startPhi="10*deg" deltaPhi="90*deg" cutAtStart="25*cm" cutAtDelta="35*cm" cutInside="true"/>
```

**Comment by MarkusFrankATcernch** [comment]
Yes, but this is like in your code:
https://cmssdt.cern.ch/lxr/source/Fireworks/Geometry/src/TGeoMgrFromDdd.cc#0538
I did not invent this....

**Comment by ianna** [comment]
Ok, let's keep it that way for now.
