### ISSUE TITLE
problems with geoDisplay

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#477]
From @jhrdinka

> 
> I was not using geoDisplay for a long time, since there was some problem with the last lcg-setup. Now that it is working again, I was trying to display an old geometry example of mine.
> This tracking geometry consists of volumes containing layers, which contain modules and the modules are made of components. For some reason I can display the modules, but the components can not be displayed. I checked a few times and I can not find the problem. I also uncommented all layers but one and just tried to display the components of one module, in case the problem are too many components, but it is still not working again. Do you know what could be wrong?

**Comment by petricm** [comment]
Are you sure that in your constructor code components get assigned the correct visualization attributes, and that you set in your XML `showDaughters="true" visible="true"`

**Comment by jhrdinka** [comment]
Yes I checked. If that is ok, I will try to give you a minimal working example tomorrow.

**Comment by MarkusFrankATcernch** [comment]
Hi Julia,
1) the ROOT display stops (by default) displaying after 4 levels of the geometry hierarchy.
    Probably the items you do not see are further down the hierarchy.
2) When trying out I noticed that geoDisplay has a bug :-((( ; the default works, but overriding the default level  fails. I will fix this asap.
3) as an intermediate measure you can run e.g.:
geoPluginRun -input checkout/examples/CLICSiD/compact/compact.xml -interactive -plugin DD4hep_GeometryDisplay -level 8 

further optional arguments are: -visopt ogl -detector SiTrackerBarrel
--    -visopt ogl is default
--    -detector <det-name> allows you to display selectively only one subdetector as they are declared in the 
       constructors default is everything.

**Comment by jhrdinka** [comment]
Hello,

I have another question:

with geoDisplay it was possible to have more than one input file. Is this also possible for the `geoPluginRun` and if yes, how?


Cheers,
Julia

**Comment by MarkusFrankATcernch** [comment]
Just as a reminder: if you use the head, you can also specify the -level <number> argument to geoDisplay.
It is a bit more 'handy'.

**Comment by MarkusFrankATcernch** [comment]
Calling:
geoPluginRun -input <file> -input <file> -input <file> ....   
should work the same way as with geoDisplay.

At the end of the day geoDisplay calls geoPluginRun....

**Comment by jhrdinka** [comment]
Thanks, that works. It was not clear to me that I need to add a second -input.
