### ISSUE TITLE
Multisegmentation with two keys?

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#481]
I am a Amine Elkhalii PhD student, I am working with the ahcal detector development group! Curretly I am working in the simulation and trying to have a geometry which is compatible to our real detector and for that I need some help from you.
I have a question about the `Multisegmentation`, the question : is it possible to have one multisegmentation with 2 keys ? or is it possible to have two multisegmenation in one readout (Collection)? 

Firstly, to explain the problem, we have a detector of 39 layers each layer have 24x24 scintillators tiles with a size of 3x3cm for each tile but only layer 38 which have different tiles size 6x6cm. For that, we did the segmenation for all the layer and inculiding also the layer 38 with 6x6cm size. As you see below the segmentation has a key "K" which is the layer number and we use this key for to set physical volume ID and the placement of each layer : `layer_phv.addPhysVolID(); & layer.setPlacement(layer_phv);`
```xml
<readouts>
  <readout name="HCALCollection">
    <!-- Multi-segmentation for HCAL: all cell sizes are in [cm] -->
    <segmentation type="MultiSegmentation"  key="K">
      <segmentation type="TiledLayerGridXY"  key_min="0" key_max="36" grid_size_x="3" 
       grid_size_y="3" offset_x="-HCAL_dim_x/2.0-3/2*cm" offset_y="-HCAL_dim_y/2.0-3/2*cm" 
       identifier_x="I" identifier_y="J" identifier_layer="K"/>
      <segmentation type="TiledLayerGridXY" key_value="37" grid_size_x="6" grid_size_y="6" 
       offset_x="-HCAL_dim_x/2.0-6/2*cm" offset_y="-HCAL_dim_y/2.0-6/2*cm" identifier_x="I" 
       identifier_y="J" identifier_layer="K"/>
      <segmentation type="TiledLayerGridXY" key_min="38" key_max="100" grid_size_x="3" 
       grid_size_y="3" offset_x="-HCAL_dim_x/2.0-3/2*cm" offset_y="-HCAL_dim_y/2.0-3/2*cm" 
       identifier_x="I" identifier_y="J" identifier_layer="K"/>
    </segmentation>
    <id>slice:0,system:4,K:6,I:9,J:9</id> 
  </readout>
</readouts>
```

Now what we want to devide each layer in 2 slabs and we did the segmenation of each slab and we used the slab number as a key of the multisegmentation. Now the problem is that we need two keys for the placement of physical volume for each slab and also for the layer which has different segmentation "6x6cm". As you see below the text we managed to do segmentation for each slab and it works perfectly but all the layer have the same tiles size 3x3cm. Now I need to combine this segmentation bellow to the segmentation shown above.
```xml
<readouts>
  <readout name="HCALCollection">
    <segmentation type="MultiSegmentation"  key="slab">
      <segmentation type="TiledLayerGridXY"  key_value="0" grid_size_x="3" grid_size_y="3" 
       offset_x="-slab_dim_x/2.0-3/2*cm" offset_y="-HCAL_dim_y/2.0-3/2*cm" identifier_x="I" 
       identifier_y="J" identifier_layer="K"/>
      <segmentation type="TiledLayerGridXY" key_value="1" grid_size_x="3" grid_size_y="3" 
       offset_x="-HCAL_dim_x/2.0-slab_dim_x/2.0-3/2*cm" offset_y="-HCAL_dim_y/2.0-3/2*cm" 
       identifier_x="I" identifier_y="J" identifier_layer="K"/>
    </segmentation>
    <id>slice:0,system:4,slab:2,K:6,I:9,J:9</id>
  </readout>
</readouts>
```
Is there any possibility to combine both segmentation in the same collection by having two keys in one multisegmentation which can help me afterwords to have the correct physical volume ID and placement!

I hope my email is clear, please feel free to ask me any question if my problem is not clear for you!!

Thank you so much in advance for your reply!

Best regards,

Amine

**Comment by MarkusFrankATcernch** [comment]
I think this is currently (i.e. with the existing implementation) not possible.
I do not think that the current machinery allows to define segmentations truly recursive.
However, looking at the code: DDCore/src/segmentations/MultiSegmentation.cpp

What must be solved is the lookup of the sub-segmentation given any volume ID in your subdetector.
For "regular" multi-segmentations the code is as follows:

    const Segmentation& MultiSegmentation::subsegmentation(const CellID& cID)   const  {
      if ( m_discriminator )  {
        long seg_id = m_discriminator->value(cID);
        for(Segmentations::const_iterator i=m_segmentations.begin(); i != m_segmentations.end(); ++i)  {
          const Entry& e = *i; 
          if ( e.key_min<= seg_id && e.key_max >= seg_id )   {
            Segmentation* s = e.segmentation;
....
            return *s;
          }
        }
      }
      throw runtime_error("MultiSegmentation: Invalid sub-segmentation identifier!");;
    }

The relevant lines are these:
        for(Segmentations::const_iterator i=m_segmentations.begin(); i != m_segmentations.end(); ++i)  {
          const Entry& e = *i; 
          if ( e.key_min<= seg_id && e.key_max >= seg_id )   {
....
Here the sub-segmentation is selected which fits the subdetector part identified by the volume ID.

If you would implement a separate segmentation (don't call it MultiSegmentation, rather something like
MultiDimensionalSegmentation you would have to replace the simple logic:
`(e.key_min<= seg_id && e.key_max >= seg_id )` by something, which picks your specific
sub-segementation relevant for this volume ID. 
That would be it...

**Comment by elkhalia** [comment]
> I think this is currently (i.e. with the existing implementation) not possible.
> I do not think that the current machinery allows to define segmentations truly recursive.
> However, looking at the code: `DDCore/src/segmentations/MultiSegmentation.cpp`
> 
> What must be solved is the lookup of the sub-segmentation given any volume ID in your subdetector.
> For "regular" multi-segmentations the code is as follows:
> 
> ```c++
>     const Segmentation& MultiSegmentation::subsegmentation(const CellID& cID)   const  {
>       if ( m_discriminator )  {
>         long seg_id = m_discriminator->value(cID);
>         for(Segmentations::const_iterator i=m_segmentations.begin(); i != m_segmentations.end(); ++i)  {
>           const Entry& e = *i; 
>           if ( e.key_min<= seg_id && e.key_max >= seg_id )   {
>             Segmentation* s = e.segmentation;
> ....
>             return *s;
>           }
>         }
>       }
>       throw runtime_error("MultiSegmentation: Invalid sub-segmentation identifier!");;
>     }
> ```
> 
> The relevant lines are these:
> 
> ```c++
>         for(Segmentations::const_iterator i=m_segmentations.begin(); i != m_segmentations.end(); ++i)  {
>           const Entry& e = *i; 
>           if ( e.key_min<= seg_id && e.key_max >= seg_id )   {
> ....
> ```
> 
> Here the sub-segmentation is selected which fits the subdetector part identified by the volume ID.
> 
> If you would implement a separate segmentation (don't call it MultiSegmentation, rather something like
> MultiDimensionalSegmentation you would have to replace the simple logic:
> `(e.key_min<= seg_id && e.key_max >= seg_id )` by something, which picks your specific
> sub-segementation relevant for this volume ID.
> That would be it...

Thank you Markus for your reply! As you suggested, I am trying to implement a separate segmentation!!
Hope it will work!!

**Comment by MarkusFrankATcernch** [comment]
Good luck!
There is a bit of machinery around - in particular the factory mechanism. 
I would suggest you copy the MultiSegementation files to something with 
another base name, try to use this segmentation and, once the technical 
stuff is solved, implement the logic.

**Comment by petricm** [comment]
Dear @elkhalia, did you try to implement the suggestion of @MarkusFrankATcernch? Any success?

**Comment by elkhalia** [comment]
Dear Marko Petric

Sorry I didn't implement it yet because I had some other tasks to do and I decided to try it later! Beside that I had so many conferences this last months. 

I will try it as possible as possible! 

Best regards, 
Amine 

⁣Get BlueMail for Android ​
