### ISSUE TITLE
How to add optical properties to materials?

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#484]
From @CoralieNeubueser

> I have a question concerning the material description in dd4hep.
> I would like to add some material properties, such that Geant4 picks them up and uses them in the simulation.
> 
> As a bit of explanation, in FCCSW we define the material like [this](https://github.com/HEP-FCC/FCCSW/blob/master/Detector/DetCommon/compact/materials.xml)
> 
> And afterwards, follow the geant4 steps in the [sensitive detector](https://github.com/HEP-FCC/FCCSW/blob/master/Detector/DetSensitive/src/SimpleCalorimeterSD.cpp)
> 
> What I would like to add, is some optical properties like refraction index and absorption length, e.g.:
 ```cpp
 const G4int lar_Nbin_optical_energy = 2;  // It must be > 1 because it needs a range of energy values
G4double lar_optical_energy[ lar_Nbin_optical_energy ]= { 1.0*eV, 5.0*eV };  // Min and max energy
 G4double lar_Rindex[ lar_Nbin_optical_energy ] = { 1.5, 1.4 };  // Index of refraction
 G4double lar_Labsorption[ lar_Nbin_optical_energy ] = { 10.0*cm, 100.0*cm };  // Absorption length
 G4MaterialPropertiesTable* lar_mpt = new G4MaterialPropertiesTable;
 lar_mpt->AddProperty( "RINDEX",    lar_optical_energy, lar_Rindex, lar_Nbin_optical_energy );
 lar_mpt->AddProperty( "ABSLENGTH", lar_optical_energy, lar_Labsorption, lar_Nbin_optical_energy   );
 LiquidArgon->SetMaterialPropertiesTable( lar_mpt ); 
 ```
> Is there a way to do this on the dd4hep level?

**Comment by petricm** [comment]
Your question is related to #440 for which the accompanying ticket is [ROOT-JIRA](https://sft.its.cern.ch/jira/browse/ROOT-9742). The first task was resolved and merged in December but I think this is still an open issue. @MarkusFrankATcernch ?

**Comment by sdudeveloper** [comment]
Hi @petricm 
 It looks that DD4hep now supports the optical surface. where can I find the example? thanks.

**Comment by MarkusFrankATcernch** [comment]
<dd4hep>/examples/OpticalSurfaces

It is the direct translation of the Geant4 OpNovice example

**Comment by sdudeveloper** [comment]
Thanks @MarkusFrankATcernch,  we'll have a try.

**Comment by petricm** [comment]
@sdudeveloper please  take note that for this functionality to work, you need ROOT 6.18
