### ISSUE TITLE
Set shooting direction in DDG4

### ISSUE THREAD

**Issue by GibbonLee** [AIDASoft/DD4hep#487]
Hi, guys! I'm new to DD4hep, and trying to shoot photons in a certain solid angle range with DDG4. I find there is a class called Geant4IsotropeGenerator, but I don't know how to use it in XML or other configuration files. Besides, I'm not very sure about some handles' usage, such as Geant4ParticleHandler::SaveProcesses. Could anyone please answer my question?Thanks

**Comment by andresailer** [comment]
The easiest would be to use the included python based command `ddsim`
If you have a fully working installation
```
ddsim --help
```

**Comment by GibbonLee** [comment]
Thanks! I'll have a try later.
