### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by GibbonLee** [AIDASoft/DD4hep#488]
Hi! Sorry for disturbing you again. I've compiled my own code successfully. But when I try to use command `geoDisplay --compact t.xml` , I meet with symbol lookup error. The error message is as followed:
`PersistencyIO    INFO  +++ Set Streamer to dd4hep::OpaqueDataBlock
Info in <TGeoManager::TGeoManager>: Geometry default, Detector Geometry created
CompactLoader    INFO  +++ Processing compact file: ../ECAL/compact/t.xml with flag BUILD_DEFAULT
DocumentHandler  INFO  +++ Loading document URI: ../ECAL/compact/t.xml [Resolved:'../ECAL/compact/t.xml']
DocumentHandler  INFO  +++ Document ../ECAL/compact/t.xml succesfully parsed with TinyXML .....
DocumentHandler  INFO  +++ Loading document URI: ../ECAL/compact/elements.xml [Resolved:'../ECAL/compact/elements.xml']
DocumentHandler  INFO  +++ Document ../ECAL/compact/elements.xml succesfully parsed with TinyXML .....
DocumentHandler  INFO  +++ Loading document URI: ../ECAL/compact/materials.xml [Resolved:'../ECAL/compact/materials.xml']
DocumentHandler  INFO  +++ Document ../ECAL/compact/materials.xml succesfully parsed with TinyXML .....
Detector         INFO  *********** Created World volume with size:  500  500  500
Info in <TGeoManager::SetTopVolume>: Top volume is world_volume. Master volume is world_volume
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
geoDisplay: symbol lookup error: /home/jiazk/build/lib/libSimpleDetector.so: undefined symbol: _ZN6dd4hep6detail9safe_castI10TGeoVolumeE4castI10TGeoMediumEEPS2_PT_
`
I suspect this problem is produced by wrong syntax in XML file. Have anyone met this kind of problem before? Thanks

**Comment by andresailer** [comment]
@GibbonLee , if you solved the problem, it would be nice if you write briefly described how, so that other people that run into the same problem could benefit! Thanks
