### ISSUE TITLE
Problem about geoConverter

### ISSUE THREAD

**Issue by GibbonLee** [AIDASoft/DD4hep#492]
Hi! Sorry for bothering you again.
  When I try to convert a compact file into a gdml file. I find that the readout infomation and infomation about DetElement, such as sensitive detector or detector name are lost. Besides, I use this function to copy volume:

> PlacedVolume Volume::placeVolume(const Volume& volume, int copy_no, const Position& pos)

Theoretically, the copy number should present in the gdml file. But I couldn't find it. 
In the following directory, you can find my source code and the gdml file produced by geoconverter:
`https://github.com/GibbonLee/STCF`
Are these program bugs or my coding problem? Looking forward to your reply. Thanks!

**Comment by MarkusFrankATcernch** [comment]
Hi Lee,

you are using here a very old GDML converter -- which I should probably remove from DD4hep.
It was only used when we were still supporting Slic.

Please use the ROOT GDML utilities for creating GDML:
        TGDMLWrite extract;
        TUri uri(output.c_str());
       Volume top = description.worldVolume();
        extract.WriteGDMLfile(&description.manager(), top, uri.GetRelativePart());

To write sub-trees, you can replace "top" with any volume in the volume hierarchy.

There is also a plugin in DD4hep, which does the same thing:
See examples/CLICSiD how to use it:  CLICSiD_GDML_export_LONGTEST

Markus

**Comment by GibbonLee** [comment]
> Hi Lee,
> 
> you are using here a very old GDML converter -- which I should probably remove from DD4hep.
> It was only used when we were still supporting Slic.
> 
> Please use the ROOT GDML utilities for creating GDML:
> TGDMLWrite extract;
> TUri uri(output.c_str());
> Volume top = description.worldVolume();
> extract.WriteGDMLfile(&description.manager(), top, uri.GetRelativePart());
> 
> To write sub-trees, you can replace "top" with any volume in the volume hierarchy.
> 
> There is also a plugin in DD4hep, which does the same thing:
> See examples/CLICSiD how to use it: CLICSiD_GDML_export_LONGTEST
> 
> Markus

Thanks a lot, Markus. I'll have a try!

**Comment by MarkusFrankATcernch** [comment]
Small correction:
extract.WriteGDMLfile(&description.manager(), top, uri.GetRelativePart());
Should read:
extract.WriteGDMLfile(&description.manager(), top.ptr(), uri.GetRelativePart());

**Comment by GibbonLee** [comment]
> Small correction:
> extract.WriteGDMLfile(&description.manager(), top, uri.GetRelativePart());
> Should read:
> extract.WriteGDMLfile(&description.manager(), top.ptr(), uri.GetRelativePart());

Sorry for disturbing you again. But when I use geoPluginRun command and DD4hep_ROOTGDMLExtract plugin, it says that:

> ERROR ++ Exception while executing plugin DD4hep_ROOTGDMLExtract:
		dd4hep: apply-plugin: Failed to locate plugin DD4hep_ROOTGDMLExtract. 		No factory with name Create(DD4hep_ROOTGDMLExtract) for type DD4hep_ROOTGDMLExtract found.

I have fully installed DD4hep, should I do some other operation, thanks?
My command is as followed:

> geoPluginRun -input ECAL/compact/b.xml -print WARNING -destroy -volmgr -plugin DD4hep_ROOTGDMLExtract -output 2.gdml

**Comment by MarkusFrankATcernch** [comment]
When you build ROOT, did you enable GDML ?

DDCore/CMakeLists.txt checks if GDML is present:
#---------------------------  Specialized  GDML  plugin ----------------------------
# This plugins depends on the ROOT GDML readers. Hence, extra library
dd4hep_add_plugin(DDGDMLPlugins
  OPTIONAL    [ROOT REQUIRED COMPONENTS Gdml SOURCES src/gdml/*.cpp]
)

These are the options I use to build ROOT:
         -Dxrootd=OFF \
          -Dgdml=ON \
          -Dhttp=ON \
	  -Dbonjour=OFF \
   ....

**Comment by GibbonLee** [comment]
> When you built ROOT, did you enable GDML ?
> 
> DDCore/CMakeLists.txt checks if GDML is present:
> 
> dd4hep_add_plugin(DDGDMLPlugins
> OPTIONAL [ROOT REQUIRED COMPONENTS Gdml SOURCES src/gdml/*.cpp]
> )
> 
> These are the options I use to build ROOT:
> -Dxrootd=OFF 
> -Dgdml=ON 
> -Dhttp=ON 
> -Dbonjour=OFF 
> ....

Hi, Markus. I'm sorry to tell you that the problem still exists even I've recompiled root and DD4hep as your configuration ...

**Comment by MarkusFrankATcernch** [comment]
If you look in the lib directory:
$> cat lib/libDDGDMLPlugins.components

libDDGDMLPlugins.so:DD4hep_DetElementCreator
libDDGDMLPlugins.so:DD4hep_DetNominalCreator
libDDGDMLPlugins.so:DD4hep_PlainROOT
libDDGDMLPlugins.so:DD4hep_ROOTGDMLExtract
libDDGDMLPlugins.so:DD4hep_ROOTGDMLParse

Do you see all these plugin factories?
IF they are present, you have a problem with the LD_LIBRARY_PATH and the plugin manager does not find this file.

IF they are NOT present, DD4hep did not build the GDML plugins.

**Comment by GibbonLee** [comment]
> If you look in the lib directory:
> $> cat lib/libDDGDMLPlugins.components
> 
> libDDGDMLPlugins.so:DD4hep_DetElementCreator
> libDDGDMLPlugins.so:DD4hep_DetNominalCreator
> libDDGDMLPlugins.so:DD4hep_PlainROOT
> libDDGDMLPlugins.so:DD4hep_ROOTGDMLExtract
> libDDGDMLPlugins.so:DD4hep_ROOTGDMLParse
> 
> Do you see all these plugin factories?
> IF they are present, you have a problem with the LD_LIBRARY_PATH and the plugin manager does not find this file.
> 
> IF they are NOT present, DD4hep did not build the GDML plugins.

You are right. DD4hep didn't build the GDML plugins, we will find ways to solve the problem by ourself. 
Thanks a lot. Maybe we will keep in touch frequently in the future~
