### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by GibbonLee** [AIDASoft/DD4hep#495]
Hi, It's me! Again...
On my server, DD4hep_ROOTGDMLExtract plugin still can't be installed by default. Here are the lost ingredients  when I build DD4hep. Is there any necessary part I've lost? Thanks!

//Path to a program.
BIBER_COMPILER:FILEPATH=BIBER_COMPILER-NOTFOUND

//The directory containing a CMake configuration file for Boost.
Boost_DIR:PATH=Boost_DIR-NOTFOUND

//Dot tool for use with Doxygen
DOXYGEN_DOT_EXECUTABLE:FILEPATH=DOXYGEN_DOT_EXECUTABLE-NOTFOUND

//Path to a program.
HTLATEX_COMPILER:FILEPATH=HTLATEX_COMPILER-NOTFOUND

//Path to a program.
LATEX2HTML_CONVERTER:FILEPATH=LATEX2HTML_CONVERTER-NOTFOUND

//Path to a program.
LUALATEX_COMPILER:FILEPATH=LUALATEX_COMPILER-NOTFOUND

//Path to a program.
P4COMMAND:FILEPATH=P4COMMAND-NOTFOUND

//Path to a library.
PYTHON_LIBRARY_DEBUG:FILEPATH=PYTHON_LIBRARY_DEBUG-NOTFOUND

//Path to a program.
ROOT_genmap_CMD:FILEPATH=ROOT_genmap_CMD-NOTFOUND

//Path to a program.
ROOT_rootdraw_CMD:FILEPATH=ROOT_rootdraw_CMD-NOTFOUND

//Path to the SLURM sbatch executable
SLURM_SBATCH_COMMAND:FILEPATH=SLURM_SBATCH_COMMAND-NOTFOUND

//Path to the SLURM srun executable
SLURM_SRUN_COMMAND:FILEPATH=SLURM_SRUN_COMMAND-NOTFOUND

//Path to a program.
XELATEX_COMPILER:FILEPATH=XELATEX_COMPILER-NOTFOUND

//Path to a program.
XINDY_COMPILER:FILEPATH=XINDY_COMPILER-NOTFOUND

**Comment by andresailer** [comment]
What exactly are you showing us here? It looks like cmake variable cache, but what are you trying to build?
Can you please follow the request in the issue template and provide more information about which steps you are taking?
Especially the cmake command you are using, and the complete output would seem to be important

This information:
```
 - OS version: e.g. SLC6
 - Compiler version: e.g GCC 6.2
 - DD4hep version: tag or commit ID, or GitHub branch
 - Reproduced by: exact steps to reproduce the problem: checkout, setup environment (Geant, ROOT versions, iLCSoft release), cmake, build, run...
 - Input: link to input files if applicable
 - Output: full build and run log output
 - Goal: A short description of what you are trying to achieve
```

**Comment by GibbonLee** [comment]
Sorry for not expressing myself clearly! 
This is the ccmake options that are not found by ccmake when I build DD4hep.  This doesn't affect the normal use of DD4hep, but the plugin DD4hep_ROOTGDMLExtract is not compiled by default. I don't know whether the problem lies in these not-found options...

**Comment by andresailer** [comment]
Which ROOT version are you using?

**Comment by GibbonLee** [comment]
6.10.08

**Comment by andresailer** [comment]
The plugin you want to use only compiles with Root 6.13 and beyond

https://github.com/AIDASoft/DD4hep/blob/afbf9bd56bd1442d405d8eb3a93d834f3e5a3071/DDCore/src/gdml/GdmlPlugins.cpp#L33

**Comment by GibbonLee** [comment]
All right. It's embarrassing to ask such a naive question. Thanks a lot anyway~

**Comment by andresailer** [comment]
No, it is totally fine to ask these questions, but next time just please fill the "questionnaire", which among other things also asks about the root version ;). That makes it easier to investigate the problem and saves everyone's time.
