### ISSUE TITLE
ddsim crashes when drawing ILD geometry by dawn

### ISSUE THREAD

**Issue by akiyamiyamoto** [AIDASoft/DD4hep#498]
ddsim crashes when creating DAWNFILE of ILD_l5_v02 detector geometry.

My environment is as follows.
- OS version : SL6
- Compiler version: gcc4.9.3 
- DD4hep version: v01-07-02
- Reproduced as follows:

====== beginning of run script =====================
$ source /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v02-00-02/init_ilcsoft.sh
$ ddsim --compactFile ${ILCSOFT}/lcgeo/v00-16-03/ILD/compact/ILD_l5_v02/ILD_l5_v02.xml \
   --steeringFile  /cvmfs/ilc.desy.de/sw/ILDConfig/v02-00-02/StandardConfig/production/ddsim_steer.py \
   --macroFile dawn.mac \
   --runType vis
=================== end of run script ================

The file, dawn.mac, is as follows.
=================== beginning of dawn.mac ( Geant4 command) =========
/vis/scene/create
/vis/scene/add/volume
/vis/sceneHandler/create DAWNFILE
/vis/viewer/create
/vis/drawVolume world
/vis/viewer/flush
=================== end of dawn.mac

When ddsim is executed this way, it outputs the message like, 
  Polyhedron not available for FTD_envelope_shape_0x9bbfa50
then, at the end, ddsim crashed. 
The log file is attached for you your information.

I wonder why error happens.
Is there way to avoid this error and successfully draw detector geometry by DAWN ?
[vis_ddsim.log](https://github.com/AIDASoft/DD4hep/files/3057193/vis_ddsim.log)

**Comment by petricm** [comment]
I don't think this is really a DD4hep problem, since the geometry is converted to Geant4 correctly. After the geometry is converted you call in the G4 command line to flush the already converted geometry and G4 complains, that it does not know how to do this for certain shapes.

This seems that this is related to [this](http://hypernews.slac.stanford.edu/HyperNews/geant4/get/geometry/1558/2.html). If I apply this patch 2 out of the 3 errors disappear.

**Comment by MarkusFrankATcernch** [comment]
This change should be present in git head.

However, it was not entirely possible in a 100% strict mode:
When plugins are called, const-ness is violated:
Geant4Converter.cpp: line 1045
    Detector* detPtr = const_cast<Detector*>(&m_detDesc);
    long result = PluginService::Create<long>(tag, detPtr, hdlr, &vals);

This I cannot avoid.

**Comment by andresailer** [comment]
@MarkusFrankATcernch wrong issue? #499 ?

**Comment by andresailer** [comment]
You can set the envelopes to invisible to before calling `/vis/viewer/flush`
```
/vis/scene/create
/vis/scene/add/volume
/vis/sceneHandler/create DAWNFILE
/vis/viewer/create
/vis/drawVolume world
vis/geometry/set/visibility FTD_envelope 0 False
/vis/geometry/set/visibility SET_envelope 0 False
/vis/geometry/set/visibility SIT_envelope 0 False
/vis/geometry/set/visibility VXD_envelope 0 False
/vis/geometry/set/visibility TPC_envelope 0 False
/vis/geometry/set/visibility EcalPlug_envelope 0 False
/vis/geometry/set/visibility HcalBarrel_envelope 0 False
/vis/geometry/set/visibility EcalBarrel_envelope 0 False
/vis/geometry/set/visibility EcalEndcap_envelope 0 False
/vis/geometry/set/visibility HcalRing_envelope 0 False
/vis/geometry/set/visibility HcalEndcap_envelope 0 False
/vis/geometry/set/visibility YokeBarrel_envelope 0 False
/vis/geometry/set/visibility YokeEndcap_envelope 0 False
/vis/geometry/set/visibility Lcal_envelope 0 False
/vis/geometry/set/visibility LHCal_envelope 0 False
/vis/geometry/set/visibility Coil_envelope 0 False
/vis/geometry/set/visibility BeamCal_envelope 0 False
/vis/viewer/flush
```
This make the crash disappear for me

**Comment by akiyamiyamoto** [comment]
Thanks.  Your suggestion works.

**Comment by petricm** [comment]
But just for the record, this is not a DD4hep problem.
