### ISSUE TITLE
XML references non-existent schema

### ISSUE THREAD

**Issue by penguish** [AIDASoft/DD4hep#500]
Looking in master at
https://github.com/AIDASoft/DD4hep/blob/master/DDDetectors/compact/SiD.xml
and trying to reference the schema quoted there. The schema appears to no longer exist. 
(nb. dd4hep documentation also states that "the DD4hep parsers do not validate against a ﬁx schema "). Personally, I find them useful when using a schema-aware xml editor.

**Comment by penguish** [comment]
ok, that's fine; but then the references to the schema should be removed in the existing xml files.

**Comment by MarkusFrankATcernch** [comment]
I think we can close this issue.
