### ISSUE TITLE
Convert geometry with Geant4GDMLWriteAction in DDG4

### ISSUE THREAD

**Issue by GibbonLee** [AIDASoft/DD4hep#507]
Hi! I'm glad to find that you have add an example about writing Geant4 GDML file.
When I try this new plugin, I find that some information like energy cut or region is lost in the generated gdml file.
It seems that you create the gdml file by calling G4GDMLParser, which supports writing auxiliary and region information into gdml file. So why these information are lost?
Looking forward to your reply!

**Comment by GibbonLee** [comment]
Maybe we should add these lines in /home/jiazk/ustcfs/software/DD/DD4hep/DDG4/plugins/Geant4GDMLWriteAction.cpp before line 125?
`parser.SetRegionExport(true);`
`parser.SetEnergyCutsExport(true);`
`parser.SetSDExport(true);`
Or make a function like SetRegionExport() in DD4hep?

**Comment by MarkusFrankATcernch** [comment]
Huh! Hi Gibbon,
these are the customers I love: Not only complaining, but providing the solution!
I will apply your solution as soon as I find a bit of time. Perhaps not next week which is already busy,
but certainly the week after!

Thanks,
Markus

**Comment by GibbonLee** [comment]
Sorry for complaining again and again :-)
Appendix: There is no problem when I add `parser.SetRegionExport(true);` in code. But when I put all the lines in it, the converting script will break and says:
`G4ParticleDefintion (other than ions and shortlived) should be created in Pre_Init state  gamma`
`-------- WWWW ------- G4Exception-START -------- WWWW -------`
`*** G4Exception : PART101`
`      issued by : G4ParticleDefintion::G4ParticleDefintion`
`G4ParticleDefinition should be created in PreInit state`
`*** This is just a warning message. ***`
`-------- WWWW -------- G4Exception-END --------- WWWW -------`

These are just part of error messages, this problem seems lying in lacking some basic particles' definition? I'm not very  sure
