### ISSUE TITLE
Remove cxx standard from DD4hepConfig.cmake

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#509]
Replace CMAKE_CXX_STANDARD with DD4hep_CXX_STANDARD in DD4hepConfig.cmake

**Comment by andresailer** [comment]
A cleaner solution than setting some variable, is setting the required standard as a compiler feature for the DD4hep libraries https://cmake.org/cmake/help/v3.8/manual/cmake-compile-features.7.html#id4

This would need some re-working of the CMake setup in DD4hep

**Comment by andresailer** [comment]
Done
