### ISSUE TITLE
Support C++17

### ISSUE THREAD

**Issue by paulgessinger** [AIDASoft/DD4hep#515]
As far as I understand it, currently, there is no support for C++17. 

Adding support appears to be non-trivial, because of the usage of macros and functions internal to the implementation of the standard library in `Primitives.cpp`, but possibly in more places.

Are there any plans for this?

**Comment by MarkusFrankATcernch** [comment]
I just compiled it with C++ 17. You have to tell cmake which standard to use:
 -DCMAKE_CXX_STANDARD=17
I just compiled it and did not see problems during the compilation

**Comment by paulgessinger** [comment]
Hm. 

I'm trying to build DD4hep from source on LCG94 on gcc8, so ROOT has a baked in C++17 dependency.

If I set up a build without an explicit C++ version, the CMake output reports C++11, but the actual flags given to the compiler include `-std=c++1z` (i.e. C++17), this doesn't appear to do anything, however, since the build fails due to ROOT's baked in C++17 dependency.

If I set up the build with explicit C++14 like `cmake .. -DCMAKE_CXX_STANDARD=14`, the compiler flags actually switch to `-std=c++14` but the build still fails for the same reason as expected.

When I set up the build with `cmake .. -DCMAKE_CXX_STANDARD=17` the compiler flags contain `-std=c++1z` **twice**. The build then fails somewhere else, I think during the generation of a ROOT dictionary file, with something like

```
/atlas/scratch0/pagessin/dev/DD4hep/DDCond/include/DDCond/ConditionsPool.h:204:92: error: no member named 'get_2nd' in namespace 'dd4hep::detail'
        std::transform(std::begin(c), std::end(c), std::back_inserter(conditions), detail::get_2nd<CONT>());
                                                                                   ~~~~~~~~^
/atlas/scratch0/pagessin/dev/DD4hep/DDCond/include/DDCond/ConditionsPool.h:204:100: error: 'CONT' does not refer to a value
        std::transform(std::begin(c), std::end(c), std::back_inserter(conditions), detail::get_2nd<CONT>());
                                                                                                   ^
/atlas/scratch0/pagessin/dev/DD4hep/DDCond/include/DDCond/ConditionsPool.h:201:26: note: declared here
      template <typename CONT> size_t registerMapping(const IOV& iov, CONT& c)     {
                         ^
/atlas/scratch0/pagessin/dev/DD4hep/DDCond/include/DDCond/ConditionsPool.h:204:106: error: expected expression
        std::transform(std::begin(c), std::end(c), std::back_inserter(conditions), detail::get_2nd<CONT>());
                                                                                                         ^
```

I remember trying to trace this further, and I think this lead me to `Primitives.cpp`, but it's possible I'm wrong here, or misremembering.

Hope that helps!

**Comment by MarkusFrankATcernch** [comment]
I just executed this from a fresh login:
source /cvmfs/sft.cern.ch/lcg/views/LCG_95a/x86_64-centos7-gcc8-dbg/setup.sh 

cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=OFF -DBUILD_TESTING=ON  -DCMAKE_BUILD_TYPE=Debug -DROOT_DIR=$ROOTSYS -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always -Werror" -DCMAKE_CXX_STANDARD=17 ..

make -j 5

Was compiling nicely (3 warnings, no errors)
Could you please verify this?

**Comment by paulgessinger** [comment]
In LCG95 this works on my machine, on LCG94 it fails with the errors mentioned before. That's odd, no idea what might change in the build between those versions.

**Comment by MarkusFrankATcernch** [comment]
This sounds odd.
You will have to ensure when building ***dependent*** packages (including the DD4hep examples), that for cmake your local DD4hep installation takes precedence over the one provided by LCG.

**Comment by andresailer** [comment]
If I apply the following patches I can compile against LCG94a, the problem is that the include path for some of the dd4hep includes comes after the include path from the LCG view otherwise.
The difference between LCG94 and LCG95 is the DD4hep version contained in them, 1.8 and 1.10 respectively. So probably also for LCG95 the header files from the view come before that of the parsers, but they don't lead to any compiler error. They could lead to more subtle bugs, I guess.

```diff
diff --git a/DDCond/CMakeLists.txt b/DDCond/CMakeLists.txt
index 97d93ef..94117c2 100644
--- a/DDCond/CMakeLists.txt
+++ b/DDCond/CMakeLists.txt
@@ -9,7 +9,7 @@
 #
 #==========================================================================
 dd4hep_package(    DDCond
-  USES             BOOST DDCore
+  USES             DDCore BOOST
   INCLUDE_DIRS     include
   INSTALL_INCLUDES include/DDCond)

diff --git a/cmake/DD4hepBuild.cmake b/cmake/DD4hepBuild.cmake
index 1605e96..8ebb194 100644
--- a/cmake/DD4hepBuild.cmake
+++ b/cmake/DD4hepBuild.cmake
@@ -898,7 +898,7 @@ function( dd4hep_package packageName )
       #
       list(APPEND used_incs ${CMAKE_CURRENT_SOURCE_DIR}/include )
       foreach( inc ${ARG_INCLUDE_DIRS} )
-        list( APPEND used_incs ${CMAKE_CURRENT_SOURCE_DIR}/${inc} )
+        list(INSERT used_incs 0 ${CMAKE_CURRENT_SOURCE_DIR}/${inc} )
       endforeach()
       #
       #  Build the list of link libraries required to build the package library and plugins etc.
```



Bad (replaced local paths with `<DD4HEP>`:
```
[ 94%] Generating G__DDCond.cxx
cd <DD4HEP>/build94/DDCond && /cvmfs/sft.cern.ch/lcg/views/LCG_94a/x86_64-slc6-gcc8-opt/bin/rootcling
 -cint
 [snip]
 -std=c++17
 -I<DD4HEP>/DDCond/include
 -I/cvmfs/sft.cern.ch/lcg/views/LCG_94a/x86_64-slc6-gcc8-opt/include
 -I<DD4HEP>/DDParsers/include
 -I<DD4HEP>/DDCore/include <DD4HEP>/DDCond/src/ConditionsDictionary.h
```
Good
```
[ 94%] Generating G__DDCond.cxx
cd <DD4HEP>/build94/DDCond && /cvmfs/sft.cern.ch/lcg/views/LCG_94a/x86_64-slc6-gcc8-opt/bin/rootcling
 -cint
 [snip]
 -std=c++17
 -I<DD4HEP>/DDCond/include
 -I<DD4HEP>/DDCore/include
 -I/cvmfs/sft.cern.ch/lcg/views/LCG_94a/x86_64-slc6-gcc8-opt/include
 -I<DD4HEP>/DDParsers/include <DD4HEP>/DDCond/src/ConditionsDictionary.h               
```
