### ISSUE TITLE
how to set up visualization with DDG4

### ISSUE THREAD

**Issue by GibbonLee** [AIDASoft/DD4hep#518]
Hi! I'm new to DDG4 and I have a naive question: Is there any example showing the usage of visualization with DDG4, or is it supported in DDG4 to use visualization? Thanks!

**Comment by petricm** [comment]
Hi, DDG4 is tool to convert the detector description to Geant4, this in principle has nothing to do with visualization. 

What exactly do you want to do? Visualize a detector described with DD4hep?

**Comment by MarkusFrankATcernch** [comment]
The support for visualization in DDG4 we inherit from Geant4 such as Dawn, etc. 
Once you are at the Geant4 prompt, you can invoke the Geant4 visualization utilities as usual: 
Geant4 prompt stays Geant4 prompt.
We do not have anything beyond this.

**Comment by GibbonLee** [comment]
I created some trapezoids in DD4hep and there seems no problem under DD4HEP. After I convert it into gdml by means of DDG4 and visualize it with geant4. The Trepezoids changed their shape.
So I want to locate the problem by visualizing it under ddg4.

**Comment by andresailer** [comment]
```
ddsim --compactFile pathToCompactFile.xml --runType vis
```
The rest are geant4 visualisation commands

**Comment by GibbonLee** [comment]
> ```
> ddsim --compactFile pathToCompactFile.xml --runType vis
> ```
> 
> The rest are geant4 visualisation commands

I'll try  it later. Thanks!

**Comment by GibbonLee** [comment]
ddsim is a good solution!
