### ISSUE TITLE
Reflection Rotation placement is needed

### ISSUE THREAD

**Issue by ianna** [AIDASoft/DD4hep#534]
CMS detector endcap subdetectors are described using reflection rotation. For example:

```xml
<ReflectionRotation name="ReflectionY" phiY="270.*deg" thetaY="90.*deg" phiX=" 0.*deg" thetaX="90.*deg" phiZ="0.*deg" thetaZ="0.*deg"/>
```
 which should give the following placement of a red shape when the above transformation is applied to the green shape. Ok, it gets inverted in the process, but that's how it is now:

![Screen Shot 2019-07-12 at 14 46 58](https://user-images.githubusercontent.com/1390682/61129125-05ce8580-a4b4-11e9-97a0-7cc15a3fe2ad.png)

When the same Rotation3D matrix is used to placeVolume, the result is as follows:

![Screen Shot 2019-07-11 at 11 20 21](https://user-images.githubusercontent.com/1390682/61129335-78d7fc00-a4b4-11e9-85fe-fff38d91fe8c.png)

**Workaround:** If instead, the TGeoCombiTrans is used to process the same Rotation3D obtained from Transform3D, the expected result is obtained with DD4hep:

![Screen Shot 2019-07-12 at 14 56 16](https://user-images.githubusercontent.com/1390682/61129720-51356380-a4b5-11e9-850c-47863cd70efc.png)

```cpp
  TGeoCombiTrans* createPlacement(const Rotation3D& iRot, const Position& iTrans) {
    double elements[9];
    iRot.GetComponents(elements);
    TGeoRotation r;
    r.SetMatrix(elements);

    TGeoTranslation t(iTrans.x(), iTrans.y(), iTrans.z());

    return new TGeoCombiTrans(t, r);
  }
```
as follows:
```cpp
    Transform3D transform;
    Converter<DDLTransform3D>(description, param, &transform)(element);
    Rotation3D rot(transform.Rotation());
    Translation3D trans(transform.Translation());
    double x, y, z;
    trans.GetComponents(x, y, z);
    Position pos(x, y, z);
    parent->AddNode(
		    child, copy,
		    createPlacement(rot, pos));

```

**Comment by MarkusFrankATcernch** [comment]
Hi Yana,

It is not clear to me where this is needed:
- In the DD4hep core or
- In the CMS specific XML translator
Neither TGeo nor Geant4 have such a specialized placement function. 
This tends to suggest, that this should be done in the CMS specific XML parser.

**Comment by ianna** [comment]
Hi Markus,

Yes, I have implemented it in the parser, but I think it's more generic since the translation to G4 takes it as a correct geometry. I'm sure CMS is not the only experiment with reflected geometry.

**Comment by ianna** [comment]
Hi Markus,

We also need to know if it's the volume is reflected. The sensitive detector assignment and numbering takes this in consideration to calculate a DetId.

**Comment by MarkusFrankATcernch** [comment]
Yana, Carl,

for the reflections: what is "more" correct
1) reflect the volume and its daughters (to left handed coords) and the you place it yourself using 
TGeoMatrix::ReflectZ(kTRUE)

or
2) take a placed volume and then internally do 1) and also reflect the placement matrix.

For me it's technically the same, but what is the typical use case?

**Comment by ianna** [comment]
Hi Markus,

We do not explicitly specify in a description that the volume is reflected. This is done as a result of a matrix transformation applied to a volume when it's placed. It can happen that a volume is reflected in the Y coordinate, for example.

We do check for check for the ortho-normality and left-handedness: https://cmssdt.cern.ch/lxr/source/DetectorDescription/Parser/src/DDLRotationAndReflection.cc#0087

Here is what we do to convert the DD to G4:
https://cmssdt.cern.ch/lxr/source/SimG4Core/Geometry/src/DDG4Builder.cc#0100

**Comment by MarkusFrankATcernch** [comment]
Hi Ianna, Carl,

just as an update. I created a reflection in the XY-plane in ROOT with the xml:
```<detector id="1" name="Shape_Trapezoid" type="DD4hep_TestShape_Creator">
      <check vis="Shape1_vis">
        <shape type="EightPointSolid" dz="30*cm">
           <vertex x="-30*cm" y="-25*cm"/>
           <vertex x="-25*cm" y=" 25*cm"/>
           <vertex x="  5*cm" y=" 25*cm"/>
           <vertex x=" 25*cm" y="-25*cm"/>
           <vertex x="-28*cm" y="-23*cm"/>
           <vertex x="-23*cm" y=" 27*cm"/>
           <vertex x="-23*cm" y=" 27*cm"/>
           <vertex x=" 13*cm" y="-27*cm"/>
        </shape>
        <position x="0"  y="0" z="100"/>
        <rotation x="0"  y="0" z="0"/>
      </check>
      <check vis="Shape2_vis">
        <shape type="EightPointSolid" dz="30*cm">
           <vertex x="-30*cm" y="-25*cm"/>
           <vertex x="-25*cm" y=" 25*cm"/>
           <vertex x="  5*cm" y=" 25*cm"/>
           <vertex x=" 25*cm" y="-25*cm"/>
           <vertex x="-28*cm" y="-23*cm"/>
           <vertex x="-23*cm" y=" 27*cm"/>
           <vertex x="-23*cm" y=" 27*cm"/>
           <vertex x=" 13*cm" y="-27*cm"/>
        </shape>
        <position x="0"  y="0" z="-100"/>
        <rotation x="0"  y="0" z="0"/>
        <reflect/>
      </check>
    </detector>
  </detectors>
```
The 2 shapes are identical, but the red one is reflected (rotation multiplied by Rotation3D(1., 0., 0., 0., 1., 0., 0., 0., -1.)). 

![Selection_008](https://user-images.githubusercontent.com/8831087/65959661-e01da080-e452-11e9-9404-43625776e7a6.jpg)

This looks in Geant4 the same:
![Selection_007](https://user-images.githubusercontent.com/8831087/65959503-769d9200-e452-11e9-977d-11d7358b6dca.jpg)

I think this should be roughly what you wanted. Not ?

**Comment by ianna** [comment]
@MarkusFrankATcernch - there is a problem with Ecal endcap simhits that looks similar to this one. Could you, please, check if reflected volumes are translated to G4 correctly? Thanks.
<img width="1176" alt="Screenshot 2020-10-15 at 23 14 32" src="https://user-images.githubusercontent.com/1390682/96837070-2242c700-1446-11eb-9ddf-514ade4797b3.png">

**Comment by ianna** [comment]
@cvuosalo, @ghugo83, @bsunanda - FYI

**Comment by MarkusFrankATcernch** [comment]
Hmm. What would be a representative test to verify this?

**Comment by ianna** [comment]
I can give you a root file produced from CMSSW with DD4hep. Would it work if you take it as an input to G4 converter?

**Comment by ianna** [comment]
yana@lxplus763.cern.ch:/tmp/yana/cmsDD4HepGeom.root

**Comment by MarkusFrankATcernch** [comment]
I think this would be too complicated to get anything out. There would be too many volumes.
I will try to take the simple reflection example and dump the absolute coordinates of the volumes.
If this does not show something weird, we have to see.

**Comment by ianna** [comment]
Is there an API to dump a GDML file?

**Comment by ianna** [comment]
@MarkusFrankATcernch - we used to use `G4ReflectionFactory` to place reflected volumes: https://cmssdt.cern.ch/lxr/source/SimG4Core/Geometry/src/DDG4Builder.cc#0098

**Comment by MarkusFrankATcernch** [comment]
G4ReflectionFactory: This is a good point.
What is correct: First reflect volume in the origin and then place the reflected volume - or - 
place the volume and then reflect the placed volume.
In DD4hep I do the first. 
The DDG4builder does some gymnastics around line https://cmssdt.cern.ch/lxr/source/SimG4Core/Geometry/src/DDG4Builder.cc#0149

**Comment by bsunanda** [comment]
When you reflect a volume do you create a new volume and if so how the 2 volumes one placed with RH rotation and one with LH rotation coexist? Do they have the same name, how the copy number is affected? We rely in many parts of the code how DDG4Builder handles in many parts of the code

**Comment by MarkusFrankATcernch** [comment]
@bsunanda
This is absolutely correct and this is how it is done in DD4hep. 
When reflecting a volume,
1) first the volume is cloned
2) From the original shape a TGeoScaledShape is created taking the original shape and a scale of (1,1,-1).
  This TGeoScaledShape is then the reflected shape and has the name <original shape>->GetName() + "_shape_refl".
3) This procedure is then applied to all daughter volumes of the reflected volume.
I do not see wrong logic in this procedure.

Are you sure you completely build the volume before reflecting it?
If you would add daughters after reflecting it, step 3) would be incomplete.

**Comment by bsunanda** [comment]
We do not see _refl appearing in the names of the reflected volumes. I also wonder about the parameters of these solids - they look odd.

**Comment by MarkusFrankATcernch** [comment]
@ bsunanda No, you do not. Ianna does not use the mechanism provided by dd4hep. We discussed this during yesterday's meeting and have to find a different solution for you....

**Comment by MarkusFrankATcernch** [comment]
@ianna @cvuosalo 

I had a longer chat with Andrei today about this issue. Apparently the reflections have a long historical story due to different approaches in `TGeo` and `Geant4`.... Anyhow this was our conclusion:

- In `TGeo/dd4hep` you simply place your volumes as you did before and in case of reflection, the matrix shall be left-handed.
  To propagate this properly to `TGeo` an equivalent  call `TGeoMatrix::CheckMatrix()` will be added whenever a daughter volume is added.
  Since apparently today `Geant4` accepts left-handed matrices (what apparently was not the case at some point in the past)
  There is nothing else to be done on the `TGeo` side: a left-handed placement matrix is sufficient to handle reflected volumes.
  The reflection mechanism in `TGeo` was sort of a workaround of Andrei to move the left-handed coordinate system out of the 
  Volume into the Shape so that `Geant4` would not complain about left-handed placement matrices.....
- When translating to `Geant4`, the `G4ReflectionFactory` should be used when placing individual volumes. For assemblies the 
  implementation of `G4AssemblyVolume` anyhow uses the `G4ReflectionFactory` when placing imprints.

Conclusions:
1) I will provide the changes as discussed with Andrei.
2) Do you have some quick mechanism to test this with simulation without having to invoke your entire release cycle ?
Then I would simply provide the updates on my fork of dd4hep on github.

Cheers,
Markus

**Comment by ianna** [comment]
> @ianna @cvuosalo
> 
> I had a longer chat with Andrei today about this issue. Apparently the reflections have a long historical story due to different approaches in `TGeo` and `Geant4`.... Anyhow this was our conclusion:
> 
> * In `TGeo/dd4hep` you simply place your volumes as you did before and in case of reflection, the matrix shall be left-handed.
>   To propagate this properly to `TGeo` an equivalent  call `TGeoMatrix::CheckMatrix()` will be added whenever a daughter volume is added.
>   Since apparently today `Geant4` accepts left-handed matrices (what apparently was not the case at some point in the past)
>   There is nothing else to be done on the `TGeo` side: a left-handed placement matrix is sufficient to handle reflected volumes.
>   The reflection mechanism in `TGeo` was sort of a workaround of Andrei to move the left-handed coordinate system out of the
>   Volume into the Shape so that `Geant4` would not complain about left-handed placement matrices.....
> * When translating to `Geant4`, the `G4ReflectionFactory` should be used when placing individual volumes. For assemblies the
>   implementation of `G4AssemblyVolume` anyhow uses the `G4ReflectionFactory` when placing imprints.
> 
> Conclusions:
> 
> 1. I will provide the changes as discussed with Andrei.
> 2. Do you have some quick mechanism to test this with simulation without having to invoke your entire release cycle ?
>    Then I would simply provide the updates on my fork of dd4hep on github.
> 
> Cheers,
> Markus

@MarkusFrankATcernch - Thanks! Great news!

Yes, I can easily test a master branch of DD4hep. The private branch is trickier, but doable. Please, let me know when I can test it. Thanks!

**Comment by MarkusFrankATcernch** [comment]
@ianna Could you please give it a try?
https://github.com/MarkusFrankATcernch/DD4hep

**Comment by ianna** [comment]
> @ianna Could you please give it a try?
> https://github.com/MarkusFrankATcernch/DD4hep

Thanks! I'll do it asap.

**Comment by etcherniaev** [comment]
`Geant4` has `G4ReflectedSolid` that can be used directly, without `G4ReflectionFactory`. The constructor of `G4ReflectionSolid` contains as a parameter `G4Transform3D`, which can be a reflection.

**Comment by ianna** [comment]
@MarkusFrankATcernch - there are lots of errors such as:
```
PlacedVolume     ERROR ++ Severe error: MBWheel_2N Attempt to add already exiting copy number 1 MBBTL_1
PlacedVolume     ERROR ++ Severe error: MBWheel_2N Attempt to add already exiting copy number 2 MBBTL_2
PlacedVolume     ERROR ++ Severe error: MBWheel_2N Attempt to add already exiting copy number 3 MBBTL_3
PlacedVolume     ERROR ++ Severe error: MBWheel_2N Attempt to add already exiting copy number 4 MBBTL_4
PlacedVolume     ERROR ++ Severe error: MBWheel_2N Attempt to add already exiting copy number 5 MBBTL_5
PlacedVolume     ERROR ++ Severe error: MBWheel_2N Attempt to add already exiting copy number 6 MBBTL_6
PlacedVolume     ERROR ++ Severe error: MBWheel_2N Attempt to add already exiting copy number 7 MBBTL_7
PlacedVolume     ERROR ++ Severe error: MBWheel_2N Attempt to add already exiting copy number 8 MBBTL_8
PlacedVolume     ERROR ++ Severe error: MBWheel_2N Attempt to add already exiting copy number 9 MBBTL_9
PlacedVolume     ERROR ++ Severe error: MBWheel_2N Attempt to add already exiting copy number 10 MBBTL_10
PlacedVolume     ERROR ++ Severe error: MBWheel_2N Attempt to add already exiting copy number 11 MBBTL_11
PlacedVolume     ERROR ++ Severe error: MBWheel_2N Attempt to add already exiting copy number 12 MBBTL_12
```

**Comment by ianna** [comment]
The EE simhits are still in two quarters, but different ones ;-)
This is with @MarkusFrankATcernch branch:
<img width="863" alt="Screenshot 2020-10-24 at 23 45 15" src="https://user-images.githubusercontent.com/1390682/97094247-7cfd3e00-1653-11eb-8ad0-5b7efa6b3eb3.png">
this is without:
<img width="926" alt="Screenshot 2020-10-24 at 23 48 23" src="https://user-images.githubusercontent.com/1390682/97094252-81295b80-1653-11eb-87d9-512e308d7e79.png">

**Comment by MarkusFrankATcernch** [comment]
Ohhh. I think I start to understand. I have to learn how to use the G4ReflectionFactory correctly. I'll come back soon.

**Comment by MarkusFrankATcernch** [comment]
According to Gabrielle the problem is understood and fixed.
