### ISSUE TITLE
Error in converting Trapezoid with DDG4

### ISSUE THREAD

**Issue by GibbonLee** [AIDASoft/DD4hep#536]
Hi! After solving the problem of visualization under DDG4, I find a serious bug. 
First, I created some trapezoids with DD4hep, It looks like this, and that's what I expected.
![QQ截图20190715152207](https://user-images.githubusercontent.com/35398009/61200928-8cce6880-a715-11e9-941c-b211c8f0194f.jpg)

After converting the geometry into gdml file with DDG4 or use ddsim under "vis" mode to see the geometry directly, the geometry turns out to be like this:
![QQ截图20190715152110](https://user-images.githubusercontent.com/35398009/61201076-eb93e200-a715-11e9-854a-2832bbfa4422.jpg)
 

The code to create trapezoid in DD4hep is like this:
```cpp
        a = rmin*Tan(dtheta)/Cos(theta0)-offsetw*2;
	c = a+b*Tan(dtheta);
	h1= rmin*Tan(dphi/2) - offsetw;
	h2= (rmin+a*Sin(theta0))*Tan(dphi/2) - offsetw;
	alpha1 = 0; alpha2 = 0;
	h3= (b*Cos(theta0)+rmin)*Tan(dphi/2) - offsetw;
	h4= (c*Sin(theta0)+b*Cos(theta0)+rmin)*Tan(dphi/2) - offsetw;
	mtheta = ATan((c-a)/b/2); mphi = M_PI/2; 
	Trap* MyTrap = new Trap(b/2, mtheta, -mphi, a/2, h1, h2, alpha1, c/2, h3, h4, alpha2);
```

And each trapezoid will be rotated like this:
`PlacedVolume rowPlvr = staveVol.placeVolume(rowVolr, Transform3D(RotationZYX(0, 0, -theta0), Position(x,y,z)));`

I'm not very sure whether the problem is induced by the rotation operation, because the trapezoid not be rotated shows no problem, as shown  in Fig.2 with write colour.

For more details, you can find my entire codes in my repo called [ECAL_DD4hep](https://github.com/GibbonLee/ECAL_DD4hep).

 - OS version: e.g. SLC6
 - Compiler version: e.g GCC 6.2
 - DD4hep version: Master branch
 - Geant4 version: 10.04.p01

**Comment by andresailer** [comment]
@GibbonLee 
Can you provide us with the code and commands you used to obtain the pictures above? That would make it easier to reproduce the problem

**Comment by MarkusFrankATcernch** [comment]
Hi,
is this problem related to Yana's issue:
https://github.com/AIDASoft/DD4hep/issues/534  ?

**Comment by MarkusFrankATcernch** [comment]
One comment to your code:

In dd4hep you should NOT use new:
ConeSegment* MyConeSegment = new ConeSegment(dz, rui, ruo, rli, rlo, phi1, phi2);

The handle carries the pointer. There is no destruction. Destruction is done by the TGeoManager once the shape is registered.
You can also return directly the handle. There is no overhead.

Hence:
ConeSegment MyConeSegment(dz, rui, ruo, rli, rlo, phi1, phi2);
...
return MyConeSegment;

**Comment by GibbonLee** [comment]
Fig.1: `geodisplay -compact b.xml`
Fig.2: The code I create gdml file can be seen in `scripts/gdml.py` in my `ECAL_DD4hep` repo.
          It can also be visualized by `ddsim --compactFile=b.xml --runType=vis` toghther with some Geant4 UI commands like `/vis/open OGLSQt`,`/vis/drawVolume` and so on.

> @GibbonLee
> Can you provide us with the code and commands you used to obtain the pictures above? That would make it easier to reproduce the problem

**Comment by GibbonLee** [comment]
Hi, Markus! 
1, I'm afraid they don't have strong relationship.(It's just my point of view)
2, The code I create gdml file can be seen in scripts/gdml.py in my ECAL_DD4hep repo. It's implemented from `CLICSiD/scripts/CLIC_GDML.py`.
3,  Yes. Fig.2 is actually a snapshot of graph generated by `ddsim` .
> Hi,
> 
> 1. is this problem related to Yana's issue:
>    #534  ?
> 2. How did you exactly create the GDML?
> 3. If you invoke the visualization using the converted geometry (without the GDML step)
>    Do you see the same?

**Comment by GibbonLee** [comment]
Thanks, I'll correct it later!
> One comment to your code:
> 
> In dd4hep you should NOT use new:
> ConeSegment* MyConeSegment = new ConeSegment(dz, rui, ruo, rli, rlo, phi1, phi2);
> 
> The handle carries the pointer. There is no destruction. Destruction is done by the TGeoManager once the shape is registered.
> You can also return directly the handle. There is no overhead.
> 
> Hence:
> ConeSegment MyConeSegment(dz, rui, ruo, rli, rlo, phi1, phi2);
> ...
> return MyConeSegment;

**Comment by GibbonLee** [comment]
Correction: the shape has problems is called `Trap` in DD4hep, not `Trapezoid`. As a result, there is no business with rotation operation, because the shape with white colour in Fig.2 is `Trapezoid`...
> Hi! After solving the problem of visualization under DDG4, I find a serious bug.
> First, I created some trapezoids with DD4hep, It looks like this, and that's what I expected.
> ![QQ截图20190715152207](https://user-images.githubusercontent.com/35398009/61200928-8cce6880-a715-11e9-941c-b211c8f0194f.jpg)
> 
> After converting the geometry into gdml file with DDG4 or use ddsim under "vis" mode to see the geometry directly, the geometry turns out to be like this:
> ![QQ截图20190715152110](https://user-images.githubusercontent.com/35398009/61201076-eb93e200-a715-11e9-854a-2832bbfa4422.jpg)
> 
> The code to create trapezoid in DD4hep is like this:
> 
> ```c++
>         a = rmin*Tan(dtheta)/Cos(theta0)-offsetw*2;
> 	c = a+b*Tan(dtheta);
> 	h1= rmin*Tan(dphi/2) - offsetw;
> 	h2= (rmin+a*Sin(theta0))*Tan(dphi/2) - offsetw;
> 	alpha1 = 0; alpha2 = 0;
> 	h3= (b*Cos(theta0)+rmin)*Tan(dphi/2) - offsetw;
> 	h4= (c*Sin(theta0)+b*Cos(theta0)+rmin)*Tan(dphi/2) - offsetw;
> 	mtheta = ATan((c-a)/b/2); mphi = M_PI/2; 
> 	Trap* MyTrap = new Trap(b/2, mtheta, -mphi, a/2, h1, h2, alpha1, c/2, h3, h4, alpha2);
> ```
> 
> And each trapezoid will be rotated like this:
> `PlacedVolume rowPlvr = staveVol.placeVolume(rowVolr, Transform3D(RotationZYX(0, 0, -theta0), Position(x,y,z)));`
> 
> I'm not very sure whether the problem is induced by the rotation operation, because the trapezoid not be rotated shows no problem, as shown in Fig.2 with write colour.
> 
> For more details, you can find my entire codes in my repo called [ECAL_DD4hep](https://github.com/GibbonLee/ECAL_DD4hep).
> 
> * OS version: e.g. SLC6
> * Compiler version: e.g GCC 6.2
> * DD4hep version: Master branch
> * Geant4 version: 10.04.p01

**Comment by MarkusFrankATcernch** [comment]
I think I found something:
In DDG4/src/Geant4Converter.cpp check line 691:
      solid = new G4Trap(name, sh->GetDz() * CM_2_MM, sh->GetTheta() * DEGREE_2_RAD, sh->GetPhi() * DEGREE_2_RAD,
                         sh->GetH1() * CM_2_MM, sh->GetBl1() * CM_2_MM, sh->GetTl1() * CM_2_MM, sh->GetAlpha1() * DEGREE_2_RAD,
                         sh->GetH2() * CM_2_MM, sh->GetBl2() * CM_2_MM, sh->GetTl2() * CM_2_MM, sh->GetAlpha2() * DEGREE_2_RAD);

The conversions for GetTheta() and GetPhi() had no conversions from degree to rad. Could you check with adding this please ?

**Comment by GibbonLee** [comment]
Hi! Markus,
  Congratulations! That's just where the problem lies.
  Thank you so much for promoting DD4hep to be a better software!
> I think I found something:
> In DDG4/src/Geant4Converter.cpp check line 691:
> 
> ```c++
> solid = new G4Trap(name, sh->GetDz() * CM_2_MM, sh->GetTheta() * DEGREE_2_RAD, sh->GetPhi() * DEGREE_2_RAD,
>   sh->GetH1() * CM_2_MM, sh->GetBl1() * CM_2_MM, sh->GetTl1() * CM_2_MM, sh->GetAlpha1() * DEGREE_2_RAD,
>   sh->GetH2() * CM_2_MM, sh->GetBl2() * CM_2_MM, sh->GetTl2() * CM_2_MM, sh->GetAlpha2() * DEGREE_2_RAD);
> ```
> 
> The conversions for GetTheta() and GetPhi() had no conversions from degree to rad. Could you check with adding this please ?
