### ISSUE TITLE
DD4hep reference manual permissions?

### ISSUE THREAD

**Issue by ianna** [AIDASoft/DD4hep#543]
Hi,

It looks like I do not have permissions to see the source code. BTW, the new format of the home web page is a bit odd. I get only half of a search field and the links to the other pages are not so obvious. They look like one line with a small font...

**Comment by petricm** [comment]
Hi @ianna 
>It looks like I do not have permissions to see the source code

where, to which location are you reffing, can you post a link.

>BTW, the new format of the home web page is a bit odd. I get only half of a search field and the links to the other pages are not so obvious. They look like one line with a small font...

The format has not been change for quite some time. What exactly are you referring to? Screen shot please.

**Comment by ianna** [comment]
![Screen Shot 2019-07-18 at 12 44 09](https://user-images.githubusercontent.com/1390682/61451577-0a82b600-a95a-11e9-9c85-a414b9d770ce.png)

There are no links here:
![Screen Shot 2019-07-18 at 12 46 40](https://user-images.githubusercontent.com/1390682/61451686-3aca5480-a95a-11e9-99e4-346a15fe55dd.png)

It I try https://dd4hep.web.cern.ch/dd4hep/reference/XMLParsers_8cpp.html#abc62e8b4beeaa768e91addbb37a131f3
![Screen Shot 2019-07-18 at 12 45 26](https://user-images.githubusercontent.com/1390682/61451578-0a82b600-a95a-11e9-8c23-afd60f9df15b.png)

**Comment by petricm** [comment]
I have regenerated the website, but this might be today of the hypervisor restart at cern

**Comment by ianna** [comment]
yes, there are some oddities observed today due to the central services maintenance...

**Comment by ianna** [comment]
thanks, it works now!
