### ISSUE TITLE
Flat DetElement tree while keeping nested Volume placements

### ISSUE THREAD

**Issue by asalzburger** [AIDASoft/DD4hep#546]
I am finally getting around finishing the TrackML follow-up detector in DD4Hep.
As I want to introduce some realism, I defined  (simplified):

```
<detector>
<module  name=“PixelModule” … />
<stave … module=“PixelModule” />
<layer id=“0” staves=16/>
<layer id=“1” staves=28/>
<layer id=“2” … />
<layer id=“3” … />
</detector>
```

This all works fine, i.e. I define a template module with several components, place it into a template stave and then place the template stave n times per layer,
see the screen-shot attached.

For the DetElement tree, however, I would like to have a rather flat tree, something like

barrelDet -> [ layerDet0, layerDet1, layerDet2, layerDet3 ]

Where in each layer I have no other hierarchy then 

layerDet0 -> [ moduleDet_0_0, moduleDet_0_1, … moduleDet_n_m ]

Since I build the template module and stave upfront and place them repetitively into the layers, I seem to have troubles though to assign the unique placedVolumes XY to the moduleDet_x_y DetElements.

```
moduleDet_x_y.setPlacement(XY);
```

At building time I mark the right volume sensitive though, so I think I could just after building recursively walk through the geometry and collect sensitively placed volumes to build my DetElement tree:
  - Is there a way to do so or am I missing something here?

**Comment by andresailer** [comment]
>   I seem to have troubles though to assign the unique placedVolumes XY to the moduleDet_x_y DetElements.

Why does it seem to you that you have these troubles?

**Comment by MarkusFrankATcernch** [comment]
Andreas,
I think I can close this issue.
The solution was to strategically clone DetElement sub-trees.
