### ISSUE TITLE
Python compatibility check with ROOT

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#563]
Add python compatibility check between the version that was used to build ROOT and the version CMake has found for the build of DD4hep. Requires ROOT 6.20 and this [ticket](https://sft.its.cern.ch/jira/browse/ROOT-10293).

At this point review also [this](https://github.com/AIDASoft/DD4hep/commit/f225a01955d94f1679178174b78e9e51005254e1) implementation.

**Comment by whit2333** [comment]
What version of python is best to use?  I am having issues getting ddsim to work...

**Comment by petricm** [comment]
You need to provide a bit more details about your problem. This issue is just here as a remainder to implement a mechanism to check that the version of python used to build ROOT is also used to build DD4hep. Apart from this there are no restrictions, we are testing 2.7 and 3.6.

**Comment by whit2333** [comment]
The dd4hep python packages don't follow convention. Whatever is in thisdd4hep.sh does the trick. 

PYTHONPATH={INSTALL_PREFIX}/lib  should work for the python packages but does not...

**Comment by petricm** [comment]
What do you mean by convention?

DD4hep python stuff is installed in DD4HEP_PYTHON_INSTALL_DIR
```cmake
find_package(Python COMPONENTS Development)
set(DD4HEP_PYTHON_INSTALL_DIR lib/python${Python_VERSION_MAJOR}.${Python_VERSION_MINOR}/site-packages)
```

**Comment by whit2333** [comment]
I think the problem is in the python packaging not the cmake install. Say you install into `/usr/local`, all that should be needed is the env variable `PYTHONPATH=/usr/local/lib`. But ddsim needs `/usr/local/lib/python3.7/site-packages`, which is the convention-breaking thing I was referring. Here is a little demo:

```
$ echo $PYTHONPATH
/usr/local/lib:/usr/local/lib:                                            
$ ddsim                                             
Traceback (most recent call last):
  File "/usr/local/bin/ddsim", line 13, in <module>
    from DDSim.DD4hepSimulation import DD4hepSimulation
ImportError: No module named DDSim.DD4hepSimulation
$ . /usr/local/bin/thisdd4hep.sh
$ echo $PYTHONPATH
/usr/local/lib/python3.7/site-packages:/usr/local/lib:/usr/local/lib:
$ ddsim
usage: Running DD4hep Simulations: [-h] [--steeringFile STEERINGFILE] [--compactFile COMPACTFILE] [--runType {batch,vis,run,shell}]
                                   [--inputFiles INPUTFILES [INPUTFILES ...]] [--outputFile OUTPUTFILE]
                                   [-v {1,2,3,4,5,6,7,VERBOSE,DEBUG,INFO,WARNING,ERROR,FATAL,ALWAYS}] [--numberOfEvents NUMBEROFEVENTS]
                                   [--skipNEvents SKIPNEVENTS] [--physicsList PHYSICSLIST] [--crossingAngleBoost CROSSINGANGLEBOOST]
                                   [--vertexSigma X Y Z T] [--vertexOffset X Y Z T] [--macroFile MACROFILE] [--enableGun] [--enableG4GPS]
                                   [--enableG4Gun] [--dumpParameter] [--enableDetailedShowerMode] [--dumpSteeringFile]
                                   [--meta.eventNumberOffset META.EVENTNUMBEROFFSET]
                                   [--meta.eventParameters META.EVENTPARAMETERS [META.EVENTPARAMETERS ...]]
                                   [--meta.runNumberOffset META.RUNNUMBEROFFSET] [--filter.mapDetFilter FILTER.MAPDETFILTER]
                                   [--filter.tracker FILTER.TRACKER] [--filter.filters FILTER.FILTERS] [--filter.calo FILTER.CALO]
                                   [--field.delta_intersection FIELD.DELTA_INTERSECTION] [--field.min_chord_step FIELD.MIN_CHORD_STEP]
                                   [--field.equation FIELD.EQUATION] [--field.stepper FIELD.STEPPER] [--field.largest_step FIELD.LARGEST_STEP]
                                   [--field.delta_chord FIELD.DELTA_CHORD] [--field.eps_min FIELD.EPS_MIN] [--field.eps_max FIELD.EPS_MAX]
                                   [--field.delta_one_step FIELD.DELTA_ONE_STEP] [--guineapig._parameters GUINEAPIG._PARAMETERS]
                                   [--guineapig.particlesPerEvent GUINEAPIG.PARTICLESPEREVENT] [--gun.thetaMin GUN.THETAMIN]
                                   [--gun.phiMin GUN.PHIMIN] [--gun.direction GUN.DIRECTION] [--gun.particle GUN.PARTICLE]
```

**Comment by petricm** [comment]
For us convention for python packages is `__destination__/lib/pythonX.Y/site-packages`, also very helpful when dealing with multiple version of python.

If you desire something else overwrite `DD4HEP_PYTHON_INSTALL_DIR` to whatever suits your use-case.

**Comment by whit2333** [comment]
Again, the CMAKE side of things is fine. I am not a python expert but if the python is properly packaged, only `__destination__/lib` is need in `PYTHONPATH` for any version of python to find the packages.

**Comment by petricm** [comment]
No, you need to point the the `PYTHONPATH` to the site-packages.
Example with some random pip package (e.g. certifi), install into `/some/dir`
```
pip install --install-option="--prefix=/some/dir" certifi
```
if you now set
```
export PYTHONPATH=/some/dir
$ python
>>> import certifi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named certifi
```

or 

```
export PYTHONPATH=/some/dir/lib
$ python
>>> import certifi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named certifi
```

only if you set to the site-packages it works

```
export PYTHONPATH=/some/dir/lib/python2.7/site-packages
$ python
>>> import certifi
>>> 
```

**Comment by andresailer** [comment]
The automatic inclusion of `pythonX.Y/site-packages` only applies to the folders pointed to by `site.PREFIXES`, see https://docs.python.org/2.7/library/site.html .
