### ISSUE TITLE
 List All Readout Channels

### ISSUE THREAD

**Issue by vvolkl** [AIDASoft/DD4hep#580]
Looking for some advice: Is there a good, generic way to list all the possible readout channels of a detector? That is all sensitive volumes including segmentations. Example: I have defined a detector with readout:
```xml
<readout name="ECalBarrelPhiEta">
  <segmentation type="FCCSWGridPhiEta" grid_size_eta="0.01" phi_bins="704" offset_eta="-1.68024" offset_phi="-pi+(pi/704.)"/>
  <id>system:4,cryo:1,type:3,subtype:3,layer:8,eta:9,phi:10</id>
</readout>
``` 
and want (to add some noise for example) to create an exhaustive list of all cellIDs that Geant4  might deposit energy in.

I think it should be straightforward enough to iterate over sensitive DetElements, but to find all possible segmentation cells  is a bit trickier; is there already some generic code to do that?

**Comment by MarkusFrankATcernch** [comment]
I am not aware of generic code to perform this.
However, I can see the usefulness - 
in fact I would be interested in such code as soon as I start with the digitization package....

It is also not clear how do do this, unless your sensitive volume is read-out throughout; ie without taking into account possible dead zones around the edges, cut-outs etc.
I think to really describe such segmentations taking into account such effects is more complex than our simple bit-field.

**Comment by MarkusFrankATcernch** [comment]
Hi Valentin,

I just remembered this.
This command does not give you all readout channels, but at least all sensitive volumes together with their corresponding id decoding (x/y or eta/phi decoding not present):

$> geoPluginRun -input ../checkout/DDDetectors/compact/SiD.xml -volmgr \
-plugin DD4hep_VolumeDump -detector EcalBarrel -sensitive -volume_ids

Does this partially help you?

**Comment by vvolkl** [comment]
Sorry for the very late reply, this is actually very nice! I think we can close.
