### ISSUE TITLE
More Geant4 shapes?

### ISSUE THREAD

**Issue by dannielliu** [AIDASoft/DD4hep#588]
Dear Developers,

It seems the dd4hep does not support all shapes in Geant4. What we now try to construct is a G4TwistedTubs, we do not know how to implement it in DD4hep. I suppose it is not implemented in ROOT too, its not a simple question for DD4hep. We would like to know whether there are plans for this, Or are there other solutions?

Thank you very much!

Best regards,
Dong Liu

**Comment by petricm** [comment]
Dear @dannielliu,
indeed `G4TwistedTubs` is missing in DD4hep and an appropriate class is also missing in ROOT. We will have to get in touch the ROOT developers to incorporate this. If you look a the table bellow you will sthat other twisted shapes are also missing, but there at least the ROOT class `TGeoGtra` is there.

In short currently DD4hep misses:
  - G4EllipticalCone
  - G4Tet
  - G4TwistedTubs
  - G4TwistedBox
  - G4TwistedTrap
  - G4TwistedTrd

| GEANT4 | TGeo | DD4hep |
| :-------------: |:-------------:| :-----:|
| G4IntersectionSolid | TGeoIntersection | IntersectionSolid |
| G4SubtractionSolid | TGeoSubtraction | SubtractionSolid |
| G4UnionSolid | TGeoUnion | UnionSolid |
| G4Box | TGeoBBox | Box |
| G4Cons | TGeoConeSeg | Cone |
| G4CutTubs | TGeoCtub | Cone |
| G4Orb | TGeoSphere | Sphere |
| G4Paraboloid | TGeoPara | Paraboloid |
| G4Sphere | TGeoSphere | Sphere |
| G4Torus | TGeoTorus | Torus |
| G4Trap | TGeoTrap | Trap |
| G4Trd | TGeoTrd1 and Trd2 | Trd1 and Trd2 |
| G4Tubs | TGeoTubeSeg | Tube |
| G4Elipsoid | TGeoSphere* sph = new TGeoSphere("sph",0.,1.); TGeoScale *scl = new TGeoScale(1.,1.,0.5); TGeoScaledShape *ellipsoid new TGeoScaledShape("ell", sph, scl); | Not direct |
| G4EllipticalCone | no | no |
| G4EllipticalTube | TGeoEltu | ElipticalTube |
| G4GenericTrap | TGeoArb8 | EightPointSolid |
| G4Hype | TGeoHype | Hypeboloid |
| G4Paraboloid | TGeoParaboloid | Paraboloid |
| G4ScaledSolid | TGeoScaledShape | ? |
| G4ExtrudedSolid | TGeoXtru | TGeoXtru |
| G4Tet | no | no |
| G4TwistedTubs | no | no |
| G4GenericPolycone | ? | ? |
| G4Polycone | TGeoPcon | Polycone |
| G4Polyhedra | TGeoPgon | TGeoPgon |
| G4TwistedBox | TGeoGtra | no |
| G4TwistedTrap | TGeoGtra | no |
| G4TwistedTrd | TGeoGtra | no |

**Comment by MarkusFrankATcernch** [comment]
It looks to me that 
- G4TwistedBox G4TwistedTrap and G4TwistedTrd could be realized with a TGeoArb8 (EightpointSolid)
- G4GenericPolycone is simply a TGeoPcon (Polycone)
- G4TwistedTubs I think neither TGeo  and consequently DD4hep does not have
- G4Elipsoid we could realize as described above.

**Comment by MarkusFrankATcernch** [comment]
Hi Dong,

as far as I know, there are no plans from the ROOT side to support the twisted tube. For some of the other twisted shapes I think I can do something using TGeoArb8, but tubes and cones are currently not possible. If it is absolutely required, I maybe can do something to have a "special" tube shape, which translates to a G4TwistedTube when converted to geant4, but uses a pure tube in ROOT. If some hybrid like this would help, I could investigate.

Cheers,
Markus

**Comment by dannielliu** [comment]
Hi Markus,

It would be very nice if we can have a tube shape. 
We are now trying to replace TwistedTub with some similar shapes, but some problems occur in simulation. We are making efforts to figure out problems and trying other similar shapes. 
If similar shapes can work, this would not be so urgent. If not, the twisted shapes would be required. Whatever, we will let you know when we have progress.

Thank you very much!

best regards,
Dong

**Comment by dannielliu** [comment]
Dear Markus,

We may still need a "special" twist tube. 
We have tried to use "G4GenericTrap" to do the simulation. When there is magnetic field, geant4 may trace tracks to a wrong volume. If using G4TwistedTubs, there is no such problem.
And another reason we want a G4TwistedTubs is that it can describe our detector more precisely. 

Thank you very much!

best regards,
Dong

**Comment by MarkusFrankATcernch** [comment]
Hi Dong,
I implemented some sort of "fake" TwistedTube shape in DD4hep. To see in ROOT:
$> geoDisplay -compact ../checkout/examples/ClientTests/compact/Check_Shape_TwistedTube.xml
When converted to geant4 it translates to a G4TwistedTube. See with:
$> python ../checkout/examples/ClientTests/scripts/Check_shape.py -geometry ../checkout/examples/ClientTests/compact/Check_Shape_TwistedTube.xml

Foir details to construct such a shape please see Shapes.h. Arguments should be the same as for G4TwistedTube/

**Comment by dannielliu** [comment]
Thank you very much!
I will have a try.

best regards,
Dong

**Comment by MarkusFrankATcernch** [comment]
Please wait a couple of minutes until merge https://github.com/AIDASoft/DD4hep/pull/594
is committed....
