### ISSUE TITLE
How do I add a quadrupole magnetic field to geant4

### ISSUE THREAD

**Issue by wangwei19980727** [AIDASoft/DD4hep#589]
How do I add a quadrupole magnetic field to geant4?Can you give me a simple example to study?
thanks!

**Comment by andresailer** [comment]
Similar to this:
https://github.com/AIDASoft/DD4hep/blob/280c7d748d56a704699408ac8e57815d029b169a/examples/ClientTests/compact/MagnetFields.xml#L54-L61
See  here for the description of the coefficients to use for a Quadrupole
https://dd4hep.web.cern.ch/dd4hep/reference/classdd4hep_1_1MultipoleField.html

**Comment by wangwei19980727** [comment]
> Similar to this:
> https://github.com/AIDASoft/DD4hep/blob/280c7d748d56a704699408ac8e57815d029b169a/examples/ClientTests/compact/MagnetFields.xml#L54-L61
> 
> 
> See here for the description of the coefficients to use for a Quadrupole
> https://dd4hep.web.cern.ch/dd4hep/reference/classdd4hep_1_1MultipoleField.html
Thank you for your reply！I just started learning G4, I wonder if you have any simple examples。

Best Wish！

**Comment by andresailer** [comment]
Well, what I linked to is a simple example. You just have to put in the coefficients and skews to turn the Generic multi-pole into a pure quadrupole, which is explained in the documentation link.
To try out the parameters you can copy the "MagnetFields.xml" file and modify it, or use your own compact file and add or modify the "fields" section, for example removing all the other fields.

If you have an installation of DD4hep, or CVMFS (`source /cvmfs/clicdp.cern.ch/iLCSoft/builds/2019-09-04/x86_64-slc6-gcc62-opt/init_ilcsoft.sh`) at your disposal:
you can use the "dumpBfield" tool to "see" the bfield.
For example:
```
dumpBfield /cvmfs/clicdp.cern.ch/iLCSoft/builds/2019-09-04/x86_64-slc6-gcc62-opt/DD4hep/HEAD/examples/ClientTests/compact/MagnetFields.xml 100 100 100 1 1 1
```
Will print out the BField vectors of the detector.

**Comment by wangwei19980727** [comment]
Sorry，I was too stupid to understand how to do it.
cry~~~~thank you

**Comment by andresailer** [comment]
Please also take not of the small error fixed with this PR #590

```diff
-  <field name="MagnetFields_GlobalMultipole" type="MultipoleMagnet" Z="50*cm"> 
+  <field name="MagnetFields_GlobalMultipole" type="MultipoleMagnet" Z="50*tesla"> 
```

**Comment by wangwei19980727** [comment]
> Please also take not of the small error fixed with this PR #590
> 
> ```diff
> -  <field name="MagnetFields_GlobalMultipole" type="MultipoleMagnet" Z="50*cm"> 
> +  <field name="MagnetFields_GlobalMultipole" type="MultipoleMagnet" Z="50*tesla"> 
> ```
Can you help me add a quadrupole field to a simple example of B1 in G4？

**Comment by andresailer** [comment]
If you mean a pure Geant4 example, then no, you would have to ask the Geant4 support channels.

If you ported a Geant4 example to DD4hep, all the information should be here. If there are still problems with DD4hep you need to give more details on what is not working for you.

**Comment by wangwei19980727** [comment]
> If you mean a pure Geant4 example, then no, you would have to ask the Geant4 support channels.
> 
> If you ported a Geant4 example to DD4hep, all the information should be here. If there are still problems with DD4hep you need to give more details on what is not working for you.

ok,i try it.but i dont know how to  install this DD4hep,download all code?then ...?
