### ISSUE TITLE
Moving to minor version 11 broke some of the tests

### ISSUE THREAD

**Issue by andresailer** [AIDASoft/DD4hep#591]
For example this test `t_CLICSiD_DDG4_CLICSiDXML_as_AClick_LONGTEST` now times out, instead of finishing successfully after 25 seconds. Trying things locally the test passes when I move the version back to 1.10, but fails when I move to 1.11.
I am not sure if the test somehow picks up DD4hep libraries installed on CVMFS or somewhere else and the test passes because of this, or if something else is broken.

There also some configurations that work:
https://gitlab.cern.ch/CLICdp/DetectorSoftware/DD4hep/pipelines/1179026

**Comment by petricm** [comment]
Same behavior on Travis https://travis-ci.org/AIDASoft/DD4hep/builds/603853282?utm_source=github_status&utm_medium=notification
