### ISSUE TITLE
Empty Solid_type<T>::type() leads to segmentation fault if Solid_type<T>::name() is called

### ISSUE THREAD

**Issue by cvuosalo** [AIDASoft/DD4hep#599]
If `Solid_type<T>::type()` returns an empty string, then any subsequent call to `Solid_type<T>::name()` or `Solid_type<T>::title()` on the same object will cause a segmentation fault.
If users should always check `Solid_type<T>::type()` before trying to call `Solid_type<T>::name()` or `Solid_type<T>::title()`, the documentation should say so.
Otherwise, `Solid_type<T>::name()` and `Solid_type<T>::title()` should be revised so they don't cause segmentation faults even  if `this->ptr()` is null.

CMS would like to prevent segmentation faults when using `Solid_type` objects, even if the objects are not complete.

 - OS version: SLC7
 - Compiler version:GCC 8.3.1
 - DD4hep version:  DD4hep/DDCore/src/Shapes.cpp as of 27-Nov-2019

**Comment by MarkusFrankATcernch** [comment]
Problem acknowledged.
For efficiency reasons not all calls are protected. 
Fact is you were dealing with an invalid handle with no underlying pointer.
It is implicitly assumed that the most frequent ones are only called after they are checked. Which ones should necessarily be protected and which ones not is not so clear: e.g. if Solid.type() is always called before any other call it is sufficient to protect Solid.type() only and not Solid.name() or Solid.title().
Maybe we can discuss it today during the meeting.

**Comment by petricm** [comment]
We had a discussion today about this issue at the developers meeting. Could you please give a bit of context, what I mean with that is, what have you been doing when this problem appeared?
Were you traversing the tree and just printing stuff... just to see what function are called before.

**Comment by cvuosalo** [comment]
I see now that `Solid_type<T>` has an `isValid()` method. I added to our code a check for `isValid()` before calling `Solid_type<T>::name()`, so that will protect against these segmentation faults as long as we always make the check before calling the vulnerable methods (`name()` and `title()`).

I would prefer that `Solid_type<T>::name()` would gracefully return something like an empty string when called with an invalid solid rather than terminating the program, but we can manage with the current situation.

**Comment by cvuosalo** [comment]
@petricm The segmentation fault occurred while reading a geometry XML file, specifically reading in SubtractionSolids. When a new volume is added, there is a debug statement that prints the volume and solid name. A few of the SubtractionSolids were invalid, and the segfault occurred when the first one was encountered and an attempt was made to print out the solid name. I haven't been able to figure out why some of the SubtractionSolids in the file are invalid. They look to me like the other ones in the file.

**Comment by cvuosalo** [comment]
@ianna FYI

**Comment by MarkusFrankATcernch** [comment]
Hi Carl,
This is what we agreed in yesterday's meeting:
1) For efficiency reasons not all calls are protected. We sort-of try to anticipate the checked use of handles, so that at the event processing level no invalid handles are dangling around. What for this reason shall NOT be protected is the operator->() and operator *().
2) Whenever strings are involved typically efficiency goes down the drain and - as a corollary - calls like handle->name() etc. shall be protected.

Hence:
Your specific use case shall be protected. An exception (std::runtime_error) shall be thrown for calls to
Solid::name()
Solid::type()
Solid::title()  if the underlying pointer is invalid.

Is this a valid solution for you?

Markus

**Comment by cvuosalo** [comment]
Hi Markus,
I think we would like to continue using `isValid()` to make sure the object is valid before trying to get its name. We don't really like using exceptions, and, in this case, an exception is too extreme. Our program can continue if the solid is not valid -- we just can't print out its name, which is only needed for debugging anyway.

If you protect those methods with exceptions, that is OK with us, but we will just avoid calling those methods on invalid objects rather than calling them and trying to catch the exceptions.

Thanks.

---Carl

**Comment by MarkusFrankATcernch** [comment]
Hi Carl,
I think this is a good approach. 
isValid() will ensure you got a valid object and if someone does not check, on some selected methods the SEGV is avoided and an exception thrown.

Markus
