### ISSUE TITLE
Typo in header file

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#601]
https://github.com/AIDASoft/DD4hep/blob/982b65499b76600ede1e0e6f79c40fb832967c35/DDCore/include/DD4hep/Shapes.h#L1023

```
dd4hep/include/DD4hep/Shapes.h:1023:27: error: ‘_toDOuble’ was not declared in this scope
                  _toDOuble(rmin),       _toDouble(rmax),
                  ~~~~~~~~~^~~~~~
```

**Comment by whit2333** [comment]
PR here https://github.com/AIDASoft/DD4hep/pull/602

**Comment by MarkusFrankATcernch** [comment]
I will fix it. Shall be in my next commit....
