### ISSUE TITLE
Overridden children's ids when cloning DetElement

### ISSUE THREAD

**Issue by sponce** [AIDASoft/DD4hep#605]
I think there is a bug in the clone method of DetElement, here : https://github.com/AIDASoft/DD4hep/blob/5bbbb8c86ff764eb452608b5439db90b5e3d2450/DDCore/src/DetectorInterna.cpp#L121

As you can see the id of all children are overriden to the one of the parent. I would rather keep them by replacing `obj->` by `d.`

**Comment by MarkusFrankATcernch** [comment]
If this issue is solved. Please close the issue.
Thanks!

**Comment by sponce** [comment]
I suppose it's fixed yes. Now may I ask why you did not just fix it, but kept a flag to be able to resurrect the bug ? Seems to me like an unneeded complication that can only lead to problems if ever someone activates it.
