### ISSUE TITLE
Surface installer manager plugin

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#609]
I get the following runtime error:
```
...
DD4hep_GenericSurfaceInstallerPlugin: argument[1] = dimension = 2
DD4hep_GenericSurfaceInstallerPlugin: argument[2] = u_x = -1
DD4hep_GenericSurfaceInstallerPlugin: argument[3] = v_y = -1
DD4hep_GenericSurfaceInstallerPlugin: argument[4] = n_z = 1
DD4hep_GenericSurfaceInstallerPlugin: vectors: u( -1 , 0 , 0) v( 0 , -1 , 0) n( 0 , 0 , 1) o( 0 , 0 , 0) 
PluginService    ERROR Factory requested: InstallSurfaceManager (N10__cxxabiv120__function_type_infoE) :bad any_cast

**************************************************** 
*  A runtime error has occured :                     
*    dd4hep: apply-plugin: Failed to locate plugin InstallSurfaceManager. 		No factory with name Create(InstallSurfaceManager) for type InstallSurfaceManager found.
		Please check library load path and/or plugin factory name.
dd4hep: with plugin:InstallSurfaceManager
dd4hep: Error interpreting XML nodes of type <plugin/>
dd4hep: Error interpreting XML nodes of type <plugins/>
dd4hep: while parsing gem_tracker_disc.xml
*  the program will have to be terminated - sorry.   
**************************************************** 
```

 - OS version: Ubuntu 18.04
 - Compiler version:  GCC 9.2
 - DD4hep version: master
 - Reproduced by: singularity container
 - Goal: Get ROOT script running again. 

Also using c++17

**Comment by petricm** [comment]
Sorry, but this is unclear, you need to describe the issue a bit more that we are able to reproduce or at least get an idea what of you do.

**Comment by whit2333** [comment]
Assuming you have singularity, with this singularity image:
```
wget https://eicweb.phy.anl.gov/containers/eic_container/-/jobs/14065/artifacts/raw/build/eic.sif
```
or with your dd4hep install you can build NPDet (with the repo below).

Then run the example script:
```
git clone https://eicweb.phy.anl.gov/EIC/NPDet
cd NPDet/examples
./run_example
```

Not sure what you prefer.

**Comment by andresailer** [comment]
@whit2333 
Do you have the DDRecPlugin library with the InstallSurfaceManager compiled?
E.g.:
/cvmfs/clicdp.cern.ch/iLCSoft/builds/2019-09-04/x86_64-slc6-gcc62-opt/DD4hep/HEAD/lib/libDDRecPlugins.components

**Comment by andresailer** [comment]
So I can see the libDDRecPlugins.components which contains the line for the InstallSurfaceManager in your singularity file, but it would be very helpful, if you could also tell us how to run your example based on that image.

**Comment by whit2333** [comment]
@andresailer Thanks for looking at this. To run the example with the singularity container:

```
git clone https://eicweb.phy.anl.gov/EIC/NPDet.git
cd NPDet/examples
wget https://eicweb.phy.anl.gov/containers/eic_container/-/jobs/14065/artifacts/raw/build/eic.sif
# wait for download (sorry for the large debugging container)
singularity shell eic.sif
source /usr/local/bin/thisdd4hep.sh
./run_example
```

**Comment by andresailer** [comment]
In the `NPDet/examples/rootlogon.C` file, you only need to load
```
gSystem->Load("libDDG4IO");
```

Then I get
```
Singularity> root -b -q scripts/example_cell_size.cxx+
...
Segmentation-Cell Position : (-126,1.54305e-14,-68)                                     
   Surface Origin Position :   ( 0, 0, 0 ) -  [ phi: 0 , rho: 0 ]   [ theta: 0 , r: 0 ] 
 dim 2, 2.19911,               Hit Position : (-126.442,0.672822,-68.3868)              
Segmentation-Cell Position : (-126,1.54305e-14,-68)                                     
   Surface Origin Position :   ( 0, 0, 0 ) -  [ phi: 0 , rho: 0 ]   [ theta: 0 , r: 0 ] 
Singularity>
```
Please try removing the other Load statements from the rootlogon to confirm.

Loading `libDDDetectors` or `libDDCorePlugins` leads to an exception with a plugin, but it is not clear to me why that is the case. Generally the plugin libraries are loaded at runtime by the pluginservice and should't be loaded manually or linked against.

**Comment by whit2333** [comment]
Fantastic, thank you. 

About 2 years ago, I needed to load `libDDDetectors` to get things to work then worked on other things. So I am catching up with all the changes to DD4hep since then.

Is this bit of code below still using the right interfaces/doing things the right way?

```
  dd4hep::Detector& detector = dd4hep::Detector::getInstance();
  detector.fromCompact("gem_tracker_disc.xml");
  dd4hep::rec::CellIDPositionConverter cellid_converter(detector);
  // Get the surfaces map
  dd4hep::rec::SurfaceManager& surfMan = *detector.extension<dd4hep::rec::SurfaceManager>() ;
  auto surfMap = surfMan.map( "world" ) ;
```

Thanks again for all your help.

**Comment by andresailer** [comment]
You're welcome.

Uhh, I think that is all OK
