### ISSUE TITLE
DD4 assumes file TGeoTessellated.h exists in the ROOT installation

### ISSUE THREAD

**Issue by mrodozov** [AIDASoft/DD4hep#617]
- OS version: e.g. CC7
 - Compiler version: e.g GCC 8.3 
 - DD4hep version: since https://github.com/AIDASoft/DD4hep/commit/8ba8e004ddafff2ee66ef519aefb1ca7313700f9 on master 
 - Reproduced by: build DD4Hep with any other branch but ROOT master
 - Goal: Make it work also with other ROOT branches

This probably requires changes in ROOT, but I'll report it also here: 
we were building our ROOT 6.20 
https://github.com/cms-sw/cmsdist/pull/5533
which requires also dd4hep to be rebuild since dd4 depends on root. 
The test is showing that there is a file missing namely this one:
https://github.com/root-project/root/commits/56b5c4e58f77a585077ab1e869858b7d93697867/geom/geom/inc/TGeoTessellated.h
which shows this file exists only on root master. 
And if I try building dd4 with root 6.20 well the file is not there

**Comment by andresailer** [comment]
Hmm, this probably means the assumption of #610 that this goes to root 6.20 is not correct, and it only will be there in 6.22

**Comment by petricm** [comment]
But it seems that it's in none of the lcg devset if you look at the build of #610
 - LCG_DEV3 `D++> [DD4hep] ROOT_VERSION: 6.19.01` 
 - LCG_DEV4 `D++> [DD4hep] ROOT_VERSION: 6.20.99`

**Comment by andresailer** [comment]
Dev3 compiles and fails some test because of a wrong path to `/DD4hep/examples/examples/ClientTests/ref/Ref_Tessellated.txt` (two examples)

dev4 fails to compile because of missing TGEoTesselated.h

**Comment by petricm** [comment]
root master has also now been fixed https://github.com/root-project/root/commit/09934e9d6a2a55248efca3ad9659e684850b2426 so that it announces itself as 6.21.1
