### ISSUE TITLE
New version of DD4hep rejects NULL values in XML that worked previously

### ISSUE THREAD

**Issue by cvuosalo** [AIDASoft/DD4hep#628]
A recent version of DD4hep reports errors for NULL values in XML files, while the Dec. 18 version and previous versions processed these files without problem.

 - OS version: CC7
 - Compiler version: GCC 8.2.0
 - Failing DD4hep version: e7882469767472c5d018b74fa13e600e9aba31d3
 - Working DD4hep version: 5bbbb8c86ff764eb452608b5439db90b5e3d2450 (Dec.18 2019)

XML file that uses NULL:
```
<Algorithm name="track:DDTrackerZPosAlgo">
         <rParent name="tibstring0ll:TIBString0LoMin1"/>
         <String name="ChildName" value="tibmodule0b:TIBModule0B"/>
         <Numeric name="StartCopyNo" value="1"/>
         <Numeric name="IncrCopyNo" value="1"/>
         <Vector name="ZPositions" type="numeric" nEntries="3">
             ([Det0Z]+[ShiftDet]), ([Det1Z]+[ShiftDet]),
([Det2Z]+[ShiftDet]) </Vector>
         <Vector name="Rotations" type="string" nEntries="3">
             tibstringpar:NULL, tibstringpar:NULL,
tibstringpar:NULL</Vector>
     </Algorithm>
```
New DD4hep causes this error:
```
ERROR ----> The type std::vector<std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char> >,
std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>,
std::allocator<char> > > > cannot be converted: Data conversion of
[tibstringpar:NULL,tibstringpar:NULL,tibstringpar:NULL] to type
'std::vector<std::__cxx11::basic_string<char, std::char_traits<char>,
std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char> > > >' is not defined.
dd4hep: Error interpreting XML nodes of type <Algorithm/>
```
CMS has used NULL in dozens of files for years, and previous versions of DD4hep have supported it.

**Comment by cvuosalo** [comment]
FYI @ianna

**Comment by petricm** [comment]
@cvuosalo @ianna @mrodozov can you retry with the current master, we have reverted the grammar changes

**Comment by mrodozov** [comment]
It builds with the latest commits

**Comment by petricm** [comment]
@mrodozov just to be clear, also the unit test mentioned passes now?

**Comment by mrodozov** [comment]
@petricm yes, the integration test is passing
https://github.com/cms-sw/cmsdist/pull/5554

**Comment by cvuosalo** [comment]
Just to provide some additional background information: These NULL values are not intended to be interpreted by the parser. They should be treated as strings and just passed on to the algorithm, which knows how to interpret them. The problem occurred when the e788246 version of DD4hep started trying to interpret these NULL values, which are never defined in XML because they are only intended to be used inside an algorithm. With the new version of DD4hep, the problem is solved, and I presume DD4hep is just treating these NULLs as strings.
