### ISSUE TITLE
HTML Manual MathML error 

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#651]
Hello,

I noticed between to different browser (firefox and chrome)  the html DD4hep manual has a MathML bug here:
https://dd4hep.web.cern.ch/dd4hep/usermanuals/DD4hepManual/DD4hepManualch2.html#x3-210002.4

Everything below "Note the macros" is not rendered in the browser because of a MathML error:
```
Error parsing MathML: not well-formed Line Number 1, Column 120:<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mtext class="texttt" mathvariant="monospace"><mstyle&#x00a0; class="text"><mtext&#x00a0;class="texttt"&#x00a0;mathvariant="monospace"&#x00a0;>_U(layer) -----------------------------------------------------------------------------------------------------------------------^
```

The PDF version looks OK.

Cheers

**Comment by andresailer** [comment]
Thanks for reporting the problem. The fixed documentation files are now deployed
