### ISSUE TITLE
Geant4 visualization using Qt GUI and GPS UI

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#655]
Hello, 

How do I get the full Qt GUI user interface when running ddsim? Is it a compile time issue with dd4hep that isn't configured or something in the plugin framework that is missing?

Thanks

**Comment by whit2333** [comment]
I suppose the answer is, "do not use ddsim". Using a python script, I can get a GPS primary generation going only after doing a `/run/beamOn`. It is only after issuing this command that `/gps` appears as a UI command directory. Then I can run my gps configuration macro. 

Is there a reason why the GPS UI commands are registered with geant4 until `/run/beamOn`?

The event generator part of the python script looks like this:
```
  gen = DDG4.GeneratorAction(kernel, "Geant4GeneratorActionInit/GenerationInit")
  kernel.generatorAction().adopt(gen)

  gen = DDG4.GeneratorAction(kernel, "Geant4GeneratorWrapper/GPS")
  gen.Uses = 'G4GeneralParticleSource'
  gen.OutputLevel = Output.INFO
  gen.Mask = 1
  gen.enableUI()
  kernel.generatorAction().adopt(gen)
```

Thanks

**Comment by andresailer** [comment]
So far everybody who tried, had Qt just crash on them, so we force TCSH, if you say this works for you we can add a switch to enable it.

https://github.com/AIDASoft/DD4hep/blob/d3159ed5448f735b8f6b992378de6e4b7b2a345b/DDG4/python/DDSim/DD4hepSimulation.py#L106-L107

You can get the GPS with `--enableG4GPS` in ddsim command line or related value in the steering file.
```
ddsim --compactFile geometry.xml --runType shell --enableG4GPS
```
I get `/gps` right away.

I guess you are missing something in the rest of your script

**Comment by whit2333** [comment]
Thanks for the reply. Sorry for not being clear.

- With `ddsim` I can get the gps to work as expected. However, I could not use the Qt GUI UI. This appears to be a known issue. 
- With a python script I can get the Qt GUI UI working but the GPS, constructed via
```
  gen = DDG4.GeneratorAction(kernel, "Geant4GeneratorWrapper/GPS")
```
does not appear in the UI command tree as expected. Only after after a `/run/beamOn` is executed does it appear. This is puzzling. Maybe this is a bug?

**Comment by andresailer** [comment]
Have  you tried changing ddsim to allow the QT GUI to be used?

**Comment by andresailer** [comment]
Commenting the setting of the environment variable linked above gives me the QT GUI (surprise right there), and /gps is ready to go (--enableG4GPS)
![gps](https://user-images.githubusercontent.com/2115797/78052792-e9df7c80-737f-11ea-98b6-a01f6a1837ef.png)

**Comment by whit2333** [comment]
Thanks. I'll give this a try.
