### ISSUE TITLE
SD Filter name confusion

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#657]
I just wanted to draw your attention to something that seems to behave opposite of what the language indicates.

If I register the "optical photon selector" filter with the SD action which detects photons, PhotoMultiplierSDAction), it does not work as desired. If I register the "optical photon rejector" then the SD action sees and processes the optical photons as desired.

Shouldn't these names/meanings be swapped?

```py
  f2 = DDG4.Filter(kernel, 'ParticleRejectFilter/OpticalPhotonRejector')
  f2.particle = 'opticalphoton'
  f3 = DDG4.Filter(kernel, 'ParticleSelectFilter/OpticalPhotonSelector')
  f3.particle = 'opticalphoton'

  kernel.registerGlobalFilter(f2)
  kernel.registerGlobalFilter(f3)

  seq, act = geant4.setupDetector('ForwardRICH','PhotoMultiplierSDAction')
  act.adopt(f2)
```

**Comment by andresailer** [comment]
Thank you for reporting this problem. I think I fixed it in #660 .
