### ISSUE TITLE
CMake error: Target "" links to target "Vdt::Vdt" but the target was not found.

### ISSUE THREAD

**Issue by rockybala** [AIDASoft/DD4hep#658]
- OS version: e.g. MAC OS 10.15
 - Compiler version: e.g GCC 6.2
 - DD4hep version: https://github.com/AIDASoft/DD4hep
 - Reproduced by: exact steps to reproduce the problem: checkout: git clone https://github.com/AIDASoft/DD4hep, setup environment (Geant, ROOT versions, iLCSoft release), cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DBUILD_TESTING=ON -DGeant4_DIR=$G4INSTALL/lib/Geant4-10.6.1 -DROOT_DIR=$ROOTSYS .. 
 - Goal: A short description of what you are trying to achieve: Trying to build DD4HEP plugin on local laptop.

After cloning, I tried to do cmake into the build directory using the command above, but I am facing this error at cmake: 
```
-------------------------
-- DD4HEP_LIBRARY_PATH= /Users/rbgarg/Applications/DD4hep/build/lib:/lib:/Users/rbgarg/Applications/LCIO/lib:/Users/rbgarg/Applications/geant4.10.06.p01-install/lib:/Users/rbgarg/Applications/root-6.14.06_Build/lib:/usr/local/lib
-- Configuring done
CMake Error at cmake/DD4hepBuild.cmake:620 (add_library):
  Target "DDPythonPlugins" links to target "Vdt::Vdt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  DDCore/CMakeLists.txt:108 (dd4hep_add_plugin)


CMake Error at cmake/DD4hepBuild.cmake:620 (add_library):
  Target "DDPythonPlugins" links to target "Vdt::Vdt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  DDCore/CMakeLists.txt:108 (dd4hep_add_plugin)


CMake Error at cmake/DD4hepBuild.cmake:620 (add_library):
  Target "DDG4Python" links to target "Vdt::Vdt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  DDG4/CMakeLists.txt:71 (dd4hep_add_plugin)


CMake Error at cmake/DD4hepBuild.cmake:620 (add_library):
  Target "DDG4Python" links to target "Vdt::Vdt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  DDG4/CMakeLists.txt:71 (dd4hep_add_plugin)
 
CMake Error at DDG4/CMakeLists.txt:77 (add_executable):
  Target "pyddg4" links to target "Vdt::Vdt" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at DDG4/CMakeLists.txt:64 (add_library):
  Target "DDPython" links to target "Vdt::Vdt" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at DDG4/CMakeLists.txt:64 (add_library):
  Target "DDPython" links to target "Vdt::Vdt" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at DDG4/CMakeLists.txt:77 (add_executable):
  Target "pyddg4" links to target "Vdt::Vdt" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Please suggest a solution.

Thanks

**Comment by andresailer** [comment]
DD4hep doesn't directly depend on Vdt, that dependency is brought in by another package, probably ROOT, 
I think you are using ROOT 6.14, so you are probably running into the bug reported here.
https://root-forum.cern.ch/t/cmake-linking-rdataframe/30944/8

So the solution would be upgrading root, or manually patching the ROOT cmake related file that adds the dependency on Vdt::Vdt, which may or may not work

**Comment by rockybala** [comment]
Hi Andre,

Thanks a lot for the reply!
So which version of ROOT should I upgrade to? Please suggest.

Thanks,
Rocky
________________________________

**Comment by andresailer** [comment]
6.20 should work, that is the latest root release.
We also just merged some major improvements for macOS #654 so if you use the git version of dd4hep, please pull the master branch

**Comment by rockybala** [comment]
Hi Andre,

After updating root, I could successfully do cmake. Thank you so much for this.
But when I try to do make after this, it gives the following errors:
-------------------------------------------------------
Scanning dependencies of target ddeve
Scanning dependencies of target DD4hepGaudiPluginMgr
Scanning dependencies of target DDParsers
[  0%] Building CXX object DDEve/CMakeFiles/ddeve.dir/DDEve/DDEve.cpp.o
[  0%] Building CXX object GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/src/PluginServiceV1.cpp.o
[  0%] Building CXX object GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/src/PluginServiceV2.cpp.o
In file included from /Users/rbgarg/Applications/DD4hep/DDEve/DDEve/DDEve.cpp:19:
/Users/rbgarg/Applications/root-6.20.02/core/rint/inc/TRint.h:25:10: fatal error: 'TApplication.h' file not found
#include "TApplication.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [DDEve/CMakeFiles/ddeve.dir/DDEve/DDEve.cpp.o] Error 1
make[1]: *** [DDEve/CMakeFiles/ddeve.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  0%] Building CXX object GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/interface/DD4hepV1.cpp.o
[  0%] Building CXX object GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/interface/DD4hepV2.cpp.o
[  0%] Building CXX object DDParsers/CMakeFiles/DDParsers.dir/src/Evaluator/setStdMath.cpp.o
[  0%] Building CXX object DDParsers/CMakeFiles/DDParsers.dir/src/Evaluator/Evaluator.cpp.o
[  0%] Building CXX object DDParsers/CMakeFiles/DDParsers.dir/src/Evaluator/ExpressionEvaluator.cpp.o
In file included from /Users/rbgarg/Applications/DD4hep/DDParsers/src/Evaluator/ExpressionEvaluator.cpp:15:
/Users/rbgarg/Applications/DD4hep/DDParsers/include/Evaluator/DD4hepUnits.h:30:10: fatal error: 'RVersion.h' file not found
#include "RVersion.h"
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [DDParsers/CMakeFiles/DDParsers.dir/src/Evaluator/ExpressionEvaluator.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Users/rbgarg/Applications/DD4hep/DDParsers/src/Evaluator/setStdMath.cpp:16:
/Users/rbgarg/Applications/DD4hep/DDParsers/include/Evaluator/DD4hepUnits.h:30:10: fatal error: 'RVersion.h' file not found
#include "RVersion.h"
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [DDParsers/CMakeFiles/DDParsers.dir/src/Evaluator/setStdMath.cpp.o] Error 1
make[1]: *** [DDParsers/CMakeFiles/DDParsers.dir/all] Error 2
[  1%] Linking CXX shared library ../lib/libDD4hepGaudiPluginMgr.dylib
[  1%] Built target DD4hepGaudiPluginMgr
make: *** [all] Error 2
----------------------------------------------------

What possibly could be the error? Please suggest.

Thank you,
Rocky
________________________________

**Comment by andresailer** [comment]
I think you are pointing to the wrong folder for ROOT or your root installation is faulty.
All the root header files should be in a folder "include" and not in folders like "core/rint/inc/"

**Comment by rockybala** [comment]
Hi,

Within the root folder, the header files are inside include directory as expected. Also, $ROOTSYS variable is pointing to correct root build directory which contains the include and bin directories.

To DD4HEP installation, I am providing $ROOTSYS path for root, still it is showing these errors.

Though, I noted one thing that python version 2.7 has been used to build ROOT while cmake is taking python version 3.8 for building DD4HEP. I don't know if that can cause an issue. Please suggest.

Thanks,
Rocky
________________________________
