### ISSUE TITLE
compiler crash gcc48 SL6

### ISSUE THREAD

**Issue by gaede** [AIDASoft/DD4hep#66]
I get a compiler crash when building DD4hep on SL6 w/ gcc48:

In file included from /afs/desy.de/project/ilcsoft/sw/x86_64_gcc48_sl6/HEAD-2016-12-14/DD4hep/HEAD/DDCond/src/plugins/ConditionsPlugins.cpp:22:0:
/afs/desy.de/project/ilcsoft/sw/x86_64_gcc48_sl6/HEAD-2016-12-14/DD4hep/HEAD/DDCore/include/DD4hep/DetectorProcessor.h: At global scope:
/afs/desy.de/project/ilcsoft/sw/x86_64_gcc48_sl6/HEAD-2016-12-14/DD4hep/HEAD/DDCore/include/DD4hep/DetectorProcessor.h:75:15: internal compiler error: in use_thunk, at cp/method.c:338
       virtual ~DetElementProcessor() = default;
               ^
0x5cd334 use_thunk(tree_node*, bool)
	/build/vdiez/gcc-4.8.1/gcc/cp/method.c:338
0x5d823c emit_associated_thunks(tree_node*)
	/build/vdiez/gcc-4.8.1/gcc/cp/semantics.c:3763
0x5d84f7 expand_or_defer_fn(tree_node*)
	/build/vdiez/gcc-4.8.1/gcc/cp/semantics.c:3890
0x5efe55 maybe_clone_body(tree_node*)
	/build/vdiez/gcc-4.8.1/gcc/cp/optimize.c:428
0x5d82ed expand_or_defer_fn_1(tree_node*)
	/build/vdiez/gcc-4.8.1/gcc/cp/semantics.c:3814
0x5d84c8 expand_or_defer_fn(tree_node*)
	/build/vdiez/gcc-4.8.1/gcc/cp/semantics.c:3884
0x5ce49f synthesize_method(tree_node*)
	/build/vdiez/gcc-4.8.1/gcc/cp/method.c:809
0x57af5a mark_used(tree_node*)
	/build/vdiez/gcc-4.8.1/gcc/cp/decl2.c:4677
0x527c7c build_over_call
	/build/vdiez/gcc-4.8.1/gcc/cp/call.c:7055
0x525128 build_new_method_call_1
	/build/vdiez/gcc-4.8.1/gcc/cp/call.c:7715
0x525128 build_new_method_call(tree_node*, tree_node*, vec<tree_node*, va_gc, vl_embed>**, tree_node*, int, tree_node**, int)
	/build/vdiez/gcc-4.8.1/gcc/cp/call.c:7785
0x5259ce build_special_member_call(tree_node*, tree_node*, vec<tree_node*, va_gc, vl_embed>**, tree_node*, int, int)
	/build/vdiez/gcc-4.8.1/gcc/cp/call.c:7352
0x5c5baf expand_cleanup_for_base
	/build/vdiez/gcc-4.8.1/gcc/cp/init.c:1217
0x5ca0a1 expand_cleanup_for_base
	/build/vdiez/gcc-4.8.1/gcc/cp/init.c:1112
0x5ca0a1 emit_mem_initializers(tree_node*)
	/build/vdiez/gcc-4.8.1/gcc/cp/init.c:1097
0x5a1f2c cp_parser_mem_initializer_list
	/build/vdiez/gcc-4.8.1/gcc/cp/parser.c:11731
0x5a1f2c cp_parser_ctor_initializer_opt
	/build/vdiez/gcc-4.8.1/gcc/cp/parser.c:11642
0x5a1f2c cp_parser_ctor_initializer_opt_and_function_body
	/build/vdiez/gcc-4.8.1/gcc/cp/parser.c:17848
0x5a257f cp_parser_function_definition_after_declarator
	/build/vdiez/gcc-4.8.1/gcc/cp/parser.c:21843
0x58d954 cp_parser_late_parsing_for_member
	/build/vdiez/gcc-4.8.1/gcc/cp/parser.c:22484
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
make[2]: *** [DDCond/CMakeFiles/DDCondPlugins.dir/src/plugins/ConditionsPlugins.cpp.o] Error 1
make[1]: *** [DDCond/CMakeFiles/DDCondPlugins.dir/all] Error 2
make: *** [all] Error 2

**Comment by petricm** [comment]
This is exactly the same what Shaojun reported in the mail exchange between you, me, @MarkusFrankATcernch , @andresailer on 5 December. The title of the e-mail thread is "DESY AFS nightly build failed" and the conclusion is that this is gcc(4.8.1) bug(Bug 59760).
