### ISSUE TITLE
DD4HEP issue with make

### ISSUE THREAD

**Issue by rockybala** [AIDASoft/DD4hep#661]
Dear Experts,

Thank you so much for the support related to my last issue. Due to your help, I could resolve it. Now I am facing another issue. Kindly help me in figuring this out. Here are the details:

OS version: e.g. MAC OS catalina 10.15
Compiler version: e.g GCC 6.2
DD4hep version: master branch of https://github.com/AIDASoft/DD4hep
Reproduced by: exact steps to reproduce the problem: checkout: git clone https://github.com/AIDASoft/DD4hep, setup environment (Geant, ROOT versions, iLCSoft release), cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DBUILD_TESTING=ON -DGeant4_DIR=$G4INSTALL/lib/Geant4-10.6.1 -DROOT_DIR=$ROOTSYS .. , make 
Goal: A short description of what you are trying to achieve: Trying to build DD4HEP plugin on local laptop. 

I can successfully do a cmake but when I try to do make, it gives me the following errors:
```
[  0%] Building CXX object DDEve/CMakeFiles/ddeve.dir/DDEve/DDEve.cpp.o
[  1%] Built target DD4hepGaudiPluginMgr
[  1%] Built target listcomponents
In file included from /Users/rbgarg/Applications/DD4HEP/DDEve/DDEve/DDEve.cpp:19:
/Users/rbgarg/Applications/root-6.20.02/core/rint/inc/TRint.h:25:10: fatal error: 'TApplication.h' file not found
#include "TApplication.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [DDEve/CMakeFiles/ddeve.dir/DDEve/DDEve.cpp.o] Error 1
make[1]: *** [DDEve/CMakeFiles/ddeve.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Building CXX object DDParsers/CMakeFiles/DDParsers.dir/src/Evaluator/ExpressionEvaluator.cpp.o
[  2%] Building CXX object DDParsers/CMakeFiles/DDParsers.dir/src/Evaluator/setSystemOfUnits.cpp.o
[  2%] Building CXX object DDParsers/CMakeFiles/DDParsers.dir/src/Evaluator/setStdMath.cpp.o
[  2%] Building CXX object DDParsers/CMakeFiles/DDParsers.dir/src/Spirit/Evaluators.cpp.o
[  2%] Building CXX object DDParsers/CMakeFiles/DDParsers.dir/src/Spirit/ExtraParsers.cpp.o
[  2%] Building CXX object DDParsers/CMakeFiles/DDParsers.dir/src/Spirit/ParserStandardList_Mapint_bool.cpp.o
[  2%] Building CXX object DDParsers/CMakeFiles/DDParsers.dir/src/Spirit/ParserStandardList_Mapint_double.cpp.o
[  2%] Building CXX object DDParsers/CMakeFiles/DDParsers.dir/src/Spirit/ParserStandardList_Mapint_float.cpp.o
[  2%] Building CXX object DDParsers/CMakeFiles/DDParsers.dir/src/Spirit/ParserStandardList_Mapint_long.cpp.o
[  3%] Building CXX object DDParsers/CMakeFiles/DDParsers.dir/src/Spirit/ParserStandardList_Mapint_int.cpp.o
[  3%] Building CXX object DDParsers/CMakeFiles/DDParsers.dir/src/Spirit/ParserStandardList_Mapint_string.cpp.o
[  3%] Building CXX object DDParsers/CMakeFiles/DDParsers.dir/src/Spirit/ParserStandardList_Mapped_bool.cpp.o
In file included from /Users/rbgarg/Applications/DD4HEP/DDParsers/src/Evaluator/setStdMath.cpp:16:
/Users/rbgarg/Applications/DD4HEP/DDParsers/include/Evaluator/DD4hepUnits.h:30:10: fatal error: 'RVersion.h' file not found
#include "RVersion.h"
         ^~~~~~~~~~~~
In file included from /Users/rbgarg/Applications/DD4HEP/DDParsers/src/Evaluator/ExpressionEvaluator.cpp:15:
/Users/rbgarg/Applications/DD4HEP/DDParsers/include/Evaluator/DD4hepUnits.h:30:10: fatal error: 'RVersion.h' file not found
#include "RVersion.h"
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [DDParsers/CMakeFiles/DDParsers.dir/src/Evaluator/ExpressionEvaluator.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [DDParsers/CMakeFiles/DDParsers.dir/src/Evaluator/setStdMath.cpp.o] Error 1
make[1]: *** [DDParsers/CMakeFiles/DDParsers.dir/all] Error 2
make: *** [all] Error 2
```

I don't understand why it is not been able to find the root header files. The $ROOTSYS variable is pointing to correct root build directory (which contains all the header files in include dir). Please suggest a solution.

Thanks,
Rocky

**Comment by MarkusFrankATcernch** [comment]
Did you source:
bin/thisdd4hep.sh after cmake and before make ?
I think this is the reason ROOT is not found properly.

Markus

**Comment by rockybala** [comment]
Dear Markus,

I was not doing source bin/thisdd4hep.sh earlier.
But now I tried with this but I am still getting the same error.

Can a python version cause this issue? I used python3.8 to build ROOT and now using the same version to build dd4hep. Please suggest.

Thank you,
Rocky
________________________________

**Comment by andresailer** [comment]
* Please post the full output of the cmake command (attach a log file) , you need to create a new build directory or delete the existing one
* Please post the value of $ROOTSYS
* Please post the result of `find $ROOTSYS -name TApplication.h`
* Please post the result of `make VERBOSE=1 -j1` (attach a log file)

I don't see how the different python version can cause this error. It can certainly cause other errors.

**Comment by rockybala** [comment]
Dear Andre,

Please find the output of cmake command attached in the log file.
* cmake command used is: cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=ON -DBUILD_TESTING=ON -DGeant4_DIR=$G4INSTALL/lib/Geant4-10.6.1 -DROOT_DIR=$ROOTSYS ..

* echo $G4INSTALL: /Users/rbgarg/Applications/geant4.10.06.p01-install

* echo $ROOTSYS: /Users/rbgarg/Applications/root-6.20.02-build

* find $ROOTSYS -name TApplication.h: /Users/rbgarg/Applications/root-6.20.02-build/include/TApplication.h

* make VERBOSE=1 -j1 output attached in log file.

Thank you,
Rocky
________________________________

**Comment by andresailer** [comment]
For some reason separate include folders for root are added, which are pointing to the build directory.
Can you please rerun cmake with the addition of the argument `  -DDD4HEP_DEBUG_CMAKE=ON `
and attach the log file?

**Comment by rockybala** [comment]
Hi,

Please find the updated log of cmake command attached.

Thanks,
Rocky
________________________________

**Comment by andresailer** [comment]
It does seem to find the correct ROOT folder.
Can you please run cmake again, adding the `--trace` option and
```
cmake ... --trace  .... 2> dump  # redirecting the output to the file dump
grep ROOTConfig.cmake dump  # looking for which ROOTConfig.cmake file it is using
grep ROOTConfig-targets.cmake dump
``
And making sure the ROOTConfig.cmake and ROOTConfig-targets.cmake file are really in the "/Users/rbgarg/Applications/root-6.20.02-build/" folder?

And then attach the ROOTConfig-targets.cmake file, please?

Also what is your version of cmake?

Is the root-6.20.02-build folder the folder where you compiled root, or where it was installed into?

**Comment by rockybala** [comment]
Hi,

Yes, ROOTConfig.cmake and ROOTConfig-targets.cmake files are in '/Users/rbgarg/Applications/root-6.20.02-build' folder. Please find the attached ROOTConfig-targets.cmake file with the mail.

I am using cmake version 3.17.
yes, root-6.20.02-build is the folder where I complied and installed root.


Thank you,
Rocky

________________________________

**Comment by andresailer** [comment]
Thanks, but there was not attached file in the last email.

**Comment by rockybala** [comment]
Hi,

I am sorry. It is showing me attached.
Anyways, I have attached it again.
Please let me know if you can see it or not.

Thanks,
Rocky
________________________________

**Comment by andresailer** [comment]
Still nothing there, probably github filtering the file.
Please make a "gist" https://gist.github.com/

**Comment by rockybala** [comment]
Hi,

I have changed the extension to .txt. Let me know if you can open it now.
I have also created a gist at the path: https://gist.github.com/rockybala/fdc84b74967a28d1c47bd8f5caad452c

Thanks,
Rocky
________________________________

**Comment by andresailer** [comment]
Yes, I can see the file now:
There are lines like this:
```
  INTERFACE_INCLUDE_DIRECTORIES "/Users/rbgarg/Applications/root-6.20.02/proof/proof/inc"
```

They should all look like this
```
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
```

Can you use the binaries provided by root?
https://root.cern/content/release-62004 ?

Or try installing root into a separate folder instead of in the build folder.

If the problem persists you need to ask the ROOT developers for help.

**Comment by rockybala** [comment]
Ok, I try that.

Thanks a lot for your co-operation.

Rocky
________________________________

**Comment by rockybala** [comment]
Hi Andre,

I could build the DD4HEP plugin using the root binary distribution.

Thanks a lot for your suggestions and help.

Rocky
________________________________

**Comment by andresailer** [comment]
Hi Rocky,

Great! Thanks for sticking with me during the debugging :)
