### ISSUE TITLE
Eve propagator Lorentz force sign problem

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#664]
Hello,

I have just started to use ddeve and I was wondering if the sign convention of TEvePropagator was addressed/corrected for? I am still looking into this but though I might ask before digging in. 

Here an old post from when I stumbled upon it:
https://root-forum.cern.ch/t/eve-sign-of-charge-or-field-wrong/13706

Cheers

**Comment by MarkusFrankATcernch** [comment]
Hi Whitney,

DDeve is a very primitive display. It should mainly display Geant4 energy deposits to
somehow verify that the simulation works. As Matevz already mentioned, the sign problem
cannot be really addressed here easily.
Is there anything which can here be done from the dd4hep side?
A priori the remaining lifetime of DDeve is limited to the lifetime of TEve.

Cheers,

Markus

**Comment by whit2333** [comment]
Hi Markus,

I just wanted to point out that the TEve propagator does not match geant4 because of this sign problem. In the past, I had to compensate by swapping the charge of particles before using teve, otherwise, the curvature was wrong. If going backwards (in time) then I think it should work. 

I don't plan on relying on ddeve so it is not a major issue. I'll close with this comment. 

Cheers
