### ISSUE TITLE
Detector library load path problem 

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#665]
Hello, 

When loading from a compiled root script the detector library under development is not found. In this case we are developing a detector called 
`ScintillatingTileEndcapHCAL`, and it is successfully found and run with ddsim. We are doing development of [NPdet](https://eicweb.phy.anl.gov/EIC/NPDet) within a singularity container which also contains a recent version. But when going to load the detector from a root script, dd4hep appears to not find the local build of the detector library. 

The root script error:
```
Info in <TGeoManager::SetTopVolume>: Top volume is world_volume. Master volume is world_volume
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
Compact          ERROR FAILED     subdetector:ForwardHCAL of type ScintillatingTileEndcapHCAL [sensitive]
PluginService    ERROR Factory requested: ScintillatingTileEndcapHCAL (N10__cxxabiv120__function_type_infoE) :bad any_cast
PluginService    ERROR Stub is invalid!
Compact          ERROR ++ FAILED    to convert subdetector: ForwardHCAL: Failed to execute subdetector creation plugin. No factory with name Create(ScintillatingTileEndcapHCAL) for type ScintillatingTileEndcapHCAL found.
		Please check library load path and/or plugin factory name.

**************************************************** 
*  A runtime error has occured :                     
*    Failed to execute subdetector creation plugin. 		No factory with name Create(ScintillatingTileEndcapHCAL) for type ScintillatingTileEndcapHCAL found.
		Please check library load path and/or plugin factory name.
*  the program will have to be terminated - sorry.   
**************************************************** 
```

I installed NPdet to /home/ANL/warmstrong/stow/development have set the env variables:
```
warmstrong@eic:~/temp/NPDet/src/GenericDetectors/calorimeters/compact\#singularity$ echo $LD_LIBRARY_PATH 
/home/ANL/warmstrong/stow/development/lib:/home/ANL/warmstrong/stow/development/lib64:/home/ANL/warmstrong/lib:/home/ANL/warmstrong/lib64:/usr/local/lib:/usr/local/lib64:/home/ANL/warmstrong/.local/lib:/usr/local/lib::/usr/local/lib:/usr/local/lib:/usr/local/lib:/usr/local/epics/base/lib/linux-x86_64:/usr/local/epics/lib::/.singularity.d/libs:/usr/local/lib:/usr/lib/x86_64-linux-gnu
warmstrong@eic:~/temp/NPDet/src/GenericDetectors/calorimeters/compact\#singularity$ echo $PATH 
/home/ANL/warmstrong/stow/development/bin:/home/ANL/warmstrong/bin:/usr/local/bin:/home/ANL/warmstrong/.local/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/local/epics/base/bin/linux-x86_64:/usr/local/epics/bin:/usr/loca/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
```
Even tried setting DD4hep_LIBRARY_PATH

```
warmstrong@eic:~/temp/NPDet/src/GenericDetectors/calorimeters/compact\#singularity$ ls /home/ANL/warmstrong/stow/development/lib/
G__DDG4_PIDsdet_rdict.pcm   libDDG4_PIDsdet.so          libJLEIC.components  libSoLID.components
NPDet                       libGenDetectors.components  libJLEIC.so          libSoLID.so
SiEIC                       libGenDetectors.so          libSiEIC.components  libeRHIC.components
libDDG4_PIDsdet.components  libGenDigi.so               libSiEIC.so          libeRHIC.so
```

The libraries are installed (as expected because geant4 and other tools appear to run just fine). 
```
grep "ScintillatingTileEndcapHCAL" /home/ANL/warmstrong/stow/development/lib/libGenDetectors*           
/home/ANL/warmstrong/stow/development/lib/libGenDetectors.components:v2::libGenDetectors.so:ScintillatingTileEndcapHCAL
Binary file /home/ANL/warmstrong/stow/development/lib/libGenDetectors.so matches
```

I am concerned that dd4hep might be finding the npdet version installed with the same prefix as dd4hep and root:
```
warmstrong@eic:~/temp/NPDet/src/GenericDetectors/calorimeters/compact\#singularity$ ls -lrth /usr/local/lib/libGenDetectors.*
-rw-r--r--. 1 root root 11M Apr  4 20:36 /usr/local/lib/libGenDetectors.so
-rw-r--r--. 1 root root 774 Apr  4 20:36 /usr/local/lib/libGenDetectors.components
warmstrong@eic:~/temp/NPDet/src/GenericDetectors/calorimeters/compact\#singularity$ grep "ScintillatingTileEndcapHCAL" /usr/local/lib/libGenDetectors.*
warmstrong@eic:~/temp/NPDet/src/GenericDetectors/calorimeters/compact\#singularity$ 

```
This version is of course missing our new plugin that we are trying to develop.

 - OS version: Ubuntu 18.04 (container)
 - Compiler version: GCC 9.1
 - DD4hep version: master
 - Reproduced by: see above , ROOT 6.18.02 
 - Goal: Make dd4hep find local user build of detector library instead of system version from within a root script.  

I am not familiar with how the `.components` library/plugin lookup mechanism works. Is this documented anywhere?

Cheers,
Whit

**Comment by MarkusFrankATcernch** [comment]
This looks to me like:
- The LD_LIBRARY_PATH is wrong (Yes. I have read that you checked this!)
- The components file does not contain this factory (Please check. We have seen sometimes listcomponents to not work properly)
- you declared the factory somehow incorrectly.

My favorite is the second point. The components files are plain text and lists all factories contained in one binary. You should check if the name ScintillatingTileEndcapHCAL apparea in the components file.

**Comment by andresailer** [comment]
@MarkusFrankATcernch 
He did check the components file (https://github.com/AIDASoft/DD4hep/issues/665#issue-599896045)
```
grep "ScintillatingTileEndcapHCAL" /home/ANL/warmstrong/stow/development/lib/libGenDetectors*           
/home/ANL/warmstrong/stow/development/lib/libGenDetectors.components:v2::libGenDetectors.so:ScintillatingTileEndcapHCAL
Binary file /home/ANL/warmstrong/stow/development/lib/libGenDetectors.so matches
```
And if the new geometry works with ddsim then it should all be set correctly.


@whit2333 

There is some documentation for the pluginservice: https://github.com/AIDASoft/DD4hep/tree/master/GaudiPluginService/doc

Can you give a link to your root script, and how you compile and link it?
If the plugin handling works correctly with ddsim, for example, it could be that with your script the libGenDetectors.so is already loaded from the wrong location before the plugin service tries to load it again. For example if your script is linked against the old libGenDetectors.
You could run the command with `strace -f theCommand` and see what libraries are loaded.

**Comment by andresailer** [comment]
I guess we can close this issue?
Though it is not clear to me why you explicitly load libGenDetectors at the beginning of your script, as the dd4hep pluginmanager will do it on demand.
