### ISSUE TITLE
TGeoPgon memory leak

### ISSUE THREAD

**Issue by andresailer** [AIDASoft/DD4hep#666]
with anything above or equal to root 6.11.02 this leaks memory

https://github.com/AIDASoft/DD4hep/blob/cc4491b901a2c867be2b47bc498d9b8d816b440a/DDCore/src/Shapes.cpp#L409

https://sft.its.cern.ch/jira/browse/ROOT-10710

Only noticing this now, when we switched the valgrind checks to lcg 97 / root 6.20

**Comment by petricm** [comment]
This is resolved in ROOT upstream and will be released in 6.22
