### ISSUE TITLE
TBB not found in CI builds 

### ISSUE THREAD

**Issue by vvolkl** [AIDASoft/DD4hep#667]
Intel tbb (used in DDigi) should be included in the LCG releases, but it seems it is not picked up in any of the builds: https://travis-ci.org/github/AIDASoft/DD4hep/jobs/678167797#L1056

**Comment by vvolkl** [comment]
TBB 2020/02 on arch linux  is picked up correctly.

**Comment by petricm** [comment]
Here the explanation for the views
https://sft.its.cern.ch/jira/browse/SPI-1600
I don't know if we should meke it dependant on `CMakeTools`

**Comment by petricm** [comment]
So what should we do here? Place a copy of `FindTBB` in the source or any other suggestions?

**Comment by andresailer** [comment]
After #613 using FindTBB is not going to work without some additional changes in the cmake.
Also CmakeTools contains FindCLHEP (for example) so the cmaketools shouldn't leak into the CMAKE_MODULE_PATH we use in the rest of the cmake.

**Comment by andresailer** [comment]
@vvolkl how is TBB found on your arch linux? Is this compiled by hand?

**Comment by vvolkl** [comment]
No, I use the system package: https://www.archlinux.org/packages/extra/x86_64/intel-tbb/
might be the version difference 2020/1 vs 2020/2?

**Comment by andresailer** [comment]
The arch package includes `usr/lib/cmake/TBB/TBBConfig.cmake`

**Comment by andresailer** [comment]
new LCG installations will contain TBBConfig.cmake
