### ISSUE TITLE
Ignore default element table in DD4hep --> Work for Frank G.

### ISSUE THREAD

**Issue by MarkusFrankATcernch** [AIDASoft/DD4hep#69]
Hi Frank,

the following is for you....the failing ones are your tests.

Cheers, Markus
-------------------------------------------------------
If the ROOT element table is supposed to be ignored, in DDcore/src/LCDDImp.cpp (line 121)
the following block must be enabled and the failing examples must be fixed, because they
rely on the existence of he default table:
#if 0
    TGeoElementTable*	table = m_manager->GetElementTable();
    table->TGeoElementTable::~TGeoElementTable();
    new(table) TGeoElementTable();
    // This will initialize the table without filling:
    table->AddElement("VACUUM","VACUUM"   ,0,   0, 0.0);
    table->Print();
#endif

**Comment by petricm** [comment]
Can you please produce a dump from the table. I think the contents in itself are ok, we just don't want that values to change.

**Comment by petricm** [comment]
Just for future reference: use [this plugin](https://github.com/AIDASoft/DD4hep/pull/70) to create the new table

**Comment by gaede** [comment]
Moin Markus,
I get:

~~~
97% tests passed, 4 tests failed out of 115

Total Test time (real) = 463.28 sec

The following tests FAILED:
	 24 - t_ClientTests_DumpElements (Failed)
	 42 - t_ClientTests_MaterialTester_converter_lcdd (OTHER_FAULT)
	 43 - t_ClientTests_MaterialTester_converter_gdml (OTHER_FAULT)
	 44 - t_ClientTests_MaterialTester_converter_vis (OTHER_FAULT)

~~~
None of the above are my tests, really !?
Which tests fail for you ?
Cheers, Frank.

**Comment by MarkusFrankATcernch** [comment]
One or two of the basic dd4hep tests already fail, because they try to accsess elements.
test_units or so.

Gitlab then stops and does not even continue any further....

Markus

________________________________

**Comment by gaede** [comment]
Ok, basic tests are fixed with https://github.com/AIDASoft/DD4hep/pull/71. Now we are back to the above example tests failing.
