### ISSUE TITLE
Does Segmentation limit G4Step?

### ISSUE THREAD

**Issue by VyacheslavLvovichIvanov** [AIDASoft/DD4hep#693]
Hi, I'm doing the simulation for the drift chamber with the stereolayers for the charm-tau factory project.

Currently I use only one sensitive volume for the whole gas volume of the chamber. The tracker hit-to-wire association (cell_id calculation) is fully done via the segmentation.

It is well known (https://indico.cern.ch/event/294651/sessions/55918/attachments/552022/760640/UserActions.pdf, sl. 16) that GEANT4 cuts the G4Step at the border of the sensitive volume.

Do I understand correctly that in the calculation of the cell_id through the segmentation this cut of the tracking step doesn't happen, but the cell_id is calculated still on the base of the hit's PreStepPoint?

If "yes", this leads to the loss of the hits with PreStepPoint and PostStepPoint lying in different cells of the chamber.

**Comment by MarkusFrankATcernch** [comment]
Hi Vyachin addition eslav,

The segmentation is not a Geant4 concept. You have to assign a special region with region parameters to this sub-detector. 
Then you can set the step length based on this subdetector. If you  in addition need a different interpretation of the stepping callbacks in the sensitive detector you can supply  a specialized factory, which supplies this functionality.

**Comment by VyacheslavLvovichIvanov** [comment]
Thanks for the fast responce,

I've already set the UserLimit for the tracking step to the drift chamber region to be 2 mm, but compared to the cell size of 8 mm it is still not very small, this may cause inacurracy of simulation. The further lowering of max step size may lead to the increase in simulation time...

Okay, I figured out how it works, thanks for your answer.

**Comment by MarkusFrankATcernch** [comment]
@VyacheslavLvovichIvanov 
If the answer above satisfies your question, could you please close the issue?
Otherwise, please tell me how I can provide further help.

Cheers,
Markus
