### ISSUE TITLE
DDRec - surfaces

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#694]
Hello,

What is the status of the surfaces? The DDRec manual is a bit dated (2014)
https://dd4hep.web.cern.ch/dd4hep/usermanuals/DDRecManual/DDRecManual.html
Also, is there a strong argument for these components being separate manuals?

Many of the ideas are duplicated in Acts. https://github.com/acts-project/acts

**Comment by gaede** [comment]
The surfaces are still actively used in iLCSoft, i.e. track reconstruction for ILC and CLIC. Some of the ideas have indeed be duplicated in ACTS. In the mid-term we want to see, if and how these two slightly different approached can be merged or unified.
