### ISSUE TITLE
DD4HEP building issue

### ISSUE THREAD

**Issue by jhaimber** [AIDASoft/DD4hep#695]
[CMakeOutput.log](https://github.com/AIDASoft/DD4hep/files/5092188/CMakeOutput.log)
[CMakeError.log](https://github.com/AIDASoft/DD4hep/files/5092189/CMakeError.log)

!!!IMPORTANT!!!: To facilitate faster and easier response to your issue please provide in addition to the description of the issue also the following information

 - OS version: Centos7
 - Compiler version: GCC 8.3.1
 - DD4hep version: v01-13-01
 - Geant4:10.6.2
 -  cmake: 3.16.2
 - Boost: 1.72
 - ROOT:  6.22/01
 - Xerces: 3.2.3

 - Reproduced by:
  source thisroot.sh and geant4.sh
  cmake -DDD4HEP_USE_XERCESC=ON -DDD4HEP_USE_GEANT4=ON -DCMAKE_INSTALL_PREFIX=/data/software/DD4hep/install -DXERCESC_ROOT_DIR=/data/software/Xerces/xerces-c-3.2.3 -DGeant4_DIR=/data/software/Geant4/geant4.10.06.p2-install/lib64/Geant4-10.6.2 -DBoost_INCLUDE_DIR=/data/software/Boost/boost_1_72_0/install/include -DROOT_DIR=$SYSROOT ..
make

Error while building:
[ 84%] Generating libDDG4Python.components
 input_line_1:1:2: fatal error: malformed or corrupted AST file:'could not decompress embedded file contents: zlib error:STREAM_ERROR'
 #include <new>
 input_line_1:1:2: note: after modifying system headers, please delete the module cache at '/data/software/Root/root_install/lib'
 /bin/sh: line 1: 13089 Segmentation fault   (core dumped) 
 LD_LIBRARY_PATH=/data/software/DD4hep/build/lib:/data/software/DD4hep/build/lib:/data/software/Geant4/geant4.10.06.p02-install/lib64:/data/software/Root/root_install/lib:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/usr/lib/dyninst:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/usr/local/lib64 
 /data/software/DD4hep/build/bin/listcomponents -o libDDG4Python.components libDDG4Python.so.1.13
 make[2]: *** 
 [DDG4/CMakeFiles/Components_DDG4Python.dir/build.make:61: DDG4/libDDG4Python.components] Error 139
 make[1]: *** [CMakeFiles/Makefile2:2389: 
 DDG4/CMakeFiles/Components_DDG4Python.dir/all] Error 2
 make: *** [Makefile:141: all] Error 2

The error seems to occure, when the library "libDDG4Python.so.1.13" is loaded in the script listcomponents. Also using  Boost 1.73 leads also to problems.

**Comment by andresailer** [comment]
Please see this comment with a possible solution
https://github.com/AIDASoft/DD4hep/issues/567#issuecomment-565156866

**Comment by jhaimber** [comment]
Thanks. This fixed the issue.
