### ISSUE TITLE
Geant4Particle charge and hepmc

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#696]
I notice the charge was not saved with hepmc input. I guess the charge needs to be deduced from the PID?
https://github.com/AIDASoft/DD4hep/blob/c386c29785285e9facd191f3f3179f3952a83d37/DDG4/hepmc/HepMC3EventReader.cpp#L96

Which also brings up the question of `char` being used for charge and `_spare`
https://github.com/AIDASoft/DD4hep/blob/c386c29785285e9facd191f3f3179f3952a83d37/DDG4/include/DDG4/Geant4Particle.h#L116-L117
https://github.com/AIDASoft/DD4hep/blob/master/DDG4/include/DDG4/Geant4Particle.h#L116

Why is that? Some alignment magic?

Cheers

**Comment by andresailer** [comment]
1) Have you had trouble with the simulation? When I look at the output files after simulation hepmc3 files I see the proper charge for particles assigned, which lead me to believe that geant4 will just pick it up from the PDG code. I forgot to update the comment.

2) yes, alignment.

**Comment by whit2333** [comment]
Thanks. I am using my own implementation of a Geant4OutputAction seems to not copy the charge over. Not sure what is going on. https://eicweb.phy.anl.gov/EIC/NPDet/-/blob/master/src/dd4pod/plugins/Geant4Output2Podio.cxx#L197
When I print out the charge before this line it returns zero. Perhaps I am using the particle map incorrectly?

**Comment by andresailer** [comment]
Maybe I was fooled by this
https://github.com/AIDASoft/DD4hep/blob/c386c29785285e9facd191f3f3179f3952a83d37/DDG4/lcio/Geant4Output2LCIO.cpp#L296
and all the particles are neutral during simulation
:sob:

**Comment by andresailer** [comment]
Looking at the  geant4 vertex information I see for example (ddsim --output.inputStage=VERBOSE prints it)
```
>>>> Daughters
==== PDGcode 20213  Particle name a1(1260)+
 Assigned charge : 1
     Momentum ( -2.0279700338302[GeV/c], 14.110335536923[GeV/c], 49.917952295205[GeV/c] )
     kinetic Energy : 50.620440584804 [GeV]
     Mass : 1.3096210368538 [GeV]
     Polarization ( 0, 0, 0 )
     Weight : 1
     PreAssigned proper decay time : 0 [ns]
>>>> Daughters
```
So there is non-zero charge.
I would appreciate if you could confirm the charged particles are treated in geant4 the right way or not.

**Comment by whit2333** [comment]
I see the same thing.
```
==== PDGcode -13  Particle name mu+
 Assigned charge : 1                                                                                                                                                                                               
     Momentum ( -0.64544231373708[GeV/c], -0.16154174241274[GeV/c], 3.6938916104948[GeV/c] )
     kinetic Energy : 3.6491642804751 [GeV]                                                                                                                                                                        
     Mass : 0.10565800000001 [GeV]
     Polarization ( 0, 0, 0 )
     Weight : 1                   
==== PDGcode 13  Particle name mu-      
 Assigned charge : -1
     Momentum ( 1.2720142125642[GeV/c], -0.58295166481152[GeV/c], -2.9616531169062[GeV/c] )
     kinetic Energy : 3.1715978030029 [GeV]
     Mass : 0.10565799999995 [GeV]          
     Polarization ( 0, 0, 0 )
     Weight : 1 
```

I suspect it has something to do with the use of `char` but I do not know where the problem comes up. This is not critically important. I'll continue to look into it and let you know what I find.

**Comment by petricm** [comment]
Can we close this?

**Comment by petricm** [comment]
@whit2333 is this ok now?

**Comment by petricm** [comment]
Please reopen if there is a problem
