### ISSUE TITLE
TruncatedTube zHalf() accessor is inconsistent with the rest dZ()

### ISSUE THREAD

**Issue by ianna** [AIDASoft/DD4hep#714]
It's a bit confusing having a `zHalf` for one shape and `dZ` for the rest. Shouldn't it be one or the other for all?

**Comment by petricm** [comment]
I think this comes from the fact that `TruncatedTube` is a CMS shape from DD and was implemented and along the lines of the original CMS DD implementation.

**Comment by ianna** [comment]
> I think this comes from the fact that `TruncatedTube` is a CMS shape from DD and was implemented and along the lines of the original CMS DD implementation.

Yes, but wouldn't someone get confused by it? Also, there are `Box::x`,  `Box::y` and `Box::z` that return half lengths... Shouldn't we call all half `Z`s as `halfZ` and not `dZ`? I think, we are the first to use this API ;-)

**Comment by petricm** [comment]
As you are probably the only user, we can change this. Will you be fine if we break the API for TruncatedTube? Or do you want an additional assessor `dz`?

**Comment by ianna** [comment]
> As you are probably the only user, we can change this. Will you be fine if we break the API for TruncatedTube? Or do you want an additional assessor `dz`?

Yes, it's ok to break the API for TruncatedTube - to keep it clean  ;-)
Since you are at it, I've opened a similar issue about missing dZ in Trap:
https://github.com/AIDASoft/DD4hep/issues/713 

Could it be fixed together, please?

**Comment by MarkusFrankATcernch** [comment]
Sorry, I only saw this discussion now. 
Do I understand correctly: all zHalf should be replaced by dZ, which is the TGeo convention?

**Comment by ianna** [comment]
> Sorry, I only saw this discussion now.
> Do I understand correctly: all zHalf should be replaced by dZ, which is the TGeo convention?

either all `zHalf` should be replaced by `dZ` or all `dZ` should be replaced by `zHalf` - either is fine with me :-)

**Comment by MarkusFrankATcernch** [comment]
I would prefer to stay with dZ since TGeo uses dZ ...
