### ISSUE TITLE
Request: Make Event Display module optional

### ISSUE THREAD

**Issue by tomeichlersmith** [AIDASoft/DD4hep#721]
I am building DD4hep into a container that my group uses to develop and run our simulation software. In order to help lighten the (already very large) container, I have ommitted a lot of GUI-related packages, specifically `ROOT::Eve` is ommitted. This means that I can't compile DD4hep within the container without some on-the-fly changes to the `cmake` ecosystem.

 - OS version: Ubuntu 18.04 server
 - Compiler version: GCC 7.5.0
 - DD4hep version: `master` branch
 - Reproduced by: Hmmm... this is difficult without re-building the container yourself. You can see an example of a failed build [here](https://github.com/LDMX-Software/docker/runs/1220932441?check_suite_focus=true). *Beware*: This log is very long and will take a few minutes to scroll to the bottom.
 - Input: The `bash` script I use to build dd4hep during the container build is [here](https://github.com/LDMX-Software/docker/blob/iss31/install-scripts/install-dd4hep.sh).
 - Output: The `cmake` error output during the build:
```
#10 13.41 -- |> Building UtilityApps
#10 13.41 -- |++++> Building dictionary ... G__eve
#10 13.42 -- 
#10 13.42 -- -------------------------------------------------------------------------------
#10 13.42 -- Change values with: cmake -D<Variable>=<Value>
#10 13.42 -- CMAKE_INSTALL_PREFIX = /deps/dd4hep
#10 13.42 -- CMAKE_BUILD_TYPE = RelWithDebInfo
#10 13.42 -- CMAKE_CXX_FLAGS = -ftls-model=global-dynamic -pedantic -Wextra -Wall -fdiagnostics-color=auto -Wdeprecated -Wno-long-long -Wformat-security -Wshadow           -pthread
#10 13.42 -- CMAKE_CXX_STANDARD = 14
#10 13.42 -- CMAKE_SHARED_LINKER_FLAGS =  -pthread -Wl,--no-undefined
#10 13.42 -- BUILD_SHARED_LIBS = ON
#10 13.42 -- BUILD_TESTING = OFF
#10 13.42 -- CMAKE_MODULE_PATH =
#10 13.42 --    /DD4hep/cmake;
#10 13.42 -- -------------------------------------------------------------------------------
#10 13.42 -- 
#10 13.43 -- Configuring done
#10 13.47 CMake Error at UtilityApps/CMakeLists.txt:84 (add_executable):
#10 13.47   Target "teveDisplay" links to target "ROOT::Eve" but the target was not
#10 13.47   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
#10 13.47   an ALIAS target is missing?
#10 13.47 
#10 13.47 
#10 13.47 CMake Error at UtilityApps/CMakeLists.txt:84 (add_executable):
#10 13.47   Target "teveDisplay" links to target "ROOT::RGL" but the target was not
#10 13.47   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
#10 13.47   an ALIAS target is missing?
#10 13.47 
#10 13.47 
#10 13.53 CMake Error at UtilityApps/CMakeLists.txt:84 (add_executable):
#10 13.53   Target "teveDisplay" links to target "ROOT::Eve" but the target was not
#10 13.53   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
#10 13.53   an ALIAS target is missing?
#10 13.53 
#10 13.53 
#10 13.53 CMake Error at UtilityApps/CMakeLists.txt:84 (add_executable):
#10 13.53   Target "teveDisplay" links to target "ROOT::RGL" but the target was not
#10 13.53   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
#10 13.53   an ALIAS target is missing?
#10 13.53 
#10 13.53 
#10 13.71 -- Generating done
#10 13.71 CMake Generate step failed.  Build files cannot be regenerated correctly.
```
 - Goal: A perferct world would have a simple `cmake` option that turns off the modules that depend on `ROOT::Eve`, e.g. I could do `cmake -DDD4HEP_BUILD_DDEVE=OFF ..`.

**Comment by andresailer** [comment]
Instead of the sed you are doing, you can already turn off DDEve and the UtilityTools via the

DD4HEP_BUILD_PACKAGES cmake option
https://github.com/AIDASoft/DD4hep/blob/05508d0478bd8ea400fb48530affdcd39160d685/CMakeLists.txt#L81-L82

Note that we don't guarantee that all combinations of this list will build successfully, but dropping those two should hopefully work?
If you want to keep the other UtilityTools we have to make those depend on the presence of DDEve I think.

**Comment by tomeichlersmith** [comment]
Oh excellent! I didn't know that I could edit that option from the `cmake` command. I will give that a shot and come back here if I run into more issues.

**Comment by andresailer** [comment]
All the cmake variables with "CACHE" can be set from the command line
https://cmake.org/cmake/help/latest/command/set.html#set-cache-entry

**Comment by tomeichlersmith** [comment]
That worked wonderfully! (At least it finished compiling) Thank you.
