### ISSUE TITLE
HTML Documentation navigation doesn't scroll

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#722]
The right hand side contents are too long and cannot be scrolled. Therefore, the later sections are never visible. Although this is minor, it is really annoying.
https://dd4hep.web.cern.ch/dd4hep/usermanuals/DD4hepManual/DD4hepManualch2.html

![image](https://user-images.githubusercontent.com/2065918/95534482-9e033500-09ab-11eb-8a02-02433d089b0b.png)

![image](https://user-images.githubusercontent.com/2065918/95534526-b70be600-09ab-11eb-87a2-febe6ede8f45.png)

**Comment by petricm** [comment]
We don't have a solution for this, and sister projects that use a similar approach for building documentation don't either.
Honestly this will most likely never be fixed and we might sooner move to a different docs building system then somebody debugging this, so I am closing this.

**Comment by simonspa** [comment]
I concur, the LaTeX2HTML approach we're using currently is quite brittle and there is little headroom for fixing things.
