### ISSUE TITLE
type object 'dd4hep' has no attribute 'run_interpreter'

### ISSUE THREAD

**Issue by zelbitar** [AIDASoft/DD4hep#724]
- OS version: MacOs, Catalina
 - Compiler version: Apple clang version 11.0.3 (clang-1103.0.32.62)
 - DD4hep version: GitHub branch
 - Reproduced by: 
   ROOT 6.22 : installed with brew install root
   Geant4.10.6: installed with brew install geant4
   LCIO: Compilation OK
   DD4hep: Compilation OK
   LCGEO: Compilation OK

The problem occurs when I want to test the command : 
ddsim --compactFile ../ILD/compact/ILD_o1_v05/ILD_o1_v05.xml --inputFiles mcparticles.slcio -N 10

I got a long list of messages that finishes with : 

Error in <TClass::LoadClassInfo>: no interpreter information for class dd4hep::NamedObject is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class dd4hep::NamedObject is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class dd4hep::NamedObject is available even though it has a TClass initialization routine.
Traceback (most recent call last):
  File "/Users/zelbitar/ilcsoft.v1/DD4hep/bin/ddsim", line 25, in <module>
    RUNNER.run()
  File "/Users/zelbitar/ilcsoft.v1/DD4hep/lib/python3.8/site-packages/DDSim/DD4hepSimulation.py", line 293, in run
    import DDG4
  File "/Applications/root_v6.22.00/lib/ROOT/_facade.py", line 121, in _importhook
    return _orig_ihook(name, *args, **kwds)
  File "/Users/zelbitar/ilcsoft.v1/DD4hep/lib/python3.8/site-packages/DDG4.py", line 13, in <module>
    from dd4hep_base import *  # noqa: F403
  File "/Applications/root_v6.22.00/lib/ROOT/_facade.py", line 121, in _importhook
    return _orig_ihook(name, *args, **kwds)
  File "/Users/zelbitar/ilcsoft.v1/DD4hep/lib/python3.8/site-packages/dd4hep_base.py", line 124, in <module>
    import_namespace_item('core', 'run_interpreter')
  File "/Users/zelbitar/ilcsoft.v1/DD4hep/lib/python3.8/site-packages/dd4hep_base.py", line 67, in import_namespace_item
    attr = getattr(scope, nam)
AttributeError: <namespace cppyy.gbl.dd4hep at 0x7ffb47408e70> has no attribute 'run_interpreter'. Full details:
  type object 'dd4hep' has no attribute 'run_interpreter'
  'dd4hep::run_interpreter' is not a known C++ class
  'run_interpreter' is not a known C++ template
  'run_interpreter' is not a known C++ enum

ROOT is built with python 2.7
and the python version used to build DD4hep is python 3.8.

Here is the message when running cmake for DD4hep.
-- Python version used to build ROOT = 2.7.16
-- Python version detected by CMake to build DD4hep = 3.8.6

I am new to all these softwares packages so may be these problems have been already solved but I don't find the answers on the git.

Any idea

 - Input: link to input files if applicable
 - Output: full build and run log output
 - Goal: A short description of what you are trying to achieve

**Comment by andresailer** [comment]
Pretty sure you need to build DD4hep with the same python as root.

@MarkusFrankATcernch @petricm 
Why is this no longer considered a fatal error?
https://github.com/AIDASoft/DD4hep/blob/96094e0a6962eed776a1fa1ca5a4c8cf391d5812/cmake/DD4hepBuild.cmake#L658
https://github.com/AIDASoft/DD4hep/blame/96094e0a6962eed776a1fa1ca5a4c8cf391d5812/cmake/DD4hepBuild.cmake#L658

**Comment by zelbitar** [comment]
Hello and thanks for the reply,

So I've reinstalled root from scratch by cloning (git clone) root from the git repository.
Then, I have configured the root environnement for compilation using cmake and premising the python version with the option -DPYTHON_EXECUTABLE=/usr/local/bin/python3.8.

During the CMake execution, I have got this message:
PyROOT will be built for version 3.8.6 

I then compiled geant4, LCIO, DD4hep and lcgeo. All the compilation worked without any problem.

Now coming to the tests, the first one passed, which is:


zelbitar@sbgmc66 example % python lcio_particle_gun.py
Module PyMVA not found.
Loading LCIO ROOT dictionaries ...
(' opened outfile: ', 'mcparticles.slcio')
zelbitar@sbgmc66 example % 

I think Module PyMVA is not found because I am using Python3.8?

But then we trying to run dddim, I have again the following message at the end of a long list of message:

Error in <TClass::LoadClassInfo>: no interpreter information for class dd4hep::NamedObject is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class dd4hep::NamedObject is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class dd4hep::NamedObject is available even though it has a TClass initialization routine.
Error in <TProtoClass::FillTClass>: TClass dd4hep::NamedObject already initialized!
Error in <TClass::LoadClassInfo>: no interpreter information for class dd4hep::NamedObject is available even though it has a TClass initialization routine.
Traceback (most recent call last):
  File "/Users/zelbitar/ilcsoft.v1/DD4hep/bin/ddsim", line 25, in <module>
    RUNNER.run()
  File "/Users/zelbitar/ilcsoft.v1/DD4hep/lib/python3.8/site-packages/DDSim/DD4hepSimulation.py", line 293, in run
    import DDG4
  File "/Users/zelbitar/ilcsoft.v1/root-install/lib/ROOT/_facade.py", line 121, in _importhook
    return _orig_ihook(name, *args, **kwds)
  File "/Users/zelbitar/ilcsoft.v1/DD4hep/lib/python3.8/site-packages/DDG4.py", line 13, in <module>
    from dd4hep_base import *  # noqa: F403
  File "/Users/zelbitar/ilcsoft.v1/root-install/lib/ROOT/_facade.py", line 121, in _importhook
    return _orig_ihook(name, *args, **kwds)
  File "/Users/zelbitar/ilcsoft.v1/DD4hep/lib/python3.8/site-packages/dd4hep_base.py", line 124, in <module>
    import_namespace_item('core', 'run_interpreter')
  File "/Users/zelbitar/ilcsoft.v1/DD4hep/lib/python3.8/site-packages/dd4hep_base.py", line 67, in import_namespace_item
    attr = getattr(scope, nam)
AttributeError: <namespace cppyy.gbl.dd4hep at 0x7ff0bc386120> has no attribute 'run_interpreter'. Full details:
  type object 'dd4hep' has no attribute 'run_interpreter'
  'dd4hep::run_interpreter' is not a known C++ class
  'run_interpreter' is not a known C++ template
  'run_interpreter' is not a known C++ enum


What am I missing or doing wrong ?

**Comment by andresailer** [comment]
What is the output of
```
echo $PATH
echo $LD_LIBRARY_PATH
echo $PYTHONPATH
```
Which commit of DD4hep are you using?
Please attach the whole output of ddsim, the complete error message.

**Comment by zelbitar** [comment]
zelbitar@sbgmc66 example % echo $PATH                 
/Users/zelbitar/ilcsoft.v1/lcgeo/bin:/Users/zelbitar/ilcsoft.v1/DD4hep/bin:/usr/local/Cellar/geant4/10.6.2/bin:/Users/zelbitar/ilcsoft.v1/root-install/bin:/Users/zelbitar/ilcsoft.v1/DD4hep/bin:/usr/local/Cellar/geant4/10.6.2/bin:/Users/zelbitar/ilcsoft.v1/LCIO/bin:/Users/zelbitar/ilcsoft.v1/LCIO/tools:/usr/local/Cellar/geant4/10.6.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin



zelbitar@sbgmc66 example % echo $LD_LIBRARY_PATH 
/Users/zelbitar/ilcsoft.v1/lcgeo/lib:/Users/zelbitar/ilcsoft.v1/DD4hep/lib:/Users/zelbitar/ilcsoft.v1/root-install/lib:/Users/zelbitar/ilcsoft.v1/DD4hep/lib:/Users/zelbitar/ilcsoft.v1/LCIO/lib

zelbitar@sbgmc66 example % echo $DYLD_LIBRARY_PATH 
/Users/zelbitar/ilcsoft.v1/lcgeo/lib:/Users/zelbitar/ilcsoft.v1/DD4hep/lib:/Users/zelbitar/ilcsoft.v1/root-install/lib:/Users/zelbitar/ilcsoft.v1/DD4hep/lib


zelbitar@sbgmc66 example % echo $PYTHONPATH 
/Users/zelbitar/ilcsoft.v1/lcgeo/:/Users/zelbitar/ilcsoft.v1/DD4hep/lib/python3.8/site-packages:/Users/zelbitar/ilcsoft.v1/root-install/lib:/Users/zelbitar/ilcsoft.v1/DD4hep/lib/python3.8/site-packages:/Users/zelbitar/ilcsoft.v1/LCIO/src/python

[log_ddsim.txt](https://github.com/AIDASoft/DD4hep/files/5409258/log_ddsim.txt)

**Comment by andresailer** [comment]
Did you compile root and dd4hep with the same c++ standard?
This looks like a mixture of boost any and std any
```

In file included from G__DD4hep dictionary payload:16239:
In file included from /Users/zelbitar/ilcsoft.v1/DD4hep/include/DD4hep/Factories.h:17:
/Users/zelbitar/ilcsoft.v1/DD4hep/include/DD4hep/Plugins.h:33:16: error: target of using declaration conflicts with declaration already in scope
  using boost::bad_any_cast;
               ^
/usr/local/include/boost/any.hpp:233:32: note: target of using declaration
    class BOOST_SYMBOL_VISIBLE bad_any_cast :
                               ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/any:96:63: note: conflicting declaration
class _LIBCPP_EXCEPTION_ABI _LIBCPP_AVAILABILITY_BAD_ANY_CAST bad_any_cast : public bad_cast
                                                              ^
```
This looks like a mixture of boost any and std any

**Comment by zelbitar** [comment]
Not sure,

I will recompile with the option -DCMAKE_CXX_STANDARD=17 in both root and dd4hep.

**Comment by zelbitar** [comment]
Thanks,

I recompiled all the softs below from scratch using -DCMAKE_CXX_STANDARD=17
ROOT 6.23.01
Geant4.10.7
LCIO
DD4hep
LCGEO 

Things work better.

I still have a small problem when running ddsim from the example directory.
ddsim --compactFile ../ILD/compact/ILD_o1_v05/ILD_o1_v05.xml --inputFiles mcparticles.slcio -N 10

WARNING: cannot load liblcgeo.dylib for factory Beampipe_o1_v01
WARNING: dlopen(liblcgeo.dylib, 9): image not found
Compact          ERROR FAILED     subdetector:Tube of type Beampipe_o1_v01 
WARNING: cannot load liblcgeo.dylib for factory Beampipe_o1_v01
WARNING: dlopen(liblcgeo.dylib, 9): image not found
PluginService    ERROR Factory requested: Beampipe_o1_v01 (N10__cxxabiv120__function_type_infoE) :bad any cast
PluginService    ERROR Stub is invalid!
Compact          ERROR ++ FAILED    to convert subdetector: Tube: Failed to execute subdetector creation plugin. 		No factory with name Create(Beampipe_o1_v01) for type Beampipe_o1_v01 found.
		Please check library load path and/or plugin factory name.

**************************************************** 
*  A runtime error has occured :                     
*    Failed to execute subdetector creation plugin. 		No factory with name Create(Beampipe_o1_v01) for type Beampipe_o1_v01 found.
		Please check library load path and/or plugin factory name.
*  the program will have to be terminated - sorry.   
**************************************************** 

All the output is attached to this message. 

The problem is that is that liblcgeo.dylib can not be loaded. This is solved when a copy all the files in the /lib subdirectory of lcgeo in the example directory. But I don't think it is the right way to solve the problem. 

Is there any environment variable I need to set.

LD_LIBRARY_PATH and DYLD_LIBRARY_PATH are set as follows:

zelbitar@sbgmc66 example % echo $LD_LIBRARY_PATH 
/Users/zelbitar/ilcsoft.v1/lcgeo/lib:/Users/zelbitar/ilcsoft.v1/DD4hep/lib:/Users/zelbitar/ilcsoft.v1/root-install/lib:/Users/zelbitar/ilcsoft.v1/DD4hep/lib:/Users/zelbitar/ilcsoft.v1/LCIO/lib:/Users/zelbitar/ilcsoft.v1/lcgeo/lib:/Users/zelbitar/ilcsoft.v1/DD4hep/lib:/Users/zelbitar/ilcsoft.v1/DD4hep/lib:/Users/zelbitar/lib

zelbitar@sbgmc66 example % echo $DYLD_LIBRARY_PATH
/Users/zelbitar/ilcsoft.v1/lcgeo/lib:/Users/zelbitar/ilcsoft.v1/DD4hep/lib:/Users/zelbitar/ilcsoft.v1/root-install/lib:/Users/zelbitar/ilcsoft.v1/DD4hep/lib:/Users/zelbitar/ilcsoft.v1/lcgeo/lib:/Users/zelbitar/ilcsoft.v1/DD4hep/lib:/Users/zelbitar/ilcsoft.v1/DD4hep/lib

Thanks for the help,


[log_ddsim_lib.txt](https://github.com/AIDASoft/DD4hep/files/5414011/log_ddsim_lib.txt)

**Comment by andresailer** [comment]
What about  `$DD4HEP_LIBRARY_PATH`

**Comment by zelbitar** [comment]
zelbitar@sbgmc66 ~ % echo $DD4HEP_LIBRARY_PATH 
/Users/zelbitar/ilcsoft.v1/lcgeo/lib:/Users/zelbitar/ilcsoft.v1/DD4hep/lib:/Users/zelbitar/ilcsoft.v1/root-install/lib:/Users/zelbitar/ilcsoft.v1/DD4hep/lib:/Users/zelbitar/lib

**Comment by andresailer** [comment]
That looks good.

What does your `python` executable point to?
`which python`?

Can you try
```
python3.8 `which ddsim`  all the other options
```
Because ddsim has `/usr/bin/env python`

**Comment by zelbitar** [comment]
By default the python version is 2.7

zelbitar@sbgmc66 example % python --version
Python 2.7.16

I had to use the following to make the first test works:

zelbitar@sbgmc66 example % python3.8 lcio_particle_gun.py 
Loading LCIO ROOT dictionaries ...
 opened outfile:  mcparticles.slcio

I doesn't work if I write "python lcio_particle_gun.py" 

also in ddsim I changed the first line from 
/usr/bin/env python --> /usr/bin/env python3.8

Still having the same error

zelbitar@sbgmc66 example % which ddsim
/Users/zelbitar/ilcsoft.v1/DD4hep/bin/ddsim

**Comment by zelbitar** [comment]
zelbitar@sbgmc66 example % python3.8 `which ddsim` --compactFile ../ILD/compact/ILD_o1_v05/ILD_o1_v05.xml --inputFiles mcparticles.slcio -N 10

Everything worked fine ! (output file is attached)

It doesn't work if I write in the ddsim "/usr/bin/env python3.8" instead of "/usr/bin/env python".

I am working in zsh environment, does it have something to do?
[log_ddsim_python3.8.txt](https://github.com/AIDASoft/DD4hep/files/5414678/log_ddsim_python3.8.txt)

**Comment by andresailer** [comment]
It is probably the `/usr/bin/env` that clears the environment because of the system integrity protection (@petricm ?).

**Comment by petricm** [comment]
Can you give the result of
```
which python
which python3.8
which python3
```

**Comment by zelbitar** [comment]
zelbitar@sbgmc66 ~ % which python
/usr/bin/python
zelbitar@sbgmc66 ~ % which python3.8
/usr/local/bin/python3.8
zelbitar@sbgmc66 ~ % which python3  
/usr/local/bin/python3
zelbitar@sbgmc66 ~ %

**Comment by petricm** [comment]
I agree that probably `/usr/bin/env` strips the env. 
Try the following:
 - make an alias 
  ```
  alias python=`which python3`
  ```
 - in reset bash the shabang in `ddsim` to `#!/usr/bin/env python`
 - re-try `ddsim --compactFile ...`

**Comment by zelbitar** [comment]
I have done the following:

Create an alias in zshrc:
alias python=`which python3`

in ddsim:
#!/usr/bin/env python
"""

DD4hep simulation with some argument parsing

The first example worked : 
zelbitar@sbgmc66 example % python lcio_particle_gun.py                                                                                      
Loading LCIO ROOT dictionaries ...
 opened outfile:  mcparticles.slcio

But then, I got the following error message when running ddsim:

zelbitar@sbgmc66 example % ddsim --compactFile ../ILD/compact/ILD_o1_v05/ILD_o1_v05.xml --inputFiles mcparticles.slcio -N 10                
Traceback (most recent call last):
  File "/Users/zelbitar/ilcsoft.v1/DD4hep/bin/ddsim", line 25, in <module>
    RUNNER.run()
  File "/Users/zelbitar/ilcsoft.v1/DD4hep/lib/python3.8/site-packages/DDSim/DD4hepSimulation.py", line 290, in run
    import ROOT
  File "/Users/zelbitar/ilcsoft.v1/root-install/lib/ROOT/__init__.py", line 22, in <module>
    import cppyy
  File "/Users/zelbitar/ilcsoft.v1/root-install/lib/cppyy/__init__.py", line 64, in <module>
    libcppyy_mod_name, major, minor))
ImportError: Failed to import libcppyy2_7. Please check that ROOT has been built for Python 2.7
zelbitar@sbgmc66 example % 

It seems like it is not considering the alias.

A problem with /usr/bin/env ?




I !/usr/bin/env python
"""

DD4hep simulation with some argument parsing
Based on M. Frank and F. Gaede runSim.py
   @author  A.Sailer
   @version 0.1

**Comment by petricm** [comment]
Do you have in `/usr/local/bin/` a `python` executable? without 3 or 3.8?

**Comment by zelbitar** [comment]
no.

zelbitar@sbgmc66 ilcsoft.v1 % ls /usr/local/bin/python*
/usr/local/bin/python3		/usr/local/bin/python3-config	/usr/local/bin/python3.8	/usr/local/bin/python3.8-config

**Comment by petricm** [comment]
I think this cannot work. For DD4hep on macOS you need a `python` executable with name `python` (not `python3` or else) that is not located in `/System`, `/bin`, `/sbin`, `/usr` (`/usr/local` goes ), otherwise SIP will intervene.

**Comment by zelbitar** [comment]
Ok ! 
I can still run ddsim with:

python3.8 `which ddsim` all the options.

Thanks for helping me getting here.

Now, I have been moving on with the compilation of MarlinUtil (and all the ilcsofts) and having some error messages while doing cmake. I think I'll have to open a ticket on the git corresponding to MarlinUtil.

If not, than the message is below. (problem with CLHEP).
zelbitar@sbgmc66 build % cmake -DCMAKE_CXX_STANDARD=17 -Wno-dev ../
-- Check for ILCUTIL (1.6.1)
-- FLAGS -Wall;-Wextra;-Wshadow;-Weffc++;-pedantic;-Wno-long-long;-Wuninitialized
-- Adding -Wall to CXX_FLAGS
-- Adding -Wextra to CXX_FLAGS
-- Adding -Wshadow to CXX_FLAGS
-- Adding -Weffc++ to CXX_FLAGS
-- Adding -pedantic to CXX_FLAGS
-- Adding -Wno-long-long to CXX_FLAGS
-- Adding -Wuninitialized to CXX_FLAGS
-- Check for Marlin (1.17.1)
-- Check for Marlin_LIBRARIES: Marlin;MarlinXML
-- Check for Marlin_MARLIN_LIBRARY: /Users/zelbitar/ilcsoft.v1/Marlin/lib/libMarlin.dylib -- ok
-- Check for Marlin_MARLINXML_LIBRARY: /Users/zelbitar/ilcsoft.v1/Marlin/lib/libMarlinXML.dylib -- ok
-- Check for CED (1.9.3)
-- Check for CED_LIBRARIES: CED
-- Check for CED_CED_LIBRARY: /Users/zelbitar/ilcsoft.v1/CED/lib/libCED.dylib -- ok
-- Check for GSL (2.6)
-- Check for GSL_LIBRARIES: gsl;gslcblas
-- Check for GSL_GSL_LIBRARY: /usr/local/Cellar/gsl/2.6/lib/libgsl.dylib -- ok
-- Check for GSL_GSLCBLAS_LIBRARY: /usr/local/Cellar/gsl/2.6/lib/libgslcblas.dylib -- ok
-- Including DD4hepBuild.cmake
-- |++> Compiler supports filesystem when linking against 
-- DD4hep uses Geant4
CMake Error at /Users/zelbitar/ilcsoft.v1/DD4hep/cmake/DD4hepBuild.cmake:773 (ADD_LIBRARY):
  ADD_LIBRARY cannot create imported target "CLHEP::CLHEP" because another
  target with the same name already exists.
Call Stack (most recent call first):
  /Users/zelbitar/ilcsoft.v1/DD4hep/cmake/DD4hepConfig.cmake:60 (DD4HEP_SETUP_GEANT4_TARGETS)
  CMakeLists.txt:42 (FIND_PACKAGE)


-- DD4hep uses LCIO
-- Check for LCIO (2.15.1)
-- Check for LCIO_LIBRARIES: lcio;sio
-- Check for LCIO_LCIO_LIBRARY: /Users/zelbitar/ilcsoft.v1/LCIO/lib/liblcio.dylib -- ok
-- Check for LCIO_SIO_LIBRARY: /Users/zelbitar/ilcsoft.v1/LCIO/lib/libsio.dylib -- ok
-- |++> DD4hep: Looking for Components: DDRec
-- 
-- -------------------------------------------------------------------------------
-- Change values with: cmake -D<Variable>=<Value>
-- CMAKE_INSTALL_PREFIX = /Users/zelbitar/ilcsoft.v1/MarlinUtil
-- CMAKE_BUILD_TYPE = RelWithDebInfo
-- BUILD_TESTING = ON
-- INSTALL_DOC = OFF
-- CMAKE_PREFIX_PATH =
--    /Users/zelbitar/ilcsoft.v1/iLCUtil;
-- CMAKE_MODULE_PATH =
--    /Users/zelbitar/ilcsoft.v1/iLCUtil/cmakemodules;
--    /Users/zelbitar/ilcsoft.v1/DD4hep/cmake;
-- -------------------------------------------------------------------------------
-- 
-- Configuring incomplete, errors occurred!
See also "/Users/zelbitar/ilcsoft.v1/MarlinUtil/build/CMakeFiles/CMakeOutput.log".
zelbitar@sbgmc66 build % cmake -DCMAKE_CXX_STANDARD=17 -Wno-dev ../ > log_cmake_MarlinUtil.txt 2>&1
zelbitar@sbgmc66 build % vi log_cmake_MarlinUtil.txt 
zelbitar@sbgmc66 build % cmake -DCMAKE_CXX_STANDARD=17 -Wno-dev ../                                
-- Check for ILCUTIL (1.6.1)
-- FLAGS -Wall;-Wextra;-Wshadow;-Weffc++;-pedantic;-Wno-long-long;-Wuninitialized
-- Adding -Wall to CXX_FLAGS
-- Adding -Wextra to CXX_FLAGS
-- Adding -Wshadow to CXX_FLAGS
-- Adding -Weffc++ to CXX_FLAGS
-- Adding -pedantic to CXX_FLAGS
-- Adding -Wno-long-long to CXX_FLAGS
-- Adding -Wuninitialized to CXX_FLAGS
-- Check for Marlin (1.17.1)
-- Check for Marlin_LIBRARIES: Marlin;MarlinXML
-- Check for Marlin_MARLIN_LIBRARY: /Users/zelbitar/ilcsoft.v1/Marlin/lib/libMarlin.dylib -- ok
-- Check for Marlin_MARLINXML_LIBRARY: /Users/zelbitar/ilcsoft.v1/Marlin/lib/libMarlinXML.dylib -- ok
-- Check for CED (1.9.3)
-- Check for CED_LIBRARIES: CED
-- Check for CED_CED_LIBRARY: /Users/zelbitar/ilcsoft.v1/CED/lib/libCED.dylib -- ok
-- Check for GSL (2.6)
-- Check for GSL_LIBRARIES: gsl;gslcblas
-- Check for GSL_GSL_LIBRARY: /usr/local/Cellar/gsl/2.6/lib/libgsl.dylib -- ok
-- Check for GSL_GSLCBLAS_LIBRARY: /usr/local/Cellar/gsl/2.6/lib/libgslcblas.dylib -- ok
-- Including DD4hepBuild.cmake
-- |++> Compiler supports filesystem when linking against 
-- DD4hep uses Geant4
CMake Error at /Users/zelbitar/ilcsoft.v1/DD4hep/cmake/DD4hepBuild.cmake:773 (ADD_LIBRARY):
  ADD_LIBRARY cannot create imported target "CLHEP::CLHEP" because another
  target with the same name already exists.
Call Stack (most recent call first):
  /Users/zelbitar/ilcsoft.v1/DD4hep/cmake/DD4hepConfig.cmake:60 (DD4HEP_SETUP_GEANT4_TARGETS)
  CMakeLists.txt:42 (FIND_PACKAGE)


-- DD4hep uses LCIO
-- Check for LCIO (2.15.1)
-- Check for LCIO_LIBRARIES: lcio;sio
-- Check for LCIO_LCIO_LIBRARY: /Users/zelbitar/ilcsoft.v1/LCIO/lib/liblcio.dylib -- ok
-- Check for LCIO_SIO_LIBRARY: /Users/zelbitar/ilcsoft.v1/LCIO/lib/libsio.dylib -- ok
-- |++> DD4hep: Looking for Components: DDRec
-- 
-- -------------------------------------------------------------------------------
-- Change values with: cmake -D<Variable>=<Value>
-- CMAKE_INSTALL_PREFIX = /Users/zelbitar/ilcsoft.v1/MarlinUtil
-- CMAKE_BUILD_TYPE = RelWithDebInfo
-- BUILD_TESTING = ON
-- INSTALL_DOC = OFF
-- CMAKE_PREFIX_PATH =
--    /Users/zelbitar/ilcsoft.v1/iLCUtil;
-- CMAKE_MODULE_PATH =
--    /Users/zelbitar/ilcsoft.v1/iLCUtil/cmakemodules;
--    /Users/zelbitar/ilcsoft.v1/DD4hep/cmake;
-- -------------------------------------------------------------------------------
-- 
-- Configuring incomplete, errors occurred!
See also "/Users/zelbitar/ilcsoft.v1/MarlinUtil/build/CMakeFiles/CMakeOutput.log".

**Comment by petricm** [comment]
Please open question related to MarlinUtil on the corresponding repo
