### ISSUE TITLE
Undocumented MC truth handling

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#726]
Hello,
I just wanted to draw to your attention that the MC truth handling is undocumented.
 https://dd4hep.web.cern.ch/dd4hep/usermanuals/DDG4Manual/DDG4Manualse5.html#x8-300005.3

**Comment by utkarsh147-del** [comment]
I want to work on this project.Please give me this project

**Comment by petricm** [comment]
Was added on the to-do list

**Comment by whit2333** [comment]
Thanks.

**Comment by MarkusFrankATcernch** [comment]
See https://github.com/AIDASoft/DD4hep/pull/747
