### ISSUE TITLE
Documentation: Units

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#727]
Was the manual ever updated to document this units issue?
https://github.com/AIDASoft/DD4hep/issues/398#issuecomment-395453231

I just had my brain melt for a few hours as I tried to understand a units related bug. 

Also from @gaede https://github.com/AIDASoft/DD4hep/issues/398#issuecomment-393431435
> So I think the simple solution to the problem is keep the DD4hepUnits.h file as is and tell people (if they ask) we use TGeo units except for the angle.

I don't think this is correct because time appears is reported in G4 units (ns), right?

**Comment by petricm** [comment]
@whit2333 we were waiting with this as a new solution for unis was about to be deployed, but this is now delayed... will update the documentation on this.

**Comment by whit2333** [comment]
Thanks for the update. The problem  showed up as I was going from CLHEP/G4 -> DD4hep -> ACTS which are each slightly different. I have figured things out now so feel free to close this issue.

Cheers
