### ISSUE TITLE
update requirement of TGeoScaledShape converter

### ISSUE THREAD

**Issue by fucd** [AIDASoft/DD4hep#750]
While I use TGeoScaledShape by following method, DD4hep geometry work well, but once converted to Geant4 and simulating, some warning will happen and the real solid is not wanted. I use Geant4.10.06.p01 and found that newer versions have added G4ScaledSolid. If changing G4ReflectedSolid to G4ScaledSolid for TGeoScaledShape converter in [DDG4/src/Geant4Converter.cpp](https://github.com/AIDASoft/DD4hep/blob/master/DDG4/src/Geant4Converter.cpp), my codes can obtain right result. 
```cpp
TGeoCone* pCone1 = new TGeoCone(pzTopCut, 0, rOuterTop, 0, rOuterBottom);
TGeoScale* pScale1 = new TGeoScale(1, ratio, 1);
TGeoScaledShape* pScaledShape1 = new TGeoScaledShape(pCone1, pScale1);
dd4hep::Solid_type<TGeoScaledShape> side1(pScaledShape1);

DD4HEP_INSTANTIATE_SHAPE_HANDLE(TGeoScaledShape);
```
```
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomNav0003
      issued by : G4Navigator::GetGlobalExitNormal()
G4Navigator::GetGlobalExitNormal:   Using Local Normal - from call to GetLocalExitNormalAndCheck. 
  Local  Exit Normal :  || = 1.023917627 vec = (-0.6073575837,0.8239826986,-0.02401220255)
  Global Exit Normal :  || = 0 vec = (0,0,0)
  Global point: (17.5611934,-12.42315123,829.6092007)
  Calculated It      = 1
  Volume: pWorld
  Solid: world_volume_shape_0x4a60610, Type: G4Box
UnplacedBox {25000, 25000, 25000}Value obtained from new local *solid* is incorrect.

*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------
```

**Comment by MarkusFrankATcernch** [comment]
@fucd 
Let me recapitulate:
1) You create a scaled shape in DD4hep
    "ratio": is it positive or negative ?
    The scaled shape is not the shape of the world volume.
2) You convert the DD4hep geometry to Geant4
3) You start simulating. Then you see the G4Exception.

Is this correct ?

**Comment by fucd** [comment]
@MarkusFrankATcernch 

Yes, correct, and I use positive ratio in this case.

**Comment by MarkusFrankATcernch** [comment]
@fucd Please give a try once PR 756 is merged. For me this PR did fix the problem.

**Comment by fucd** [comment]
@MarkusFrankATcernch Thank you very much. The update looks like very great for me, and I believe it is efficacious. I am testing. But I meet some other problem while I switch DD4hep library in my environment . If I find any issue once test finished, I will give more message.

**Comment by MarkusFrankATcernch** [comment]
@fucd Did you have a chance to test PR #756 ?
Can I close this issue?

**Comment by fucd** [comment]
@MarkusFrankATcernch Sure, please close this issue.
