### ISSUE TITLE
Can not determine decay channel

### ISSUE THREAD

**Issue by gianelle** [AIDASoft/DD4hep#759]
Hi,
I have just update DD4Hep from v01-13-01 to v01-14, but using the same steering file for ddsim and as input file an
_HepMC v2_ I obtain the following exception:

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : DECAY003
      issued by : G4Decay::DoIt
Can not determine decay channel for pi+
  mass of dynamic particle: 0.00013957 (GEV)
  dacay table has 1 entries
0: BR 1, IsOK? 0, --> mu+ + nu_mu

*** Fatal Exception *** core dump ***
G4Track (0x55dbad5e0750) - track ID = 46, parent ID = 0
 Particle type : pi+ - creator process : not available
 Kinetic energy : 3.07433 keV - Momentum direction : (-0.406946,-0.336187,-0.849337)
 Step length : 59.4478 cm  - total energy deposit : 2.36553e-69 eV 
 Pre-step point : (0,0,0) - Physical volume : BeampipeInner_0 (Vacuum)
 - defined by : not available
 Post-step point : (0.00566908,-0.0250374,-506.893) - Physical volume : BeampipeInner_0 (Vacuum)
 - defined by : Decay - step status : 4
 *** Note: Step information might not be properly updated.

-------- EEEE -------- G4Exception-END --------- EEEE -------

*** G4Exception: Aborting execution ***
 *** Break *** abort

I tried also different input files (it seems that happen only with HepMC input files) but I have always 
the same error (what changes is the particle name).
I tried also to update geant4 to last patch  10.6.3 but nothing changes.

Do you have any idea?

Ale

**Comment by andresailer** [comment]
This is a problem of the units, the values are off by 1e3. Maybe #753 fixes this .

**Comment by gianelle** [comment]
I have tried with patch #753 and it fixes my problem.
Thank you.
Ale

**Comment by andresailer** [comment]
Thank you for testing and confirming!
