### ISSUE TITLE
CMS needs DD4hep version that uses Geant4 units convention

### ISSUE THREAD

**Issue by cvuosalo** [AIDASoft/DD4hep#770]
CMS is now ready to use a version of DD4hep that uses the Geant4 units convention (mm = 1), instead of the ROOT units convention (cm = 1). CMSSW will be able to work invariantly (with recompilation) with DD4hep using either units convention.

We would like to get the new version of DD4hep in January 2021.

We hope that using the Geant4 units convention will give some performance improvement and preserve precision by avoiding unnecessary multiplications.

**Comment by cvuosalo** [comment]
@ianna FYI

**Comment by petricm** [comment]
This is very good news, let's discuss this on the next developers meeting...

**Comment by MarkusFrankATcernch** [comment]
@cvuosalo @ianna 

https://github.com/AIDASoft/DD4hep/pull/774
https://github.com/AIDASoft/DD4hep/pull/772

Note the different cmake flags.

**Comment by petricm** [comment]
I am closing, if there is something new on this please open a new issue
