### ISSUE TITLE
b and c hadrons in HepMC files do not fly

### ISSUE THREAD

**Issue by casarsa** [AIDASoft/DD4hep#785]
Dear experts,

I am writing to report an issue we ran into and didn't manage to solve.

To perform b-tagging studies at a muon collider, we are running ddsim on different HepMC files
containing samples with b and c quarks. The samples were generated with both WIZARD and MadGraph + PYTHIA. 

We noticed that some of the hadrons that are supposed to fly some distance before decaying do not
and have zero endpoints in the output SLCIO files. Not all of them, though: for example B0's are fine, while B+'s and B-'s are not.

In DDG4/src/Geant4InputAction.cpp the particles' endpoints seem to be correctly set and have non-zero values, but when the particles are written out in DDG4/lcio/Geant4Output2LCIO.cpp, Geant4Particle's vex, vey and vez velues are 0.

In our debugging, we ran ddsim on an old stdhep file and the output is fine for that. So, as a test, we made an attempt to convert our HepMC files to the stdhep format. In this case, the flight distances are OK, but we get this exception:

*** G4Exception : DECAY101
      issued by : G4Decay::DecayIt 
For B- decay probability exist but decay table is not defined - the particle will be killed;
    isExtDecayer: 0; isPreAssigned: 0
*** This is just a warning message. ***

and the assignment of particles to the vertices looks weird. It seems that not only the first daughters are linked to the vertices, but all the descendants.

Hope you can help.

              Massimo

--------------------------------------------------------------------------

 - OS version: CentOS Linux release 8.2.2004
 - Compiler version: gcc 8.3.1 20191121
 - DD4hep version: v01-13-01 (but we get the same result with v01-15)
 - ILCSoft version: v02-02
 - WIZARD version: 2.8.2
 - GEANT4 version: 10.6.3
 - PYTHIA versions: 8.230, 8.244 and 8.303
 - HepMC versions: 2.06.09 and 2.06.10

**Comment by petricm** [comment]
Which HepMC reader do you use for DD4hep?
 - the builtin HepMC reader 2
 - or do you build DD4hep with `-DDD4HEP_USE_HEPMC3=OFF` and use the HepMC3 reader

**Comment by casarsa** [comment]
HepMC reader 2

**Comment by petricm** [comment]
A longer discussion on this topic is #760 I think it is the same problem, but in short
>  The hepmc2 reader does not treat the vertex information correctly.

Can you make a test with HepMC3 reader?

```
source /cvmfs/sw-nightlies.hsf.org/spackages/linux-centos7-broadwell/gcc-8.3.0/key4hep-stack-master-2020-12-07-qca3v5rnrsmeqsrsrb4zkhsi7xattb4k/setup.sh
```

**Comment by casarsa** [comment]
Is the HepMC3 reader compatible also with HepMC v2?

**Comment by petricm** [comment]
yes

**Comment by andresailer** [comment]
See also here: https://dd4hep.web.cern.ch/dd4hep/reference/namespaceHepMC3FileReader.html also the "note"

**Comment by casarsa** [comment]
Thank you both.

A quick update. We are still doing some checks.

Reading our HepMC v2 files with the HepMC3 reader seems to solve the issue with the displaced vertices. 
However, we are noticing two anomalies:
- For some resonances like B*'s, while the daughters' origin vertex is at 0,0,0, the mother's has values of the order O(-12). Is this just a rounding effect?
- The HepMC3 reader is changing all the run numbers to -1 for both the whizard and madgraph samples.

**Comment by andresailer** [comment]
a) Really hard to say if everything is done correctly without looking at the file itself.
Are these B*'s known to geant4? Are you passing the "particle.tbl" file?

b) could be the run numbers are not correctly read from the event header, can you make your input file available somewhere?

**Comment by casarsa** [comment]
We've investigated a little further:

- The HepMC3 reader is correctly assigning the particle endpoints and the displaced vertices look fine.

- It seems that in the HepMC file there is no header with a run number. So I think it's fine that the reader does not find a run number and leaves it set at the initialization value -1.

- The infinitesimal vertex coordinates we noticed are actually already present in the generator file, so that's fine too.

- The only thing that remains unexplained to us is the following.
For short-lived resonances like for example the B*'s, that are produced at the origin and decay immediately into a B meson + other particles, we see that in the HepMC file the production and decay vertices of the resonances coincide and have some infinitesimal (epsilon_x,  epsilon_y, epsilon_z) values. In the HepMC file, the daughters are produced at (epsilon_x,  epsilon_y, epsilon_z).
After having run ddsim, we see that in the output slcio file the production/decay vertex of the resonance mother is (epsilon_x, epsilon_y, epsilon_z), while the production vertex of the daughters has become (0, 0, 0). So somewhere it has been reset.

I think that it's happening in Geant4ParticleHandler::begin.
I've modified the initialization of the production vertex of the primary particles:

```
  if ( prim_part )   {
    m_currTrack.id           = prim_part->id;
                 .
                 .
                 .
    m_currTrack.vsx          = prim_part->vsx;
    m_currTrack.vsy          = prim_part->vsy;
    m_currTrack.vsz          = prim_part->vsz;

  }
  else  {
    m_currTrack.id           = m_globalParticleID; 
                 .
                 .
                 .
    m_currTrack.vsx          = v.x();
    m_currTrack.vsy          = v.y();
    m_currTrack.vsz          = v.z();
    ++m_globalParticleID;
  }
```

This seems to solve the inconsistency at the output. But, not having a deep understanding of the code, I don't know whether my hack is fine or may cause terrible consequences downstream.

**Comment by petricm** [comment]
[bbout_1000.hepmc.gz](https://github.com/AIDASoft/DD4hep/files/6044129/bbout_1000.hepmc.gz) example file

**Comment by andresailer** [comment]
@casarsa Do you have a particular event number?

**Comment by casarsa** [comment]
For example in the first event the particle 10084 is a 523 that decays into a 521 in V -71.

**Printout in Geant4InputAction:**
523
(vsx, vsy, vsz) = -8.57249e-12, 4.24797e-12, 1.21807e-11
(vex, vey, vez) = -8.57249e-12, 4.24797e-12, 1.21807e-11

521
(vsx, vsy, vsz) = -8.57249e-12, 4.24797e-12, 1.21807e-11
(vex, vey, vez) = -0.233998, -0.0492613, 0.467172

**Printout in  Geant4Output2LCIO:**
523
(vsx, vsy, vsz) = -8.57249e-12, 4.24797e-12, 1.21807e-11
(vex, vey, vez) = -8.57249e-12, 4.24797e-12, 1.21807e-11

521
(vsx, vsy, vsz) = 0., 0., 0.
(vex, vey, vez) = -0.233998, -0.0492613, 0.467172

**Comment by andresailer** [comment]
Ok, good thing I started at event 1 :)

So I think the problem is that the 523's are considered stable following these lines
https://github.com/AIDASoft/DD4hep/blob/83079901b96a071a37177cd7366a8ba82e0d072a/DDG4/examples/particle.tbl#L146-L147
As they have a assigned decay with basically zero flight distance they are not passed to geant4, and then their vertex information etc is not updated from the geant4 information
(if you are not using this file with ddsim --physics.pdgfile=path/to/particle.tbl then they are considered unknown and not passed to geant4 either)

Their width should be set to -1 (or, if this is known by now, their correct values) so that they are passed to geant, and then their vertex is updated correctly from the geant4 particle that immediately decays.
There is an inconsistency between the quark/generator string whatever (PDG 21) endpoint and the startpoint of the first particle given to Geant4.

With your patch this inconsistency moves to the first parent given to Geant4 and its daughter, which is maybe a bit worse.

**Comment by casarsa** [comment]
Thanks.
I'm using DDG4/examples/particle.tbl
Is there an updated version of particle.tbl?

**Comment by andresailer** [comment]
I don't know if there is an updated version...
we could update a couple lines ourselves.
In the end the changed result is rather cosmetic if the particles don't fly a significant distance, right?

**Comment by petricm** [comment]
Maybe some clarification on `DDG4/examples/particle.tbl`. This file a an example that is aimed that you start easier, but DD4hep does not have the intention of curating this file (of course we update it from time to time) it is only an example. In essence it is up to the user/experiment to supply the correct `particle.tbl` file that reflects the particles that you want to pass to DD4hep/G4.

**Comment by LaSavannah** [comment]
> Ok, good thing I started at event 1 :)
> 
> So I think the problem is that the 523's are considered stable following these lines
> 
> https://github.com/AIDASoft/DD4hep/blob/83079901b96a071a37177cd7366a8ba82e0d072a/DDG4/examples/particle.tbl#L146-L147
> 
> As they have a assigned decay with basically zero flight distance they are not passed to geant4, and then their vertex information etc is not updated from the geant4 information
> (if you are not using this file with ddsim --physics.pdgfile=path/to/particle.tbl then they are considered unknown and not passed to geant4 either)
> 
> Their width should be set to -1 (or, if this is known by now, their correct values) so that they are passed to geant, and then their vertex is updated correctly from the geant4 particle that immediately decays.
> There is an inconsistency between the quark/generator string whatever (PDG 21) endpoint and the startpoint of the first particle given to Geant4.
> 
> With your patch this inconsistency moves to the first parent given to Geant4 and its daughter, which is maybe a bit worse.

Dear all,

I have still some doubts about how the particle decays is calculated and the endpoints/production vertices.

In the example reported by Massimo why is the 521 particle production vertex (0,0,0) in "Printout in Geant4Output2LCIO"? It should be coincident with the mother endpoint (particle 531), as can be seen above, in "Printout in Geant4InputAction". 

I tried to change the width and the lifetime of 521 in the particle.tbl, but its production vertex is always (0,0,0) in "Printout in Geant4Output2LCIO".

**Comment by Laura-Buonincontri** [comment]
> Ok, good thing I started at event 1 :)
> 
> So I think the problem is that the 523's are considered stable following these lines
> 
> https://github.com/AIDASoft/DD4hep/blob/83079901b96a071a37177cd7366a8ba82e0d072a/DDG4/examples/particle.tbl#L146-L147
> 
> As they have a assigned decay with basically zero flight distance they are not passed to geant4, and then their vertex information etc is not updated from the geant4 information
> (if you are not using this file with ddsim --physics.pdgfile=path/to/particle.tbl then they are considered unknown and not passed to geant4 either)
> 
> Their width should be set to -1 (or, if this is known by now, their correct values) so that they are passed to geant, and then their vertex is updated correctly from the geant4 particle that immediately decays.
> There is an inconsistency between the quark/generator string whatever (PDG 21) endpoint and the startpoint of the first particle given to Geant4.
> 
> With your patch this inconsistency moves to the first parent given to Geant4 and its daughter, which is maybe a bit worse.

Dear all,

I have still some doubts about how the particle decays is calculated and the endpoints/production vertices.

In the example reported by Massimo why is the 521 particle production vertex (0,0,0) in "Printout in Geant4Output2LCIO"? It should be coincident with the mother endpoint (particle 531), as can be seen above, in "Printout in Geant4InputAction".

I tried to change the width and the lifetime of 521 in the particle.tbl, but its production vertex is always (0,0,0) in "Printout in Geant4Output2LCIO".

**Comment by andresailer** [comment]
Can you clarify what exactly you changed, and which version of the input you are using? Did you change the 523 width to -1?
Changing the lifetime or width of 521 isn't going to change its vertex, And, as the decay is "pre-assigned" from the MC Generator it will also not affect its decay time in the simulation. 
With the pre-assigned decays it is only important if Geant4 thinks the particle is stable or not. Because stable particles are not decayed by Geant4, even if pre-assigned decays exist, we do not forward them to geant4 in the first place.

**Comment by Laura-Buonincontri** [comment]
I am using DD4hep version: v01-16 (with HEPMC3 enabled).
The input file is bbout_1000.hepmc.gz, the same uploaded in the previous comments.
The path of the particle.tbl is DD4hep/v01-16/DDG4/examples/particle.tbl

I am looking the 523 and 521 particles in the first event.

I want also to clarify that my goal is to understand how to have a coherent production vertex-endpoint chain between mother and daughter particles. This implies also the coherence between the 523 production vertex and its mothers that, in "Printout in Geant4Output2LCIO:", have endpoints: (-8.57249e-12, 4.24797e-12, 1.21807e-11).
I would like to avoid the fact that at some point of the chain, one of the daughters production vertex is reset to zero. Is it possible?

With the default setup (the DD4hep/v01-16/DDG4/examples/particle.tbl) I see this:

Printout in Geant4Output2LCIO:
523
(vsx, vsy, vsz) = -8.57249e-12, 4.24797e-12, 1.21807e-11
(vex, vey, vez) = -8.57249e-12, 4.24797e-12, 1.21807e-11

521
(vsx, vsy, vsz) = 0., 0., 0.
(vex, vey, vez) = -0.233998, -0.0492613, 0.467172

These are my attempts:
1) If I change the 521 width and lifetime (with -1,0, and other values), the "Printout in Geant4Output2LCIO" is always the same, as you explained.

2) If I change the width of the 523 in the particle.tbl from zero to -1:

diff /opt/ilcsoft/muonc/DD4hep/v01-16/DDG4/examples/particle.tbl particle.tbl
146,147c146,147
<         523 B*^+                    3      5.32480     0.00000   0.00000E+00
<        -523 B*^-                   -3      5.32480     0.00000   0.00000E+00
---
>         523 B*^+                    3      5.32480    -1.00000   0.00000E+00
>        -523 B*^-                   -3      5.32480    -1.00000   0.00000E+00

I obtain this:
Printout in Geant4Output2LCIO:
523
(vsx, vsy, vsz) = 0., 0., 0.
(vex, vey, vez) = 0., 0., 0.

521
(vsx, vsy, vsz) = 0., 0., 0.
(vex, vey, vez) = -2.34e-01,-4.93e-02, 4.67e-01

In this last case production vertices and endpoints are coherent, but the start point of the 523 is not coherent with the endpoints of its mothers. I report here some examples:

21
(vsx, vsy, vsz) = -8.57e-12, 4.25e-12, 1.22e-11
(vex, vey, vez) = -8.57e-12, 4.25e-12, 1.22e-11

5
(vsx, vsy, vsz) = -8.57e-12, 4.25e-12, 1.22e-11
(vex, vey, vez) = -8.57e-12, 4.25e-12, 1.22e-11

**Comment by andresailer** [comment]
Yes, there will always be a discrepancy at some point.
As I said in  https://github.com/AIDASoft/DD4hep/issues/785#issuecomment-786074159
>There is an inconsistency between the quark/generator string whatever (PDG 21) endpoint and the startpoint of the first particle given to Geant4.

>  I would like to avoid the fact that at some point of the chain, one of the daughters production vertex is reset to zero. Is it possible?

Is there a significant difference between 1e-11 mm and 0 that would make it worth the effort? The problem is that the MC generator information starts at 0 0 0, and then goes to not 0 0 0 for no clear reason (to me). And in the simulation starting at 0 0 0 or a fraction of an atom next to it doesn't make a difference.

**Comment by Laura-Buonincontri** [comment]
Now I understand better what you meant, thank you.
So it is only a matter of understanding which particles are passed to Geant via the particle.tbl file and check that they have correct width/lifetime. Perhaps do you know any reference where we can find the particles known to Geant?
Thank you again.

**Comment by andresailer** [comment]
`ddsim --runType shell --compactFile <something.xml>`
With some xml compact file.
Then in the geant4 shell
`/particle/list`
Will print the list of known particles.

**Comment by Laura-Buonincontri** [comment]
Ok, I have checked the particles and I have understood most of the issues I had.
I have only one further question. I tried to change the width of some particles (unknown to Geant) in the particle.tbl file.

I tried to change the width of the particle 413 that have a width of 0.000096 GeV in the particle.tbl:

        413 D*(2010)^+              3      2.01000     0.000096  0.00000E+00
       -413 D*(2010)^-             -3      2.01000     0.000096  0.00000E+00

You can find this particle in the event 1 of the bbout_1000.hepmc.gz uploaded above.
If I put any other value of the width different from zero, I see always the same endpoint of the width set at 0.000096 GeV case, that is:

Printout in Geant4Output2LCIO:
(vsx, vsy, vsz): 1.85e+00,-3.67e+00,-1.86e+00
(vex, vey, vez): 1.85e+00,-3.67e+00,-1.86e+00

I would expect different endpoints for different widths.
Then, if I put width=0, the simulation doesn't reach the end, keep running. Am I missing something?

**Comment by andresailer** [comment]
The decay is pre-assigned by the Monte Carlo generator, this includes the decay channel, lifetime of parent and momentum children. The whole decay chain is given to geant4 to simulate in the detector. Therefore changing the width in particle.tbl doesn't have an effect, unless it changes a particle from unstable to stable. If a particle is considered stable that shouldn't be things go wrong in manifold ways.

**Comment by casarsa** [comment]
@andresailer @petricm thank you for you help
