### ISSUE TITLE
Build fails missing tests

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#80]
Here are the cmake errors:

`CMake Warning at cmake/DD4hepBuild.cmake:395 (find_package):
  By not providing "FindDDTEST.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "DDTEST", but
  CMake did not find one.

  Could not find a package configuration file provided by "DDTEST" with any
  of the following names:

    DDTESTConfig.cmake
    ddtest-config.cmake

  Add the installation prefix of "DDTEST" to CMAKE_PREFIX_PATH or set
  "DDTEST_DIR" to a directory containing one of the above files.  If "DDTEST"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  cmake/DD4hepBuild.cmake:486 (dd4hep_find_packageEx)
  cmake/DD4hepBuild.cmake:737 (dd4hep_find_package)
  cmake/DD4hepBuild.cmake:1188 (dd4hep_use_package)
  UtilityApps/CMakeLists.txt:36 (dd4hep_add_executable)

CMake Error at cmake/DD4hepBuild.cmake:185 (message):
  ++> [UtilityApps] Unknown package DDTEST
Call Stack (most recent call first):
  cmake/DD4hepBuild.cmake:415 (dd4hep_fatal)
  cmake/DD4hepBuild.cmake:486 (dd4hep_find_packageEx)
  cmake/DD4hepBuild.cmake:737 (dd4hep_find_package)
  cmake/DD4hepBuild.cmake:1188 (dd4hep_use_package)
  UtilityApps/CMakeLists.txt:36 (dd4hep_add_executable)

`

**Comment by petricm** [comment]
What is the cmake command that produces this?

**Comment by whit2333** [comment]
`cmake sources/DD4hep/.  \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DUSE_CXX11=ON \
    -DUSE_CXX14=ON \
    -DDD4HEP_USE_XERCESC=ON \
    -DDD4HEP_USE_PYROOT=ON \
    -DDD4HEP_USE_GEANT4=ON \
    -DDD4HEP_USE_GEAR=ON   \
    -DDD4HEP_USE_LCIO=ON   \
    -DBUILD_TESTING=OFF
`

**Comment by whit2333** [comment]
Adding  `add_subdirectory(DDTest)` seems to fix this issue.

**Comment by petricm** [comment]
Can you please try
`cmake -D DD4HEP_USE_GEANT4=ON -D DD4HEP_USE_BOOST=ON -DBoost_NO_BOOST_CMAKE=ON -D DD4HEP_USE_LCIO=ON -D BUILD_TESTING=ON  -D Geant4_DIR=$G4INSTALL/lib64/Geant4-10.2.2 -D DD4HEP_USE_CXX11=ON -DCMAKE_BUILD_TYPE=Release -DROOT_DIR=$ROOTSYS ..`

**Comment by whit2333** [comment]
Thank you. I can try that but what is the test? I think it was a missing add_subdirectory in the CMakeLists.txt

Also, why do I need to give geant4 and root directories? They should be found by cmake.

**Comment by petricm** [comment]
We would like to know what causes this behavior you reported, because the CI does not seem to pick up the error you reported (https://travis-ci.org/AIDASoft/DD4hep/jobs/195910200)

**Comment by whit2333** [comment]
I will submit a merge request which fixed the issues for myself. There appear to be two issues but they could originate with the fact that I am using a system-wide install of CLHEP (i.e. not the built-in geant4 version).
