### ISSUE TITLE
Bug in evaluator reported by Coverity

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#800]
It is not clear if this report from Coverity is correct and it is a bug or is this code intentional?
![Evaluator-Coverity](https://user-images.githubusercontent.com/8983816/114038086-dbc11780-9881-11eb-92bb-0f18c851fc04.png)

**Comment by petricm** [comment]
@Dr15Jones can you please comment

**Comment by Dr15Jones** [comment]
It's a bug. Line 932 should be deleted and line 936 should change to
```C++
if(env_status.first) result.second = env_status.first;
```
That would match what is done on line 945
