### ISSUE TITLE
.dd4hep-ci.d

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#801]
Hi,
I was working in November on adding a new dual readout crystal calorimeter in the dd4hep environment.  I then had to take a long break to write grant proposals :)

I decided to start from a fresh fork, because just at the end of my last work, Markus Frank had given me a better way to make a new calorimeter hit category and also I wanted to put things in a form where eventually it could be pushed into the main repository.

Unfortunately, the compile commands that worked for the old fork no longer work.  Specifically, I used to do

 COMPILER_VERSION=gcc8 LCG_RELEASE=LCG_96b source .dd4hep-ci.d/init_x86_64.sh

but the .dd4hep-ci.d area is no longer there.    also, it does not seem to have been moved to a new area:

[eno@hepcms-in1 DD4hep]$ find ./ -name init_x86_64.sh -print
[eno@hepcms-in1 DD4hep]$

Any help would be appreciated.

**Comment by petricm** [comment]
try this:
```
source /cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-centos8-gcc10-opt/setup.sh
```

**Comment by saraheno** [comment]
When I do that, I get

[eno@hepcms-in1 DD4hep]$ source /cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-centos8-gcc10-opt/setup.sh
/cvmfs/sft.cern.ch/lcg/releases/R/3.6.3-a2901/x86_64-centos8-gcc10-opt/lib64/R/bin/exec/R: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
/cvmfs/sft.cern.ch/lcg/releases/R/3.6.3-a2901/x86_64-centos8-gcc10-opt/lib64/R/bin/exec/R: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
/cvmfs/sft.cern.ch/lcg/releases/R/3.6.3-a2901/x86_64-centos8-gcc10-opt/lib64/R/bin/exec/R: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
/cvmfs/sft.cern.ch/lcg/releases/R/3.6.3-a2901/x86_64-centos8-gcc10-opt/lib64/R/bin/exec/R: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
/cvmfs/sft.cern.ch/lcg/releases/R/3.6.3-a2901/x86_64-centos8-gcc10-opt/lib64/R/bin/exec/R: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory

**Comment by petricm** [comment]
what is the OS you are using?

**Comment by saraheno** [comment]
[eno@hepcms-in1 DD4hep]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by petricm** [comment]
sorry my typo, I pasted wrong link for centos8 instead of centos7
```
source /cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-centos7-gcc10-opt/setup.sh
```

**Comment by petricm** [comment]
Try
```
          cmake \
            -DDD4HEP_USE_GEANT4=ON \
            -DBoost_NO_BOOST_CMAKE=ON \
            -DDD4HEP_USE_LCIO=ON \
            -DDD4HEP_USE_EDM4HEP=ON \
            -DDD4HEP_USE_TBB=ON \
            -DDD4HEP_USE_HEPMC3=ON \
            -DDD4HEP_BUILD_DEBUG=OFF \
            -DBUILD_TESTING=ON \
            -DDD4HEP_DEBUG_CMAKE=ON \
            -DDD4HEP_USE_XERCESC=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always"  \
            -DCMAKE_CXX_STANDARD=17 ..
          make install
```

**Comment by saraheno** [comment]
I'm still having problems.  I did

 cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=ON  -DDD4HEP_USE_HEPMC3=ON -DBUILD_TESTING=ON -DDD4HEP_USE_XERCESC=ON -DCMAKE_CXX_STANDARD=17 -DGeant4_DIR=$G4INSTALL/lib/Geant4-10.4.0 -DROOT_DIR=$ROOTSYS -DDD4HEP_BUILD_EXAMPLES=ON ..


and got-- Could NOT find LATEX (missing: LATEX_COMPILER)
-- No LaTeX/Biber found, cannot compile user manual.
-- Will be building these packages: DDRec;DDDetectors;DDCond;DDAlign;DDCAD;DDDigi;DDG4;DDEve;Ut\
ilityApps
-- Including DD4hepBuild.cmake
-- DD4hep_configure_output: set CMAKE_INSTALL_PREFIX to /home/eno/dd4hep/DD4hep
-- |++> Compiler supports filesystem when linking against stdc++fs
-- Detected Compiler: GCC 10.1.0
-- Detected CPU: penryn
-- Sadly the Penryn architecture exists in variants with SSE4.1 and without SSE4.1.
-- SSE4.1: enabled (auto-detected from this computer's CPU flags)
CMake Error at /cvmfs/sft.cern.ch/lcg/releases/CMake/3.18.4-2ffec/x86_64-centos7-gcc10-opt/shar\
e/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find X11 (missing: X11_X11_INCLUDE_PATH X11_X11_LIB)
Call Stack (most recent call first):
  /cvmfs/sft.cern.ch/lcg/releases/CMake/3.18.4-2ffec/x86_64-centos7-gcc10-opt/share/cmake-3.18/\
Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /cvmfs/sft.cern.ch/lcg/releases/CMake/3.18.4-2ffec/x86_64-centos7-gcc10-opt/share/cmake-3.18/\
Modules/FindX11.cmake:414 (find_package_handle_standard_args)
  /cvmfs/sft.cern.ch/lcg/releases/CMake/3.18.4-2ffec/x86_64-centos7-gcc10-opt/share/cmake-3.18/\
Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-centos7-gcc10-opt/lib64/Geant4-10.7.0/Geant4Config\
.cmake:433 (find_dependency)
  CMakeLists.txt:134 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/eno/dd4hep/DD4hep/build/CMakeFiles/CMakeOutput.log".
See also "/home/eno/dd4hep/DD4hep/build/CMakeFiles/CMakeError.log".

**Comment by petricm** [comment]
Well, this is a problem on your PC, you are missing the necessary openGL libraries for running Geant.
I think this should solve it.
```
sudo yum install libICE-devel libXmu-devel libXpm-devel libxslt-devel mesa-libGL-devel mesa-libGLU-devel -y
```

**Comment by saraheno** [comment]
Thanks.  The cmake now works error free.  However, when I try to make I get

[ 42%] Built target Components_DDAlignPlugins
DDCAD/CMakeFiles/DDCAD.dir/build.make:156: *** target pattern contains no `%'.  Stop.
make[1]: *** [DDCAD/CMakeFiles/DDCAD.dir/all] Error 2
make: *** [all] Error 2


should I not have cloned the header?

that file looks like (where I added the .txt so I could drag it into this thing)

[build.make.txt](https://github.com/AIDASoft/DD4hep/files/6281866/build.make.txt)

**Comment by saraheno** [comment]
I guess the problem has to do with something called assimp

I imagine this is therefore a problem at my end?  That I need to install this?

Is there someplace that lists all the needed external libraries?

**Comment by saraheno** [comment]
also, what version of assimp do you recommend?

**Comment by andresailer** [comment]
assimp should be part of the LCG stack.
Can you attach the whole cmake log, please?

**Comment by saraheno** [comment]
this is the spew to the screen when doing the cmake command
[eno@hepcms-in2 build]$ cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=ON -DDD4HEP_USE_HEPMC3=ON -DBUILD_TESTING=ON -DDD4HEP_USE_XERCESC=ON -DCMAKE_CXX_STANDARD=17 -DGeant4_DIR=$G4INSTALL/lib/Geant4-10.4.0 -DROOT_DIR=$ROOTSYS -DDD4HEP_BUILD_EXAMPLES=ON ..  >& cmake.txt


[cmake.txt](https://github.com/AIDASoft/DD4hep/files/6286844/cmake.txt)

**Comment by andresailer** [comment]
It finds assimp from the stack
```
-- +++> Use existing assimp implementation
-- Open-Asset-Importer: ASSIMP_INCLUDE_DIRS:  /cvmfs/sft.cern.ch/lcg/releases/assimp/5.0.1-8ea63/x86_64-centos7-gcc10-opt/include
-- Open-Asset-Importer: ASSIMP_LIBRARIES:     libassimp.so.5
-- |++++> Building dictionary ... G__DDCAD
-- have target assimp::assimp
```

**Comment by andresailer** [comment]
please add
```
    -DCMAKE_BUILD_TYPE=Release 
```
to your cmake command and try compiling again.

**Comment by saraheno** [comment]
but then in 
 DDCAD/CMakeFiles/DDCAD.dir/build.make

it has

lib/libDDCAD.so.1.16: assimp::assimp-NOTFOUND


this is line 156 on the attached
[build.make.txt](https://github.com/AIDASoft/DD4hep/files/6286900/build.make.txt)

**Comment by saraheno** [comment]
I tried adding \
-DCMAKE_BUILD_TYPE=Release

and still got the same error  (line 156 in DDCAD/CMakeFiles/DDCAD.dir/build.make:156:

**Comment by andresailer** [comment]
Can you confirm that  you ran?
```
cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=ON -DDD4HEP_USE_HEPMC3=ON -DBUILD_TESTING=ON -DDD4HEP_USE_XERCESC=ON -DCMAKE_CXX_STANDARD=17 -DGeant4_DIR=$G4INSTALL/lib/Geant4-10.4.0 -DROOT_DIR=$ROOTSYS -DDD4HEP_BUILD_EXAMPLES=ON -D CMAKE_BUILD_TYPE=Release ..
```
Because that fixes the issue for me.

**Comment by saraheno** [comment]
yes, I did that.  Also I just redid it and cut and pasted your cmake above, but I still get the error

**Comment by saraheno** [comment]
do I need to do something like "cmake clean" or something?

**Comment by andresailer** [comment]
You could try removing the whole build directory.

**Comment by saraheno** [comment]
Thanks everybody! It compiled!
