### ISSUE TITLE
Gflash parametrization 

### ISSUE THREAD

**Issue by EnginEren** [AIDASoft/DD4hep#802]
Dear all,

I'm wondering if anyone has implemented `Gflash` EM-shower parametrization into DD4hep. This program is already in Geant4 [*] and I'm wondering how can we apply it to iLC or CLIC detector geometry via DD4hep

Cheers,
Engin

[*] https://geant4-userdoc.web.cern.ch/UsersGuides/ForApplicationDeveloper/BackupVersions/V10.4/html/TrackingAndPhysics/physicsProcess.html#gflash-parameterization

**Comment by MarkusFrankATcernch** [comment]
Will need to have a closer look. Is there a comprehensive Geant4 example available for such a parametrized shower example ?

**Comment by EnginEren** [comment]
Dear Markus,

Thanks a lot. There is an example in Geant4 folder. E.g here:

```bash
bash-4.2# pwd
/home/ilc/ilcsoft/geant4/10.04.p03/examples/extended/parameterisations/gflash
````

Cheers,
Engin

**Comment by vvolkl** [comment]
Dear Engin,

There has already been some work done on using GFlash / Geant4 fast simulations for FCC (also using dd4hep geometries), see https://iopscience.iop.org/article/10.1088/1742-6596/898/4/042053/pdf
Now that iLCSoft and FCC are collaborating in the key4hep software project, this code  (find it on https://github.com/hep-fcc/k4simgeant4 ) is available also for use with ILC detectors, although this has not been tried yet. Let me know if that could be useful for you, then I'd go ahead and try to run the fast simulation with a CLIC detector model.

Of course any integration of GFlash in dd4hep can still be done if @MarkusFrankATcernch  is interested, but using the key4hep framework might be even quicker.
Cheers,
Valentin

**Comment by EnginEren** [comment]
Dear Valentin,

thanks a lot for the information and source code. I'm well aware of impressive key4hep efforts. I would be happy if you could run GFlash with the ILD detector model via key4hep.

Also having dd4hep intergration of GFlash doesnt hurt and I would be happy to try it out!

Cheers,
Engin

**Comment by EnginEren** [comment]
Hi @MarkusFrankATcernch , seeing 2 merged PRs, I'm excited to ask you about the status of GFlash and how can we use it for ILD ?

**Comment by MarkusFrankATcernch** [comment]
Well - things are not yet ready. I was taking a G4 example and see what is necessary to implement GFlash.
Though I have not run any test.

**Comment by EnginEren** [comment]
Hi Markus, Just curious while looking at your PR #929 , is there a chance that we can use GFlash parametrization in a near future ? I'm also happy to test it.

**Comment by MarkusFrankATcernch** [comment]
I am happy to actually welcome beta testers !
I have a mini-detector (2 silicon boxes) and tested with these.
There I got hits in the GFlash callbacks.

You can have a look in examples/ClientTests/scripts/SiliconBlockGFlash.py
To use GFlash is quite simple. Compare the script with the "normal" one:
examples/ClientTests/scripts/SiliconBlock.py

I am curious if it easily applies to more complex sub-detectors. However, I think you
will need to study a bit the Region settings to get the optimal out of it.
