### ISSUE TITLE
detector declaration in xml file

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#805]
Hi,
I am implementing a new calorimeter, and want to make sure I understand the detector declaration syntax.

For example, if I look at DD4hep/DDDetectors/compact/SiD/SiD_EcalBarrel.xml, I see

```xml
 <detector id="EcalBarrel_ID" name="EcalBarrel" type="DD4hep_EcalBarrel" 
    readout="EcalBarrelHits" vis="EcalBarrelVis" calorimeterType="EM_BARREL">
```

a) The argument for id (EcalBarrel_ID) is defined in DDDetectors/compact/SiDConstants.xml, right?

b) The argument for type is defined in DDDetectors/src/EcalBarrel_geo.cpp via the line
```
      DECLARE_DETELEMENT(DD4hep_EcalBarrel,create_detector)
```
right?

c)  The argument for readout is defined in DDDetectors/compact/SiD/SiD_Ecal.xml, via
```
                 <readout name="EcalBarrelHits">
```
right?

d) The argument for vis in also defined in DDDetectors/compact/SiDConstants.xml,, via
```
                 <vis name="EcalBarrelVis" 
```
right?

e) But where are name and calorimeterType defined?

thank you,
Sarah Eno
      

Edit: added triple ticks and enumeration of questions

**Comment by andresailer** [comment]
a) yes, 
b) yes
c) yes
d) I guess you mean `SiD_Ecal.xml` again
https://github.com/AIDASoft/DD4hep/blob/05508d0478bd8ea400fb48530affdcd39160d685/DDDetectors/compact/SiD/SiD_Ecal.xml#L27
e) `name` is just a string.

calorimeterType and EM_BARREL seem to be a left over of the "SLIC", geoConverter origins of the SiD example.
https://github.com/AIDASoft/DD4hep/blob/c8a425b30b3832d858045265c969b17cca1f6d82/DDCore/src/plugins/PandoraConverter.cpp#L152
(note this is "java" and commented)

We are now using "type_flags" to identify calorimeter and other type of detectors
https://github.com/iLCSoft/lcgeo/blob/a5d2309dc39c20b4570b9d586dea5c4eb6ea2495/CLIC/compact/CLIC_o3_v14/ECalBarrel_o2_v01_02.xml#L26
```
   <type_flags type=" DetType_CALORIMETER + DetType_ELECTROMAGNETIC + DetType_BARREL"/>
```
Defined in 
https://github.com/AIDASoft/DD4hep/blob/05508d0478bd8ea400fb48530affdcd39160d685/DDDetectors/compact/detector_types.xml

**Comment by saraheno** [comment]
where is the components file located?
