### ISSUE TITLE
Adding a new subdetector library example

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#806]
Hi,
I wanted to setup an example for my dual crystal calorimeter.  I forked DD4hep to: https://github.com/saraheno/DD4hep

I copied code similar to that in DD4hep/DDDetectors to this area and added a start of the crystal calorimeter routine https://github.com/saraheno/DD4hep/blob/master/examples/dualcrystal/src/CrystalEcalBarrel_geo.cpp  and also at https://github.com/saraheno/DD4hep/blob/master/examples/dualcrystal/SCEPCdetector/SCEPCAL.xml

However, when I try to use geoDisplay, it cannot find the new detector.  I assume this is because the new detector is in the wrong library.  If I compare to a routine that it can display (EcalBarrel_geo.cpp, I see them in different libraries

```
[eno@hepcms-in2 build]$ grep -r DD4hep_EcalBarrel *
Binary file DDDetectors/CMakeFiles/DDDetectors.dir/src/EcalBarrel_geo.cpp.o matches
examples/lib/libdualcrystal.components:v2::libdualcrystal.so.1.16:DD4hep_EcalBarrel
Binary file examples/lib/libdualcrystal.so.1.16 matches
Binary file examples/dualcrystal/CMakeFiles/dualcrystal.dir/src/EcalBarrel_geo.cpp.o matches
Binary file lib/libDDDetectors.so.1.16 matches
lib/libDDDetectors.components:v2::libDDDetectors.so.1.16:DD4hep_EcalBarrel
[eno@hepcms-in2 build]$ grep -r DD4hep_CEcalBarrel *
examples/lib/libdualcrystal.components:v2::libdualcrystal.so.1.16:DD4hep_CEcalBarrel
Binary file examples/lib/libdualcrystal.so.1.16 matches
Binary file examples/dualcrystal/CMakeFiles/dualcrystal.dir/src/CrystalEcalBarrel_geo.cpp.o matches
```

Is there some way I can put code in the examples area but still use geoDisplay to visiualize the geometry?

**Comment by saraheno** [comment]
I was looking at 

DD4hep/examples/DDCMS

in its makefile it has

#  Test CMS tracker detector construction
dd4hep_add_test_reg( DDCMS_LoadGeometry
  COMMAND    "${CMAKE_INSTALL_PREFIX}/bin/run_test_DDCMS.sh"
  EXEC_ARGS  geoDisplay
  -input file:${CMAKE_CURRENT_SOURCE_DIR}/data/dd4hep-config.xml
  -destroy -print WARNING -load
  REGEX_PASS "Instrumented 5 subdetectors with 36091 DetElements 25776 sensitives\
 out of 224404 volumes and 1161 sensitive placements."
  REGEX_FAIL "Exception"
  REGEX_FAIL "FAILED"
  )


I think I might need something like this?    What does the DDCMS_LoadGeometry do?  Is this one the right track?

**Comment by MarkusFrankATcernch** [comment]
@saraheno 
At the first level you do not need a test entry. 
But:
- If you copy DDDetectors, you have to eliminate all files except the one containing your detector
- You need to specify the proper factory both in the C++ snippet and in the xml file you use to instantiate this detector.
From your git clone this seems to be done properly, but you have to remove all factories with duplicate names, so that
only the CrystalEcalBarrel files are left.

Then you have to check if your factory is properly listed in the lib/libdualcrystal.components file. 
If this entry is not present something went wrong in building. We will have to have a look there first.

**Comment by saraheno** [comment]
Thanks Markus.  I cleaned it up, removing the duplicate files.  I also renamed the example to DDDualCrystal to conform better to the naming convention in examples.  However, I am still getting a similar error.  

The cleaned code is in:  https://github.com/saraheno/DD4hep

the libDDDualCrystal.components looks like:


[eno@hepcms-in2 build]$ pwd
/home/eno/dd4hep/DD4hep/build
[eno@hepcms-in2 build]$ cat ./examples/lib/libDDDualCrystal.components
v2::libDDDualCrystal.so:CrystalEcalBarrel
v2::libDDDualCrystal.so:DD4hep_CrystalEcalBarrel


The bottom of DD4hep/examples/DDDualCrystal/SCEPCdetector/CrystalEcalBarrel_geo.cpp looks like


DECLARE_DETELEMENT(DD4hep_CrystalEcalBarrel,create_detector)
DECLARE_DEPRECATED_DETELEMENT(CrystalEcalBarrel,create_detector)

The xml file I am running is: /DD4hep/examples/DDDualCrystal/SCEPCdetector/SCEPCAL.xml
which points to
DD4hep/examples/DDDualCrystal/SCEPCdetector/SCEPCAL/SCEPCAL_CrystalEcalBarrel.xml
which contains
<detectors>
  <detector id="EcalBarrel_ID" name="CrystalEcalBarrel" type="DD4hep_CrystalEcalBarrel" readout="CrystalEcalBarrelHits" vis="CrystalEcalBarrelVis" calorimeterType="EM_BARREL">


The error message is:
[eno@hepcms-in2 SCEPCdetector]$ pwd
/home/eno/dd4hep/DD4hep/examples/DDDualCrystal/SCEPCdetector
[eno@hepcms-in2 SCEPCdetector]$ geoDisplay SCEPCAL.xml
PersistencyIO    INFO  +++ Set Streamer to dd4hep::OpaqueDataBlock
Info in <TGeoManager::TGeoManager>: Geometry default, Detector Geometry created
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
CompactLoader    INFO  +++ Processing compact file: SCEPCAL.xml with flag BUILD_DEFAULT
DD4hep           WARN  ++ STD conditions NOT defined by client. NTP defaults taken.
Detector         INFO  *********** Created World volume with size: 3000 3000 3000
Info in <TGeoManager::SetTopVolume>: Top volume is world_volume. Master volume is world_volume
Compact          ERROR FAILED     subdetector:CrystalEcalBarrel of type DD4hep_CrystalEcalBarrel [sensitive]
PluginService    ERROR Factory requested: DD4hep_CrystalEcalBarrel (N10__cxxabiv120__function_type_infoE) :bad any_cast
PluginService    ERROR Stub is invalid!
Compact          ERROR ++ FAILED    to convert subdetector: CrystalEcalBarrel: Failed to execute subdetector creation plugin.              No factory with name Create(DD4hep_CrystalEcalBarrel) for type DD4hep_CrystalEcalBarrel found.
                Please check library load path and/or plugin factory name.

****************************************************
*  A runtime error has occured :
*    Failed to execute subdetector creation plugin.             No factory with name Create(DD4hep_CrystalEcalBarrel) for type DD4hep_CrystalEcalBarrel found.
                Please check library load path and/or plugin factory name.
*  the program will have to be terminated - sorry.
****************************************************

**Comment by andresailer** [comment]
>                 Please check library load path and/or plugin factory name.
Is the folder where libDDDualCrystal.so is located in the LD_LIBRARY_PATH?
Did you `source bin/thisDDDualCrystal.sh` (?)
There probably isn't a file like this...
You need to add a line like this
https://github.com/AIDASoft/DD4hep/blob/c8a425b30b3832d858045265c969b17cca1f6d82/examples/ClientTests/CMakeLists.txt#L53

**Comment by saraheno** [comment]
Thanks!  Indeed I had forgotten the source bin/this...

I guess you can close this.

**Comment by andresailer** [comment]
Did you have to add the `dd4hep_configure_scripts`?

**Comment by saraheno** [comment]
no, I did not.

**Comment by saraheno** [comment]
So I have another linking/building problem.  Since I could now link the basic geometry, I tried to add code like your DDG4_MySensDet

The code is at: https://github.com/saraheno/DD4hep/tree/master/examples/DDDualCrystal/src
and you can see the naming convention is following your convention.

I thought the CMakeLists.txt https://github.com/saraheno/DD4hep/blob/master/examples/DDDualCrystal/CMakeLists.txt would pick up this new code 

but there seems to be a problem?  
When I make a new build area, do
 cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=ON -DDD4HEP_USE_HEPMC3=ON -DBUILD_TESTING=ON -DDD4HEP_USE_XERCESC=ON -DCMAKE_CXX_STANDARD=17 -DGeant4_DIR=$G4INSTALL/lib/Geant4-10.4.0 -DROOT_DIR=$ROOTSYS -DDD4HEP_BUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release ..


and then look for it being picked up.  When I do 

 grep -r CrystalEcalBarrel_geo * in the build area, I can see it found this file in the same area.

but when I do  grep -r DualCrystalCalorimeter *
I get nothing...

**Comment by andresailer** [comment]
Works for me. Maybe there is an error when cmake runs?
```
DD4hep/examples/DDDualCrystal/build (eno_Master)$ grep -r DualCrystalCalorimeter * | tail
Makefile:.PHONY : src/DualCrystalCalorimeterSDAction.s
Makefile:src/DualCrystalCalorimeterSDAction.cpp.s:
Makefile:	$(MAKE) $(MAKESILENT) -f CMakeFiles/DDDualCrystal.dir/build.make CMakeFiles/DDDualCrystal.dir/src/DualCrystalCalorimeterSDAction.cpp.s
Makefile:.PHONY : src/DualCrystalCalorimeterSDAction.cpp.s
Makefile:	@echo "... src/DualCrystalCalorimeterHit.o"
Makefile:	@echo "... src/DualCrystalCalorimeterHit.i"
Makefile:	@echo "... src/DualCrystalCalorimeterHit.s"
Makefile:	@echo "... src/DualCrystalCalorimeterSDAction.o"
Makefile:	@echo "... src/DualCrystalCalorimeterSDAction.i"
Makefile:	@echo "... src/DualCrystalCalorimeterSDAction.s"
```

**Comment by saraheno** [comment]
interesting.  So I guess it must be something wrong with ...  actually I think I am using CMAKE from source /cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-centos7-gcc10-opt/setup.sh so it should be the same CMAKE installation as you?


I don't know what could be wrong...

[eno@hepcms-in2 build]$ find ./ -name "*DDDu*" -print
./examples/CMakeFiles/Components_DDDualCrystal.dir
./examples/CMakeFiles/DDDualCrystal.dir
[eno@hepcms-in2 build]$ ls ./examples/CMakeFiles/DDDualCrystal.dir/
build.make         DependInfo.cmake  flags.make  progress.make
cmake_clean.cmake  depend.make       link.txt    src
[eno@hepcms-in2 build]$ grep -r Hit ./examples/CMakeFiles/DDDualCrystal.dir/*


I attach the spew from the CMAKE


[cmake_spew_DDDualCrystal.txt](https://github.com/AIDASoft/DD4hep/files/6310669/cmake_spew_DDDualCrystal.txt)

**Comment by andresailer** [comment]
Ahh, yes, you are in DD4hep/build.

I was in DD4hep/examples/DDDualCrystal/build using an pre-existing DD4hep

You should probably replace
https://github.com/saraheno/DD4hep/blob/27abfeac4e9bee90f2e61ff6acdcf8a9e2ad4ce6/examples/CMakeLists.txt#L55-L59
with
```
add_subdirectory(DDDualCrystal)
```

This should have used the correct folder name `DDDualCrystal` instead of dualcrystal
https://github.com/saraheno/DD4hep/commit/e2eb1f21b7d4281f501a39359084cb4dbb175145#diff-940e5356fa1137e646ea135a6f68cacbfad4fe7124c3a69163468f588acf9283R44

```diff 
- SET(DD4HEP_EXAMPLES "AlignDet CLICSiD ClientTests Conditions DDCMS DDCodex DDDigi DDG4 DDG4_MySensDet LHeD OpticalSurfaces Persistency DDCAD SimpleDetector"
+ SET(DD4HEP_EXAMPLES "AlignDet CLICSiD ClientTests Conditions DDCMS DDCodex DDDigi DDG4 DDG4_MySensDet LHeD OpticalSurfaces Persistency DDCAD SimpleDetector dualcrystal"
```

**Comment by andresailer** [comment]
Probably better you undo the changes in examples/CMakeLists and just add DDDualCrystal to the list.

**Comment by saraheno** [comment]
that did it!

**Comment by saraheno** [comment]
The thing (https://github.com/saraheno/DD4hep) builds now.  But when I try to run it with

cd examples/DDDDualCrystal/SCEPCdetector

 ddsim --compactFile=./SCEPCAL.xml --runType=batch -G -N=2  --steeringFile SCEPCALsteering.py --outputFile=testSCEPCAL.root --gun.position "0.0 0.0 1.0*cm" --gun.direction "0.0 1.0 0.1" --gun.energy "30*GeV" --part.userParticleHandler=""   --gun.particle "e-"

I get an error which is shown in the attached file.  So somehow my new sensitive detector is not getting found?

[run_spew.txt](https://github.com/AIDASoft/DD4hep/files/6313110/run_spew.txt)

**Comment by MarkusFrankATcernch** [comment]
You sure there is no typo: 
DualCrystalCalorimeterSDAction  (DualCrystalCalorimeterSDAction.cpp) <-> Geant4DualCrystalCalorimeterAction (script)

**Comment by saraheno** [comment]
so in the steering,py, I should have

##  set the default calorimeter action
SIM.action.calo = "DualCrystalCalorimeterSDAction"

unfortunately that doesn't work either

[runagain.txt](https://github.com/AIDASoft/DD4hep/files/6313468/runagain.txt)

**Comment by MarkusFrankATcernch** [comment]
What is the string inside the components file ?
Could you please post the components file generated by the example ?
Either the components file was not generated properly or the LD_LIBRARY_PATH was incorrect and did not contain this location.
Thanks

**Comment by saraheno** [comment]
where is the components file located

**Comment by MarkusFrankATcernch** [comment]
It is the same location where the library is located.
It has the same file name as the library, but the extension .components
It must be in the LD_LIBRARY_PATH

**Comment by saraheno** [comment]
I guess the library is at:
[eno@hepcms-in2 DD4hep]$ pwd
/home/eno/dd4hep/DD4hep
[eno@hepcms-in2 DD4hep]$

[eno@hepcms-in2 DD4hep]$ find ./ -name "*DualCrystal*so*" -print
./lib/libDDDualCrystal.so
./build/examples/DDDualCrystal/lib/libDDDualCrystal.so


and when I look these two directories, I see

[eno@hepcms-in2 DD4hep]$ ls ./lib*
G__DD4hepGeo_rdict.pcm            libDDDigi.so
G__DD4hepProperties_rdict.pcm     libDDDigi.so.1.16
G__DD4hep_rdict.pcm               libDDDualCrystal.components
G__DD4hepSegmentations_rdict.pcm  libDDDualCrystal.so
G__DDCAD_rdict.pcm                libDDEvePlugins.components
G__DDCond_rdict.pcm               libDDEvePlugins.so
G__DDDigi_rdict.pcm               libDDEvePlugins.so.1.16
G__DDEve_rdict.pcm                libDDG4HepMC3.components
G__DDG4IO_rdict.pcm               libDDG4HepMC3.so
G__DDG4Python_rdict.pcm           libDDG4HepMC3.so.1.16
G__DDG4_rdict.pcm                 libDDG4IO.so
G__DDPython_rdict.pcm             libDDG4IO.so.1.16
G__DDRec_rdict.pcm                libDDG4LCIO.components
G__eve1_rdict.pcm                 libDDG4LCIO.so
G__eve_rdict.pcm                  libDDG4LCIO.so.1.16
libDD4hepGaudiPluginMgr.so        libDDG4Legacy.components
libDD4hepGaudiPluginMgr.so.1.16   libDDG4Legacy.so
libDDAlignPlugins.components      libDDG4Legacy.so.1.16
libDDAlignPlugins.so              libDDG4Plugins.components
libDDAlignPlugins.so.1.16         libDDG4Plugins.so
libDDAlign.so                     libDDG4Plugins.so.1.16
libDDAlign.so.1.16                libDDG4Python.components
libDDCADPlugins.components        libDDG4Python.so
libDDCADPlugins.so                libDDG4Python.so.1.16
libDDCADPlugins.so.1.16           libDDG4.so
libDDCAD.so                       libDDG4.so.1.16
libDDCAD.so.1.16                  libDDGDMLPlugins.components
libDDCondPlugins.components       libDDGDMLPlugins.so
libDDCondPlugins.so               libDDGDMLPlugins.so.1.16
libDDCondPlugins.so.1.16          libDDParsers.so
libDDCond.so                      libDDParsers.so.1.16
libDDCond.so.1.16                 libDDPythonPlugins.components
libDDCorePlugins.components       libDDPythonPlugins.so
libDDCorePlugins.so               libDDPythonPlugins.so.1.16
libDDCorePlugins.so.1.16          libDDPython.so
libDDCore.so                      libDDPython.so.1.16
libDDCore.so.1.16                 libDDRecPlugins.components
libDDDetectors.components         libDDRecPlugins.so
libDDDetectors.so                 libDDRecPlugins.so.1.16
libDDDetectors.so.1.16            libDDRec.so
libDDDigiPlugins.components       libDDRec.so.1.16
libDDDigiPlugins.so               python3.8
libDDDigiPlugins.so.1.16


and 

[eno@hepcms-in2 DD4hep]$ ls build/examples/DDDualCrystal/lib/
libDDDualCrystal.components  libDDDualCrystal.so


there is a "components" file in the first, libDDDualCrystal.components and it has the following contents
File Edit Options Buffers Tools Help
v2::libDDDualCrystal.so:CrystalEcalBarrel
v2::libDDDualCrystal.so:DD4hep_CrystalEcalBarrel


So I guess it is missing what I need.  How do I get it in there?

**Comment by saraheno** [comment]
nevermind... I forgot to do the make install!

**Comment by MarkusFrankATcernch** [comment]
;-)))
