### ISSUE TITLE
proper CMAKELists.txt for a dictionary for a new hit definition

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#810]
In https://github.com/saraheno/DD4hep/tree/master/examples/DDDualCrystal

I have tried to follow the example in examples/DDG4_MySensDet to make a new calorimeter hit class.  However, to access the hits in the root file produced by ddsim, I am told I need to define a dictionary in the CMakeLists.txt file.  

I had put in

```cmake
if (DD4HEP_USE_GEANT4)
  #---------------------------  Plugin library for the simulation framew\
ork  ---------
  dd4hep_add_dictionary(G__DDDualCrystalCalorimeter
    SOURCES ${DD4hep_DIR}/include/ROOT/Warnings.h src/DualCrystalCalorim\
eterHit.h
    LINKDEF ${DD4hep_DIR}/include/ROOT/LinkDef.h
    OUTPUT  ${LIBRARY_OUTPUT_PATH}
    USES    DD4hep::DDCore DD4hep::DDG4 Geant4::Interface
    )
endif()
```
but that gave make install errors.  it was suggested that I change this to

```cmake
if (DD4HEP_USE_GEANT4)
  #---------------------------  Plugin library for the simulation framew\
ork  ---------
  dd4hep_add_dictionary(G__DDDualCrystalCalorimeter
    SOURCES ${DD4hep_DIR}/include/ROOT/Warnings.h src/DualCrystalCalorim\
eterHit.h
    LINKDEF ${DD4hep_DIR}/include/ROOT/LinkDef.h
    OUTPUT  ${LIBRARY_OUTPUT_PATH}
    USES    DD4hep::DDCore DD4hep::DDG4 Geant4::Interface
    )


GENERATED G__DDDualCrystalCalorimeter.cxx


endif()
```
but when I try
```
 cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=ON -DDD4HEP_USE_HEPMC3=ON -DBUILD_TESTING=ON -DDD4HEP_USE_XERCESC=ON -DCMAKE_CXX_STANDARD=17 -DGeant4_DIR=$G4INSTALL/lib/Geant4-10.4.0 -DROOT_DIR=$ROOTSYS -DDD4HEP_BUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release ..
```

I get the error
```
-- |++> Building Plugin: SimpleDetector
-- |++> Setting up test environment for SimpleDetector: Testing:ON Setup:TRUE With Tests(TRUE): DIRS: SimpleDetector
-- |++> Enable CTest environment....BUILD:ON
-- |> Building DDDualCrystal
CMake Error at examples/DDDualCrystal/CMakeLists.txt:54:
  Parse error.  Expected "(", got unquoted argument with text
  "G__DDDualCrystalCalorimeter.cxx".
```

I will confess the Cmake mystifies me.  Any help would be appreciated.

**Comment by MarkusFrankATcernch** [comment]
You have to close the bracket at dd4hep_add_dictionary(...)
AFTER 
GENERATED G__DDDualCrystalCalorimeter.cxx
Then it should work.

**Comment by saraheno** [comment]
thanks it is working now.

**Comment by andresailer** [comment]
>  it was suggested that I change this to

I just want to clarify that it was suggested add the line  "GENERATED G__DDDualCrystalCalorimeter.cxx" to dd4hep_add_plugin.

Which is done correctly now
https://github.com/saraheno/DD4hep/blob/6a1d1221d405a093873bbe886a119808b5895346/examples/DDDualCrystal/CMakeLists.txt#L70


And can also be seen in the example

https://github.com/AIDASoft/DD4hep/blob/9bbe12b080ce52615251facc6f6ff5dd58a60e69/examples/DDG4_MySensDet/CMakeLists.txt#L38-L50
