### ISSUE TITLE
turning on cerenkov radiation

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#811]
In a previous issue, in November, you gave me instructions on how to turn on cerenkov radiation.  I had to give a material an index of refraction and then you said:

"At the moment it might be the easiest to add this to DDG4/python/DDSim/Helper/Physics.py in the setupPhysics function

    # Add cerenkov physics
    seq = kernel.physicsList()
    cerenkov = PhysicsList(kernel, 'Geant4CerenkovPhysics/CerenkovPhys')
    cerenkov.MaxNumPhotonsPerStep = 10
    cerenkov.MaxBetaChangePerStep = 10.0
    cerenkov.TrackSecondariesFirst = True
    cerenkov.VerboseLevel = 2
    cerenkov.enableUI()
    seq.adopt(cerenkov)
We will have to come up with something for users to extend the simulation easily"

Unfortunately, this recipe does not seem to work now.  I made these changes in DDG4/python/DDSim/Helper and then did the standard cmake, make, make install

but there is no sign of cerenkov photons being made when I run by:

 ddsim --compactFile=./SCEPCAL.xml --runType=batch -G -N=10  --steeringFile SCEPCALsteering.py --outputFile=testSCEPCAL.root --gun.position "0.0 0.0 1.0*cm" --gun.direction "0.0 1.0 0.1" --gun.energy "30*GeV" --part.userParticleHandler=""   --gun.particle "e-" >& haha.txt

The steering file is https://github.com/saraheno/DD4hep/blob/master/examples/DDDualCrystal/SCEPCdetector/SCEPCALsteering.py

and I attach the spew from ddsim

[haha.txt](https://github.com/AIDASoft/DD4hep/files/6353297/haha.txt)

**Comment by andresailer** [comment]
Original comment
https://github.com/AIDASoft/DD4hep/issues/703#issuecomment-705652757

Did you also add whatever you added for this comment https://github.com/AIDASoft/DD4hep/issues/703#issuecomment-716840605 ?

**Comment by saraheno** [comment]
yes, I copied the code from the previous area.

**Comment by saraheno** [comment]
also, can you remind me how/when is DDG4/python/DDSim/Helper/Physics.py called?  Because right now, when I put debug couts into DDG4/plugins/Geant4CerenkovPhysics.cpp it doesn't looks like it is being called.  But when I add those extra lines to the Physics.py, it calls this to update the settings, right?

**Comment by andresailer** [comment]
Yes this helper file is still being used.  It is called by

https://github.com/AIDASoft/DD4hep/blob/9bbe12b080ce52615251facc6f6ff5dd58a60e69/DDG4/python/DDSim/DD4hepSimulation.py#L475

**Comment by saraheno** [comment]
and if I did add those lines to the Physics.py, shouldn't it call DDG4/plugins/Geant4CerenkovPhysics.cpp

**Comment by andresailer** [comment]
What are "those lines"? Can you push your `Physics.py` to your fork?

**Comment by saraheno** [comment]
it is there now

**Comment by saraheno** [comment]
oh wait.  I have too many ret seq, right?

**Comment by andresailer** [comment]
yeah

**Comment by saraheno** [comment]
Now it tunrs, but I'm getting this error


---------------------------------------------------
                           Hadronic Processes for triton

  Process: hadElastic
        Model:              hElasticLHEP: 0 eV /n ---> 100 TeV/n
     Cr_sctns:  Glauber-Gribov Nucl-nucl: 0 eV  ---> 25.6 PeV

  Process: tInelastic
        Model:  Binary Light Ion Cascade: 0 eV /n ---> 6 GeV/n
        Model:                      FTFP: 3 GeV/n ---> 100 TeV/n
     Cr_sctns:  Glauber-Gribov Nucl-nucl: 0 eV  ---> 25.6 PeV

================================================================
ParticleHandler  FATAL +++ Add Primary    0 G4:   1 [e-          ,  lepton] reason:     158 E:+3.00e+04 in record:YES  #Par:  0      #Dau:  0



any idea what this is?

**Comment by saraheno** [comment]
I'm going to try rebuilding from scratch.  I'll let you know if that fixes it.

**Comment by saraheno** [comment]
So, just in case anybody gets this error again, it is a message you seem to get when you set 

SIM.output.part = 7

in  your steering file when you use a steering file doing something like

ddsim --compactFile=./SCEPCAL.xml --runType=batch -G -N=2  --steeringFile SCEPCALsteering.py --outputFile=testSCEPCAL.root --gun.position "0.0 0.0 1.0*cm" --gun.direction "0.0 1.0 0.1" --gun.energy "30*GeV" --part.userParticleHandler=""   --gun.particle "e-"
