### ISSUE TITLE
question about DDG4_MySensDet/scripts/MyTrackerSD_sim.py

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#814]
Thank you providing this example.  I was looking at trying to write a script like this for my calorimeter.  However, I do not understand the lines:
```
  seq, act = geant4.setupTracker('SiliconBlockUpper')
  act.OutputLevel = Output.INFO
  seq, act = geant4.setupTracker('SiliconBlockDown')
  act.OutputLevel = Output.INFO
````

when I grep SiliconBlockUpper in examples/DDG4_MySensDet, they only show up in this script.  

When I look at DDCMS/scripts/CMSEcalSim.py, they have instead

```
 # Now setup all tracking detectors
  for i in geant4.description.detectors():
    o = DDG4.DetElement(i.second.ptr())
    sd = geant4.description.sensitiveDetector(o.name())
    if sd.isValid():
      type = geant4.sensitive_types[sd.type()]
      logger.info('CMSTracker: Configure subdetector %-24s of type %s' % (o.name(), type,))
      geant4.setupDetector(o.name(), type)

  # And handle the simulation particles.
  part = DDG4.GeneratorAction(kernel, "Geant4ParticleHandler/ParticleHandler")
  kernel.generatorAction().adopt(part)
  part.SaveProcesses = ['conv', 'Decay']
  part.MinimalKineticEnergy = 1 * MeV
  part.OutputLevel = 5  # generator_output_level
  part.enableUI()

```

I guess I would want something more like this for my case?  or?  (and I guess it is actually setting up calorimeters, not trackers?  the "tracker" is just left over from copying and paste from CMSTrackerSim.py?

Is this in general a better way to run than using
```
ddsim --compactFile=./SCEPCAL.xml --runType=batch -G -N=2  --steeringFile SCEPCALsteering.py --outputFile=testSCEPCAL.root --gun.position "0.0 0.0 1.0*cm" --gun.direction "0.0 1.0 0.1" --gun.energy "30*GeV" --part.userParticleHandler=""   --gun.particle "e-"
```

and I guess I need a line like 
```
geant4 = DDG4.Geant4(kernel, calorimeter='DDDualCrystalCalorimeterSDAction')
```
but am not sure where to put it?
  I've put a guess at what might work at: https://github.com/saraheno/DD4hep/blob/master/examples/DDDualCrystal/scripts/SCEPCAL_sim.py

**Comment by andresailer** [comment]
Why do you want to write this script?

**Comment by saraheno** [comment]
I thought it might be a more standard way to run the geant, since that is the way you chose in DDG4_MySensDet?

**Comment by andresailer** [comment]
Please try using ddsim. It should be much easier to configure from the user point of view.

**Comment by saraheno** [comment]
yes, that is what I have been using.  So if that is the preferred way, then I won't make the script.

**Comment by andresailer** [comment]
Thanks!
