### ISSUE TITLE
geoDisplay error: Segmentation: FAILED to create segmentation: GridDRcalo

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#815]
So now that I have a rough dual crystal calorimeter working (Thanks so much for your help!) I wanted to add the back end spaghetti dual readout hadron calorimeter.  I use a a start the lovely code by Sanghyuan Ko at https://github.com/SanghyunKo/dual-readout

I copied what I thought were the relevent pieces into my area: https://github.com/saraheno/DD4hep/tree/master/examples/DDDualCrystal/src

The code from his repository has names with "DR" in them.

It all seemed to compile fine.

But when I tried to look at his calorimeter using geoDisplay using

geoDisplay DRcalo.xml (this file is at https://github.com/saraheno/DD4hep/blob/master/examples/DDDualCrystal/SCEPCdetector/DRcalo.xml )

I find somehow I am missing some code or some link or something

[eno@hepcms-in2 SCEPCdetector]$ geoDisplay DRcalo.xml
PersistencyIO    INFO  +++ Set Streamer to dd4hep::OpaqueDataBlock
Info in <TGeoManager::TGeoManager>: Geometry default, Detector Geometry created
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
CompactLoader    INFO  +++ Processing compact file: DRcalo.xml with flag BUILD_DEFAULT
DD4hep           WARN  ++ STD conditions NOT defined by client. NTP defaults taken.
Detector         INFO  *********** Created World volume with size: 1000 1000 1000
Info in <TGeoManager::SetTopVolume>: Top volume is world_volume. Master volume is world_volume
Segmentation     ERROR FAILED to create segmentation: GridDRcalo. [Missing factory]
RunPlugin        ERROR ++ Exception while executing plugin DD4hep_CompactLoader:
                Segmentation: FAILED to create segmentation: GridDRcalo. [Missing factory]
dd4hep: Error interpreting XML nodes of type <readout/>
dd4hep: Error interpreting XML nodes of type <readouts/>
dd4hep: while parsing DRcalo.xml
dd4hep: with plugin:DD4hep_CompactLoader
Application      ERROR geoPluginRun: Uncaught exception: RunPlugin: ++ Exception while executing plugin DD4hep_CompactLoader:
                Segmentation: FAILED to create segmentation: GridDRcalo. [Missing factory]
dd4hep: Error interpreting XML nodes of type <readout/>
dd4hep: Error interpreting XML nodes of type <readouts/>
dd4hep: while parsing DRcalo.xml
dd4hep: with plugin:DD4hep_CompactLoader

Any idea what might be wrong?
 to me it looks like the right code should be there
[eno@hepcms-in2 src]$ grep -ri factory *
CrystalEcalBarrel_geo.cpp:#include "DD4hep/DetFactoryHelper.h"
DRparamBarrel.h:#include "DD4hep/DetFactoryHelper.h"
DRparamBase.h:#include "DD4hep/DetFactoryHelper.h"
DRparamEndcap.h:#include "DD4hep/DetFactoryHelper.h"
DualCrystalCalorimeterSDAction.cpp://--- Factory declaration

**Comment by andresailer** [comment]
As before, when plugins (GridDRcalo in this case, not factory) cannot be found you have to check the components file where this plugin should be in, if the pieces of code are compiled and installed, and the library and components file are part of a folder in the LD_LIBRARY_PATH. There is nothing about GridDRcalo in the libDDDualCrystal.components file. Though as GridDRcalo was compiled. I compared with what is happening for the Segmentations existing for DD4hep, which are part of DDCore and found them in the components file. Further investigations lead me to the missing DECLARE_SEGMENTATION call.

There needs to be a little bit of re-arranging in DD4hep to support this more easily, as soon as #817 is merged, I'll let you know how to change the file.

**Comment by saraheno** [comment]
Thanks Andre.

Where does the DECLARE_SEGMENTATION call go?

**Comment by saraheno** [comment]
So the current code has 
REGISTER_SEGMENTATION(GridDRcalo)


Is DECLARE_SEGMENTATION  a replacement for that?

**Comment by saraheno** [comment]
I don't think that create_segmentation, which is called by DECLARE_SEGMENTATION in the examples in DDCORE can be used outside of DDCore.

It is defined in DDCORE/src/plugins and it is both defined and only used there.  When I try to put it into my code, I get

[ 97%] Built target Components_SimpleDetector
[ 97%] Building CXX object examples/DDDualCrystal/CMakeFiles/DDDualCrystal.dir/src/GridDRcalo.cpp.o
In file included from /home/eno/dd4hep/DD4hep/examples/DDDualCrystal/src/GridDRcalo.h:5,
                 from /home/eno/dd4hep/DD4hep/examples/DDDualCrystal/src/GridDRcalo.cpp:2:
/home/eno/dd4hep/DD4hep/examples/DDDualCrystal/src/GridDRcalo.cpp: In static member function ‘static dd4hep::SegmentationObject* dd4hep::SegmentationFactory<T>::create(const dd4hep::DDSegmentation::BitFieldCoder*) [with T = dd4hep::{anonymous}::GridDRcalo]’:
/home/eno/dd4hep/DD4hep/examples/DDDualCrystal/src/GridDRcalo.cpp:3:33: error: ‘create_segmentation’ was not declared in this scope
    3 | DECLARE_SEGMENTATION(GridDRcalo,create_segmentation<dd4hep::DDSegmentation::GridDRcalo>)
      |                                 ^~~~~~~~~~~~~~~~~~~
/home/eno/dd4hep/DD4hep/DDCore/include/DD4hep/Factories.h:256:90: note: in definition of macro ‘DECLARE_SEGMENTATION’
  256 | ame>::create(const DDSegmentation::BitFieldCoder* d) { return func(d); } \
      |                                                               ^~~~

/home/eno/dd4hep/DD4hep/examples/DDDualCrystal/src/GridDRcalo.cpp:3:87: error: expected primary-expression before ‘>’ token
    3 | ATION(GridDRcalo,create_segmentation<dd4hep::DDSegmentation::GridDRcalo>)
      |                                                                        ^

/home/eno/dd4hep/DD4hep/DDCore/include/DD4hep/Factories.h:256:90: note: in definition of macro ‘DECLARE_SEGMENTATION’
  256 | ame>::create(const DDSegmentation::BitFieldCoder* d) { return func(d); } \
      |                                                               ^~~~

make[2]: *** [examples/DDDualCrystal/CMakeFiles/DDDualCrystal.dir/src/GridDRcalo.cpp.o] Error 1
make[1]: *** [examples/DDDualCrystal/CMakeFiles/DDDualCrystal.dir/all] Error 2
make: *** [all] Error 2

**Comment by andresailer** [comment]
> as soon as #817 is merged, I'll let you know how to change the file.

**Comment by andresailer** [comment]
If you pull the latest DD4hep master, maybe also including #818 .
You just need to remove
REGISTER_SEGMANTATION and replace the include
```diff
diff --git a/examples/DDDualCrystal/src/GridDRcalo.cpp b/examples/DDDualCrystal/src/GridDRcalo.cpp
index d4010c01..0a61b5ee 100644
--- a/examples/DDDualCrystal/src/GridDRcalo.cpp
+++ b/examples/DDDualCrystal/src/GridDRcalo.cpp
@@ -1,6 +1,6 @@
 #include "GridDRcalo.h"
 
-#include "DD4hep/detail/SegmentationsInterna.h"
+#include "DD4hep/Factories.h"
 
 #include <climits>
 #include <cmath>
@@ -227,7 +227,6 @@ DRparamBase* GridDRcalo::setParamBase(int noEta) const {
   return paramBase;
 }
 
-REGISTER_SEGMENTATION(GridDRcalo)
 }
```

**Comment by saraheno** [comment]
Thanks.  My code is running okay right now, so probably I'll try this in about a month.

**Comment by andresailer** [comment]
It would be great if you could try this now. It would be more effort for me to re-investigate this issue in about a month.
Thanks.

**Comment by saraheno** [comment]
okay.  I teach most of today, but will try tomorrow.

**Comment by saraheno** [comment]
I made the change and it worked well.

**Comment by andresailer** [comment]
Thank you for confirming the fix works.
