### ISSUE TITLE
Significant memory increase of GeoHandler from v01-15

### ISSUE THREAD

**Issue by SanghyunKo** [AIDASoft/DD4hep#820]
While moving from DD4hep v01-12-01 to v01-16-01, I realized that my application's memory consumption increased significantly (almost 3-4 times). To factor out which caused the issue, I checked out several versions of DD4hep and found that it happens when moving from v01-14-01 to v01-15.

I made a minimal (but heavy enough to track memory increase) example to reproduce the issue: https://github.com/SanghyunKo/ddG4Demo. Profiling memory usage with this example, it seems that the new object
```
std::pair<std::_Rb_tree_iterator<std::pair<TGeoNode const*, TGeoNode const*>>, bool> std::_Rb_tree<std::pair<TGeoNode const*, TGeoNode const*>, std::pair<TGeoNode const*, TGeoNode const*>, std::_Identity<std::pair<TGeoNode const*, TGeoNode const*>>, std::less<std::pair<TGeoNode const*, TGeoNode const*>>, std::allocator<std::pair<TGeoNode const*, TGeoNode const*>>>::_M_emplace_unique<std::pair<TGeoNode const*. TGeoNode const*>>(std::pair<TGeoNode const*, TGeoNode const*>&&)
```
is added from v01-15 and occupying most of the heap, which is called by `dd4hep::detail::GeoHandler::i_collect(TGeoNode const*, TGeoNode const*, int, dd4hep::Region, dd4hep::LimitSet)`.

#### v01-14-01
![cap01](https://user-images.githubusercontent.com/37464245/116684218-a7a5c600-a9eb-11eb-96aa-5d719dae7671.png)
#### v01-15 (and beyond)
![cap02](https://user-images.githubusercontent.com/37464245/116684298-c5732b00-a9eb-11eb-8951-f4ee09bb1ac3.png)

Guessing from the name of the function and PR between v01-14-01 and v01-15, the line [here](https://github.com/AIDASoft/DD4hep/pull/734/files#diff-4ab4678be68e428e34209aaa4003030d0791273a55bc75c78569e2774fd1ddbaR157) looks suspicious to me (but not sure). Could you look into the issue?

 - OS version: cc7
 - Compiler version: gcc8.3
 - DD4hep version: v01-15
 - Reproduced by: https://github.com/SanghyunKo/ddG4Demo

**Comment by MarkusFrankATcernch** [comment]
Thanks for reporting. I will have a look if this change is really needed.

**Comment by MarkusFrankATcernch** [comment]
Assumed to be fixed. If not please re-open.

**Comment by SanghyunKo** [comment]
Sorry, somehow I overlooked this. Indeed this issue is fixed in `v01-17`.
