### ISSUE TITLE
Question about positioning of sensitive volumes

### ISSUE THREAD

**Issue by Vlad-Orlov** [AIDASoft/DD4hep#822]
Hello! I have a rather simple question about sensitive volumes positioning. I would like to have in my simulation a sensitive volume placed inside another volume and this construction repeated several times. So I'm trying to do something like:
```
DetElement   det_de(det_name, x_det.id());
Assembly     det_vol( det_name + "_assembly" );

Box     env_box(10*mm, 10*mm, 10*mm);
Volume  env_vol("envelope", env_box, env_mat);

Box     sens_box(5*mm, 5*mm, 5*mm);
Volume  sens_vol("envelope", env_box, sens_mat);

sens_vol.setSensitiveDetector( sens );

PlacedVolume pv = env_vol.PlaceVolume(sens_vol);
```
and then I am placing this `env_vol` inside general detector assembly in a loop:

```
std::string name = "module%d";

for(int i = 1; i < 5; i++){
    PlacedVolume env_pv = det_vol.placeVolume( env_vol, Position( i * 5*cm, 0, 0 ) );
    env_pv.addPhysVolID( "module", i );
    DetElement env_de( det_de, _toString( i, name.c_str() ), i );
    env_de.SetPlacement( env_pv );
}
```
And this is then placed in the `world`. I'm then able to inspect the geometry with `geoDisplay` and it looks ok, but when I run the simulation, no hits are produced. However, when I am setting `env_box` as sensitive, hits are produced (but the sensitive volume is wrong). So, what is a proper way to set `sens_vol` as a sensitive volume in this scenario?

**Comment by andresailer** [comment]
Have you tried adding
`   pv.addPhysVolID( "sens_vol", 0 );`
?
Can you provide the complete reproducer otherwise?

**Comment by andresailer** [comment]
No answer for 3 weeks, so closing this now. Please re-open or let us know if needed.
