### ISSUE TITLE
question about setAttributes for Volumes and PlacedVolumes

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#830]
If I look at 

https://github.com/AIDASoft/DD4hep/blob/master/DDDetectors/src/EcalBarrel_geo.cpp

I see three similar lines doing SetAttributes commands

https://github.com/AIDASoft/DD4hep/blob/3a45e184e6b7f0b64b1f5901ed41b55dc375921c/DDDetectors/src/EcalBarrel_geo.cpp#L106

https://github.com/AIDASoft/DD4hep/blob/3a45e184e6b7f0b64b1f5901ed41b55dc375921c/DDDetectors/src/EcalBarrel_geo.cpp#L120

and 
https://github.com/AIDASoft/DD4hep/blob/3a45e184e6b7f0b64b1f5901ed41b55dc375921c/DDDetectors/src/EcalBarrel_geo.cpp#L159

However the object that is receiving this command for the first two are DetElements but for the last is a Volume
.

How do you know when you need to do the SetAttributes to a DetElement and when to do it to a volume?  The DetElemwnr corresponding to the Volume in the last command is sdet while the volume is envelope

**Comment by MarkusFrankATcernch** [comment]
All attributes always go to the volume.
If you want, DetElement::setAttributes(...) is only a helper to sort of minimize individual calls to the volume.
DetElement::setAttributes and Volume::setAttributes are functionally identical.

**Comment by saraheno** [comment]
yes
