### ISSUE TITLE
question about placedVolume and overlaps

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#831]
I have a question about placedVolumes and volume overlaps.

supposed I make a trapezoid with commands like
```c++
    DetElement tower_det("tower0",det_id);  
    dd4hep::Trap tower((thick+0.1)/2.,0.,aatheta,inphil,delzb,delzb,0.,outphil,delzt,delzt,0.);
    dd4hep::Volume towerVol( "tower", tower, description.material(fX_barrel.materialStr()) );
```
and then I make a cylinder like
```c++
  dd4hep::Tube fiber = dd4hep::Tube(0.,fX_core.rmin(),thick);
  dd4hep::Volume coreVol("core", fiber, description.material(fX_core.materialStr()));
  DetElement afiber(tower_det,"fiber",det_id);
  PlacedVolume fiber_phv = towerVol.placeVolume( coreVol, Position(0.,0.,thick/2. ));
  fiber_phv.addPhysVolID("fiber",1);
  afiber.setPlacement(fiber_phv);
```
Does the code take care of the volume overlaps?  Or should the "tower" have had a hole in it to hold the fiber so there are no volume overlaps?

**Comment by saraheno** [comment]
Thanks for this answer.  So I should make sure there are no overlaps and then once I think I have it right, run one of these tools to make sure.

Does one of the examples in DDDetectors show a case where a hole has to be made in a volume to put another volume inside of it?  I guess I can find this on the GEANT4 page, but if you have an example handy, it would be great if you could point me to it.

**Comment by MarkusFrankATcernch** [comment]
There are plenty:
grep -r Subtraction DDDetectors/src/

This one should be simple:  ForwardDetector_geo.cpp

**Comment by andresailer** [comment]
Maybe I am misreading something, but if you place one volume inside another as parent/child (as you do in your example as far as I understand)
```c++
towerVol.placeVolume( coreVol, Position(0.,0.,thick/2. ));
```
the child must be fully contained inside the parent. You must not make a subtraction of the parent to place the child, otherwise the child is no longer contained in the parent volume.

**Comment by saraheno** [comment]
Thanks Andre.  This makes me realize I am confused about parent/child.  I thought parent/child was used to help in placement.  I put the fiber in the tower once, and then only have to place the parent/child combination in the envelope at the various phis.  But certainly I don't want to have volume overlap errors, where geant cannot decide if the particle is in the fiber or in the absorber.  So I guess this means I should make an air trapezoid as the mother and then place both the brass and the fiber in separately as children?

**Comment by andresailer** [comment]
I hope I didn't cause more confusion. Yes, parent/child can also be used for placements, but still children must be fully contained inside their parents. Children must also not overlap one another.

I don't understand what your geometry is supposed to be like. In what geometry are absorber and fiber placed? 
If the fiber is geometrically fully contained inside the absorber and placed as a child of that absorber, Geant will do the right thing.
If both are placed as children of the same parent volume, and still overlap, things will be wrong.

**Comment by saraheno** [comment]
I have a trapezoidal "tower" with a single fiber going up the middle of it.  (it is a IDEA like DR spaghetti calorimeter.  I haven't been able to get Sang Hyuna's code to work.  As I said in another issue, for some reason no cerenkov light is produced, only direct hits on the sensors.  so I decided to make a very simple sphaghetti on my own, rather than try to debug his very detailed detector)

So if I create a mother that is a brass trapezoid, and make the fiber a daughter, I do not need to make a hole in the brass?  But if I make a mother that is air and place the brass trapezoid and the fiber separately as daughters to the air mother, then I do need to make a hole in the brass?

**Comment by andresailer** [comment]
> So if I create a mother that is a brass trapezoid, and make the fiber a daughter, I do not need to make a hole in the brass? 
> But if I make a mother that is air and place the brass trapezoid and the fiber separately as daughters to the air mother, then I do need to make a hole in the brass?

Yes, exactly.

**Comment by saraheno** [comment]
so regarding the mother/daughter relations..

suppose I want a brass trapezoid with a air hole running along the z axis in the center and a fiber in the air hole

do I make a mother air trapezoid and put the brass trap, the air hole, and the fiber each as daughters in it?

or do I put the fiber as a daughter of the air hole, and the air hole as a daughter of the brass, and the brass as a daughter of the air trap?

**Comment by andresailer** [comment]
The second one: fiber in air_hole in trap_brass in trap_air

**Comment by saraheno** [comment]
when I make the corresponding DetElements, does it follow the same pattern? so

 DetElement fiber_det(hole_det,"fiber",det_id);
DetElement hole_det(absorber_det,"hole",det_id);
DetElement absorber_det(tower_det,"absorber",det_id);
DetElement tower_det("tower",det_id);

**Comment by saraheno** [comment]
I made a new version with what I hope are correct mother/daughter relations.  When I look at it in geoDisplay, I do not see any volume overlaps and the overlap test also says there are no overlaps.

However, SDAction is still not being called for the fiber.  but if I set towerVol instead to sensitive, it is called.

**Comment by andresailer** [comment]
There is still at least one overlap
```
Idle> /geometry/test/run
Running geometry overlaps check...
Checking overlaps for volume DRSimple_0 (G4Polyhedra) ... 
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomVol1002
      issued by : G4PVPlacement::CheckOverlaps()
Overlap with mother volume !
          Overlap is detected for volume DRSimple_0:0 (G4Polyhedra)
          with its mother volume world_volume (G4Box)
          at mother local point (9158.79,-38136,-364.108), overlapping by at least: 18.136 m  
NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------

```
I increased the world volume
I also increased the fiber size to 50 mm so I didn't have to figure out were they are located and have a better change of hitting them.

Here are all my changes
https://github.com/andresailer/DD4hep/commit/6344115d977c1855de1cecedb834c9c0ae12940d

I run
```
ddsim --steeringFile SCEPCALsteering.py --compact ./DRonly.xml  --runType batch --part.userParticleHandler='' -G --gun.direction "1 1 0.1" --gun.energy "10*GeV" --gun.particle="e-"  --gun.distribution=uniform -N 20  -O out.root
```

And I get

```
...
entering DualCrystalAction
 prevolume is fiber_0
 postVolume is hole_0
 pid is -22
...
```
Which is what is wanted, right?

**Comment by saraheno** [comment]
Thank you so very very much Andre!
