### ISSUE TITLE
problem with cmake and ROOT:  Target "DDEvePlugins" links to target "ROOT::Eve" but the target was not   found. 

### ISSUE THREAD

**Issue by miguelignacio** [AIDASoft/DD4hep#832]
Hi, 
I did obtain the DD4hep from git. 
I tried to do:
`cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=ON -DBUILD_TESTING=ON -DCMAKE_CXX_STANDARD=17 -DGeant4_DIR=$G4INSTALL/lib/Geant4-10.4.0 -DROOT_DIR=$ROOTSYS ..
`

But then I got
```

CMake Error at cmake/DD4hepBuild.cmake:650 (add_library):
  Target "DDEvePlugins" links to target "ROOT::Eve" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  DDEve/CMakeLists.txt:43 (dd4hep_add_plugin)


CMake Error at cmake/DD4hepBuild.cmake:650 (add_library):
  Target "DDEvePlugins" links to target "ROOT::RGL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  DDEve/CMakeLists.txt:43 (dd4hep_add_plugin)
```

My ROOT installation works fine. Here are details:

```
echo $ROOTSYS
/home/miguel/root_install

```

```
root-config --cflags
-pthread -std=c++17 -m64 -I/home/miguel/root_install/include

```
```
ROOT Version: 6.22/09
Built for linuxx8664gcc on May 17 2021, 15:00:00
From heads/v6-22-00-patches@v6-22-08-24-gdd3f79d017

```

You see that I installed ROOT with c+177 and then I passed the c++17 flag to the DD4Hep cmake command. What is the issue

**Comment by miguelignacio** [comment]
PS:

cmake --version
cmake version 3.16.3

**Comment by andresailer** [comment]
Do you need the DDEve package? if not, you can remove it from the DD4HEP_BUILD_PACKAGES list.
https://github.com/AIDASoft/DD4hep/blob/77c6310ec4eca4c406ba0162eb17b8b0abfe57ea/CMakeLists.txt#L84-L85
Via cmake, e.g., 
```
cmake -D DD4HEP_BUILD_PACKAGES="DDRec DDDetectors DDCond DDAlign DDCAD DDDigi DDG4 UtilityApps" ...
```
If you do need it: Are the libEve, libRGL libraries part of your root installation? probably opengl wasn't found or enabled for your root compilation.

**Comment by miguelignacio** [comment]
Thanks, it was indeed the missing opengl in the ROOT installation. Installing opengl and reinstalling ROOT fixed it.
