### ISSUE TITLE
visAttributes problem

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#834]
When I do something like

 <vis name="CrystalEcalStaveVis"        alpha="0.1" r="0.0"  g="0.0"  b="1.0" drawingStyle="wireframe" lineStyle="wire"  showDaughters="true" visible="true"/>

the "alpha" , "drawingStyle" and "lineStyle" options do not seem to do anything.  Is it maybe my version of root?  do these options work for others?

**Comment by MarkusFrankATcernch** [comment]
Alpha works, but sometimes has side-effects on daughter volume drawings. 
Drawingstyle and linestyle are ignored by ROOT. 
The ROOT viewer only allows to globally switch between surface drawing and wireframe drawing. 
ROOT also ignores wireframe colors.
If I remember the key-strokes correctly, try CTRL-w, CTRL-e, CTRL-r to switch wireframes on/off.
