### ISSUE TITLE
difficulty properly aligning daughter volumes with trap

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#837]
I am trying to make a tower trapezoid and put into it two daughter trapezoids that basically divide it into two.
However, while I can get them to align very closely, there is still a very small misalignment that I just cannot figure out.  

My code is in https://github.com/saraheno/DD4hep
and I have 2 example towers displayed using https://github.com/saraheno/DD4hep/blob/master/examples/DDDualCrystal/SCEPCdetector/DRConly.xml

I did notice (after unfortunately long investigation) is that the 0,0,0 of the trapezoid is not where I would have guessed it to be, and also it has an "origin" that is not at 0,0,0.  But still even correcting for this, there is a subtle shift.

any help would be appreciated.

**Comment by MarkusFrankATcernch** [comment]
Is this still a open issue ? If yes, please re-open.

**Comment by saraheno** [comment]
I haven't had time to work on it.  I will work on it again in late October,
after the DOE grant submission deadline.
