### ISSUE TITLE
feature: Extend/inherit visualization attributes. 

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#841]
Is there a way to reuse visualization attributes and extend/inherit them?

For example:

```
<vis name="MyColor"                r="1.0" g="0.0" b="0.0" />
<vis name="MyDetector" alpha="0.5" r="1.0" g="0.0" b="0.0"     showDaughters="false" visible="true" />
<vis name="Detector2"  alpha="0.1" r="1.0" g="0.0" b="0.0"     showDaughters="true"  visible="true" />
```

Instead could be this:

```
<vis name="MyColor"  r="1.0" g="0.0" b="0.0" />
<vis name="MyDetector" extend="MyColor"    alpha="0.5" showDaughters="false" visible="true" />
<vis name="Detector2"  extend="MyDetector" alpha="0.1" showDaughters="true" />
```

Now I can change "MyColor" and it propagates to all extended attributes. 

This would be a very nice feature to add if it does not already exist in some form.

**Comment by MarkusFrankATcernch** [comment]
This functionality does not exist. Could be done at the level of the compact XML 
if "MyColor" would be fully qualified and not only half. 
However, do features like this really help or only add to the confusion?

**Comment by whit2333** [comment]
@MarkusFrankATcernch 
Yes, "MyColor" would be fully qualified. The idea is that it defines part of the subsequent attributes.
For example, this means N slightly different attributes can have their RGB values changed via one attribute. This is **very** useful IMO, especially with detectors many included files.
