### ISSUE TITLE
Using ddsim with different output action

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#845]
I have a modified file output action that uses podio to write rootfiles. Currently I have a modified version of `ddsim` which just replaces the default root output action (among other things). Is there a way to make this swap without modifying the `ddsim` source code?

I ask because with [this recent change](https://github.com/aidasoft/DD4hep/pull/823), I might be able to avoid using a modified ddsim. 

Thanks!

**Comment by andresailer** [comment]
What modifications are you doing, then I can modify things to allow this from the "steering" file for example.
At the moment only the physics part has this call back.

**Comment by whit2333** [comment]
I replace the line in `DDG4.py`  
```
evt_root = EventAction(self.kernel(), 'Geant4Output2Podio/' + name, True)
```
Where `Geant4Output2Podio` is my podio implementation of the `Geant4Output2Root`.

**Comment by andresailer** [comment]
@whit2333 Please have  a look at the implementation in #863

**Comment by whit2333** [comment]
Would this be a steering-file only feature?

**Comment by andresailer** [comment]
Yes the proposed implementation would be steering file only. 
On top of that you could add a parameter to change the plugin to load, like the `myExtension` example.
In principle one could add a `exec` call for a string on the command line to define the function, but at that point just having a steering file would be much more sensible I think?

If you would like a solution without any steering file, one could add a flag to change the plugin, but this wouldn't really scale to setting properties for the plugin, so I am not sure how useful this would be?

**Comment by andresailer** [comment]
@whit2333 Is the proposed solution OK for you, or would you prefer something command line only?

**Comment by whit2333** [comment]
Yes. This is reasonable. Thank you!

On September 2, 2021 8:11:36 AM CDT, Andre Sailer ***@***.***> wrote:
***@***.*** Is the proposed solution OK for you, or would you prefer something command line only?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/AIDASoft/DD4hep/issues/845#issuecomment-911666105
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
