### ISSUE TITLE
XML vs python setup and ddsim

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#846]
Hello,

I have a few questions around the topic of simulation setup via XML files (ie using `<geant4_setup>`) and ddsim steering.

1. Can I mix XML setup and ddsim steering?
2. Can XML setup files be included from the compact detector file?
3. Where is the best documentation for ddsim?

Thanks

**Comment by MarkusFrankATcernch** [comment]
@whit2333 
The XML setup was not used for years. We are planning to remove the XML setup. Please do not use it.

**Comment by whit2333** [comment]
@MarkusFrankATcernch, Thanks! This is good to know.
