### ISSUE TITLE
Incorrect Trap shape 

### ISSUE THREAD

**Issue by DraTeots** [AIDASoft/DD4hep#850]
- OS version: linux mint 20.02 (Ubuntu 20.04 based)
 - Compiler version: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
 - DD4hep version: tag v01-17
 - Reproduced by: ROOT 6-24-02, 6-20-04. Geant v10.7.1
 - When I try to create Trap prizm through `Trap(double pz, double py, double px, double pLTX)` constructor, it creates the wrong shape both for ROOT and Geant4 part. 
 
 Trap I'm trying to create: 

```c++
// Look full code below
Trap prizm_shape(360 * mm, 300 * mm, 237.4608 * mm, 50 * mm);
```

What I see in TGeo viewer: 

![image](https://user-images.githubusercontent.com/4732545/126736183-55ac970d-38f8-42f9-9185-74d558061e8f.png)

What I see in Geant4 using DDSIM 

![image](https://user-images.githubusercontent.com/4732545/126736219-28f3c532-4f06-4a2f-b184-63e0268589ff.png)

So both ROOT and Geant4 conversion are affected. The picture is not correct as there should be right angles.

Just in case the same prism created in **pure** Geant4 (or how it should look) 

![image](https://user-images.githubusercontent.com/4732545/126736308-21d79d71-e090-4cf8-b643-7fab2a7e0ccc.png)

The code to reproduce is really slim and straight forward: 

```c++
#include "DD4hep/DetFactoryHelper.h"
#include "DD4hep/OpticalSurfaces.h"
#include "DD4hep/Printout.h"
#include "DDRec/Surface.h"
#include <XML/Helper.h>

using namespace std;
using namespace dd4hep;

static Ref_t createDetector(Detector& desc, xml_h e, SensitiveDetector sens)
{
    xml_det_t xml_det   = e;
    std::string det_name = xml_det.nameStr();
    int det_id   = xml_det.id();

    DetElement   det(det_name, det_id);
    Volume       mother_vol = desc.pickMotherVolume(det);
    Material quartz = desc.material("Quartz");

    Trap prizm_shape(360 * mm, 300 * mm, 237.4608 * mm, 50 * mm);
    Volume prizm("prizm", prizm_shape, quartz);

    PlacedVolume det_plvol = mother_vol.placeVolume(prizm, Position(50, 0, 0));
    det.setPlacement(det_plvol);
}
DECLARE_DETELEMENT(cb_DIRC, createDetector)

**Comment by DraTeots** [comment]
Probably you have an error in the constructor. This workaround simulates the right constructor and works

```c++
dd4hep::Trap MakeTrap( const std::string& pName, double pZ, double pY, double pX, double pLTX )
{
    double fDz  = 0.5*pZ;
    double fTthetaCphi = 0;
    double fTthetaSphi = 0;
    double fDy1 = 0.5*pY;
    double fDx1 = 0.5*pX;
    double fDx2 = 0.5*pLTX;
    double fTalpha1 = 0.5*(pLTX - pX)/pY;
    double fDy2 = fDy1;
    double fDx3 = fDx1;
    double fDx4 = fDx2;
    double fTalpha2 = fTalpha1;

    return Trap(pName, fDz,  fTthetaCphi,  fTthetaSphi,
                fDy1,  fDx1,  fDx2,  fTalpha1,
                fDy2,  fDx3,  fDx4,  fTalpha2);
}
```

<img width="396" alt="image" src="https://user-images.githubusercontent.com/4732545/126737680-f68b47de-1e4b-4f27-abb0-e1d4ce7324ff.png">

<img width="175" alt="image" src="https://user-images.githubusercontent.com/4732545/126737731-106884f7-8786-415f-8e95-09651be886a5.png">

**Comment by whit2333** [comment]
@DraTeots ,
Check that the constructor for G4Trap correctly constructed here: 
https://dd4hep.web.cern.ch/dd4hep/reference/Geant4ShapeConverter_8cpp_source.html#l00215

- [G4Trap](https://apc.u-paris.fr/~franco/g4doxy/html/classG4Trap.html)
- [TGeoTrap](https://root.cern.ch/doc/master/classTGeoTrap.html#a0e27ff95f2ffa2eb8c320a7778e1f403)
- [dd4hep::Trap](https://dd4hep.web.cern.ch/dd4hep/reference/Shapes_8cpp_source.html#l00588)

**Comment by DraTeots** [comment]
That is what I did to create the workaround above

**Comment by MarkusFrankATcernch** [comment]
@DraTeots @whit2333 @ianna @cvuosalo 
If I remember correctly, then this constructor was asked for by CMS. We first have to check with them.
Ianna, Carl, do you use this constructor ? If yes, could you please confirm that this is a bug ?

**Comment by cvuosalo** [comment]
As far as I can tell, CMS always uses the 12-parameter version of the `Trap` constructor,  so we don't have experience with this short version of the constructor.

**Comment by MarkusFrankATcernch** [comment]
@DraTeots Hi Dimitry,
could you please check if this PR is correct ? https://github.com/AIDASoft/DD4hep/pull/853 
Thanks a lot!

**Comment by DraTeots** [comment]
Ok!

**Comment by DraTeots** [comment]
Confirm it is fixed now

<img width="345" alt="image" src="https://user-images.githubusercontent.com/4732545/127761975-bc443aa5-5822-4d42-bc6d-a1067d0d4a9d.png">
