### ISSUE TITLE
Export of geometry to CAD

### ISSUE THREAD

**Issue by miguelignacio** [AIDASoft/DD4hep#858]
I see this is a new capability, which is great. Can you please provide an example on what command to use for this?
I did not find it in the examples DDCAD folder.

**Comment by MarkusFrankATcernch** [comment]
Please have look in examples/DDCAD
The export to CAD however does not yet work properly. 
There is work to be done, but I have no time currently.
Primitive shapes can be exported, but booleans not.

Markus

**Comment by MarkusFrankATcernch** [comment]
Export of geometries to CAD was confirmed by colleagues from FCC.
Also boolean shapes work now.

**Comment by DraTeots** [comment]
As a workaround. You can export geometry to root and then use root2cad

https://github.com/eic/root2cad
