### ISSUE TITLE
Volume identification

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#86]
Hello,

I have  a geometry navigation question.

Given an LCIO::SimTrackerHit, how would I determine the sensitive element? I am very confused at the moment.

Having loaded the geometry with the compact file, I can get the top level DetElement associated with the readout.

How do I determine the VolumeID?

Do I need to use the global position to find these?

How do I determine the CellID?

Is there a "best" method to get this information?

Cheers

**Comment by whit2333** [comment]
Does VolumeID = CellID ?

**Comment by andresailer** [comment]
The CellID also sets bits for the segmentation if the sensitive detector is using a segmentation. If there is no segmentation then CellID == VolumeID.

**Comment by whit2333** [comment]
How do I get the volumeid and position from a global position?

**Comment by andresailer** [comment]
Try the functions of the IDDecoder: http://test-dd4hep.web.cern.ch/test-dd4hep/doxygen/html/class_d_d4hep_1_1_d_d_rec_1_1_i_d_decoder.html

**Comment by whit2333** [comment]
Seems to have a bug. Crashes when getting cellid. It prints the module but it returns zero volumeid.

**Comment by andresailer** [comment]
What geometry are you using?

**Comment by whit2333** [comment]
I have tried a few. I am  using DDDetetors/compact/SiD.xml at the 
moment. I am looking at the SiTrackerBarrelHits and using the position 
of the hit to look up the information. Here is what I do

```
for(int i_track=0 ; i_track<nSimTrackHits ; ++i_track) {
  auto  ahit = (EVENT::SimTrackerHit*) simtrackhits_col->getElementAt(i_track);
  std::cout << "id " << ahit->getCellID0() << std::endl;

  TVector3 x0(ahit->getPosition());
  x0.Print();

  auto hit_pos = DD4hep::Geometry::Position(x0.x(),x0.y(),x0.z());
  std::cout << " hit  pos : x=" << hit_pos.x() << ", y=" << hit_pos.y() << ", z=" << hit_pos.z() << std::endl;

  auto volumeid = id_decoder.volumeID(hit_pos);
  std::cout << " volumeID : " << volumeid << std::endl;

  auto cellid = id_decoder.cellID(hit_pos);
  std::cout << " cellID : " << cellid << std::endl;

  auto bpos   = id_decoder.position(cellid);
  std::cout << " cell pos : x=" << bpos.x() << ", y=" << bpos.y() << ", z=" << bpos.z() << std::endl;
}
...
```

This outputs 

```
TVector3 A 3D physics vector (x,y,z)=(1222.945308,47.504868,1044.025024) 
(rho,theta,phi)=(1608.676534,49.534035,2.224515)
 hit  pos : x=1.22e+03, y=4.75e+01, z=1.04e+03
world
 volumeID : 0
world
 A runtime error has occured : DD4hep: VolumeManager::lookupContext: Failed to search Volume context [Unknown identifier]0
 the program will have to be terminated - sorry.
```

**Comment by andresailer** [comment]
After some trial and error, I think the IDDecoder probably only works properly if the detector geometry has DetElements all the way down to the sensitive element and there is a segmentation object associated to them.

What information are you trying to find for the hits?

**Comment by whit2333** [comment]
So extra/unused readout layers could be causing the problem?

**Comment by andresailer** [comment]
No. Not having DetElements assigned to the sensitive volumes and not having a segmentation for the tracking detector could be causing the problem.
There might be other ways to get the information you want, if you would just tell me what that is.

**Comment by whit2333** [comment]
Sorry for the delay.

I would like to get the sensitive element's position. Ideally the pixel location and normal vector. Of course there is not a volume for each pixel but this is what the segmentation is for, right?

**Comment by andresailer** [comment]
Does your tracking detector have a segmentation assigned to it?
If it does the SimCalorimeterHit should be the position of the pixel

You can use surfaces to get the normal vector, local coordinates, etc. for sensitive volumes(if they have a surface, run the InstallSurfaceManager plugin etc. if it doesn't already happen, 
see
```
  SurfaceManager& surfMan = *lcdd.extension< SurfaceManager >() ;
  // const SurfaceMap& _surfMap = *surfMan.map( "world" ) ;
  _surfMap = *surfMan.map( "world" ) ;
  SurfaceMap::const_iterator si = _surfMap.find( cellID ); //cellID of the tracker hit
  ISurface* surf = (si != _surfMap.end() ?  si->second  : 0);
  DDSurfaces::Vector3D fit_global(pivot[0],pivot[1],pivot[2]);
// transform lcio units to dd4hep units, see documentation for other functions              
  DDSurfaces::Vector2D fit_local = surf->globalToLocal( dd4hep::mm * fit_global );
```
You can probably add the surfaces by adding towards the end of the SiD.XML file
```
   <plugins>
       <plugin name="DD4hep_GenericSurfaceInstallerPlugin">
           <argument value="TrackerDetectorName"/>
           <argument value="dimension=2"/>
           <argument value="u_x=-1."/>
           <argument value="v_y=-1."/>
           <argument value="n_z=1."/>
       </plugin>	
       <plugin name="InstallSurfaceManager"/>
   </plugins>
```

See these files for concrete examples:
https://github.com/iLCSoft/lcgeo/blob/master/CLIC/compact/CLIC_o3_v08/CLIC_o3_v08.xml#241
https://github.com/iLCSoft/lcgeo/blob/master/CLIC/compact/CLIC_o3_v08/InnerTracker_o2_v06_01.xml#L403

**Comment by whit2333** [comment]
> Does your tracking detector have a segmentation assigned to it?
If it does the SimCalorimeterHit should be the position of the pixel

Thanks, but this really the exercise I want to do. I want to grab the pixel from the unique ID assigned to the hit (and not use the position). I am building a very simple example (since one does not appear to exist) and will share it when I am done.

**Comment by andresailer** [comment]
It is on purpose that one does not _have to_ add a segmentation to a sensitive detector. There are cases where we want to record the position of the step independent of a segmentation. Using a default segmentation like you propose would not work for us.

**Comment by whit2333** [comment]
Please do show how to do this without a segmentation. All the IDDecoder methods fail because they assume a segmentation.

**Comment by andresailer** [comment]
How to do what without a segmentation?

**Comment by whit2333** [comment]
Use IDDecoder::position with this line commented out:
https://github.com/whit2333/dd_test/blob/master/src/simple_example/compact/simple_example.xml#L86

**Comment by andresailer** [comment]
As we have both found out, the IDDecoder doesn't work without a segmentation. You added a segmentation to your detector, do you now get all the information you want? Except for the problem that the function returns the wrong information?

**Comment by whit2333** [comment]
Yes, this is correct.

Just do be clear: Should the IDDecoder work without segmentation? Is this a bug?

The "wrong information" can be found in the discussion 
https://github.com/AIDASoft/DD4hep/issues/94

**Comment by andresailer** [comment]
If it can work without a segmentation then it should.
Was your statement about "default" segmentation above only applying to the IDDecoder?

**Comment by whit2333** [comment]
> Was your statement about "default" segmentation above only applying to the IDDecoder?

Yes. Because the IDDecoder::position(cellID) calls for a segmentation even if there is not one created. So I thought that a "default" segmentation should be used such that it really returns the position associated with the VolumeID since in this case the VolumeID should be the same as the CellID.

So otherwise there is a bug since a segmentation is always assumed to be defined:
http://test-dd4hep.web.cern.ch/test-dd4hep/doxygen/html/_i_d_decoder_8cpp_source.html#l00074
