### ISSUE TITLE
Multiple readouts or G4VUserParallelWorld equivalent

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#861]
Hi,

Is there a way to use the G4MultiFunctionalDetector, which allows  multiple sensitive detectors to be attached to a volume or something equivalent?

I suppose the dd4hep way of asking this question is: Can more than one readout be associated with a detector? (not multi segmentation or collection names)

**Comment by whit2333** [comment]
I realize this could also be accomplished with a parallel world (G4VUserParallelWorld) but this does not appear to be available. There is something called "parallelWorld" but appears to be conceptually different?

**Comment by andresailer** [comment]
As far as I understand the Gean4 documentation `G4MultiFunctionalDetector` allows one to attach multiple `G4VPrimitiveScorer` not multiple SensitiveDetectors.

**Comment by whit2333** [comment]
@andresailer you are correct. But the question still stands.

**Comment by MarkusFrankATcernch** [comment]
A priori every sensitive detector in DDG4 is modeled be a sequence of sensitive actions (aka GeantSensitive or any user specified derivation thereof). Each of these actions is able to produce it's own hit collection. 

Depending on the implementation of these concrete sensitive actions various readout segmentations could be exercised simultaneously. Clearly for such use cases the sensitive actions will have to be user provided -- the default implementation cannot support this. However, the framework including the setup using python (which will use the abstract factory mechanism) will fully support this approach.

In this sense though the G4MultiFunctionalDetector is not supported, the mechanism is. If I understand Andres answer correctly, then the DDG4 approach look even more flexible.
