### ISSUE TITLE
DDG4: isotropic gun distribution also forces uniform momentum distribution

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/DD4hep#862]
The isotropic gun distributions (e.g. getParticleDirectionUniform, and its siblings) also change the magnitude of the momentum, e.g. in line [Geant4IsotropeGenerator.cpp#L51](https://github.com/AIDASoft/DD4hep/blob/ee51c48c5aaadb0f38d56c7a5b3b8e0c6b890c49/DDG4/src/Geant4IsotropeGenerator.cpp#L51). 

## Steps to reproduce
The following simulation steering file `test.steer`:
```
from DDSim.DD4hepSimulation import DD4hepSimulation
from g4units import mm, GeV, MeV, degree
SIM = DD4hepSimulation()

SIM.gun.energy = 1*GeV
SIM.gun.particle = "e-"
SIM.gun.position = (0.0, 0.0, 0.0)
SIM.gun.direction = (0.0, 0.0, 1.0)
SIM.gun.distribution = "cos(theta)"
SIM.gun.thetaMin = 45*degree
SIM.gun.thetaMax = 135*degree
```
with a simulation that is run as (with a potential change to the dd4hep install path):
```
ddsim -G --steeringFile test.steer --compactFile /opt/local/DDDetectors/compact/SiD.xml --outputFile test.root --numberOfEvents 1000
```
produces a file `test.root`.

## Expected output
The steer file above would seem to indicate a fixed 1*GeV beam energy:
- there is no way to specify an energy range in the command line flags,
- the instructions indicate that `gun.distribution` only changes the direction:
```
  --gun.energy GUN.ENERGY
  --gun.particle GUN.PARTICLE
  --gun.multiplicity GUN.MULTIPLICITY
  --gun.phiMin GUN.PHIMIN
                        Minimal azimuthal angle for random distribution
  --gun.phiMax GUN.PHIMAX
  --gun.thetaMin GUN.THETAMIN
  --gun.thetaMax GUN.THETAMAX
  --gun.direction GUN.DIRECTION
                         direction of the particle gun, 3 vector 
  --gun.distribution {uniform,cos(theta),eta,pseudorapidity,ffbar}
                        choose the distribution of the random direction for theta
                        
                            Options for random distributions:
                        
                            'uniform' is the default distribution, flat in theta
                            'cos(theta)' is flat in cos(theta)
                            'eta', or 'pseudorapidity' is flat in pseudorapity
                            'ffbar' is distributed according to 1+cos^2(theta)
                        
                            Setting a distribution will set isotrop = True
                            
  --gun.isotrop GUN.ISOTROP
                         isotropic distribution for the particle gun
                        
                            use the options phiMin, phiMax, thetaMin, and thetaMax to limit the range of randomly distributed directions
                            if one of these options is not None the random distribution will be set to True and cannot be turned off!
                            
  --gun.position GUN.POSITION
                         position of the particle gun, 3 vector 
```

## Actual output
The actual simulation has a uniform distribution in momentum, as demonstrated by plotting the magnitude of the initial momentum for generated particles, i.e.
```
root -l test.root -e 'EVENT->Draw("sqrt(MCParticles.psx**2+MCParticles.psy**2+MCParticles.psz**2)","MCParticles.g4Parent==0")'
```
which returns a uniform distribution.

Also, while running ddsim, the following event output is seen:
```
ParticleHandler  INFO  +++ Event 998 Begin event action. Access event related information.
GenerationInit   INFO  +++ Initializing event 1000. Within run:0 event 1000.
Gun              INFO  Particle [0] e-           Mom:0.654 GeV vertex:( 0.000  0.000  0.000)[mm] direction:(-0.523 -0.740 -0.423)
Gun              INFO  Shoot [999] 1.000 GeV e- pos:(0.000 0.000 0.000)[mm] dir:( 0.000  0.000  1.000)
Gun              INFO  +-> Interaction [0] 1.000 GeV e- pos:(0.000 0.000 0.000)[mm]
Gun              INFO  +++   +-> ID:  0 e-           status:00000002 PDG:    11 Vtx:(+0.00e+00,+0.00e+00,+0.00e+00)[mm] time: +0.00e+00 [ns] #Dau:  0 #Par:0      
```
which makes clear that the actual momentum was changed from 1.000 GeV to 0.654 GeV (for this particular event). (The fact that 1.000 GeV appears after hte 0.654 GeV is because the 1.000 GeV is the energy, which is not used in generating the particle. Instead the energy is copied to the momentum and that is the changed.)

## Suggested resolution
I can see two ways to resolve this:
- Remove the lines that change the momentum in e.g. https://github.com/AIDASoft/DD4hep/blob/ee51c48c5aaadb0f38d56c7a5b3b8e0c6b890c49/DDG4/src/Geant4IsotropeGenerator.cpp#L51. If someone is relying on getting a uniform distribution in momentum as well as direction, then this will disagree with those assumptions and introduce a breaking change.
- Clarify the instructions and explicitly add a min and max energy so a fixed value can be achieved (a single fixed energy is not currently possible).

Let me know which direction you think makes sense to proceed and I can prepare a PR.

**Comment by andresailer** [comment]
@wdconinc Thanks for your report. I think adding explicit E_min and E_max options are the most sensible approach.

**Comment by wdconinc** [comment]
Sure thing, I'll put that in place.

**Comment by wdconinc** [comment]
Just an update after a week or two. This turns out to not be as trivial to implement in a consistent and backwards compatible way.

My current thinking is to initialize the energy min to 0 and max to, say, -1 and then maintain the uniform random distribution between min and original momentum when min > max (reproducing original behavior), and between min and max when min <= max (allowing for fixed energy when min == max or other ranges when min < max).

I don't quite like the two behaviors, but don't see a way to have a single consistent behavior that still reproduces the original behavior while allowing for constant energies as well.

Suggestions welcome.
