### ISSUE TITLE
Geant4CerenkovPhysics and geant4.10.7: changing Cerenkov settings not possible

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/DD4hep#868]
- OS version: ubuntu 21.04
 - Compiler version: gcc 10.3
 - DD4hep version: 1.17
 - Reproduced by: presumably https://github.com/AIDASoft/DD4hep/blob/master/examples/OpticalSurfaces/scripts/OpNovice.py
 - Input: n/a
 - Output: n/a
 - Goal: setting Cerenkov parameters

The implemtation of the Cerenkov plugin suggested in https://github.com/AIDASoft/DD4hep/issues/703#issuecomment-705652757
```python
    # Add cerenkov physics
    seq = kernel.physicsList()
    cerenkov = PhysicsList(kernel, 'Geant4CerenkovPhysics/CerenkovPhys')
    cerenkov.MaxNumPhotonsPerStep = 10
    cerenkov.MaxBetaChangePerStep = 10.0
    cerenkov.TrackSecondariesFirst = True
    cerenkov.VerboseLevel = 2
    cerenkov.enableUI()
    seq.adopt(cerenkov)
```
is not functional as of geant4.10.7. That version introduced the [G4OpticalParameters](https://github.com/Geant4/geant4/blob/master/source/processes/electromagnetic/utils/src/G4OpticalParameters.cc) class which is now used on initialization to set the options, as in this line https://github.com/Geant4/geant4/blob/geant4-10.7-release/source/processes/electromagnetic/xrays/src/G4Cerenkov.cc#L115.

This new approach effectively overwrites the values that have been set by as properties of the Geant4CerenkovPhysics plugin, which are set immediately after construction, e.g. in this line https://github.com/AIDASoft/DD4hep/blob/v01-17/DDG4/plugins/Geant4CerenkovPhysics.cpp#L78.

A new approach may required getting the G4OpticalParameters::Instance() singleton in Geant4CerenkovPhysics (for G4VERSION_NUMBER>1070) and setting the respective parameters in that singleton.

A similar thing applies to Geant4ScintillationPhysics.

**Comment by andresailer** [comment]
Fixed by @wdconinc
