### ISSUE TITLE
[CMS] DD4hep should not terminate with a G4Exception -- let CMSSW handle it

### ISSUE THREAD

**Issue by cvuosalo** [AIDASoft/DD4hep#874]
CMS made a test with Native Geant4 and found that G4Exceptions were thrown for trapezoids that didn't meet strict rules. These exceptions were caught by DD4hep and caused immediate termination. The CMSSW exception model requires that exceptions be propagated up to the CMSSW Framework, where they can be handled properly.

We request a change in DD4hep so that G4Exceptions would not be caught and cause termination but rather be allowed to propagate up to the CMSSW Framework. It looks like the location in the code where the exceptions are caught is here:

https://github.com/AIDASoft/DD4hep/blob/bec0603758167434fbd008340537ba36c8baf50b/DDCore/src/DetectorImp.cpp#L229-L232

A sample error message that occurs when an exception causes termination is the following:
```
**************************************************** 
*  A runtime error has occured :                     
*    
-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : GeomSolids0002
      issued by : G4Trap::CheckParameters()
Invalid Length Parameters for Solid: tidmodule0:TIDModule0StereoKaptonCut
  X - 4.67989, 4.67989, 0, 0
  Y - 0.15, 0.15
  Z - 46.877

-------- EEEE -------- G4Exception-END --------- EEEE -------

*  the program will have to be terminated - sorry.   
**************************************************** 
```

**Comment by MarkusFrankATcernch** [comment]
@cvuosalo  Hi Carl, did this solution solve your problem ?

**Comment by cvuosalo** [comment]
@MarkusFrankATcernch Sorry, we haven't had a chance to test this yet. We removed the cause of the exception from our code. Also, we haven't updated our DD4hep version since Sept. 20. When we are ready to update our DD4hep version, we can test the new exception handling.

Thanks for fixing the issue.
