### ISSUE TITLE
Behaviour of DetElement.child() when nochild is found

### ISSUE THREAD

**Issue by bencouturier** [AIDASoft/DD4hep#878]
The behaviour of the DetElement::child() method is to return an empty (invalid) DetElement when the child with the given name is not found.
Would it be possible to have an exception in that case, or could we do another method that has that behaviour ? I'm happy to do the PR if that is ok.

**Comment by MarkusFrankATcernch** [comment]
I will put this change in

**Comment by MarkusFrankATcernch** [comment]
Please see: https://github.com/AIDASoft/DD4hep/pull/877

**Comment by bencouturier** [comment]
Thanks, that works for me
