### ISSUE TITLE
How to define id for parallel volumes in readout section?

### ISSUE THREAD

**Issue by huilinglhl** [AIDASoft/DD4hep#889]
Hi,

I'm simulating a scintillating fiber layer, which is detected by two types of PMTs. So I want to define the readout section with something like the following:
 <readout name="sciHit">
           <segmentation type="NoSegmentation"/>
           <id>system:2,layer:4,PMT1:8,PMT2:8</id>
       </readout>
But the above doesn't work. So what are the rules to define IDs for parallel daughter volumes in readout?

Regards,
Huiling

**Comment by andresailer** [comment]
Hi Huiling,

Can you be a lot more specific on what doesn't work, please?

Source code, steering files, xml files, error messages,...

Have you tried something like `system:2,layer:4,PMTType:1,PMT:8`?

**Comment by huilinglhl** [comment]
Thanks for your reply.
I made a mistake with "system:2,layer:4,PMT1:8,PMT2:8" because only part of ID is defined. Your suggestion with system:2,layer:4,PMTType:1,PMT:8 works well. 

Regards,
Huiling

**Comment by andresailer** [comment]
Great that it works now!
