### ISSUE TITLE
Event Display 

### ISSUE THREAD

**Issue by shiqian997** [AIDASoft/DD4hep#893]
I used the CLICSiD example to display events, but only the default pane can be seen. I don't know if it's because of the XML configuration file that I can't get examples of customized view with sub-planes shown in the DDEve User Manual .

**Comment by andresailer** [comment]
Please give us the information requested when an Issue is opened:

 - [ ] DD4hep version: tag or commit ID, or GitHub branch
 - [ ] Reproduced by: exact steps to reproduce the problem: checkout, setup environment (Geant, ROOT versions, iLCSoft release), cmake, build, run...
 - [ ] Input: link to input files if applicable
 - [ ] Output: full build and run log output
 - [x] Goal: A short description of what you are trying to achieve

**Comment by shiqian997** [comment]
Hi,
Here are the details:
DD4hep version: v01-13-01
Reproduced by: Geant4 10.5.1, ROOT version: 6.22, cmake: 3.17.3
Input: CLICSiD/eve/DDEve.xml

**Comment by shiqian997** [comment]
Hi,
Here are the details:
DD4hep version: v01-13-01
Reproduced by: Geant4 10.5.1, ROOT version: 6.22, cmake: 3.17.3
Input: CLICSiD/eve/DDEve.xml

**Comment by MarkusFrankATcernch** [comment]
Problem is acknowledged. 
I did not invoke it for a long time....
- The other views are accessible in the tab "Views"
-  Unfortunately they cause a SEGV....
I will have to do some debugging.

Markus

**Comment by MarkusFrankATcernch** [comment]
Please use the GIT HEAD. The projections should work.
https://github.com/AIDASoft/DD4hep/pull/894
