### ISSUE TITLE
DDDigi TBB code needs migration to new oneAPI TBB interfaces

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/DD4hep#901]
- OS version: Linux
 - Compiler version: gcc-11 or Intel oneAPI 2022.0.0, when linking against Intel oneAPI TBB 2021.5.1
 - DD4hep version: master 9cfbeb2683f9636dd19a9d68ff94703c1843183a
 - Reproduced by: compilation with TBB enabled against a virtual TBB package (in spack develop, DD4hep depends on legacy intel-tbb, not the newer intel-oneapi-tbb):
 ```console
sed -i 's/intel-tbb/tbb/g' $(spack location -p dd4hep)/package.py
spack install dd4hep +tbb ^intel-oneapi-tbb
```
 - Output:
```console
     1325    /opt/spack/lib/spack/env/oneapi/icpx -DBOOST_SPIRIT_USE_PHOENIX_V3 -DDD4HEP_USE_TBB -DDD4HEP_USE_TINYXML -DDDDigi_EXPORTS -I/home/wdconinc/git/DD4hep/DDDigi/include -I/home/wdconinc/git/DD4hep/DDCore/include -I/home/wdconi
             nc/git/DD4hep/DDParsers/include -isystem /opt/intel/oneapi/tbb/2021.5.1/include -isystem /opt/software/linux-ubuntu21.10-skylake_avx512/oneapi-2022.0.0/root-6.24.06-xwdhnrshgsqbfamp5iflktgmlwioagmt/include -isystem /opt/so
             ftware/linux-ubuntu21.10-skylake_avx512/oneapi-2022.0.0/boost-1.78.0-zajtbzgsl5fjx533uec4qnwgdp677wuv/include -ftls-model=global-dynamic -pedantic -Wextra -Wall -fdiagnostics-color=auto -Wdeprecated -Wno-long-long -Wformat
             -security -Wshadow           -pthread -O2 -g -DNDEBUG -fPIC -std=c++17 -MD -MT DDDigi/CMakeFiles/DDDigi.dir/src/DigiKernel.cpp.o -MF DDDigi/CMakeFiles/DDDigi.dir/src/DigiKernel.cpp.o.d -o DDDigi/CMakeFiles/DDDigi.dir/src/D
             igiKernel.cpp.o -c /home/wdconinc/git/DD4hep/DDDigi/src/DigiKernel.cpp
  >> 1326    /home/wdconinc/git/DD4hep/DDDigi/src/DigiKernel.cpp:143:32: error: no member named 'task_scheduler_init' in namespace 'tbb'
     1327      internals->numThreads = tbb::task_scheduler_init::default_num_threads();
     1328                              ~~~~~^
  >> 1329    /home/wdconinc/git/DD4hep/DDDigi/src/DigiKernel.cpp:165:8: error: no type named 'task_scheduler_init' in namespace 'tbb'
     1330      tbb::task_scheduler_init* init = (tbb::task_scheduler_init*)internals->tbbInit;
     1331      ~~~~~^
  >> 1332    /home/wdconinc/git/DD4hep/DDDigi/src/DigiKernel.cpp:165:62: error: expected expression
     1333      tbb::task_scheduler_init* init = (tbb::task_scheduler_init*)internals->tbbInit;
     1334                                                                 ^
  >> 1335    /home/wdconinc/git/DD4hep/DDDigi/src/DigiKernel.cpp:165:42: error: no member named 'task_scheduler_init' in namespace 'tbb'
     1336      tbb::task_scheduler_init* init = (tbb::task_scheduler_init*)internals->tbbInit;
     1337                                        ~~~~~^
  >> 1338    /home/wdconinc/git/DD4hep/DDDigi/src/DigiKernel.cpp:340:36: error: no member named 'task_scheduler_init' in namespace 'tbb'
     1339          internals->numThreads = tbb::task_scheduler_init::default_num_threads();
     1340                                  ~~~~~^
  >> 1341    /home/wdconinc/git/DD4hep/DDDigi/src/DigiKernel.cpp:345:35: error: no type named 'task_scheduler_init' in namespace 'tbb'
     1342        internals->tbbInit = new tbb::task_scheduler_init(internals->numThreads);
     1343                                 ~~~~~^
     1344    6 errors generated.
```
 - Goal: Since the Intel oneAPI compiler suite comes with its version of TBB, we would like to link DD4hep against this bundled version of TBB in our simulation+reconstruction environments. We use the Intel oneAPI compiler (DPC++) because it provides SYCL abstraction in other code in our reconstruction. We don't critically depend on the DD4hep digitization (or its TBB parallelism) but we're flagging this issue here.

A migration guide from the older TBB interface to the newer interface is at:
https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Migration_Guide/Task_Scheduler_Init.html

I will try to find some time to look into this, and hopefully it's not too onerous to address the issue while keeping support for the older interface as well. I need to figure out the preprocessor defines to use.

**Comment by wdconinc** [comment]
End of year is a good time to pick up some of these old non-critical issues... but I appears https://github.com/AIDASoft/DD4hep/commit/52dcd2d23bf55f8394877b1baf4f6092eea978cf has fixed this in master.

**Comment by MarkusFrankATcernch** [comment]
@wdconinc Is this confirmed, that the issue is solved by https://github.com/AIDASoft/DD4hep/commit/52dcd2d23bf55f8394877b1baf4f6092eea978cf ?
If yes, please close.

**Comment by wdconinc** [comment]
Sorry for the slow feedback on this. It takes a while to test this on my system because every time I want to get dd4hep compiled against a different version of intel-tbb, I also need to(?) build root with that version. It doesn't help that gaudi doesn't work with the most recent intel-tbb either, so I also need to plan on not needing gaudi for a while.

In any case, I can confirm that dd4hep-1.24 builds fine with the most recent intel-tbb-2021.7.0, which wasn't possible before. I'll close this.

**Comment by wdconinc** [comment]
Great to hear. This is now closed, but can you put a link to the PR/MR here when it's live?
