### ISSUE TITLE
Missing file in compilation instructions

### ISSUE THREAD

**Issue by kjvbrt** [AIDASoft/DD4hep#904]
Trying to compile DD4hep following the instructions, but the file
`.dd4hep-ci.d/init_x86_64.sh` is nowhere to be found.

 - OS version: -
 - Compiler version: -
 - DD4hep version: master
 - Reproduced by: following Beginners Guide or Installation instructions
 - Input: -
 - Output: `-bash: .dd4hep-ci.d/init_x86_64.sh: No such file or directory`
 - Goal: Compile DD4hep on CC7 machine with access to CVMFS

**Comment by andresailer** [comment]
Hi @kjvbrt 
I updated the installation instructions: https://dd4hep.web.cern.ch/dd4hep/page/installation/
No special file is needed the LCG views setup script can be used directly.

**Comment by kjvbrt** [comment]
Thanks @andresailer 
The missing file remains in the Beginners Guide though:
https://dd4hep.web.cern.ch/dd4hep/page/beginners-guide/

**Comment by andresailer** [comment]
Thanks! I fixed that page as well.

**Comment by kjvbrt** [comment]
I can see the update :)
Is `bootstrap.sh` still being used?
