### ISSUE TITLE
Prereq ImageMagick missing in documentation (or shouldn't be  a hard prereq)

### ISSUE THREAD

**Issue by kkauder** [AIDASoft/DD4hep#907]
- OS version: macOS 12.3.1
 - Compiler version: AppleClang 13.1.6.13160021
 - DD4hep version: v01-20-02
 - Reproduced by: 
On a mac without ImageMagick, ```cmake -Bbuild -DUSE_EXTERNAL_CATCH2=OFF```
 - Input: n/a
 - Output: I don't think the full log is helpful.
 Final three lines before errors:
```
-- Found LaTeX compiler.
-- Found UnixCommands: /bin/bash
-- I could not find the pdftops command.
```
Afterward, infinite avalanche of errors:
```
CMake Error at cmake/LATEX.cmake:1137 (message):
  Could not find convert program.  Please download ImageMagick from
  http://www.imagemagick.org and install.
Call Stack (most recent call first):
  cmake/LATEX.cmake:1209 (latex_add_convert_command)
  cmake/LATEX.cmake:1244 (latex_convert_image)
  cmake/LATEX.cmake:1497 (latex_process_images)
  cmake/LATEX.cmake:1892 (add_latex_targets_internal)
  doc/usermanuals/DD4hep/CMakeLists.txt:2 (ADD_LATEX_DOCUMENT)
```
Stopped by ctrl-c

 - Goal:
 This was easy enough to find a solution for with homebrew, but a) endless errors are not graceful, and b) is ImageMagick really needed?

**Comment by andresailer** [comment]
I added the optional requirements for documentation building https://dd4hep.web.cern.ch/dd4hep/page/installation/

**Comment by kkauder** [comment]
If somebody has the time, I'd still suggest investigating what's lurking in the `CMakeLists.txt`. An infinite loop of error messages isn't healthy.

**Comment by andresailer** [comment]
Is it literally infinite in your case?
If I make that find_program call fail on my machine by renaming the programs to search I get 66 errors.

Can you give the complete list of commands to reproduce the error? (git clone, mkdir, cd, etc.)? USE_EXTERNAL_CATCH2 isn't a variable we use in DD4hep cmake.

**Comment by andresailer** [comment]
I propose to add a statement after the possible errors that should help everyone to solve the issue quickly
https://github.com/AIDASoft/DD4hep/pull/908
