### ISSUE TITLE
Question: Best approach to implement weighted background event overlays

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/DD4hep#919]
In the EIC we are anticipating the need of overlaying multiple event generator input files, in particular combining DIS events from Pythia8 with background event distributions from other generators. This is similar to event stacking to study pile-up (which I think is what ddsim already does when multiple input files are specified, with the Geant4InteractionMerger), but differs somewhat since we would want to weight multiple input files differently. Instead of:
```console
ddsim --inputFiles dis.hepmc bg.hepmc 
```
we'd want something like
```console
ddsim --inputFiles dis.hepmc bg.hepmc --input.weighting [1, 0.1]
```
to pick with probability 1 an event from input file 1, and pick with probability 0.1 an event from input file 2.

Is there a way to achieve this already in ddsim or using existing plugins, and is there possibly an example or some code you could point us to?

**Comment by andresailer** [comment]
For ILC and CLIC studies, we always do the overlay in the digitisation stage independent of the simulation. So at least I am not aware of anything in DD4hep that does this.

**Comment by wdconinc** [comment]
We'd been considering doing this at the digitization stage too, but that opens up a whole different set of issue that I'd be curious about too:
- 'simple' model-based individual-pixel-only backgrounds at digitization do not include the correlations in our main source of background (actual tracks from residual beam gas interactions),
- inserting previously simulated background simulations at digitization could work, but would likely be done in gaudi (I assume that's what you're doing for ILC and CLIC then? do you have pointers to where that's done?),
- geometry changes are still fairly frequent, so a resimulation of the backgrounds would be required, which we'd integrate in CI.

**Comment by andresailer** [comment]
For CLIC we use the overlaytiming processor: https://github.com/iLCSoft/Overlay/blob/master/src/OverlayTiming.cc (possibly with the k4MarlinWrapper for a little longer)

**Comment by andresailer** [comment]
I think the question was answered, and no development in DD4hep is foreseen, so closing.
