### ISSUE TITLE
EDM4hep output MCParticleCollection should be named MCParticle

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/DD4hep#921]
In order to be compatible with the default LCIO output the `MCParticle` collection should be named `"MCParticle"`

Fix here:
https://github.com/AIDASoft/DD4hep/blob/84088bb832b53dbccd33ae954029b1540bf3a1a4/DDG4/edm4hep/Geant4Output2EDM4hep.cpp#L277

**Comment by tmadlener** [comment]
@wdconinc how many things would break for you if this collection would be renamed?

**Comment by tmadlener** [comment]
Yes exactly. Essentially, we found this minor difference today, while looking at running an event display with EDM4hep inputs. The change is not strictly necessary from a technical point of view, but it would make a few of the converter scripts that are involved at the moment work out of the box.

However, 'collections are plural' are actually a really compelling argument. Maybe we should have a look at how much work it would be to address this specific "problem" downstream.

**Comment by andresailer** [comment]
We can add a property for the collection name
