### ISSUE TITLE
Search path for compact files

### ISSUE THREAD

**Issue by veprbl** [AIDASoft/DD4hep#934]
This is not a bug, but more of a question or a feature request. Currently, a way to use detector descriptions is to set (DY)LD_LIBRARY_PATH to point to a directory containing the *.so/*.dylib/*.components files and provide a path to the top-level compact *.xml file. However, the compact files can include other XML, which may be importing detector descriptions from other repositories, installed at a different prefix (e.g. by a package manager). It would be nice to have an environment variable like DD4HEP_XML_INCLUDE_PATH that would allow users to include xml using paths relative to this prefix list.

As far as I understand, there is no feature like this available currently. Would it make sense to implement this?

**Comment by MarkusFrankATcernch** [comment]
It is currently not possible to have a bulk xxx_PATH variable. However, you can customize the inclusion using environment variables to set the concrete path for a file.
Is this not sufficient ?

**Comment by veprbl** [comment]
> However, you can customize the inclusion using environment variables to set the concrete path for a file.

How can one do that?

**Comment by MarkusFrankATcernch** [comment]
See for example here:
https://github.com/AIDASoft/DD4hep/blob/master/examples/CLICSiD/compact/SiD_detectors_1.xml
To properly detect environment variables in the expression evaluator the brackets `{}` around the name are mandatory!

**Comment by veprbl** [comment]
This seems reasonable to use. Thank you for your help!
