### ISSUE TITLE
IDDecoder::position returns local position

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#94]
http://test-dd4hep.web.cern.ch/test-dd4hep/doxygen/html/class_d_d4hep_1_1_d_d_rec_1_1_i_d_decoder.html#a2fa7177db38cced4a6f5173a2fc17b4f

It seems too return the local position of the cellID despite saying it should return the global position.

Here is a simple test. https://github.com/whit2333/dd_test
Perhaps I am missing something or it is related to the comments found here
http://test-dd4hep.web.cern.ch/test-dd4hep/doxygen/html/_i_d_decoder_8cpp_source.html#l00080

**Comment by andresailer** [comment]
You test is not compiling for me (and there is an error in the readme)
Can you please make sure that it compiles with:
```
git clone https://github.com/whit2333/dd_test.git
mkdir dd_test_build && cd dd_test_build
source /cvmfs/clicdp.cern.ch/iLCSoft/builds/2017-02-02/x86_64-slc6-gcc62-opt/init_ilcsoft.sh
cmake -C $ILCSOFT/ILCSoft.cmake ../dd_test
make
```

```
Scanning dependencies of target recon_test
[ 90%] Building CXX object src/runtest/CMakeFiles/recon_test.dir/recon_test.cxx.o
[ 90%] Built target SimpleDetector
/data/sailer/temp/ddtemp/dd_test/src/runtest/recon_test.cxx: In function ‘void recon_test(const char*, const char*)’:
/data/sailer/temp/ddtemp/dd_test/src/runtest/recon_test.cxx:65:58: warning: pointer to a function used in arithmetic [-Wpointer-arith]
   if(!f) { std::cout << " root file not found\n";  exit -1; }
                                                          ^
/data/sailer/temp/ddtemp/dd_test/src/runtest/recon_test.cxx:65:57: warning: statement has no effect [-Wunused-value]
   if(!f) { std::cout << " root file not found\n";  exit -1; }
                                                    ~~~~~^~
/data/sailer/temp/ddtemp/dd_test/src/runtest/recon_test.cxx:67:53: warning: pointer to a function used in arithmetic [-Wpointer-arith]
   if(!t) { std::cout << " tree not found\n";  exit -1; }
                                                     ^
/data/sailer/temp/ddtemp/dd_test/src/runtest/recon_test.cxx:67:52: warning: statement has no effect [-Wunused-value]
   if(!t) { std::cout << " tree not found\n";  exit -1; }
                                               ~~~~~^~
/data/sailer/temp/ddtemp/dd_test/src/runtest/recon_test.cxx:52:32: warning: variable ‘det’ set but not used [-Wunused-but-set-variable]
   DD4hep::Geometry::DetElement det = lcdd.detector( "TrackerPlanes" ) ;
                                ^~~
/data/sailer/temp/ddtemp/dd_test/src/runtest/recon_test.cxx:54:8: warning: variable ‘seg’ set but not used [-Wunused-but-set-variable]
   auto seg     = readout.segmentation();
        ^~~
[100%] Linking CXX executable ../../bin/recon_test
/usr/bin/ld: cannot find -lDDRec
collect2: error: ld returned 1 exit status
make[2]: *** [bin/recon_test] Error 1
make[1]: *** [src/runtest/CMakeFiles/recon_test.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by whit2333** [comment]
Hmm... what does `make VERBOSE=1` print?

**Comment by andresailer** [comment]
I gave you the commands to re-produce my problem. please try them.

**Comment by whit2333** [comment]
Hmm... Hard to debug without knowing why DDRec isn't found by the linker. It likely has to do with the extra ilc-style cmake cruft. I'll look into it.

**Comment by whit2333** [comment]
Well compiling issues aside, here is what I observe.

First the geometry consists of a series of planes with normals in the z direction. Each layer has 4 sensitive elements, one in each quadrant of the mother volume. Each quadrant is 1x1 m^2. 

When IDDecoder::position(cellID) is used for hits in the first quadrant (x>0,y>0) the returned position is consistent with the world coordinate system.

When IDDecoder::position(cellID) is used for any hits not in the first quadrant (x<0 and/or y<0) the returned position is consistent with the xy origin located at the center of each quadrant's volume.

For example, in the first quadrant (x>0,y>0):

>  Cell ID               1407357703733313
 hit pos  : x=82.8493, y=896.959, z=400
 cell pos : x=100, y=900, z=400

which is what we expected with 10 cm segments.  The origin appears to be at (x=0, y=0).

In the second quadrant (x<0,y>0):

>  Cell ID               -12884869087
 hit pos  : x=-842.349, y=419.599, z=200
 cell pos : x=-300, y=-100, z=200

this is consistent with the xy origin being at (x=-500 mm, y=+500 mm)

In the third quadrant (x<0,y<0)

>  Cell ID               844420635164673
 hit pos  : x=-603.969, y=-292.585, z=100
 cell pos : x=-100, y=200, z=100

Again consistent with the xy origin being at (x=-500 mm, y= -500 mm)

In the fourth quadrant (x>0,y<0)

>  Cell ID               844420635181089
 hit pos  : x=447.114, y=-321.131, z=200
 cell pos : x=-100, y=200, z=200

Again consistent with the xy origin being at (x= +500 mm, y= -500 mm)

**Comment by andresailer** [comment]
Could you move this DetElement creation
https://github.com/whit2333/dd_test/blob/master/src/simple_example/src/PlaneTracker_geo.cpp#L57
Into the loop so each sensitive element gets their own DetElement.
https://github.com/whit2333/dd_test/blob/master/src/simple_example/src/PlaneTracker_geo.cpp#L113

**Comment by whit2333** [comment]
Aha! Wonderful. That fixed things right up. Thank you.
