### ISSUE TITLE
Const-correctness in Geant4SensitiveAction<T>::process leads to regression 

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/DD4hep#947]
> The SensitiveDetectors shouldn't modify the G4Step.

Some sensitive detectors, e.g. Geant4OpticalCalorimeterAction, kill the incident optical photon and absorb the energy completely. See e.g.
https://github.com/AIDASoft/DD4hep/blob/master/DDG4/plugins/Geant4SDActions.cpp#L312
The only reason why I think this doesn't fail on compilation is because Geant4OpticalCalorimeterAction is not used anywhere and probably no compilation is even attempted for this template specialization.

This is failing in our EIC code for the exact same reason (but in a PMT detector SD action that absorbs the optical photon).

_Originally posted by @wdconinc in https://github.com/AIDASoft/DD4hep/issues/933#issuecomment-1205896156_

**Comment by wdconinc** [comment]
We can work around this with const_cast but I figured I'd report it.

**Comment by MarkusFrankATcernch** [comment]
Maybe I have not fully understood your argument, but stopping and kill the track is neverless possible
and no const_cast is necessary for this:
[see e.g. Geant4SensitiveAction<Geant4OpticalCalorimeter>::process(...)]
```
      G4Track * track =  step->GetTrack();
...
      if ( track->GetCreatorProcess()->G4VProcess::GetProcessName() != "Cerenkov")
        track->SetTrackStatus(fStopAndKill);
```
What is really required from the G4Step to make it non-const ?
Do I miss here the point?

**Comment by wdconinc** [comment]
This must be related then to our wrapping of the step, essentially:
```cpp
Geant4StepHandler h(step);
h.track->SetTrackStatus(fStopAndKill);
```
With the change to `const G4Step*` we have to modify this to:
```cpp
const_cast<G4Track*>(h.track)->SetTrackStatus(fStopAndKill)
```
Maybe there is no need to wrap this in a handle at all anymore?

**Comment by MarkusFrankATcernch** [comment]
OK. I understand. The alternative is:
```
G4Step* step ....
step->GetTrack()->SetTrackStatus(fStopAndKill);  // No const_cast necessary
```
For full simulation this is still possible in the callbacks and this is actually what is done in the SDAction code.

The problem is that for fat simulation and GFlash the G4Track is only const, because these models implicitly
call SetTrackStatus(fStopAndKill) since the shower must be contained and any modification of the original G4Track
actually would be an error.
There is then no easy possibility to marry both solutions.
I have to think a bit.

**Comment by wdconinc** [comment]
To be honest, this is in some relatively obscure code of ours, and we can remove the use of the handle there, I think. But I'm not quite sure why we are using handles since we should be able to do exactly what is done in `DDG4/plugins/Geant4SDActions.cpp`...

**Comment by MarkusFrankATcernch** [comment]
Hi Wouter,
there are three possibilities to kill a track in sensitive callback:
- Using the pointer to the G4Step in the handler:
```
Geant4StepHandler h(step);
h.step->GetTrack()->SetTrackStatus(fStopAndKill);
```
-   Using directly the pointer to the step passed to `process(const G4Step* step, G4TouchableHistory* hist)`
```
  step->GetTrack()->SetTrackStatus(fStopAndKill);
```
- I could add an track accessor in the `Geant4StepHandler`:
```
  h.getTrack()->SetTrackStatus(fStopAndKill);
```
which is your aesthetically favored solution ?
If it not the last one, we could close this issue....

**Comment by wdconinc** [comment]
I implemented the solution with `h.step->GetTrack()->SetTrackStatus(fStopAndKill)` which works just fine in our code. Thanks for the help here.
