### ISSUE TITLE
Can DD4hep handle Geant4 extended material and derived logical volume classes? (In order to build a Crystal)

### ISSUE THREAD

**Issue by chiaramaccani** [AIDASoft/DD4hep#948]
Dear developers,
I’m trying to include in DD4hep the physics of crystal channeling in order to perform simulations of a detector that makes use of bent crystal. I would like to reproduce what in Geant4 is coded in this example: [geant4](https://github.com/Geant4/geant4)/[examples](https://github.com/Geant4/geant4/tree/master/examples)/[extended](https://github.com/Geant4/geant4/tree/master/examples/extended)/[exoticphysics](https://github.com/Geant4/geant4/tree/master/examples/extended/exoticphysics)/[channeling](https://github.com/Geant4/geant4/tree/master/examples/extended/exoticphysics/channeling)/. 

In order to di this I should make Geant4 create a material with crystal properties. In Geant4 this is achieved by making use of the class [G4ExtendedMaterial](https://github.com/Geant4/geant4/blob/99d10a46dc78367c58913995519648b8b2610d56/source/materials/include/G4ExtendedMaterial.hh) (which inherits from [G4Material](https://github.com/Geant4/geant4/blob/99d10a46dc78367c58913995519648b8b2610d56/source/materials/include/G4Material.hh)) in which are registered the extensions [G4CrystalExetnsion](https://github.com/Geant4/geant4/blob/3dfcdb544e19888c7a5979720ae09596207436f2/source/materials/include/G4CrystalExtension.hh) and [G4ChannelingMaterialData](https://github.com/Geant4/geant4/blob/3dfcdb544e19888c7a5979720ae09596207436f2/source/processes/solidstate/channeling/include/G4ChannelingMaterialData.hh) and then it should be created a logical volume through the class [G4LogicalCrystalVolume](https://github.com/Geant4/geant4/blob/3dfcdb544e19888c7a5979720ae09596207436f2/source/geometry/management/include/G4LogicalCrystalVolume.hh) (which inherits from [G4LogicalVolume](https://github.com/Geant4/geant4/blob/3dfcdb544e19888c7a5979720ae09596207436f2/source/geometry/management/include/G4LogicalVolume.hh).

My question is: can DD4hep handle also extended materials and derived logical volumes? Because I had a look into DD4hep class [Geant4Converter.cpp](https://github.com/AIDASoft/DD4hep/blob/45f06b8917426c02ee31ad68be8f0953dfd81c7a/DDG4/src/Geant4Converter.cpp) and it seems to me that can be created only the base classes G4Material (for example at line 353 inside the handleMaterial function) and G4LogicalVolume (at line 674 inside the handleVolume function). Do you have some suggestions on how I can expand this code?

On the other hand, this information on material should also be communicated at input level. From what I have understood usually the information about materials written in a .xml file are then stored into the DD4hep class [Material](https://github.com/AIDASoft/DD4hep/blob/9bbe12b080ce52615251facc6f6ff5dd58a60e69/DDCore/include/DD4hep/Objects.h) that makes use of the ROOT TGeo classes and then it is used to create a [DetElement](https://github.com/AIDASoft/DD4hep/blob/5ac0ab2e0658ba7ec3260fcdd81f1f1e002142c4/DDCore/include/DD4hep/DetElement.h) object. From what it seems to me TGeo classes like [TGeoMaterial](https://root.cern.ch/doc/v626/classTGeoMaterial.html) and [TGeoMedium](https://root.cern.ch/doc/v626/classTGeoMedium.html) are not meant to deal with Material Extensions like Geant4 classes (aren’t they?). So, is there a simple way to write in input, store and then propagate through the code the information about the fact that we want to build a crystal material with that particular extension? (Maybe expanding the DetElement class to include also this information?)

Thank you.
Best regards,
Chiara Maccani

**Comment by MarkusFrankATcernch** [comment]
Yes -- since today. Please see https://github.com/AIDASoft/DD4hep/pull/950.
But we will anyhow have a coffee tomorrow afternoon....
