### ISSUE TITLE
ddsim shebang change to python3

### ISSUE THREAD

**Issue by DraTeots** [AIDASoft/DD4hep#952]
Modern debian and other linux systems don't have `python` executable anymore, this leads to errors (yes, there are simple ways to link something to something). On older systems python links to python2, but all new version of packages like ROOT use python3 for build so shebang `/usr/bin/env python` again leads to ddsim not working by default. Time to change shebangs. 

 - OS version: ubuntu 22.04
 - DD4hep version: 1.20.02
 - Reproduced by:
 
```bash
ddsim ...
```

**Comment by andresailer** [comment]
I think ROOT probably sets the python to what was used for building root.
We should be able to do the same.
