### ISSUE TITLE
Xml parsing does not adhere to schema definition, requires `version` in `info`

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/DD4hep#960]
- OS version: ubuntu20.04 LCG 101
- Compiler version: gcc9
- DD4hep version: 1.18 (but also happens on 1.21)
- Reproduced by:
```console
docker run --rm -it -v /cvmfs:/cvmfs:shared ghcr.io/aidasoft/ubuntu2004:latest /bin/bash
source /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-ubuntu2004-gcc9-opt/setup.sh
checkGeometry -c $DD4hepINSTALL/DDDetectors/compact/SiD.xml
cp -r $DD4hepINSTALL/DDDetectors/compact .
checkGeometry -c compact/SiD.xml
sed -i 's/^.*version=.*$/>/' compact/SiD.xml
checkGeometry -c compact/SiD.xml
```
- Output: first two `checkGeometry`s succeed, the third one fails with:
```console
root@98c46be1d7d8:~# checkGeometry -c compact/SiD.xml
INFO: +++========================================================================================================================
+++ Loading compact geometry:compact/SiD.xml
+++========================================================================================================================
TGeoManager:0: RuntimeWarning: Changing system of units to ROOT units (cm, s, GeV).
Info in <TGeoManager::TGeoManager>: Geometry default, Detector Geometry created
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-ubuntu2004-gcc9-opt/bin/checkGeometry", line 80, in <module>
    description.fromXML(opts.compact)
TypeError: none of the 2 overloaded methods succeeded. Full details:
  void dd4hep::DetectorImp::fromXML(const string& fname, dd4hep::DetectorBuildType type = BUILD_DEFAULT) =>
    runtime_error: Handle_t::attr_ptr: Element [info] has no attribute of type 'version'
dd4hep: while parsing compact/SiD.xml
  void dd4hep::DetectorImp::fromXML(const string& fname, dd4hep::xml::UriReader* entity_resolver, dd4hep::DetectorBuildType type = BUILD_DEFAULT) =>
    TypeError: takes at least 2 arguments (1 given)
```

This requirement for a `version` attribute in the `info` element seems to be different from the [compact.xsd](https://www.lcsim.org/schemas/compact/1.0/compact.xsd). And I'm in particular confused since I thought [schema validation was turned off](https://github.com/AIDASoft/DD4hep/issues/500).

**Comment by andresailer** [comment]
Hi @wdconinc 

This is not related to the schema validation being turned off, simply this line wants to have a version
https://github.com/AIDASoft/DD4hep/blob/30e35fc74c0ec2b0e6fe52ea020cd70bc3ecfbe9/DDCore/src/plugins/Compact2Objects.cpp#L375

So we could add a try/catch there?

**Comment by wdconinc** [comment]
Ah, I see. I was trying to find where the specific call was, but searching for `version` or `info` gave so many false positives. A try-catch sounds good to me.

**Comment by wdconinc** [comment]
Or a fall-back to a simple empty string as default. Also `comment` is optional but that child call does not result in a runtime error when `comment` is missing.
