### ISSUE TITLE
assigning different SDActions to different slices in a layer

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#971]
Is there a way to assign different SDActions to different slices in a layer?  For example, suppose I have a layer that has a slice that is  scintillating crystal and a slice that is a silicon detection layer.  If I want to just count  the photons created in the scintillator but I want to count and then kill the optical photons in silicon layer, could this be done by assigning different SDActions somehow to the different slices.

**Comment by andresailer** [comment]
I think you will be better off by using the same sensitive detector, but change the treatment of the hit based on the slice ID of the current hit, and then use the MultiSegmentation segmentation to get different hit collections one for each slice.

```

 <readout name="MultiSeg">
   <segmentation   type="MultiSegmentation"  key="slice">
     <segmentation name="Tungstate" type="NoSegmentation" key_value="1"  />
     <segmentation name="Silicon" type="NoSegmentation" key_value="2"  />
   </segmentation>
   <hits_collections>
     <hits_collection name="LeadTungstate" key="slice" key_value="1" />
     <hits_collection name="Sililicon" key="slice" key_value="2" />
    </hits_collections>
   <id>system:3,barrel:1,side:1,slice:2,layer:2,ieta:9,iphi:9,eta:-8,phi:9</id>
 </readout>
```

This recommendation could change based on the actual detector and implementation you have in the end.

**Comment by andresailer** [comment]
Hi @saraheno, was this answer in any way helpful to you?

**Comment by saraheno** [comment]
yes, I have it working now.  I do have another issue, but will open a new item for it.

**Comment by andresailer** [comment]
Ok, thank you for the confirmation!
