### ISSUE TITLE
problem with geant4 visualization

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#977]
Hi,
I am having problems opening the geant4 visualization with ddsim.  I am setting up my environment using

source /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-centos7-gcc11-opt/setup.sh

I am running ddsim with a command like

ddsim --compactFile=./DRSingleCrystal.xml --runType=vis -G --steeringFile SCEPCALsteering.py --outputFile=testSCEPCAL.root --part.userParticleHandler='' -G --gun.position="0.,10.,0." --gun.direction "0 -1 0" --gun.energy "1*GeV" --gun.particle="mu-" --gun.distribution=uniform

I am running  CentOS Linux release 7.9.2009 (Core)

I attach a screen grab with the error message

any help would be appreciated.  Even just hearing if other people maybe running on lxplus are able to do this successfully?

![vis](https://user-images.githubusercontent.com/5215288/191305750-959ad966-72fa-4c56-a0e9-ec5ea5663b20.png)

**Comment by andresailer** [comment]
Works for me from centos7 to lxplus with `ssh -Y`

![image](https://user-images.githubusercontent.com/2115797/191310344-12e20241-061b-430f-94e9-f0a2a1543602.png)

**Comment by andresailer** [comment]
I will close this issue and refer also to the comment from Marko a few years ago:
https://github.com/AIDASoft/DD4hep/issues/826#issuecomment-844112756

>Visualization is quite tricky as it does not solely depend on how lxplus is configured but also on the particular version of X you are running and on the particular version of root. In general we recommend to visualize always locally.

**Comment by saraheno** [comment]
Hi Andre,
My apologies for coming back to this, but it is very non-trivial to install
cvmfs on ones own laptop and compile dd4hep on one's own lap top.  I tried
to compile dd4hep at cern and run it there, and the visualization still
crashes (command like ddsim --compactFile=./SiD.xml --runType=vis -G -N=2
 --steeringFile steering.py   --outputFile=testSiD.root --gun.position "0.0
0.0 1.0*cm" --gun.direction "1.0 1.0 0.1" --gun.energy "30*GeV"
--part.userParticleHandler="" --gun.particle "e-" --runType vis )

You seem to have run a visualization on lxplus using ddsim.  Can you give
me the exact commands you used to produce the visualization from login,
including compiling?  This is such a useful tool for students, and it is
difficult not having it available, even if I run on lxplus.

Sarah Eno

**Comment by andresailer** [comment]
Hi Sarah,

My steps are, to be explicit:

1) Use a centos7 desktop PC
2) ssh -Y lxplus.cern.ch
3) source /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-centos7-gcc11-opt/setup.sh
4) ddsim --compactFile=/cvmfs/sft.cern.ch/lcg/releases/DD4hep/01.18-20d6a/x86_64-centos7-gcc11-opt/DDDetectors/compact/SiD.xml --runType vis
5) /vis/open OGLIX
6) /vis/drawVolume

Graphics work! Thus, as far as I can tell there is nothing wrong with the installation of dd4hep, geant4 etc. I can appreciate your problem, you and I discussed before how to install a virtual machine, which then can use CVMFS, so beyond that I can't see that there is anything we can do for you.

**Comment by saraheno** [comment]
but Andre!!!!  You did help me!!

I needed OGLIX instead of  OGLSXm


Thank you!!!!

**Comment by andresailer** [comment]
Awesome!

**Comment by saraheno** [comment]
Hey Andre.  Very sorry to open this again.  :)

I have a student that is using a MAC with xquartz.  The OGLIX  does not seem to work.  Do you know anybody who does this with a mac?  What visualizer do they use?

**Comment by andresailer** [comment]
Hi @saraheno,

Sorry, I can't help you there.

**Comment by veprbl** [comment]
Qt visualizer is working fine on mac. In addition to change in the steering macro, you'd need to swap `--runType vis` with `--runType qt`.
