### ISSUE TITLE
inputing runtime constants to hits

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#978]
Hi,

I have created my own Hit class to use with dualreadout calorimeters, based on Geant4Calorimeter::Hit, which uses Geant4HitData.

I would like to have some parameters that are obtained at run time for this class, for example the minimum wavelength of the cerenkov light to consider.  However, I do not see a method to use for this?  Is this possible or do I need to hardware such constants into the class and recompile when I want to change them?

**Comment by andresailer** [comment]
If you mean the minimum wavelength to consider for storing hits, then that functionality is probably covered by the "Filters" applied before sensitive detector actions are invoked.
You would probably have to write one that filters on wavelength of optical photons, and `declareProperty` the wavelength like
https://github.com/AIDASoft/DD4hep/blob/574bd1fd6b7a862b3464740cc5d5b95ae5ccad86/DDG4/plugins/Geant4SensDetFilters.cpp#L255
Or you can configure thresholds in the sensitive detectors themselves and steer them via properties.

https://github.com/AIDASoft/DD4hep/blob/b0f2db466bf05cab7d94d4242b995f143ac9ec72/DDG4/plugins/Geant4TrackerWeightedSD.cpp#L439-L440

How they are configured at runtime is documented in the ddsim steering file for filters or sensitive actions.

**Comment by saraheno** [comment]
this looks like what I want.  Can you point me to a place in the Hit code where the filter is used? so I can see how to access it?

**Comment by saraheno** [comment]
actually, this will prevent particles from reaching the hit routine, right?  What if instead of I want to store a histogram in the hit of the wavelength (with a min, max, and number of bins...)

**Comment by andresailer** [comment]
Then you use the sensitive detector, which creates the hits, to pass configurable properties to those hits.

**Comment by andresailer** [comment]
Hi @saraheno 
Is there anymore input you need from our side for this?

**Comment by saraheno** [comment]
I think I"m good.

**Comment by andresailer** [comment]
Great!
