### ISSUE TITLE
Beginner's problem in compiling DD4hep with Geant4

### ISSUE THREAD

**Issue by rarnaldi** [AIDASoft/DD4hep#995]
Dear All,

it's the first time I try to install DD4hep together with Geant4, but I have some problems while compiling. Since I'm a beginner, I might be doing a trivial mistake, but I can't figure out how to solve the issue! Any help from you is very much welcome!

Here are more details:

I work with ubuntu 20.04 and gcc 9.4.0

I've installed Geant4-v11.0.3 using the following options:
cmake -DCMAKE_INSTALL_PREFIX=~/cernbox/ACTS/geant4-v11.0.3-install ~/cernbox/ACTS/geant4-v11.0.3 -DGEANT4_BUILD_TLS_MODEL=global-dynamic 
cmake -DGEANT4_INSTALL_DATA=ON .   

The installation of Geant has been successful. 
I've then compiled DD4hep (version 01.20) in the following way:
```
source ~/bin/thisroot.sh
source ~/geant4-v11.0.3-install/bin/geant4.sh 

cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DBUILD_TESTING=ON -DROOT_DIR=$ROOTSYS -D CMAKE_BUILD_TYPE=Release ..
```
No errors appear during this step, just a warning 
"CMake Warning at /home/arnaldi/cernbox/ACTS/geant4-v11.0.3-install/lib/Geant4-11.0.3/Geant4Config.cmake:793 (message):
  Geant4 required component 'gdml' not found"

When doing make -j8 I get the following output and error message:
```
Scanning dependencies of target Components_DDEvePlugins
[ 82%] Generating libDDEvePlugins.components
[ 82%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4StackingAction.cpp.o
[ 82%] Built target Components_DDEvePlugins
[ 82%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4StepHandler.cpp.o
[ 83%] Building CXX object DDDetectors/CMakeFiles/DDDetectors.dir/src/MultiLayerTracker_geo.cpp.o
[ 83%] Building CXX object DDDetectors/CMakeFiles/DDDetectors.dir/src/PolyconeSupport_geo.cpp.o
[ 83%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4SteppingAction.cpp.o
[ 83%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4TestActions.cpp.o
[ 83%] Building CXX object DDDetectors/CMakeFiles/DDDetectors.dir/src/PolyhedraBarrelCalorimeter2_geo.cpp.o
[ 83%] Building CXX object DDDetectors/CMakeFiles/DDDetectors.dir/src/PolyhedraEndcapCalorimeter2_geo.cpp.o
[ 83%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4TouchableHandler.cpp.o
[ 84%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4TrackInformation.cpp.o
[ 84%] Building CXX object DDDetectors/CMakeFiles/DDDetectors.dir/src/PolyhedraEndcapCalorimeter2_surfaces.cpp.o
[ 84%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4TrackingAction.cpp.o
[ 84%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4TrackingPostAction.cpp.o
[ 84%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4TrackingPreAction.cpp.o
[ 85%] Building CXX object DDDetectors/CMakeFiles/DDDetectors.dir/src/ReflectedDetector_geo.cpp.o
[ 85%] Building CXX object DDDetectors/CMakeFiles/DDDetectors.dir/src/SiTrackerBarrel_geo.cpp.o
[ 85%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4UIManager.cpp.o
[ 85%] Building CXX object DDDetectors/CMakeFiles/DDDetectors.dir/src/SiTrackerBarrel_surfaces.cpp.o
[ 86%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4UIMessenger.cpp.o
[ 86%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4UserInitialization.cpp.o
[ 86%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4UserLimits.cpp.o
[ 86%] Building CXX object DDDetectors/CMakeFiles/DDDetectors.dir/src/SiTrackerEndcap2_geo.cpp.o
[ 86%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4UserParticleHandler.cpp.o
[ 86%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4Vertex.cpp.o
[ 86%] Building CXX object DDDetectors/CMakeFiles/DDDetectors.dir/src/SiTrackerEndcap_surfaces.cpp.o
[ 86%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4VolumeManager.cpp.o
[ 87%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/IoStreams.cpp.o
[ 87%] Building CXX object DDDetectors/CMakeFiles/DDDetectors.dir/src/Solenoid_o1_v01_gep.cpp.o
[ 88%] Building CXX object DDDetectors/CMakeFiles/DDDetectors.dir/src/SubdetectorAssembly_geo.cpp.o
[ 88%] Building CXX object DDDetectors/CMakeFiles/DDDetectors.dir/src/SurfaceExamplePlugin.cpp.o
[ 88%] Building CXX object DDDetectors/CMakeFiles/DDDetectors.dir/src/TubeSegment_geo.cpp.o
[ 88%] Building CXX object DDDetectors/CMakeFiles/DDDetectors.dir/src/VolumeAssembly_geo.cpp.o
[ 88%] Linking CXX shared library ../lib/libDDG4.so
[ 88%] Linking CXX shared library ../lib/libDDDetectors.so
[ 88%] Built target DDDetectors
Scanning dependencies of target Components_DDDetectors
[ 88%] Generating libDDDetectors.components
[ 88%] Built target Components_DDDetectors
/usr/bin/ld: CMakeFiles/DDG4.dir/src/Geant4Converter.cpp.o: in function `dd4hep::sim::Geant4Converter::handleProperties(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > > >&) const [clone .cold]':
Geant4Converter.cpp:(.text.unlikely+0x1089): undefined reference to `dd4hep::PluginService::print_bad_cast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::any const&, std::type_info const&, char const*)'
/usr/bin/ld: CMakeFiles/DDG4.dir/src/Geant4Exec.cpp.o: in function `Geant4Compatibility::buildDefaultDetectorConstruction(dd4hep::sim::Geant4Kernel&) [clone .cold]':
Geant4Exec.cpp:(.text.unlikely+0x1c3): undefined reference to `dd4hep::PluginService::print_bad_cast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::any const&, std::type_info const&, char const*)'
/usr/bin/ld: Geant4Exec.cpp:(.text.unlikely+0x20b): undefined reference to `dd4hep::PluginService::print_bad_cast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::any const&, std::type_info const&, char const*)'
/usr/bin/ld: CMakeFiles/DDG4.dir/src/Geant4GeneratorWrapper.cpp.o: in function `dd4hep::sim::Geant4GeneratorWrapper::generator() [clone .cold]':
Geant4GeneratorWrapper.cpp:(.text.unlikely+0xef): undefined reference to `dd4hep::PluginService::print_bad_cast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::any const&, std::type_info const&, char const*)'
/usr/bin/ld: Geant4GeneratorWrapper.cpp:(.text.unlikely+0x132): undefined reference to `dd4hep::PluginService::print_bad_cast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::any const&, std::type_info const&, char const*)'
/usr/bin/ld: CMakeFiles/DDG4.dir/src/Geant4Handle.cpp.o:Geant4Handle.cpp:(.text.unlikely+0x85): more undefined references to `dd4hep::PluginService::print_bad_cast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::any const&, std::type_info const&, char const*)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [DDG4/CMakeFiles/DDG4.dir/build.make:1138: lib/libDDG4.so.1.20] Error 1
make[1]: *** [CMakeFiles/Makefile2:2127: DDG4/CMakeFiles/DDG4.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```
Can you, please, help me in solving this compilation problem?
 
   thanks a lot and best regards
   
                                        Roberta

**Comment by andresailer** [comment]
Maybe you need to rebuild geant4 with `-DGEANT4_USE_GDML=ON `

**Comment by rarnaldi** [comment]
Dear Andre,

thanks for the suggestion. I now compiled GEANT4 with -DGEANT4_USE_GDML=ON. The warning I had previously disappeared and the Geant4 compilation seems successful. 
Still the compilation of DD4hep is not working and I keep getting the same error as before.

[ 88%] Linking CXX shared library ../lib/libDDG4.so
/usr/bin/ld: CMakeFiles/DDG4.dir/src/Geant4Converter.cpp.o: in function `dd4hep::sim::Geant4Converter::handleProperties(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > > >&) const [clone .cold]':
Geant4Converter.cpp:(.text.unlikely+0x1089): undefined reference to `dd4hep::PluginService::print_bad_cast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::any const&, std::type_info const&, char const*)'
/usr/bin/ld: CMakeFiles/DDG4.dir/src/Geant4Exec.cpp.o: in function `Geant4Compatibility::buildDefaultDetectorConstruction(dd4hep::sim::Geant4Kernel&) [clone .cold]':
Geant4Exec.cpp:(.text.unlikely+0x1c3): undefined reference to `dd4hep::PluginService::print_bad_cast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::any const&, std::type_info const&, char const*)'
/usr/bin/ld: Geant4Exec.cpp:(.text.unlikely+0x20b): undefined reference to `dd4hep::PluginService::print_bad_cast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::any const&, std::type_info const&, char const*)'
/usr/bin/ld: CMakeFiles/DDG4.dir/src/Geant4GeneratorWrapper.cpp.o: in function `dd4hep::sim::Geant4GeneratorWrapper::generator() [clone .cold]':
Geant4GeneratorWrapper.cpp:(.text.unlikely+0xef): undefined reference to `dd4hep::PluginService::print_bad_cast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::any const&, std::type_info const&, char const*)'
/usr/bin/ld: Geant4GeneratorWrapper.cpp:(.text.unlikely+0x132): undefined reference to `dd4hep::PluginService::print_bad_cast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::any const&, std::type_info const&, char const*)'
/usr/bin/ld: CMakeFiles/DDG4.dir/src/Geant4Handle.cpp.o:Geant4Handle.cpp:(.text.unlikely+0x85): more undefined references to `dd4hep::PluginService::print_bad_cast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::any const&, std::type_info const&, char const*)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [DDG4/CMakeFiles/DDG4.dir/build.make:1219: lib/libDDG4.so.1.20] Error 1
make[1]: *** [CMakeFiles/Makefile2:2035: DDG4/CMakeFiles/DDG4.dir/all] Error 2
make: *** [Makefile:146: all] Error 2


I'm using gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0. Is it ok, or should I have a more recent gcc?

Any other suggestion is more than welcome, thanks for your help!

                    best regards

                             Roberta

**Comment by andresailer** [comment]
Hi Roberta,

Can you please run 

`make VERBOSE=1 -j1 ` 

and show us the output for the linking step?
It seems the linker you are using is complaining about a missing symbol (`print_bad_cast`),
But that symbol should be part of libDDCore, and libDDG4 links against libDDCore, so the symbol should be there.

Also: please find libDDCore.so in your build folder and run the command

`nm -C libDDCore.so | grep print_bad_cast` 

Please post both outputs here. to see that the libDDCore does contain the library and that the linker is linking against it.

Can you please check what c++ standard root and geant4 were compiled with, and that is the same c++ standard that you compiled dd4hep with?

Thanks,
Andre

**Comment by rarnaldi** [comment]
Dear Andre,

thanks a lot for your support!
I now upload the output files, obtained via make VERBOSE=1
[output.txt](https://github.com/AIDASoft/DD4hep/files/9853821/output.txt)

By doing nm -C libDDCore.so | grep print_bad_cast I obtain:

0000000000328ac0 T dd4hep::PluginService::print_bad_cast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::any const&, std::type_info const&, char const*)
000000000021c5f0 t dd4hep::PluginService::print_bad_cast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::any const&, std::type_info const&, char const*) [clone .cold]

I notice that the in the above lines dd4hep::PluginService has boost:any const& as 4th argument. In the error message I get when I compile DD4hep, the 4th argument seems different, i.e.  std::any const&, I don't know if it helps.
dd4hep::PluginService::print_bad_cast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::any const&, std::type_info const&, char const*)'

Concerning the c++ standards, I'm using the following:
- ROOT 6.26.06 --> c++14
- GEANT4-v11.0.3 --> c++17
- DD4hep --> c++14 (from what I find in the output.txt file I have attached)

Does the different c++ standards create an inconsistency? As far as I can see, I can't compile this geant4 version with C++14, since c++17 or higher is mandatory.
I'm using gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

  thanks a lot for your help!  best regards
                             Roberta

**Comment by rarnaldi** [comment]
Dear Andre,

thanks a lot! I managed to compile ROOT, GEANT4 and DD4hep with C++17 and now everything works! Thanks a lot for your support and very quick and useful feedback!

    best regards

                                Roberta

**Comment by andresailer** [comment]
Great! You're welcome!
